wrf-model/WRF

compile

TYPE: bug fix
KEYWORDS: WRF-Chem,convert_emiss,emi_conv,Compilation
SOURCE: Ka Yee Wong, NOAA/GSD(CIRA)
DESCRIPTION OF CHANGES: convert_emiss compilation bug-fix
ISSUE:
Fixes #601
modified:   compile

Fix convert_emiss compilation issue (#601)

---

inc/version_decl

KEYWORDS: version
Update text string used in the WRF sytem (wrf, real, ideal, ndown) to
identify the release version.
M		inc/version_decl
Code builds, and the expected output message is OK.

Update source code character string from v4.0 to v4.0.1

---

README

KEYWORDS: README, release, v4.0.1
DESCRIPTION OF CHANGES: Updated the top of the README file to indicate V4.0.1, and added a release notes section for this version, pointing to the GitHub WRF Release page.
M   README
TESTS CONDUCTED: no tests conducted - text only

updated README file for v4.0.1 release

---

README
Registry/Registry.EM_COMMON.var
compile
doc/README.DA
dyn_em/module_small_step_em.F
dyn_em/start_em.F
inc/version_decl
phys/module_mp_thompson.F
phys/module_sf_noahmpdrv.F
phys/module_sf_noahmplsm.F
test/em_real/namelist.input.fire
var/da/da_minimisation/da_get_var_diagnostics.inc
var/da/da_minimisation/da_minimisation.f90
var/da/da_obs_io/da_read_obs_radar.inc
var/da/da_radar/da_get_innov_vector_radar.inc
var/da/da_setup_structures/da_scale_background_errors.inc
var/da/da_setup_structures/da_setup_be_regional.inc
var/da/da_tools/da_mo_correction.inc
var/da/da_transfer_model/da_transfer_xatowrf.inc
var/run/crtm_coeffs

TYPE: release merge
KEYWORDS: release, v4.0.1
DESCRIPTION OF CHANGES: merging release v4.0.1 branch onto master
TESTS CONDUCTED: no tests conducted - this is a fast-forward merge of tested code onto master

Finalize v4.0.1 release on master 

---

README

Merge bug-fixes from the v4.0.1 release into the develop branch.
This merge also connects the v4.0.1 tag to future development on
the develop branch.

Merged bug fixes from WRFV4.0.1 into the development branch

---

share/module_model_constants.F

TYPE: no impact, text only
KEYWORDS: constant variables
DESCRIPTION OF CHANGES: descriptions and units of variables listed in share/module_model_constants.F are added to meet the requirement of CCPP 
M       share/module_model_constants.F
TESTS CONDUCTED:  not necessary

Add descriptions and units of constant variables

---

share/module_model_constants.F

KEYWORDS: constants
DESCRIPTION OF CHANGES: explicitly describe constants in the code module_model_constants.F
M         share/module_model_constants.F
TESTS CONDUCTED: No test is necessary. 
RELEASE NOTE: Don't need to mention in release.

Provide brief description / units of shared model constants

---

tools/update_fork.pl

KEYWORDS: fork, update-to-date
DESCRIPTION OF CHANGES: Now 'develop' (instead of 'master') branch is the main branch for doing development. Change master to develop in the script.
M   tools/update_fork.pl
TESTS CONDUCTED: None. No impact.

fast-forward merge changed from master to develop

---

README
inc/version_decl

KEYWORDS: README, version_decl, release-v4.0.3
DESCRIPTION OF CHANGES: Updated the README and inc/version_decl files to reflect the upcoming release version (4.0.3), and correct date (December 18, 2018)
M   README
M   inc/version_decl
TESTS CONDUCTED: None - text only

Release v4.0.3 updates

---

phys/module_sf_noahmpdrv.F
phys/module_sf_noahmplsm.F
run/MPTABLE.TBL

Update Noah-MP with National Water Model changes
Noah-MP code within WRF and the National Water Model has diverged. This pull request feeds NWM development back to WRF. 
M       phys/module_sf_noahmpdrv.F
M       phys/module_sf_noahmplsm.F
M       run/MPTABLE.TBL
1. 24-hour summer/winter simulations produces expected level of changes

Update Noah-MP with National Water Model changes

---

Registry/Registry.EM_COMMON
Registry/registry.trad_fields
dyn_em/start_em.F
phys/module_diag_trad_fields.F
phys/module_diagnostics_driver.F

KEYWORDS: new variables
A few variables, including precipitable water, relative humidity, total rain, total liquid rain, and potential temperature, are added to output files of traditional fields (wrf_trad_fields). PSFC is also included. Since PSFC is updated every time step, it is not necessary to explicitly recalculate PSFC in  phys/module_diag_trad_fields.F. Instead, we simply add 'h1' stream to PSFC in Registry. 
With this option turned on (diag_nwp2=1), one doesn't have to turn on the AFWA diagnostic option to get these variables. Note that the methods to compute relative humidity and precipitable water are borrowed from the AFWA package.
To run the option:
```
&time_control
auxhist1_outname                    = …
```

Add new variables to output files of traditional fields

---

chem/chemics_init.F
chem/module_plumerise1.F

KEYWORDS: chemistry initialization, plumerise
1. Added CH4 and CO2 initialization to RACM_SOA_VBS_KPP (chem_opt=108) and RACM_SOA_VBS_KPP_AQCHEM (chem_opt=109).
2. Added NH3 and CH4 to plumerise transport for biomass_burn_opt=1.
3. Updated CO2 to 400 ppm.
LIST OF MODIFIED FILES: 	
chem/chemics_init.F
chem/module_plumerise1.F
TESTS CONDUCTED: none

Updates for completeness of gas initialization and plumerise

---

phys/module_mp_jensen_ishmael.F

KEYWORDS: comments
1. Added comments to Jensen Ishmael microphysics
2. Removed commented-out lines.
3. Removed debugging prints.
4. Renamed a few variables and routine names.
M phys/module_mp_jensen_ishmael.F

Updates/comments added to Jensen_ISHMAEL microphysics

---

phys/module_cu_mskf.F

KEYWORDS: MSKF, aerosol-cloud interaction, references
SOURCE: Alapaty of EPA
Update one and add two new references to the MSKF scheme.
M  phys/module_cu_mskf.F
It compiles.

Update one and add two references to MSKF

---

phys/module_mp_jensen_ishmael.F

KEYWORDS: code changes/enhancements 
1. Added double precision-ness for lookup tables
2. Added ice fall speed re-calculation before sedimentation but after tendency updates
3. Aggregation tendencies (mass and number) no longer occur in the aggregation subroutine and now occur along with the other microphysical tendencies
4. Ice particle shape prediction limited to threshold ice particle size and number concentration (helps limit the occurrence of extreme ice particle shapes from advection/diffusion)
5. Limited riming to threshold QCLOUD amount consistent with lookup table
6. Updated formulation for ice number mixing ratio tendency during melting
7. Consistently set the small ice size limit to 2 microns
8. Moved …

Jensen Ishmael microphysics: updates for initial release

---

phys/module_radiation_driver.F

KEYWORDS: cloud fraction scheme (icloud3)
SOURCE:  Greg Thompson (NCAR)
1. icloud=3 
a. Updates to internal parameters
b. Changing from 3D structure to 1D column only
2. Minor RH increase in the AOD calculation.
phys/module_radiation_driver.F
TESTS CONDUCTED: Ran in real-time forecast mode for a month. Compared to older version, expect far lower cloud fraction amount at high altitude (cold tropopause level temperatures for example). Full year (every 5th day) test by Mei Xu gives results with better shortwave radiation at ground comparison to observations.
RELEASE NOTE:
Cloud fraction scheme (icloud=3 namelist option) compared to prior version generally produces lower cloud fraction amount at high altitude (cold tropopause …

Update parameters in icloud3, changes to AOD for Thompson-Eidhammer aerosol-aware scheme

---

phys/module_mp_jensen_ishmael.F

KEYWORDS: code changes/enhancements
1) Added a check to melt all ice if the combination of the size and number is sufficiently small. This prevents small amounts of ice precipitation due to the numerics. 
2) Ice particle properties are now output for ice mass mixing ratios greater than 1.e-9 kg/kg (1.e-6 g/kg). 
Builds and runs correctly

Jensen Ishmael microphysics: absolutely positively and definitely the final code update for initial release

---

phys/module_mp_jensen_ishmael.F

KEYWORDS: comments, Jensen, MP, ishmael
Added/fixed comments to Jensen Ishmael microphysics
M phys/module_mp_jensen_ishmael.F
No tests required for these changes

Comments added to Jensen_ISHMAEL microphysics

---

phys/module_sf_sfclay.F

KEYWORDS: mm5, old, module_sf_sfclay.F, mpas, wrf, physics, unified
DESCRIPTION OF CHANGES: The unified_physics branch was created from the top of the master (which is the v4.0.3 release branch). These changes have already been approved for the develop branch, but I am adding them to the unified_physics branch for WRF/MPAS comparative testing purposes. 
M     phys/module_sf_sfclay.F

wrf/mpas unified old MM5 commits pushed to unified_physics branch

---

phys/module_cu_ntiedtke.F

KEYWORDS: new_tiedtke, cu, module_cu_ntiedtke.F, mpas, wrf, physics, unified
DESCRIPTION OF CHANGES: The unified_physics branch was created from the top of the master (which is the v4.0.3 release branch). These changes have already been approved for the develop branch, but I am adding them to the unified_physics branch for WRF/MPAS comparative testing purposes.
M phys/module_cu_ntiedtke.F

wrf/mpas unified new_tiedtke commits pushed to unified_physics branch

---

phys/module_bl_ysu.F
phys/module_pbl_driver.F

KEYWORDS: ysu, bl, module_bl_ysu.F, module_pbl_driver.F mpas, wrf, physics, unified
DESCRIPTION OF CHANGES: The unified_physics branch was created from the top of the master (which is the v4.0.3 release branch). These changes have already been approved for the develop branch, but I am adding them to the unified_physics branch for WRF/MPAS comparative testing purposes.
M    phys/module_bl_ysu.F
M    phys/module_pbl_driver.F

wrf/mpas unified ysu commits pushed to unified_physics branch

---

phys/module_mp_wsm6.F

KEYWORDS: wsm6, mp, module_mp_wsm6.F, mpas, wrf, physics, unified
DESCRIPTION OF CHANGES: The unified_physics branch was created from the top of the master (which is the v4.0.3 release branch). These changes have already been approved for the develop branch, but I am adding them to the unified_physics branch for WRF/MPAS comparative testing purposes.
M phys/module_mp_wsm6.F

wrf/mpas unified wsm6 commits pushed to unified_physics branch

---

doc/README.DA
var/README.namelist
var/README.radiance
var/run/README

KEYWORDS: WRFDA, README
DESCRIPTION OF CHANGES: Update WRFDA v4.1 READMEs
M doc/README.DA
M var/README.namelist
M var/README.radiance
M var/run/README
TESTS CONDUCTED: No need.

 Update WRFDA v4.1 READMEs

---

README
inc/version_decl

KEYWORDS: README, version_decl, release-v4.1
Updated the README and inc/version_decl files to reflect the upcoming release version (4.1)
M README
None - text only

update README and inc/version_decl for release-v4.1

---

README
inc/version_decl

KEYWORDS: README, release
Update the top-level README file, and the inc/version_decl file with the correct version.
Now using a string which in no longer a fixed length.
M	   README
M	   inc/version_decl
TESTS CONDUCTED:  A test case is run with the correct printout
```
taskid: 0 hostname: r5i2n23
Quilting with   1 groups of   0 I/O tasks.
Ntasks in X           12 , ntasks in Y           12
WRF V4.1.1 MODEL
*************************************
Parent domain
ids,ide,jds,jde            1         401           1         261
ims,ime,jms,jme           -4          41          -4          29
ips,ipe,jps,jpe            1          34           1          22
*************************************
```

Prepare for WRF-v4.1.1 release

---

README
inc/version_decl

KEYWORDS: README, version_decl, release-v4.1.2
Updated the README and inc/version_decl files to reflect the upcoming release version (4.1.2)
M README

update README and inc/version_decl for release-v4.1.2

---

phys/module_bl_ysu.F

Revert "YSU PBL: check on flag_qi instead of present(rqiblten)"

---

README
inc/version_decl

KEYWORDS: release, version_decl, README, v4.1.3
DESCRIPTION OF CHANGES: Updated the top-level README file, and the inc/version_decl file 
to version 4.1.3.
M    README
M    inc/version_decl
TESTS CONDUCTED: No tests necessary. Text only.

Update top-level README & version_decl for V4.1.3 release

---

phys/module_mp_fer_hires.F

These bug fixes for the Ferrier-Aligo microphysics scheme from EMC were cherrypicked from the H220baseline branch. Approved to go to b/HWRF on the HWRF developers call on 11/25/19.

FA microphysics bug fixes

---

run/README.namelist

KEYWORDS: README.namelist
Improve KSAS description
none required, text only

fix entry for KSAS

---

phys/module_sf_bem.F
phys/module_sf_bep.F
phys/module_sf_bep_bem.F
phys/module_sf_noah_seaice.F
phys/module_sf_noah_seaice_drv.F
phys/module_sf_noahdrv.F
phys/module_sf_noahlsm_glacial_only.F
phys/module_sf_urban.F

KEYWORDS: unified_physics, noah, lsm, mpas, bep, bem, seaice, glacial, urban
DESCRIPTION OF CHANGES: In an effort to merge the unified_physics branch (for unification with the MPAS model) and the develop branch, modifications made to the Noah scheme in the  
unified_physics branch were brought into the code on the develop branch.
M    phys/module_sf_bem.F
M    phys/module_sf_bep.F
M    phys/module_sf_bep_bem.F
M    phys/module_sf_noah_seaice.F
M    phys/module_sf_noah_seaice_drv.F
M    phys/module_sf_noahdrv.F
M    phys/module_sf_noahlsm_glacial_only.F
M    phys/module_sf_urban.F
TESTS CONDUCTED: Verified that modified code builds (using GNU). Jenkins test passed.
RELEASE NOTE: Modifications to Noah LSM code were made for the …

Noah LSM update to include unified_physics branch mods on develop branch

---

README
inc/version_decl

KEYWORDS: README update for release
DESCRIPTION OF CHANGES: update the top-level README file, and the inc/version_decl file with the correct version 
M       README
M       inc/version_decl
TESTS CONDUCTED: not necessary

Update README for release of WRF-v4.1.4

---

phys/module_microphysics_driver.F
phys/module_mp_fast_sbm.F

TYPE: Bug Fix
KEYWORDS: cloud microphysics
SOURCE: Jacob Shpund
Bug Fixes for the Fast Spectral Bin Microphysics (FSBM) cloud microphysical scheme
The bin-wise loops indices as well as output for the polarimetric radar were updated. Small updates inserted across all of the scheme.
M phys/module_microphysics_driver.F 
M phys/module_mp_fast_sbm.F
TEST RESULTS:
1. Jenkins is OK

Bug Fix for FAST (33 bins) Spectral-Bin Microphysics (FSBM)

---

README
inc/version_decl

KEYWORDS: version_decl
Update the version number of this release to v4.2.1
README
inc/version_decl
1. Regression test will occur

Update version to v4.2.1

---

README
inc/version_decl

Type: Text only
Keywords: prepare for release of WRFV4.2.2
Source: internal
Description of Changes: modify README and inc/version_decl
List of modified files:
M     README
M     inc/version_decl
Test conducted: not necessary

Prepare for the release of WRFv4.2.2

---

run/README.namelist

KEYWORDS: README.namelist, wudapt, rebalance, madwrf, P3, CTSM
Problem:
Several new namelist options have been added to the code for the V4.3 release, but a few weren't added to the README.namelist file.
Solution:
Added the missing namelist variables to the README.namelist file.
M    run/README.namelist
1. no tests necessary - text only
2. Jenkins are all passing.

Add new options to readme

---

inc/version_decl

KEYWORDS: version
Update version character string to the new branch name: release-v4.3
modified:   inc/version_decl
1. Jenkins testing is OK.

update version_decl to v4.3

---

main/real_em.F

TYPE: bug fix
KEYWORDS: advance_clock, ARW, real
SOURCE: Found by Craig Schwartz and Jim Bresch (NCAR), internal
Problem:
When two options were selected to be used at the same time in real (multi-file lateral boundaries, and outputting the processed metgrid data at each time), then the file I/O was incorrect.
Solution:
There was a call to domain_clockadvance, which had a side effect of changing the current_date. Removing this call is 
sufficient to give the correct results. This call was superfluous in most cases. However, with the "IF this and also that" 
logic for the failure mode, the call was advancing the time step ahead to the next lateral boundary time in the middle 
processing a metgrid input file. This left a missing file gap in some output streams from …

Remove advance_clock call in ARW real main program

---

external/io_netcdf/diffwrf.F90

KEYWORDS: diffwrf, integer
Problem:
Previously, the netcdf diffwrf utility in WRF only handled comparisons of floating point data (WRF_REAL).
Solution:
Modify the logic to permit comparisons of integer data (WRF_INTEGER).
modified:   external/io_netcdf/diffwrf.F90
1. Without mods, integer arrays are skipped. With the mods, the arrays are ingested and processed. Here is an example that includes some integer data in the input file. Now, this integer data was bit-wise identical, so we do not get any computations:
```
$ ../../../external/io_netcdf/diffwrf ORIG/$F RESTART/$F
Just plot  F
Diffing ORIG/wrfout_d01_2000-01-24_12:15:00 RESTART/wrfout_d01_2000-01-24_12:15:00
Next Time …
```

Allow integer gridded fields in diffwrf

---

phys/module_ra_farms.F

TYPE: bug fix
KEYWORDS: FARMS, undefined variable, cloud transmittance
SOURCE: Pedro A. Jimenez and Jimy Dudhia (NCAR), and Jaemo Yang and Yu Xie (NREL)
Problem: Incorrect treatment of transmittance of diffuse radiation by clouds in FARMS
Solution:
Change the cloud transmittance and initialize variables before using them
M       phys/module_ra_farms.F
1. The impact of these mods should be small.
There is no impact on the results in the test we run. We used Intel compiler which I think initializes values to 0 if the variables are not defined. And 0 happens to be the right value in this case.
RELEASE NOTE: Corrected the incorrect treatment of cloud transmittances of diffuse radiation by …

Bug fix FARMS to use correct cloud transmittance

---

phys/module_irrigation.F

TYPE: bug fix
KEYWORDS: irrigation schedule, fix
Problem:
wrong day-span selection. There were problems when either with Julian day=0 or without.
Solution:
new function to select the irrigation period
Fixes #1482
M	phys/module_irrigation.F
1. Do mods fix problem? I checked the compilation. Need further testing with data.
RELEASE NOTE: Fix for the irrigation scheduling issue.

fix irrigation schedule

---

run/README.namelist

KEYWORDS: improve MAD-WRF section of README.namelist
SOURCE: internal + Pedro Jimenez
Improve option description and refer to doc file
none needed

improve MAD-WRF section

---

README
inc/version_decl

KEYWORDS:  README and inc/version_decl
DESCRIPTION OF CHANGES: This PR changes the version number in README and inc/version_decl for release of WRFV4.3.3
TESTS CONDUCTED:  not necessary

Prepare for release-v4.3.3

---

run/README.namelist

KEYWORDS: README, namelist, v4.4, V3
Problem:
In README.namelist, a few new namelist items for V4.4 were missing. There were also still several references to V3.
Solution:
Added the new namelist options and removed all references to V3
1. No testing necessary - text only
2. Jenkins tests pass

Added missing namelist options for v4.4, removed anything pertaining to V3

---

README
inc/version_decl

KEYWORDS: README, version_decl, V4.4
M     README
M     inc/version_decl
No tests necessary - text only

Update top-level README and version_decl to V4.4

---

README
inc/version_decl

KEYWORDS: README, version_decl, v4.4.1
M   README
M   inc/version_decl
1. Text only - no tests necessary
2. Jenkins tests pass.

Update top-level README and version-decl to V4.4.1

---

README
inc/version_decl

TYPE: text only 
KEYWORDS: update, release, v4.4.2, README, version_decl
M    README
M    inc/version_decl
1. no tests necessary - text only

updated top-level README and version_decl for V4.4.2

---

Registry/registry.chem
chem/Makefile
chem/aerosol_driver.F
chem/depend.chem
chem/dry_dep_driver.F
chem/module_aerosols_soa_vbs_het.F
chem/module_data_soa_vbs_het.F

This splits chem_opt=100 from chem_opt=108 and chem_opt=109 by renamng the original module for chem_opt=100 to *_het and removing the refrences to CLNO2, HCL, and the crustal species from options 108 and 109. Relatedly, the aerosol pointers in the module_data* files are adjusted to reflect this change. In this configuration, ISORROPIA and the N2O5 heterogenous chemistry option will only be available with option 100, but both namelist options must be set.
TYPE: bug fix/enhancment
KEYWORDS: MADE-SORGAM, SOA_VBS, heterogenous chemistry, crustal species, chemistry options
SOURCE: Jordan Schnell (CIRES/NOAA)
Problem: Species in chem_opt=100 (HCL, CLNO2, MG, K, CA) are referenced by the aerosol module for chem_opt=108, 109 leading to memory mapping errors. Previous code …

Separate chem_opt=100 from opts 108 and 109

---

run/README.namelist

TYPE: no impact, text only
KEYWORDS: namelists, README
SOURCE: internal, Will Hatheway
Problem:
A few newly added as well as a few pre-existing namelists are not in the README file. 
Solution:
Add these namelists in run/README.namelist file. Also make some lines in the file shorter for easy raed.
M     run/README.namelist
1. Text only change, no tests required.

Add missed namelists

---

README
inc/version_decl

KEYWORDS: README, version_decl, release, v4.5
Updated top-level README and version_decl for V4.5.
M   README
M   inc/version_decl
Text only - no testing necessary

updated top-level README and version_decl for V4.5

---

README
inc/version_decl

KEYWORDS: v4.5.1, release, version_decl, README
Updated the top-level README and inc/version_decl files to reflect V4.5.1, in preparation for the v4.5.1 release
M       README
M       inc/version_decl
1. No tests necessary - text only

updated top-level README and version_decl for V4.5.1

---

README
inc/version_decl

KEYWORDS: release, v4.5.2, version_decl, README
Modified version in the top-level README and inc/version_decl files
M   README
M   inc/version_decl
1. No tests necessary - text only

updated top-level README and version_decl for V4.5.2

---

README
inc/version_decl

KEYWORDS: v4.6.0, release, version_decl, README
Updated the top-level README and inc/version_decl files to reflect V4.6.0, in preparation for the v4.6.0 release
M README
No tests necessary - text only

Updating version for v4.6.0

---

README
inc/version_decl

KEYWORDS: v4.6.1, release, version_decl, README
Updated the top-level README and inc/version_decl files to reflect V4.6.1, in preparation for the v4.6.1 release
M README
No tests necessary - text only

Update version info for release v4.6.1

---

phys/module_mp_radar.F
phys/module_mp_udm.F

TYPE: bug-fix
KEYWORDS: UDM microphysics
SOURCE: internal from Songyou Hong
Problem:
Some test cases were failing
Solution:
tests for divide by zero were added and some of the in-cloud physics was taken out
ISSUE:  none
modified:   phys/module_mp_radar.F
modified:   phys/module_mp_udm.F
1. yes this code passes test suite
2. code compiles
3. 
RELEASE NOTE: added to UDM scheme already committed

Updated UDM microphysics to pass test suite

---

README
inc/version_decl

KEYWORDS: v4.7.0, release, version_decl, README
Updated the top-level README and inc/version_decl files to reflect the v4.7.0 release

Update version info for release v4.7.0

---

run/README.namelist

KEYWORDS: README file, MYNN
SOURCE: internal (replacing PR-2218)
This PR moves the MYNN closure options together with other MYNN specific options, and makes a change to the description of the MYNN PBL option.
RELEASE NOTE:

Modify MYNN PBL descriptions
