wrf-model/WRF

var/da/da_transfer_model/da_transfer_xatowrf.inc

TYPE: bug fix
KEYWORDS: moist, analysis update
SOURCE: Internal (JJG)
xatowrf now requires cloud_cv_options that match packaging defined in registry.var
for xa%qrn, xa%qcw, xa%qci, xa%qsn, and xa%qgr.
This bugfix is connected to PR #283 from  11 AUG 2017 (https://github.com/wrf-model/WRF/commit/c7405bb3544a3eecd070263865de7d4834d9ee14#diff-fe8b020143d32583d82b945e2bd66f50)
The array bounds error this avoids occurs when mp_physics ~= [0, 98] and cloud_cv_options==0.
M       var/da/da_transfer_model/da_transfer_xatowrf.inc
The following error at the end of rsl.error.0000 is avoided with this fix when "debug" build is used for WRFDA:
>``forrtl: severe (408): fort: (2): Subscript #1 of the array QCW has value 2 which is …

Fixed qc, qr, qi, qs, qg updates to WRF moist variables

---

var/run/crtm_coeffs

TYPE: no impact (except for WRFDA regtests)
KEYWORDS: WRFDA, crtm_coeffs
Make var/run/crtm_coeffs point to the updated /glade/work path for release-v4.0.1.
M       var/run/crtm_coeffs
1. WRFDA regtests run with the updated path.

Update the crtm_coeffs_2.2.3 path per cheyenne file system restructuring

---

var/da/da_tools/da_mo_correction.inc

TYPE: bug fix
KEYWORDS: WRFDA, sfc wind correction
The current if-elseif coding in the code is not consistent with the intended formulation
as in figure 2 of Stauffer et al. 1991, MWR,
0<z0<0.2 : u40/u10=1.000+0.320*z0**0.2
z0>=0.2 : u40/u10=1.169+0.315*z0
Notes:
1. the sfc wind correction is applied only when
(1) sfc_assi_options=1.
(2) The obs height is below the model lowest half level height and the height difference is larger than 10 meters.
(3) Bulk Richardson number<0.0 and h/L>1.5.
2. My personal comment is that the concept of the empirical correction derived 25+ years ago
(when the lowest model level was 40 meters) is not applicable to current models that have
much higher vertical resolutions near surface. The proposed fix …

Fix in DA to make the code consistent with formulation for sfc wind correction

---

var/da/da_obs_io/da_read_obs_radar.inc
var/da/da_radar/da_get_innov_vector_radar.inc

TYPE: bug fix
KEYWORDS: WRFDA, radar rf/rv, obs error
1. Missing rv are set incorrectly as no-rain rf in NCAR-processed radar data.
The fix is to set qc to missing_data for -999.99 rv in var/da/da_radar/da_get_innov_vector_radar.inc
2. Missing rv/rf has error of missing_r in CWB-processed radar data.
The fix is to set a default error value in var/da/da_obs_io/da_read_obs_radar.inc.
NCAR-processed radar data sample
```
FM-128 RADAR   2017-06-02_03:06:00        22.961       117.830      38.0       1
5158.0    -999.990   0       0.500      -999.990   0       0.000     -8888.880
```
CWB-processed radar data sample 1
```
FM-128 RADAR   2017-07-06_06:00:00        19.570       117.335       0.0       1
12000.0 -888888.000 -88 -888888.000 …
```

Fix to assign proper radar rv/rf errors to avoid excessive check_max_iv prints

---

var/da/da_minimisation/da_get_var_diagnostics.inc
var/da/da_minimisation/da_minimisation.f90
var/da/da_setup_structures/da_scale_background_errors.inc
var/da/da_setup_structures/da_setup_be_regional.inc

TYPE: bug fix
KEYWORDS: WRFDA, cloud control variable, outerloop
1. Add cloud and w control variables that were not included in the original BE rescaling code.
2. Only root processor writes out the intermediate file for BE rescaling.
3. Change the log message from Jb factor used() to var_scaling used().
M       var/da/da_minimisation/da_get_var_diagnostics.inc
M       var/da/da_minimisation/da_minimisation.f90
M       var/da/da_setup_structures/da_scale_background_errors.inc
M       var/da/da_setup_structures/da_setup_be_regional.inc
1. Results remain the same when var_scaling[6..11] do not vary with outerloops.
2. WRFDA regtests with intel 17.0.1 on cheyenne passed.
RELEASE NOTE:
Bug fix for …

Fix for cloud/w BE rescaling for not-first outerloops

---

dyn_em/module_small_step_em.F

TYPE: bug fix
KEYWORDS: HVC, hybrid, coefficients, half, full
SOURCE: internal, found by May Wong (NCAR)
In the original implementation of the hybrid vertical coordinate (v3.9), the
cpp directives utilized capitalization to differentiate between the use
of full-level (c1f, for example) and half-level (c1h, for example) 1d
coeffieicent arrays. For several locations in the small_step, the use of the
"mu" array with the "t_2" field incorrectly was assigned to full levels.
In three statements where the half-level t_2 array is used, the half-level
c1h and c2h 1d arrays replace the incorrect full-level 1d arrays c1f and c2f.
ISSUE:
Fixes #604
M	dyn_em/module_small_step_em.F
1. Look at diffs of fields. 
a. theta fixed (new code) …

Fix half vs full 1d coeffs for HVC in small_step

---

dyn_em/start_em.F

TYPE: bug fix
KEYWORDS: use_theta_m, moist theta
SOURCE: Several users pointed out problem, solution from Wei Wang
In the porting of the theta_m mods from being ONLY inside of the WRF model
to being part of the initialization step in the real and ideal programs,
the start_em file was modified. Part of the computation of the pressure
involves dry_theta * ( 1 + rv/Rd Qv ).
When the incoming data from the real or ideal program has the namelist
option use_theta_m==1, then the factor ( 1 + Rv/Rd Qv ) is already included
in the theta field. An IF test based on the namelist option use_theta_m
tests whether or not to assign the factor qvf as either 1 or ( 1 + Rv/Rd Qv ).
ISSUE:
Fixes #608
M	dyn_em/start_em.F
1. Differences at 0h …

Remove repeated factor of (1+Rv/Rd Qv) in start_em, p computation

---

test/em_real/namelist.input.fire

TYPE:  Text only
KEYWORDS: WRF-FIRE, namelist
DESCRIPTION OF CHANGES: In the sample namelist.input.fire that comes with the released WRF.tar file, the syntax for some variables is different than the ones in the registry.fire. 
A few namelist options were spelled incorrectly in the sample namelist.input.fire. This PR corrects the spelling. I compared the namelist options with those in registry.fire to make sure they are correctly spelled in the sample namelist.
M test/em_real/namelist.input.fire
TESTS CONDUCTED: Regression test is not necessary

Correct a few wrong namelist options in namelist.input.fire

---

phys/module_sf_noahmpdrv.F

bug fix: incorrect PSISAT sign change introduced with groundwater fixes
TYPE: bug fix
PSISAT sign change incorrectly introduced in Noah-MP subroutine noahmp_init (PR #287; commit 45d1945c). This sign change is already taken into account in the equation where it is used and should not have been added. The sign change added to subroutine groundwater_init in PR #287 is correct.
Only affects the initialization of frozen soil but can have large effect on soil temperature and moisture simulations when soil temperature is below freezing.
M       phys/module_sf_noahmpdrv.F
1. Summer and winter 24-hr case

bug fix: incorrect PSISAT sign change introduced with groundwater fixes

---

phys/module_sf_noahmplsm.F

TYPE: bug fix 
Change in Noah-MP subroutine SNOWH2O to update snow liquid water as water passes to layers below. Without this fix, more water is allowed to move to layer than pore space available. This results in unrealistic snow density values during melt season.
Mods to release-v4.0.1, not develop. Replaces PR #632 
M phys/module_sf_noahmplsm.F
Summer and winter 24-hr case

bugfix: prevent excessive snow liquid water movement 

---

phys/module_sf_noahmpdrv.F

TYPE: bug fix
Bug fix introduced in #399 where divide by zero can occur if LAI is zero. Added check in IF statement. This calculation is only for diagnostics so shouldn't change answers, except to prevent model crash.
Mods to release-v4.0.1, not develop. Replaces PR #633 
M phys/module_sf_noahmpdrv.F
Summer and winter 24-hr case

bugfix: fix potential divide by zero in stomatal resistance diagnostic

---

phys/module_sf_noahmplsm.F

TYPE: bug fix
Change in Noah-MP subroutine RAGRB to limit leaf aerodynamic resistance (RB). Currently there is no lower limit. This can result is very large canopy exchange coefficients and subsequent canopy fluxes. Can result in model blow-up with high wind speed.
Mods to release-v4.0.1, not develop. Replaces PR #634 
M phys/module_sf_noahmplsm.F
Summer and winter 24-hr case

bugfix: add limit to Noah-MP leaf aerodynamic resistance

---

phys/module_sf_noahmplsm.F

TYPE: bugfix
One Noah-MP runoff option (opt_run=2) creates a 100-layer soil using soil properties from Noah-MP parameters data structure. Fix possible/likely array out of bounds by assuming homogeneous soil with depth. A more general fix should be completed later.
Mods to release-v4.0.1, not develop. Replaces PR #635 
M phys/module_sf_noahmplsm.F
Summer and winter 24-hr case

bugfix: array out of bounds occurs for certain Noah-MP options

---

phys/module_mp_thompson.F

TYPE: bug fix
KEYWORDS:
SOURCE: Greg Thompson (NCAR)
1. Line 2694:  bug fix; has been wrong in the code by skipping a reduced number of rain for approx 10 years
2. Increased maximum ice concentration permitting 10000/Liter whereas previously 500/Liter upper limit.
3. Line 3036:  minor bug fix.
4. A series of new checks using "EQV" construct to provide some loops to be skipped.
5. Minor changes to lower limits of precip to eliminate really tiny values (~1E-9).
6. Removed extraneous ELSE blocks in reading lookup tables; also removed a comment block.
7. New line number 3498 and 3500 eliminate air density - fix for extreme model top heights by Tanya S. for FIM model (and MPAS).
8. New line number 4937 - set a higher value for min dust concentration when nucleating ice. …

several Thompson BF: reduced rain, increased ice conc, remove tiny precip, allow high model tops, higher min dust conc

---

run/README.namelist

KEYWORDS: README.namelist
Modify README.namelist so that users can copy options directly. Previously the ";" character was used to denote an inline comment. Now, the "!" character is used, which is the default comment character for Fortran namelist files.
TESTS CONDUCTED:  Not necessary

Modification of README.namelist

---

chem/module_optical_averaging.F
phys/module_data_gocart_dust.F

TYPE: bug fix
KEYWORDS: optical_prep_gocart, volume-averaged refractive index, WRF-Chem
SOURCE: Alexander Ukhov, KAUST
Problem: It was found that the dust particles having radii less than 0.46 microns are not accounted in the calculation of volume-averaged refractive index needed by Mie calculations. Since the finer particles have a bigger influence on AOD in comparison to the coarser particles (per unit of mass), it eventually led to the underestimation of the AOD. 
Solution: 0.46 was replaced by 0.1, where the value 0.1 corresponds to the beginning of the first GOCART bin (radii: 0.1-1.0 μm).
Left column (1-5) - GOCART dust bins.
other columns are 8 MOZAIC size bins.
dustfrc_goc8bin BEFORE CORRECTION:
dustfrc_goc8bin AFTER CORRECTION:
M …

Bug fix in optical_prep_gocart

---

doc/README.crtm

KEYWORDS: readme, CRTM, coefficients
Added README.crtm instructing user/developer how to obtain CRTM coefficient files.
ISSUE: Addresses issue #330 
A       doc/README.crtm
TESTS CONDUCTED: not necessary
RELEASE NOTE: The CRTM coefficient files are binary and cannot be tracked by git and are placed on the WRFDA website for download (http://www2.mmm.ucar.edu/wrf/users/wrfda/download/crtm_coeffs.html) starting from the WRFDA release v4.0. A copy is also available under ~wrfhelp on the NCAR cheyenne supercomputer (for internal use).

README for CRTM coefficient procedure

---

arch/Config.pl
compile

TYPE: bug fix
KEYWORDS: WRFDA, compile, RTTOV-v11, HDF5
1. Add two more libs (hdf5hl_fortran and hdf5_hl) to CONFIGURE_HDF5_LIB_PATH
2. Add one more lib (rttov11_hdf) to RTTOV_LIB when RTTOV-v11 is built with HDF5-enabled.
**Note that this fix is specific to WRFDA with RTTOV-v11 and
should NOT be merged to the develop branch that has different RTTOV-v12 implementation.**
M       arch/Config.pl
M       compile
1. DA compiles after the fix.
2. Without the fix, users have to manually edit configure.wrf to add missing libs to LIB_EXTERNAL in order to compile.

Fix DA compilation when RTTOV-v11 is built with HDF5-enabled

---

chem/KPP/mechanisms/mozart/mozart.def
chem/KPP/mechanisms/mozart_mosaic_4bin/mozart_mosaic_4bin.def
chem/KPP/mechanisms/mozart_mosaic_4bin_aq/mozart_mosaic_4bin_aq.def
chem/KPP/mechanisms/mozcart/mozcart.def
chem/KPP/mechanisms/t1_mozcart/t1_mozcart.def

TYPE: bug fix
KEYWORDS: chemical reaction rate constant
Correct the reaction rate constant for reaction:
SO2 + OH -> SO4         (tag usr23)
The prior code had the expression:
fc    = 3.e-11_dp * (300._dp/temp) ** 3.3_dp
which has been corrected to:
fc    = 3.e-31_dp * (300._dp/temp) ** 3.3_dp
Although the coefficient change from 3.e-11 to 3.e-31 is large
this change is only part of a complex expression for the rate
constant and leads to much smaller and expected changes in
the chemical species SO4 and OH. (See pdf at end of this listing)
This change applies only to the following chem_opt options:
MOZART_KPP,MOZCART_KPP,T1_MOZCART_KPP,MOZART_MOSAIC_4BIN_KPP,MOZART_MOSAIC_4BIN_AQ_KPP
M …

BF: chemical reaction rate change: e-11 -> e-31

---

phys/module_cu_mskf.F

TYPE: bug fix
KEYWORDS: write syntax, character string continuation
SOURCE: Alexander Davies (US Naval Academy)
1. Remove comma after write statement.
2. Clean up continuation of string across more than one line.
M	phys/module_cu_mskf.F
1. Without mods, code does not compile on Cray with ftn.
2. With mods, code compiles and runs.

Bug fix: Cray compiler, character string, module_cu_mskf.F

---

phys/module_mp_morr_two_moment_aero.F

TYPE: bug fix
KEYWORDS: cray, do loop, real
SOURCE: Alexander Davies (US Naval Academy)
An index for a loop counter and also used for an array index was declared as
a real value. This is changed to an integer. There is no other place than the
do loop or the array index that this value was used.
M   module_mp_morr_two_moment_aero.F
1. Code does not compile without this mod.
2. With this mod, the code compiles.

Bug fix: cray, do loop index is real, module_mp_morr_two_moment_aero.F

---

Registry/Registry.EM_COMMON

TYPE: bug fix
KEYWORDS: input_from_file, use_theta_m, max_dom, mythical 1-character change
SOURCE: Jordan Powers (NCAR)
At the initial time of the WRF model, the perturbation dry potential
temperature field ("T" in the netcdf file) for d02 (and greater) is
identically zero when the initial conditions for the fine-domain
fields are manufactured via horizontal interpolation (in the WRF
Registry, this horizontal interpolation at the initial time is
activated through the "d" switch in the nest options).
This error is noticed when
```
&time_control
input_from_file                     = .true.,.false.,
/
```
```
&domains
max_dom                             = 2,
/
```
```
&dynamics
use_theta_m                        = 1,
/
```
This modification is diagnostic only. This …

Fix zero-valued d02 dry potential temp pert, from horiz interpolation

---

Makefile
compile

TYPE: bug fix
KEYWORDS: single column model, SCM, MPI
SOURCE: found by @sodoesaburningbus
The logic is already in place to correctly detect and stop MPI builds when
running a 2d case. Use the same logic for the 1d case of the SCM.
Instead of searching for the string "2d", search for the string "scm".
ISSUE:
Fixes #622 "WRF SCM 3x3 stencil too small for MPI runs"
M   Makefile
M   compile
1. Without this mod, the code successfully builds an MPI version of WRF. At run-time, this fails.
2. With this mod, the user is stopped at the build step:
```
------------------------------------------------------------------------------
WRF CONFIGURATION ERROR
The em_scm_xy case requires a build for only single domain.
The em_scm_xy case …
```

Remove MPI build option from single column model (SCM)

---

phys/module_cu_g3.F

TYPE: bug fix
KEYWORDS: grell, G3, cu_physics, random seed, array, bounds, bug, module_cu_g3, cup_forcing_ens_3d
SOURCE: bug found by and fix suggested by Jeremy Silver (U Melbourne)
A user reported that when configuring with a particular set of debug flags, they were getting array bound exceedance errors in subroutine cup_forcing_ens_3d inside module_cu_g3.F. They offered a seemingly legitimate fix that helped them get past it.
ISSUE: This PR fixes issue referenced in wrf-model/WRF#623 "Array bounds issue in cu_g3 random number seed"
closes:#623
M     phys/module_cu_g3.F
TESTS CONDUCTED: Verified that the code compiles after the modification.
RELEASE NOTE: A minor modification was made to the Grell 3 scheme to prevent random seed array …

bug in G3 cu_physics - random seed array bounds errors

---

.github/CODEOWNERS

KEYWORDS: CODEOWNERS
This is the start of a list for shared and individual responsibility
for files and directories. When a PR is issued that modifies one of
the known files or files within a known directory (and required
reviews are enabled on that branch), then an automatic request for
review is issued to the code owners.
CODEOWNERS file is linked to the GitHub via the following teams:
* physics
* shared_physics
* da
* chem
* hwrf_dev
* arw_dev
* infrastructure
* global_owner
* fire
Replaces PR #437 "Add CODEOWNERS file to .github directory". The fork and branch were deleted, so amending was not easy. 
More info:
```
https://help.github.com/articles/about-codeowners/
```
M	     .github/CODEOWNERS
TESTS …

Add CODEOWNERS file to .github directory

---

var/da/da_define_structures/da_random_seed.inc

TYPE: bug fix
KEYWORDS: WRFDA, random seed array size, da_message
When running WRFDA in RANDOMCV mode and put_rand_seed=.false.,
the formatted write of the random number seed array has a preceding count of 10.
Depending on compiler versions, the seed array size can be larger than 10.
In that case, the error message is
```
At line 2938 of file da_define_structures.f
Fortran runtime error: End of file
```
The solution is to build a run-time format string based on the seed_size.
M       var/da/da_define_structures/da_random_seed.inc
With gnu/7.2.0, the size of the random_seed array is 33, RANDOMCV ran after the format fix.
RELEASE NOTE: Bug fix for WRFDA RANDOMCV when put_rand_seed=.false. and the …

Fix DA formatted print of random_seed array when put_rand_seed=false

---

var/da/da_obs_io/da_read_omb_tmp.inc
var/da/da_obs_io/da_write_obs.inc

KEYWORDS: WRFDA, gts_omb_oma, time_slot
For diagnostic purpose, write out additional time slot information in the gts_omb_oma output
so that innovation and residual information can be distinguished and evaluated for each time slot.
Since the additional i8-formatted integer is written out in the end of an existing line,
it should not have impact on users' existing programs that read the ascii gts_omb_oma.
M       var/da/da_obs_io/da_read_omb_tmp.inc
M       var/da/da_obs_io/da_write_obs.inc
1. The same NCL script can process both old and new gts_omb_oma files.
2. WRFDA regtests on Cheyenne with intel 17.0.1.
RELEASE NOTE: Enhance the gts_omb_oma diagnostics by appending time slot …

Add time slot information in DA gts_omb_oma diagnostics

---

share/module_check_a_mundo.F

TYPE: bug fix
KEYWORDS: mynn, bug, shcu, ishallow, bl_mynn_edmf, check_a_mundo, fatal
Problem: 
The MYNN PBL has the EDMF (bl_mynn_edmf=1) option turned on by default. In check_a_mundo when the bl_mynn_edmf=1, (even if the user specifically asks for the shallow cumulus option to be activated (sh_cu=1)), the shallow cumulus scheme is simply turned off. 
Solution:
The check_a_mundo test is modified to give a fatal error when bl_mynn_edmf=1 AND  sh_cu=1 so that a user will not overlook this message in the log file.
ISSUE: 
This addresses the issue referenced in wrf-model/WRF#617 "MYNN PBL can't be used with SHCU"
closes:#617
M     share/module_check_a_mundo.F
TESTS CONDUCTED: Verified that code builds with modification. …

MYNN PBL shcu combo bug

---

README
inc/version_decl

KEYWORDS: Release version, README
Update both the top-level README and inc/version_decl to prepare for WRF-v4.0.2 release.
M       README
M       inc/version_decl
TESTS CONDUCTED: not needed

Prepare for the release of WRF-v4.0.2

---

chem/module_optical_averaging.F

TYPE: bug fix
KEYWORDS: optical_prep_gocart, volume-averaged refractive index, mass redistribution, AOD, WRF-Chem
SOURCE: Alexander Ukhov, KAUST
Problem: There is a code in _optical_prep_gocart_ procedure which calculates the contribution of the dust and sea salt bins into the MOZAIC bins. The code uses the interpolation over the linear axis but should use the interpolation over log axis. The similar bug was fixed In #536 "fixed coefficients for calculation of PM10 and PM2.5. For GOCART aerosol scheme".
Solution: use interpolation over the log axis instead of linear axis.
Effect: Interpolation over log axis changes the mass redistribution between the MOZAIC bins.
It leads to the increased contribution of the small dust and sea salt particles into the Aerosol …

mass redistribution between GOCART dust/sea salt and MOZAIC bins

---

phys/module_sf_noahdrv.F

TYPE: bug fix
KEYWORDS: NOAH LSM, divided by zero
DESCRIPTION OF CHANGES: when the leaf area index is derived from static input data (rdlai2d=true), the value could be zero at certain areas. This leads to extremely large, unrealistic HFX and the model eventually crashed.  
M       phys/module_sf_noahdrv.F
One case has been tested. The case crashed immediately without the fix. The same case can be done successfully  with the fix. 
Reggie passed.

Bug fix in Noah LSM - divide by zero

---

dyn_em/module_first_rk_step_part1.F
dyn_nmm/module_PHYSICS_CALLS.F
phys/module_sf_ruclsm.F
phys/module_surface_driver.F

TYPE: bug fix
KEYWORDS: MYJ PBL with RUC LSM, Leaf Area Index
SOURCE: Tanya Smirnova, NOAA/ESRL/GSD
1. The MYJ and QNSE PBLs use surface water vapor mixing ratio as low boundary condition for moisture and compute it from the latent heat flux, while other PBL schemes use directly latent heat flux as low boundary condition. Therefore, there is a special computation of latent heat flux inside RUC LSM to get correct surface Qv. In original code the check in the surface driver is made on the option of surface layer scheme, and not PBL scheme. Therefore, if MYJ PBL is not used together with MYJ surface layer scheme, there will be inaccuracy in low boundary condition for moisture.
2. The second bug is in the computation of LAI for particular day when LAI parameter is …

Bug fix in RUC LSM with MYJ PBL. Bug fix in RUC LSM for seasonal variation of LAI with .rdlai2d=.false.

---

run/README.namelist

KEYWORDS: README.namelist
DESCRIPTION OF CHANGES: The option mp_physics=40, which is missing previously, is added to README.namelist.  
LIST OF MODIFIED FILES
M      run/README.namelist
TESTS CONDUCTED: not needed   
RELEASE NOTE:  Don't need to include

Add the option mp_physics=40 to README.namelist

---

dyn_em/module_initialize_real.F

TYPE: bug fix
KEYWORDS: urban, land use, MODIS, REAL, NLCD
Problem: 
When NLCD and MODIS are used together, the land use type will be adjusted for all grid cells where  the urban fraction is greater than 0.5 in the real program. Due to an incorrect application of DeMorgan's Law, all of the urban land use categories became category 13. While 13 for MODIS is indeed urban, 13 is not the NLCD high-resolution urban categories: 24, 25, 26. These NLCD urban categories should be preferentially used if available.
Solution:
The logic is supposed to be:
if ( the grid point is urban (based on percentage) ) and 
( the grid cell is not one of the special NLCD points ) then 
reset this to the MODIS urban category.
```
if (urban>0.5)
if ((cat != 24) AND cat(!=25) …
```

Fix adjustment of urban type in REAL program when NLCD and MODIS used together

---

main/module_wrf_top.F

TYPE:  Bug fix 
KEYWORDS: WRF Plus, module_wrf_top.F, OpenMP error
SOURCE: Carlos Ross (DFM Consultores)
Problem: 
Getting an error when compiling WRF Plus with Intel compiler
```
../main/module_wrf_top.f90(756): error #6099: An ENDDO statement occurred without a corresponding DO or DO WHILE statement.
```
A DO loop in wrf_adtl_check_spot had a syntax error and a formulation error for one of the 
OpenMP parallel directives. 
1. A unnecessary trailing "&" on the last OpenMP directive caused the following  first line of the
Fortran DO loop to not be recognized.
2. The OpenMP loop was missing closing directive, "!$OMP END PARALLEL DO",  after the DO loop.
Solution:
Remove the trailing "&" and add in the missing OpenMP directive after the DO loop.
I wasn't trying to …

Error compiling WRF Plus in WRF 4.0.2 on module_wrf_top.f90

---

frame/module_quilt_outbuf_ops.F

KEYWORDS: quilt, module_quilt_outbuf_ops, write, debug
SOURCE: Kevin Thomas (CAPS/University of Oklahoma)
User requested that we remove unnecessary print-out statements from the module_quilt_outbuf_ops.F file. As these used "wrf_message" for I/O, there were no checks to determine whether the prints were requested via debug_level. This created hundreds of lines of junk in the output files. This modification changes the call from "wrf_message" to "wrf_debug" (200) to prevent this.
M     frame/module_quilt_outbuf_ops.F
TESTS CONDUCTED: Verified that code builds and runs okay. No impact.

change calls from wrf_message to wrf_debug in module_quilt_outbuf_ops

---

.github/CODEOWNERS

KEYWORDS: CODEOWNERS, hydro, WRF-hydro, README.hydro
DESCRIPTION OF CHANGES: Adding the hydro team to the CODEOWNERS file so that they will have access to approve WRF-hydro-releated PR's. They now have access to the full hydro/ directory and the doc/README.hydro file.
M     .github/CODEOWNERS
TESTS CONDUCTED: no tests - text only

Adding hydro team to the CODEOWNERS file

---

var/da/da_main/da_solve.inc

TYPE: bug fix
KEYWORDS: WRFDA, warning print
cloud_cv_options is reset to be 0 in var/da/da_main/da_solve.inc when cv_options = 3.
The second line of the warning messages stating that the cloud_cv_options = 0 were not originally printed.
M       var/da/da_main/da_solve.inc
1. After the fix, the intended full warning messages are printed.
```
--------------------------- WARNING ---------------------------
WARNING FROM FILE:  da_solve.inc  LINE:     205
Cloud control variables are not implemented for cv_options = 3
Resetting cloud_cv_options = 0 for cv_options = 3
---------------------------------------------------------------
```
RELEASE NOTE: (too minor to be mentioned)

Fix DA warning message for cv_options=3 and cloud_cv_options>0

---

Registry/registry.var

KEYWORDS: WRFDA, use_html default, registry.var
With default use_html=.true., HTML <a> href attribute constructed using another
namelist documentation_url (default=http://www.mmm.ucar.edu/people/wrfhelp/wrfvar/code/trunk)
is added for the file mentioned in the warning and error messages.
For example:
```
--------------------------- WARNING ---------------------------
WARNING FROM FILE: <A HREF="http://www.mmm.ucar.edu/people/wrfhelp/wrfvar/code/trunk/da_solve.html">da_solve.inc</a>  LINE:     205
```
```
---------------------------- FATAL ERROR -----------------------
Fatal error in file: <A HREF="http://www.mmm.ucar.edu/people/wrfhelp/wrfvar/code/trunk/da_solve.html">da_solve.inc</a>  LINE:     216
```
Since the URL is …

Change DA namelist use_html default from true to false

---

share/module_soil_pre.F

KEYWORDS: module_soil_pre, num_soil_layers, error
DESCRIPTION OF CHANGES: When num_soil_layers is incorrect, an error message tells the user to "change this in the namelist." Since V4.0, num_soil_layers has been removed from all of the default namelists, as it was considered redundant (since sf_surface should be taking care of this already). This likely will not be stumbled upon for most LSM schemes, but may for the RUC LSM, as soil layers can vary. Asking the user to "change" something in the namelist that does not exist, may be confusing. I modified the wording to make this more clear for all LSM options.
M     share/module_soil_pre.F
TESTS CONDUCTED: Verified that it compiles. No additional tests - text change only.

Reworded module_soil_pre error message for incorrect num_soil_layers

---

Registry/Registry.EM_COMMON
dyn_em/module_initialize_real.F
share/module_soil_pre.F

KEYWORDS: soil moisture, initialization, RUC LSM
SOURCE: Tanya Smirnova (GSD/ESRL/NOAA)
Issue: This enhancement was motivated by the WRF user's request who initializes RUC soil moisture from the ECMWF soil moisture. The soil moisture adjustment code uses specific Noah's vertical structure, and therefore does not work for ECMWF initialization. Plus, the user cycles soil moisture and does not need any adjustment.
Solution: Flag_sm_adj is added to turn on/off soil moisture adjustment when RUC LSM. The default value is 1 = do soil moisture adjustment.
M       dyn_em/module_initialize_real.F
M       share/module_soil_pre.F
Tested in RAP model at GSD/ESRL

Add a flag that turns on/off soil moisture adjustment

---

dyn_em/module_diffusion_em.F
dyn_em/module_first_rk_step_part2.F

TYPE: bug-fix
KEYWORDS: LES option, use_theta_m=1, V4.0 bug in surface flux fixed, calculate_N2 minor change
SOURCE: internal plus Xu Zhang (Shanghai Typhoon Institute)
When use_theta_m was updated to V4.0, diffusion was also applied to theta_m. However the surface flux was not modified to include a QFX term. This leads to a cooler PBL than in V3.9 with use_theta_m=1 and is incorrect. The fix is to add a QFX term that restores temperatures to correct values.
ISSUE: none posted
M       dyn_em/module_diffusion_em.F
M       dyn_em/module_first_rk_step_part2.F
No WTF yet. 
LES tests with fix have corrected the problem and give use_theta_m=1 results more like V3.9.1.
Theta profile plots show the cool anomaly with the old …

LES fix for use_theta_m=1

---

dyn_em/module_diffusion_em.F

TYPE: bug fix
KEYWORDS: Stability N2 in LES
calculate_N2 routine contains 1.61 instead of 0.61 when calculating moist version of N2. This has been since the beginning. Extremely small effect on results. Affects both use_theta_m=0 and 1.
ISSUE: no issue reported
M       dyn_em/module_diffusion_em.F
No WTF. Compare use_theta_m=0 before and after (see fig of theta difference in LES case after 4 hours).
RELEASE NOTE: 
LES calculation of N2 slightly corrected. Very small effect.

Fix N^2 calculation (1.61->0.61) for LES

---

phys/module_microphysics_driver.F

KEYWORDS: 
microphysics_driver, github compatibility
Reduce lines over 150 characters to less than 150 characters (2 comment lines only).
When git shows subroutines in its modification listing it is fooled by long lines.
This always shows up with mods in the microphysics_driver (e.g. see recent Jensen PR). There may be others.
ISSUE: none reported
M       phys/module_microphysics_driver.F
RELEASE NOTE: None

reduce lines to less than 150 characters for github

---

phys/module_sf_sfclay.F

KEYWORDS: wrf, mpas, unification, mm5
DESCRIPTION OF CHANGES: There were very minor modifications made to this file to make sure it's identical to the modified file submitted as a pull request to the MPAS repository. Mods consist of spacing and including an MPAS comment.
M   phys/module_sf_sfclay.F
TESTS CONDUCTED: code compiles and runs, with bit-for-bit results to unmodified code.

identically matching MM5 code with MM5 MPAS PR 

---

phys/module_mp_wsm6.F

KEYWORDS: wsm6, mp_physics, wrf, mpas, unification
DESCRIPTION OF CHANGES: Added 'optional' to the variable refl_10cm inside subroutine wsm6, so that it would work with MPAS.
M    phys/module_mp_wsm6.F
TESTS CONDUCTED: code compiles and gives bit-for-bit results before and after modifications.

WSM6 change of refl_10cm to "optional" to work with mpas

---

dyn_em/module_initialize_real.F

TYPE: bug fix
KEYWORDS: surface_input_source, isltyp, landmask
SOURCE: internal (reported by many users, including Priscilla Mooney from Norway)
To accommodate users who would like to change _LU_INDEX_ after running geogrid program, we changed namelist surface_input_source from default value of 1 (recomputing dominant categories in real) to 3 (using dominant categories from geogrid) in v3.8. 
Unfortunately, we neglected to consider in the v3.8 fix that when dominant categories for land and soil are recomputed in real, the real program also does mismatch checks: ensuring that the lower resolution _ISLTYP_ matches with _LANDMASK_ data. This check in real has two two effects:
1. the actual _ISLTYP_, _IVGTYP_, and _XLAND_ can be different from that from …

Fix mismatch isltyp and landmask 

---

dyn_em/solve_em.F
share/module_check_a_mundo.F

TYPE: bug fix
KEYWORDS: nwp_diagnostics, do_radar_ref
When we introduced 'do_radar_ref' namelist to control whether radar reflectivity will be computed by a microphysics,  we decided to do this calculation only at model history output time. But this broke one diagnostic output when nwp_diagnostics is turned on. The diagnostic output is the maximum lowest level reflectivity in a time interval, which requires radar reflectivity to be computed at every model time step. This PR fixes it. It turns on do_radar_ref and makes radar reflectivity calculation at every model time step is nwp_diagnostics is on. 
M   dyn_em/solve_em.F
M   share/module_check_a_mundo.F
Tested with various switches on and off to make sure …

make refl_10cm available if nwp_diagnostics is on

---

phys/module_sf_bep_bem.F
phys/module_sf_urban.F
run/URBPARM.TBL

Capability to prescribe buidling fraction for air conditioning in BEM urban model
KEYWORDS: urban, BEM
SOURCE: Xiaoyu Xu (IUM), Michael Barlage (NCAR)
Two urban parameter tables options are added to prescribe the fraction of building (BLDAC_FRC) and fraction of floors in a building (COOLED_FRC) that have air conditioning. 
M       phys/module_sf_urban.F
M       phys/module_sf_bep_bem.F
M       run/URBPARM.TBL
1. 24-hour winter CONUS simulation produces no difference; with fractions set to 1, summer simulation produces machine precision differences 5 hours into simulation
2. Small, GNU-only regtest OK on cheyenne. This used serial / openmp / MPI, the full suite of builds, a single test case per build, and …

Capability to prescribe building fraction for air conditioning in BEM urban model

---

Registry/Registry.EM_COMMON
main/depend.common
run/README.tslist
share/Makefile
share/module_string_tools.F
share/wrf_timeseries.F
share/wrf_tsin.F

KEYWORDS: tslist, ideal, i/j, W, cell centers, tslist_ij, tslist_interp, time-series
SOURCE: Pat Hawbecker (NREL)
1. This code modification provides a way to generate time-series output for 3d idealized cases, based on the i/j location. The wrf_tsin.F and wrf_timeseries.F files are modified so that if map_proj == 0, tslist will read in integers (as opposed to floats) and assign those to grid%itsloc and grid%jtsloc. Therefore if it's an idealized case, tslist will expect coordinates instead of lat/lon. 
2. This modification also allows a user to use either lat/lon or i/j coordinates for time-series output locations with real data cases. This is now based on the header of tslist. If a user wishes to output at i,j locations, they would replace the …

new tslist options for wider variety of usage

---

Registry/Registry.NMM

TYPE: bug fix
KEYWORDS: tslist, NMM
The tslist_ij logical flag is used in the part of the timeseries code
that is seen by both NMM and ARW. The identical line defining the tslist_ij
flag in the Registry.EM_COMMON file is put into the Registry.NMM file.
This change means that the derived namelist variable tslist_ij is now defined in the
Registry.NMM.
No effort is made to test or support any new tslist functionality in NMM.
M   Registry/Registry.NMM

BF: tslist ij mods need to have NMM Registry support

---

var/da/da_update_bc/da_update_bc.f90

KEYWORDS: Moist Theta, DA, update_bc
1.  Following PR #750 (sha 1a93c97a142), Moist theta now works with WRFDA for non-4DVAR mode. WRFDA analysis file (i.e., wrfvar_output) contains both 'T' (dry theta perturbation) and 'THM' (moist theta perturbation). They are identical when use_theta_m=0, and different when use_theta_m=1. Note that wrfbdy file includes only the variable 'T', which represents either dry or moist theta perturbation according to 'USE_THETA_M'. 
2. da_update_bc program only read 'T' from the analysis and wrfbdy files and update 'T' in wrfbdy. In the case of use_theta_m=1, 'T' in wrfbdy is moist variable and 'T' in the analysis is dry variable. Modified code now reads 'THM' from the analysis file when use_theta_m=1. …

Adjust da_update_bc for Moist Theta

---

test/em_real/examples.namelist

KEYWORDS: vertical refinement, README, radiation, HVC
In the description of the vertical refinement option, the available radiation schemes are now correctly
listed as RRTM LW only and Dudhia SW only. Also, the user is reminded that the vertical 
refinement does not work with the hybrid vertical coordinate.
M test/em_real/examples.namelist
Text only, no testing required.

Correct README for vert refinement: RRTM + Dudhia rad only, no HVC allowed

---

share/input_wrf.F

TYPE: bug fix
KEYWORDS: input_wrf.F, error messages
One of the changes due to students chatting with us at the WRF Tutorial ...
When a mismatch between domain sizes (in grid units) was identified by the input_wrf.F file, previously the error message referred to a variable that was neither in the namelist or in the input file (such as IDE, JDE, KDE). Also, if any of the dimensions were inconsistent between the namelist and the input file, all three of the i,j,k indices were all printed out. Basically, "user, figure this out".
Now the error message is specific to the dimension, and the printed names of the offending dimensions are those that are in the namelist and in the metadata of the input file.
```
d01 2000-01-24_12:00:00  input_wrf.F: SIZE …
```

BF input_wrf.F: error messages now match nml variable names

---

dyn_em/module_initialize_real.F

TYPE: bug fix
KEYWORDS: real, full-levels, base pressure, model top
Problem:
In the module_initialize_real file, the `php` array is temporarily used to hold the base state pressure on full levels. While the correct `c3` and `c4` for full-levels are used, the DO loop only extends up to `kte-1`. This leaves the top level pressure as a zero value.
Solution:
Outside of the k-index DO loop, an assignment is directly made to the `kte` index for the `php` field. This value is necessarily assigned as the model lid, `p_top`.
Impact:
This incorrect `php` array is only used when a user has asked for a rebalancing between the surface pressure field and the 500 mb height field, the `adjust_heights` option. This option is only valid if the input data is …

In real, supply base pressure at full levels at model top

---

compile

TYPE: bug fix
KEYWORDS: compile, -j, parallel
SOURCE: Found by Michael Duda (NCAR), internal fix
Problem:
The user is able to specify directly the env variable for a parallel make:
```
setenv J = "-j 4"
```
The user is supposed to be able to also specify this on the command line for
the compile script:
```
compile em_real -j 4
```
However, depending on the order of the arguments, the intended number of parallel builds 
that are selected is incorrectly assigned in the compile script. What is used is ALWAYS the
second argument of `$argv`.
Solution:
The arguments, `$argv`, to the compile command can either be processed sequentially
via the `$argv` list and a `shift` command, or the entire `$argv` can be used
in a `foreach` loop. The script intermingled these methods. …

Fix -j parallel make option for compile script

---

phys/module_diag_zld.F

TYPE: bug fix
KEYWORDS: AGL, ZLD, diagnostics
Problem:
The height-level diagnostic routine has an option that the user may specify
either the height above mean sea level or the height above ground level (AGL).
If a user chooses 50 m AGL, the height field should be almost exactly 50 m
over the ocean, and almost exactly 50 m greater than the topo over land.
This is not what was happening.
Solution:
The height trapping levels (in the WRF model, (ph+phb)/g) should be identical
to the WRF model levels (they were not). The AGL level to interpolate to, should be
the requested AGL level + the topo value (it was not).
M   phys/module_diag_zld.F
This is purely a diagnostic, and does not impact the model simulation. A …

BF: AGL interpolation incorrect for zld diagnostics

---

phys/module_ra_goddard.F

TYPE: bug fix
KEYWORDS: radiation, Goddard, OpenMP
Problem:
An OpenMP failure (invalid access) as soon as the model enters the the Goddard radiation code 
(the same top-level routine handles both the LW and SW schemes).
Solution:
The radiation driver has a large OpenMP loop. The Goddard radiation scheme is among those 
schemes that is inside of this larger OpenMP loop. Traditionally, the WRF model does not support 
nested threaded regions. The OpenMP directives (only a single block at the top of the Goddard 
radiation scheme) are now "ifdef'ed" out. They are not removed as this radiation code is used by 
other modeling systems, and they apparently have a different threading paradigm compared to WRF 
(inside the physics scheme as opposed to outside …

Remove Goddard radiation nested OpenMP regions

---

chem/module_gocart_settling.F

TYPE: bug fix
KEYWORDS: GOCART, WRF-Chem, dust and sea salt gravitational settling
SOURCE: Alexander Ukhov, KAUST
Problem: It was found that the dust (and sea salt) mass balance is violated in routine _settling_ (module module_gocart_settling.F). In particular, the total mass of the dust (and sea salt) is increasing, when the dust (and sea salt) settles from the upper to the lower layers. In the code the dust (and sea salt) mixing ratios are transfered between the layers, which is not correct, since the air density is changing.
Solution: the discretization scheme was replaced to the one, which accouts for air density change and allows to conserve the dust (and sea salt) total mass.
chem/module_gocart_settling.F
TESTS CONDUCTED: To validate …

bug fix in GOCART gravitational settling

---

chem/module_data_mgn2mech.F

TYPE: bug fix
KEYWORDS: WRF-Chem, MEGAN, CRIv2R5
SOURCE: Douglas Lowe (University of Manchester, UK), Scott Archer-Nicholls (Cambridge University, UK)
DESCRIPTION OF CHANGES: The alpha-pinene and beta-pinene products from the MEGAN
biogenic emission scheme were being mixed up when passed
to the CRIv2R5 chemical scheme. This has now been corrected.
ISSUE: None
LIST OF MODIFIED FILES: chem/module_data_mgn2mech.F
TESTS CONDUCTED: No tests conducted.
RELEASE NOTE: Correction to the mapping of MEGAN emissions of A-PINENE and B-PINENE for the CRIv2R5 gas-phase chemical scheme.

Correcting pointers for MEGAN emissions in CRIv2R5 scheme.

---

chem/chemics_init.F
run/README.namelist
share/module_check_a_mundo.F

TYPE: bug fix
KEYWORDS: WRF-Chem, Cumulus, GDSCHEME, cu_diag, cu_rad_feedback, namelist
SOURCE: Hamada S. Badr (Johns Hopkins University, USA)
Sub-grid cloud effect to the optical depth in radiation (cu_rad_feedback = .true.) requires setting additional time-averaged variables for cumulus physics (cu_diag = 1) that only works for Grell-Freitas (GF), Grell 3D (G3), Kain–Fritsch Cumulus Potential (KF-CuP), and Grell-Devenyi (GD) cumulus schemes, which are equivalent to cu_physics = 3, 5, 10, and 93, respectively.
In the namelist README and consistency checks, cu_diag = 1 is supported by 4 cumulus schemes:
1) Grell-Freitas (GFSCHEME)
2) Grell 3D (G3SCHEME)
3) Kain–Fritsch Cumulus Potential (KFCUPSCHEME), and
4) Grell-Devenyi (GDSCHEME)
These changes only impact …

chem: Add Grell-Devenyi (GD) scheme if cu_diag = 1

---

chem/chemics_init.F

TYPE: bug fix
KEYWORDS: WRF Chem, chemics_init.F
A typo was introduced in SHA d4c8bb2085b4
This is PR #606 "Updates for completeness of gas initialization and plumerise"
In a case statement, the line incorrectly included
```
RACM_SOA_VBS_KPP_AQCHEM
```
and should have had
```
RACM_SOA_VBS_AQCHEM_KPP
```
M   chem/chemics_init.F

typo in WRF Chem chem/chemics_init.F

---

inc/version_decl

KEYWORDS: version_decl, v4.1-alpha
Update the character string inside the WRF system from 4.0.3 to 4.1-alpha.
```
> ncdump -h wrfinput_d01 | grep TITLE
:TITLE = " OUTPUT FROM REAL_EM V4.1-alpha PREPROCESSOR" ;
> ncdump -h wrfinput_initialized_d01  | grep TITLE
:TITLE = " OUTPUT FROM WRF V4.1-alpha MODEL" ;
> ncdump -h met_em.d01.2019-02-15_12:00:00.nc  | grep TITLE
:TITLE = "OUTPUT FROM METGRID V4.1" ;
> ncdump -h wrfout_d01_2019-02-16_12:00:00  | grep TITLE
:TITLE = " OUTPUT FROM WRF V4.1-alpha MODEL" ;
```

Version update: 4.0.3 -> 4.1-alpha

---

share/module_check_a_mundo.F

KEYWORDS: HVC, check_a_mundo, comments
An original IF block in check_a_mundo that guarded against an inconsistent build was removed
in v4.0. However, the comments ahead of that IF block remained. That block of comments, which
now describe nothing but empty lines, is removed.
M  share/module_check_a_mundo.F
No tests required as these changes are only removing incorrect comments.

Remove extraneous HVC comments in module_check_a_mundo

---

phys/module_cu_ntiedtke.F

KEYWORDS: wrf, mpas, unification, ntiedtke, cumulus
DESCRIPTION OF CHANGES: For the purpose of WRF/MPAS physics unification, we want the 2 models to have identical versions of each physics routine. After some mods were made to the MPAS version, this version then was behind. This particular PR defines t13 in the code rather using the Prandtl number since the Prandtl number is different in WRF and MPAS.
M   phys/module_cu_ntiedtke.F
TESTS CONDUCTED: Verified that it compiles and runs fine. There were no diffs in output before/after modifications.

update module_cu_ntiedtke file to identically match MPAS version

---

share/input_wrf.F

TYPE: bug fix
KEYWORDS: obsgrid, metoa, v4, old
DESCRIPTION OF CHANGES: Due to vetting in input_wrf.F, some older (than v4.0) input data is not allowed to run with v4.0+ real.exe. This included older OBSGRID input, which should be excluded from this rule, as the version of OBSGRID is irrelevant. Added OBSGRID to the clause that excludes it from this vetting process.
M      share/input_wrf.F
TESTS CONDUCTED: Tested code before/after with new metoa* input data to make sure it behaves correctly. Compiles okay.
RELEASE NOTE: 
OBSGRID input data may now be used with V4.1 real.exe, regardless of the version of OBSGRID.

Bug fix to allow old OBSGRID input to be used in V4.0* real.exe

---

phys/module_sf_sfclay.F

KEYWORDS: mm5, Monin-Obukhov, sfclay, mpas, wrf, SFCLAY1D
DESCRIPTION OF CHANGES: When mods were made to unify wrf/mpas code, MPAS was left out of an if statement within the call to SFCLAY1D. Added it in to correct for MPAS purpose.
M    phys/module_sf_sfclay.F
1. Verified that it compiles and runs give bit-for-bit results before and after mods.
2. Simple test: does this CPP directive do what we want.
Source code
```
> cat foo.F
program foo
#if ( ( EM_CORE == 1 ) || ( defined(mpas) ) )
print *,'yep on EM_CORE == 1 || defined mpas'
#else
print *,'Nothing special at all'
#endif
end
```
```
> cpp -DEM_CORE=1 foo.F > foo.f90 ; gfortran foo.f90  ; a.out
yep on EM_CORE == 1 || defined mpas
```
```
> cpp -Dmpas foo.F > …
```

mm5 sfclay adding 'defined(mpas)' to call to SFCLAY1D

---

phys/module_cu_ntiedtke.F

KEYWORDS: ntiedtke, wrf, mpas cu_physics, dx2d
DESCRIPTION OF CHANGES: Toward an effort to use fewer if defined(mpas) (or wrfmodel) statements in the code, a dx2d variable was added to be used until WRF creates a 2d array for dx.
M   phys/module_cu_ntiedtke.F
TESTS CONDUCTED: verified that WRF builds okay and that bit-for-bit results are given before/after mods.

Ntiedtke wrf mpas unify updates - addition of dx2d variable to clean up module

---

phys/module_mp_wdm6.F
phys/module_mp_wdm7.F
phys/module_mp_wsm6.F
phys/module_mp_wsm7.F

TYPE: bug-fix
KEYWORDS: WSM6, WSM7, WDM6, WDM7, accretion terms
SOURCE: KIAPS and Brett Wilt (IBM)
Brett Wilt noted a problem where these schemes froze rainfall too easily with even very small 
amounts of ice. The fix is to reduce the efficiency proportional to the square of the ratio of ice to 
water in accretion processes. This allows rain more easily, which is in better agreement with 
observations. The changes in all 4 schemes are the same.
ISSUE: 
M       phys/module_mp_wdm6.F
M       phys/module_mp_wdm7.F
M       phys/module_mp_wsm6.F
M       phys/module_mp_wsm7.F
compile only
RELEASE NOTE: 
WSM and WDM schemes fixed to allow more freezing rain (KIAPS mods as suggested by Brett Wilt, IBM)

W[SD]M[67] accretion mods for freezing rain

---

phys/module_mp_wsm6.F

KEYWORDS: wsm6, wrf, mpas, unify, if loop
At the top of the wsm6 module was an if defined (wrfmodel) loop that included a few 'use' 
statements for models/routines that are currently not used in this MP scheme. Removed that 
loop to unify this routine with MPAS and to clean-up unnecessary dependencies.
M   phys/module_mp_wsm6.F

WSM6: remove unnecessary ifdef for purpose of WRF/MPAS unification

---

phys/module_bl_mynn.F
phys/module_bl_shinhong.F
phys/module_bl_ysu.F

TYPE: bug fix
KEYWORDS: YSU, Shin-Hong, and MYNN PBL, constant h1
SOURCE:  Ji-Young Han and Songyou Hong (KIAPS)
The constant h1 is defined as 1/3, but the value set in code is 0.33333335. This appears in YSU, Shin-Hong and MYNN PBL modules, and is fixed with this PR.
M   phys/module_bl_ysu.F
M   phys/module_bl_shinhong.F
M   phys/module_bl_mynn.F
It compiles.
RELEASE NOTE: 
In the YSU, Shin-Hong, and MYNN PBL schemes, fix the constant h1 in its 8th decimal place from 0.33333335 to 0.33333333.

PBLs: h1 constant should be 1/3, but was 0.33333335

---

Makefile
clean

TYPE: bug fix
KEYWORDS: jensen, bin, ishmael, mp_physics
1. The top-level Makefile did not have the ishmael\*bin files linking from run/ to test/em_real/. That was added so that Jensen mp will run correctly without having to manually copy those files over. 
2. The ishmael\*bin files were also added to the clean script so that they will be removed from test/\*/ upon a clean.
M    Makefile
M    clean
TESTS CONDUCTED: Verified that it configures/builds okay and properly links the files to the test/em_real directory during the build.

Jensen look-up table files: Makefile (add links), clean (add removes)

---

Registry/Registry.EM_COMMON
dyn_em/start_em.F
share/input_wrf.F
share/module_check_a_mundo.F

KEYWORDS: time_step, dx, cfl, ratio, current date, simulation start date
Problem:
Users accidentally forget to change the model time step when adjusting
the grid distance. It sometimes takes the model a while to become unstable
enough to die, and it is not always easy to determine why the model stopped.
However, we can't provide a simple "if the time step ratio > 6,
then always stop", because ideal cases would be unintentionally 
impacted. Likely there are also real-data cases, maybe LES-scale or urban heat 
island studies, where a user could realistically get a stable solution at a dt/dx ratio > 6.
Solution:
For domain 1 only, for real data cases only, for explicit dt cases (no adaptive dt):
Check to see if the time step ratio is …

Helpful printout info: 1) gross check for d01 time step, 2) current and sim start date in printout

---

Registry/Registry.EM_COMMON
dyn_em/module_initialize_real.F

TYPE: bug fix
KEYWORDS: positive definite, vertical interpolation, real
SOURCE: Found by Pedro Jimenez (NCAR), fixed internally
Problem:
Users noticed that the constituent for P_QI was negative after running real.
Solution:
The order of the vertical interpolation was originally handled by the
`lagrange_order` namelist variable. By default, this value was set to
2, meaning a quadratic was used for vertical iterpolation. For positive
definite fields, we should use only linear vertical interpolation. The
results of a linear interpolation will maintain a positive definite
field. The new namelist variable `linear_interp` is always set
to 1, and is used in the calling function for all of the known positive
definite fields (for example, constituents of moist).
LIST OF …

Use linear vertical interpolation for pos def fields

---

Registry/registry.dimspec
Registry/registry.stoch
dyn_em/module_first_rk_step_part2.F
dyn_em/module_stoch.F
share/module_check_a_mundo.F

TYPE: bug fix
KEYWORDS: stochastic, restart, b4b, hrrr_cycling
1. Made the random number seed to have a dimension that is intrinsic to the compiler.
2. Force hrrr_cycling = .true. to avoid resetting seeds on restart (the logic was broken).
3. The seeds now have a "Z" stagger (no empty or zero value in last entry).
4. Modify code to accommodate the swap from vertical dimension of seed to the new `seed_dim`.
ISSUE: 
Fixes #799 random seed length for stochastic option
M Registry/registry.dimspec
M Registry/registry.stoch
M dyn_em/module_first_rk_step_part2.F
M dyn_em/module_stoch.F
M share/module_check_a_mundo.F
1. The patterns are identical after a restart.
👍 
RELEASE NOTE: After hrrr_cycling was introduced …

Make random seeds for stochastic schemes able to be in restart file and be allocatable

---

run/README.namelist
share/module_check_a_mundo.F

TYPE:  Text only
KEYWORDS:  Deng shallow convection
The Deng shallow convection scheme only works with MYJ or MYNN PBL schemes. In addition, when this scheme is turned on, cumulus scheme must be turned off.
The README file which describes many of the namelist settings is updated to make 
this restriction clear. 
M  share/module_check_a_mundo.F
TESTS CONDUCTED: a test case with the wrong settings is conducted. Below is the error message
```
Quilting with   1 groups of   0 I/O tasks.
Ntasks in X            2 , ntasks in Y            2
--- ERROR: Deng shallow convection can only work with MYJ or MYNN PBL
--- ERROR: Fix shcu_physics or bl_pbl_physics in namelist.input.
--- ERROR: Deng shallow convection …
```

Deng convection scheme only works with MYJ or MYNN PBL, and deep convection must be turned off 

---

phys/module_radiation_driver.F

TYPE: bug fix
KEYWORDS: RRTMG, CAM Ozone
SOURCE: Takahiro Benno (???)
DESCRIPTION OF CHANGES: When RRTMG is turned on with CAM ozone as input (o3input=2), the variable ozmixm has 13 elements in time dimension, and monthly ozone data is stored in the 2nd to 13th elements, corresponding to 1-12 month. In the subroutine "ozn_time_int", however, the time dimension for "ozmixm" is not specified accordingly. More details are as follows.
(1)  In module_physics_init.F, ozone data is read by subroutine oznini, included in module_ra_cam_support.F. In subroutine oznini, ozmixm has 13 elements in time dimension, and monthly ozone data is stored in the 2nd to 13th elements. ozone is all zero in the 1st element.
(2) In module_radiation_driver.F, ozone is interpolated based on time (julian) in the …

Bug fix for RRTMG with o3input=2 option

---

phys/module_bl_mynn.F

TYPE: bug fix, small enhancement
KEYWORDS: subgrid cloud fractions
SOURCE: Joseph Olson/Jaymes Kenyon (NOAA/CIRES)
1. Bug fix for the mass-flux subgrid cloud fraction to use the environment properties instead of the plume properties (for qv & qv_sat). This bug has little/no impact on SW-down since LWP & IWP was not impacted (total subgrid cloud condensate does not change; increased cloud fractions assume the total condensate is spread over a larger area of the grid cell). This makes this change somewhat cosmetic in nature. This bug was inserted in the previous MYNN commit. Previous commit: e003369317, PR #764 "MYNN PBL (only) update"
2. Small adjustment to non-convective subgrid clouds to improve ceiling statistics. Instead of using an arbitrary constant factor to …

MYNN-EDMF: bug fix for mass-flux subgrid clouds, enhancement for non-conv subgrid clouds

---

phys/module_cu_ksas.F

TYPE: bug fix
KEYWORDS: KSAS
SOURCE: Ji-Young Han and Songyou Hong (KIAPS)
1. Revised scale-dependent triggering function (cinpcr). This makes suppression of the convection triggering at resolutions less than 10 km more significant as compared to the original KSAS.
2. Fix the conversion parameter that determines the fraction of condensate converted to precipitation (c0) for convective overshooting layer. This leads to an increase in detrained moisture near the cloud top, resulting a decreased LW cooling effect in the tropical upper troposphere.
3. Fix cloud base mass flux xmb trigger condition, and this has a minor effect.
M  phys/module_cu_ksas.F
It compiles. More later.
RELEASE NOTE:
For KSAS, the scale-dependent …

KSAS: scale dependent trigger, conversion parameter, xmb trigger condition

---

phys/module_mp_jensen_ishmael.F

TYPE: bug fix
KEYWORDS: jensen, mp_physics, qi, floating_point
DESCRIPTION OF CHANGES: In the vapor growth check in Jensen microphysics, qi had the ability to be negative, which means that in the equation for ani(cc), there was potential to raise a negative number to an exponent of a non-logical fractional value, which caused a floating point error. This only stopped the model from running when compiled with a check for floating point traps. Inserting an if statement to prevent this from happening corrects the problem.
M    phys/module_mp_jensen_ishmael.F
TESTS CONDUCTED: Verified that code builds and runs to completion, even when compiled with floating point trap checks.

Jensen microphysics: negative qi in vapor growth

---

phys/module_sf_noahmplsm.F

TYPE: bug fix
SOURCE:  Jorge Navarro (CIEMAT, Spain), Michael Barlage (NCAR)
Problem:
When running Noah-MP with no urban scheme (bulk method), the roughness length in urban areas
was not used from the MPTABLE and instead was set to a bare soil value. This resulted in a high 
temperature, high wind speed, and low sensible heat flux over cities.
Fix: use z0 from the MPTABLE
M       phys/module_sf_noahmplsm.F
1. 24-hr Noah-MP simulations in a summer and winter configuration
RELEASE NOTES:
When running Noah-MP with no urban scheme (bulk method), the roughness length in urban areas 
used a bare soil value. This resulted in a high temperature, high wind speed, and low sensible heat 
flux over cities. The …

Bug Fix: use Noah-MP table roughness length in urban areas when using bulk scheme (no urban option used)

---

phys/module_sf_noahmp_glacier.F
phys/module_sf_noahmpdrv.F
phys/module_sf_noahmplsm.F

TYPE: bug fix
SOURCE: David Mocko (NASA), Michael Barlage (NCAR)
1. A few Noah-MP variables are not initialized (now set to zero).
2. A routine did not have an 'implicit none'. This allowed default typing for an undeclared variable.
M       phys/module_sf_noahmplsm.F
M       phys/module_sf_noahmpdrv.F
M       phys/module_sf_noahmp_glacier.F
1. 24-hr Noah-MP simulations in a summer and winter configuration using PGI compiler produce no changes (results may change with other compilers)

Bug Fix: fix some uninitialized Noah-MP variables

---

phys/module_sf_noahlsm.F

TYPE: bug fix
KEYWORDS: Noah LSM sh2o unified MPAS
Problem:
A single variable was used as two calling arguments in a subroutine. Inside the subroutine, the 
separate names were pointing to the same memory and were treated differently.
Solution:
Since the two instances of the array were treated as IN and OUT, a copy of the array was made and
passed in as separately named input field. There were two locations to fix.
M phys/module_sf_noahlsm.F
1. Comparing the results before vs after show no bit-for-bit differences (what we wanted).
```
../../external/io_netcdf/diffwrf INIT_develop/wrfout_d01_2000-01-24_12:00:00 INIT_FIX_dev/wrfout_d01_2000-01-24_12:00:00 
Just plot  F
Diffing …
```

SH2O had two appearances in call to ssttep routine

---

phys/module_mp_jensen_ishmael.F

KEYWORDS: code changes/enhancements
In the check to ensure that microphysical processes do not over-deleted ice (lead to negative ice mass mixing ratios), reduce the ice mass tendency during melting (qmlt) if necessary, but do not reduce the ice number and volume mixing ratio tendencies (nmlt, amlt, cmlt), consistent with sublimation (prd). Checks to ensure that mass number and volumes stay positive after melting exist just below. 
Changes added 27 March 2019:
1) Initialize value of dsold=1 (tracks the shape) before microphysics occurs. 
2) Lower the minimum vapor growth limit and add a timestep dependence (line 1142).
3) Check on melting ice to ensure that it becomes spherical (phi=1) but that shape does not go …

Jensen Ishmael microphysics: additional update for initial release

---

dyn_em/module_initialize_scm_xy.F

TYPE: bug fix
KEYWORDS: scm_xy, process_soil_real, flag_sm_adj, compile 
In ([commit b4c8515](https://github.com/wrf-model/WRF/commit/b4c851585654)), a soil moisture
flag (flag_sm_adj) was added to module_soil_pre.F in subroutine process_soil_real. This subroutine 
is called in module_initialize_scm_xy, and therefore needed the addition of the flag in the 
declarations list for that call, as well. Since it wasn't in there, em_scm_xy was unable to compile. 
Once added, the ideal program compiles correctly. With this change, all occurrences of the call to 
subroutine process_soil_real are now handled.
M       dyn_em/module_initialize_scm_xy.F
[x] Verified that the code builds with this addition.

em_scm_xy compile bug fix: add 'flag_sm_adj' to call to process_soil_real in module_initialize_scm_xy

---

phys/module_mp_gsfcgce_4ice_nuwrf.F
phys/module_mp_jensen_ishmael.F

Type: bug fix
KEYWORDS: cray, exponent, syntax
SOURCE: Found by Peter Johnsen and Patricia Balle (Cray, Inc.), fixed internally
A few  illegal syntax examples of the form below were found by the Cray compiler in release-v4.1. 
These are the only instances in the phys directory (excluding comments).
```
a ** -b
```
The correct form is
```
a ** (-b)
```
None of the NCAR cheyenne compilers (Intel, PGI, GNU) complain about this particular syntax, 
since it is treated as an extension of the standard.
However, the code cannot compile with the CRAY compiler. 
If the Fortran 2003 standard is enforced with Intel, this construct flags a fatal error. 
```
> cat foo.f90
program foo1
print *, 'Expecting 5/9 = ',5./9., 3. ** -2 * 5.
end program foo1
```
With Intel as the …

Syntax errors: (a ** -b) becomes (a ** (-b)); in new Jensen and Goddard MP schemes

---

dyn_em/module_initialize_real.F

TYPE: NEW FEATURE
KEYWORDS: number concentrations, initial and boundary conditions, microphysics, 2-moment
SOURCE: Greg Thompson (NCAR-RAL)
Problem: 
Some incoming data from WPS/ungrib/metgrid (for example, RAP/HRRR pressure level data) only have mass mixing ratios but not number concentrations. This forces a number to be made up later for 2-moment microphysics (MP) schemes. 
Solution:
For a more fully integrated approach with initial and boundary conditions, we can calculate reasonable values of number concentration from mass (together with other variables) in module_initialize_real. Very simple functions, one each to create number of cloud droplets, cloud ice, and rain number concentrations are isolated functions added for IC/BC creation time. 
Proper mass and …

MP=8,28 initialize_real additions for cloud droplet number, cloud ice number, rain number

---

run/README.namelist

KEYWORDS: RRTMG, cldovrlp
New option, cldovrlp, an option to select cloud overlapping option for the original RRTMG scheme, 
is added to README.namelist file.
Not needed.

Add new option cldovrlp to README file

---

phys/module_shcu_deng.F
run/README.namelist
share/module_check_a_mundo.F

TYPE: no impact, and text only
KEYWORDS: Deng shallow cu, README
After some tests, we decided that we will remove the hard constraint against allowing the Deng 
scheme to run with another deep scheme (i.e., we WILL allow the Deng scheme to run with another 
deep convection scheme). This is in part because, even though there is a component in the scheme 
for deep convection, it isn't very active. Without another deep scheme, the Deng scheme could 
potentially generate grid-point storms by not removing enough instability. 
Other changes include removing prints from Deng's module, and adding some text for the 
README.namelist file.
M       phys/module_shcu_deng.F - Only removing prints and debugging comments
M …

Allow Deng shcu to work with deep cu, remove prints, edit README

---

phys/module_radiation_driver.F

TYPE: bug fix
KEYWORDS: RRTMG, CAM Ozone, o3input, wrf, mpas, unify
SOURCE: Takahiro Benno 
DESCRIPTION OF CHANGES: When RRTMG is turned on with CAM ozone as input (o3input=2), the variable ozmixm has 13 elements in time dimension, and monthly ozone data is stored in the 2nd through 13th elements, corresponding to 1-12 months. In the subroutine "ozn_time_int", however, the time dimension for "ozmixm" is not specified accordingly. More details are as follows. With a fix to the radiation driver, monthly ozone data are correctly set to correspond to the 2nd-13th elements of the 4th dimension of ozmixm. While the bug fix is already implemented in the v4.1 release branch,  it is also necessary for the WRF/MPAS comparison tests, and is therefore now being placed in the unified_physics branch. …

RRTMG bug fix for o3input option 2

---

clean

KEYWORDS: Darwin, clean, dSYM
When building the WRF system, Darwin machines may create several *.dSYM directories, 
depending on the compiler. Remove these *.dSYM directories when issuing a `clean` command.
M ./clean
1. Able to remove directories
```
> git status
On branch clean_dSYM
Your branch is up to date with 'dave/clean_dSYM'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
external/io_int/diffwrf.dSYM
external/io_int/test_io_idx.dSYM
external/io_netcdf/diffwrf.dSYM
main/ndown.exe.dSYM
main/real.exe.dSYM
main/tc.exe.dSYM
main/wrf.exe.dSYM
makeem.csh
tools/registry.dSYM
tools/standard.exe.dSYM
nothing added to commit but untracked files present (use …
```

Remove the *.dSYM directories from Darwin when "clean" command issued

---

Registry/Registry.EM_COMMON
run/README.tslist
share/wrf_timeseries.F

KEYWORDS: tslist, pressure, profile
SOURCE: Suggested by Gokhan Sever, implemented internal
1. Add the pressure field to those that are included in the vertical profiles.
2. Fixed the printout for the (i,j) case, where (lat,lon) was printed as (0.000,0.000)
3. The Registry.EM_COMMON description for W said "earth relative", but not any more
M run/README.tslist
M share/wrf_timeseries.F
1. Pressure field looks reasonable.
2. Bit-wise identical results when using (i,j) vs (lat,lon)
3. For the (i,j) case, the (lat,lon) print out is correct (tested Lambert)
RELEASE NOTES: Add "pressure" to list of profile fields that are available (release notes from SHA 43ac4e93fb29, PR #712 "new …

TSLIST: add pressure field to vertical profile output files

---

Makefile

TYPE: bug fixKEYWORDS: Makefile, link, ln, run
For the data files in the run directory, they need to be explicitly linked into the test/em_real 
directory (by the top-level Makefile). A few files were missing, a couple have been recently
renamed.
Also, I lined up all of the `ln -sf` commands as best as could be done. So tidy now.
LIST OF MODIFIED FILES: l
M Makefile

In top-level Makefile, put required run dir file links to test/em_real

---

phys/module_mp_thompson.F

TYPE: bug fix
KEYWORDS: Thompson microphysics
SOURCE:  Greg Thompson (NCAR/RAL)
1. Fix 2 bugs in rain number concentration tendencies
2. Minor consistency correction for cloud ice smallest mean size
3. Bug fix to partially-melted snow terminal velocity
phys/module_mp_thompson.F
TESTS CONDUCTED:  numerous case studies in past 2 months plus a month of real-time WRF runs for ICICLE field project all utilized this bug fixed code.
RELEASE NOTE:  For MP=8,28: A few adjustments made for rain number concentration tendencies, 2 of which are bug fixes.  Also a minor adjustment for consistency to min cloud ice size in event a balance of ice number is needed.  Lastly a bug fix for partly-melted snow.  The most notable changes are: (1) a larger mean …

mp 8,28: qnr tendency, smallest size cloud ice, partially melted snow terminal velocity

---

dyn_em/module_initialize_real.F

TYPE:  bug fix
KEYWORDS: real, vertical interpolation, microphysics, lowest level
SOURCE:  Greg Thompson (NCAR/RAL)
DESCRIPTION OF CHANGES:  For microphysical mixing ratios and number concentrations (and
chemical species) we do not actually have values at the so-called surface level, so do not try using 
surface level for vertical interpolation.  RH is *NOT* affected as we do wish the water vapor to 
continue using standard method, but we shall never have mixing ratios or number concentrations of 
microphysical species at the "surface" level per se.
ISSUE: Fixes #837 
dyn_em/module_initialize_real.F
TESTS CONDUCTED:  
1. From met_em.d0X files to wrfinput_d0X, I confirmed that microphysics mass mixing ratios and number concentrations on WRF first model level (K=1) …

Handle lowest-level microphysics species in real.exe

---

Registry/Registry.EM_COMMON

TYPE: bug fix
KEYWORDS: restart, 0 h restart, dry potential temperature - t0, th_phy_m_t00
Problem:
With a restart run, the history output at the end of the first run and the history output at the 
beginning of the second run (with write_hist_at_0h_rst=true) has a difference in the output field 
named "T". 
Solution:
The "T" field is diagnostic, and was not put into the restart file. However, a number of post-
processors rely on a valid value for dry theta form the model output. The easy solution is to put this 
field into the restart file, so it is correctly written out at the 0h of the model history file during a 
restart.

Add diagnostic dry theta - t0 to restart file

---

dyn_em/module_initialize_real.F

KEYWORDS: etac, monotonic pressure, hybrid coordinate, hvc
SOURCE: Found by Michael Toy (NOAA), fix internal
Problem:
Over very high topography, the flattened eta surfaces may intersect the eta surfaces below. The 
WRF model dies quickly, and it is very difficult to figure out what happened. In simple terms, the
reference pressure must decrease as you go up the k-index, for each (i,j). If not, then that is a 
fatal error.
Solution:
Trap this event via looking at the columns of reference pressure. Any column that is NOT monotonic 
flags a fatal error. The user is given the location, the pressure values, and a suggestion to reduce the 
etac (the critical eta surface where the levels becomes isobaric).
A similar warning was issued in 1984, though it …

Require monotonic vertical pressure decrease: test after hybrid vert coordinate calculation in real 

---

Registry/Registry.EM_COMMON
phys/module_mp_gsfcgce_4ice_nuwrf.F
phys/module_physics_init.F
phys/module_ra_goddard.F
phys/module_radiation_driver.F
share/module_check_a_mundo.F

TYPE: bug fix, enhancement
KEYWORDS: Goddard radiation, microphysics, effective radii
This PR is related to the recently added Goddard radiation (ra_lw_physics=5 and ra_sw_physics=5), and Goddard microphysics (mp_physics=7) schemes. The newly added Goddard radiation and microphysics options are general enough to work with other microphysics and radiation options. The Goddard radiation must have effective radii from microphysics, and Goddard microphysics always provides effective radii for cloud, ice, snow, graupel, hail and rain. 
- If one uses Goddard radiation, but not Goddard microphysics, the radiation output (e.g. SWDOWN) is wrong because there is no cloud effect. 
- If one uses Goddard microphysics with radiation options that don't use …

Generalize new Goddard radiation and MP schemes to partner with other schemes

---

var/da/da_main/da_update_firstguess.inc

KEYWORDS: WRFDA, print
Remove one unnecessary print added in commit 1a93c9.
The last 4 lines of the log file after commit 1a93c9.
```
nlon,nlat,nsig_regional=         414         324          50
THM = T when use_theta_m =  0
*** WRF-Var completed successfully ***
```
The nlon,nlat line should not have been added.
M       var/da/da_main/da_update_firstguess.inc
RELEASE NOTE: not needed

Remove one unnecessary DA print introduced in a recent commit

---

phys/module_mp_gsfcgce.F
phys/module_mp_lin.F
phys/module_mp_morr_two_moment.F
phys/module_mp_morr_two_moment_aero.F
phys/module_mp_wdm5.F
phys/module_mp_wdm6.F
phys/module_mp_wdm7.F
phys/module_mp_wsm5.F
phys/module_mp_wsm6.F
phys/module_mp_wsm7.F

KEYWORDS: microphysics, mp, physics, unused, alarm, clock
Inside several of the microphysics modules were USE statements related to alarms and clocks. 
These are no longer needed, as they are no longer used for the radar reflectivity calculation
(which moved into the radiation driver). This PR simply removes the unnecessary code.
M     phys/module_mp_gsfcgce.F
M     phys/module_mp_lin.F
M     phys/module_mp_morr_two_moment_aero.F
M     phys/module_mp_morr_two_moment.F
M     phys/module_mp_wdm5.F
M     phys/module_mp_wdm6.F
M     phys/module_mp_wdm7.F
M     phys/module_mp_wsm5.F
M     phys/module_mp_wsm6.F
M     phys/module_mp_wsm7.F
TESTS CONDUCTED: verified code builds with GNU/V8.1 after the modification.

Removed unused alarm and clock from microphysics schemes

---

var/da/da_obs_io/da_read_obs_bufr.inc

TYPE: bug fix
KEYWORDS: WRFDA, ob.bufr, use_ssmiretrievalobs, TPW
Even though SSM/I retrievals are no longer available after November 2009,
the fixed code can be useful for retrospective studies.
The SPSSMI (SSM/I superobed retrievals) TPW contained in the global prepbufr
files is assigned missing obs error.
To allow assimilation of SSM/I TPW when ob_format=1 and use_ssmiretrievalobs=.true.,
assign an obs error either from an external obs error table or a specified 0.2cm for
this obs type.
M       var/da/da_obs_io/da_read_obs_bufr.inc
A 2009-Oct case is able to assimilate SPSSMI TPW after the fix.
RELEASE NOTE: Fix to allow assimilation of SSMI TPW contained (prior to Nov 2009) in prepbufr obs …

Fix to allow assimilation of SSMI TPW contained in prepbufr obs files

---

Registry/Registry.EM_COMMON
dyn_em/module_first_rk_step_part1.F
dyn_em/start_em.F
phys/module_cu_ntiedtke.F
phys/module_cumulus_driver.F
phys/module_physics_init.F
phys/module_sf_sfclay.F
phys/module_surface_driver.F

TYPE: enhancement (to get closer to MPAS spatially varying dx results)
KEYWORDS: dx 2d, wrf, mpas
DESCRIPTION OF CHANGES: The unified_physics branch was created from the top of the master (which is the v4.0.3 release branch). These changes have already been approved for the develop branch, but I am adding them to the unified_physics branch for WRF/MPAS comparative testing purposes.
Similar to PR #831 "2d grid distance"
git cherry-pick 0031e002af857 3dae9791c47afc
modified:   dyn_em/module_first_rk_step_part1.F
modified:   dyn_em/start_em.F
modified:   phys/module_cu_ntiedtke.F
modified:   phys/module_cumulus_driver.F
modified:   phys/module_physics_init.F
modified:   phys/module_sf_sfclay.F
modified: …

wrf/mpas unified 2d dx commits pushed to unified_physics branch

---

share/wrf_tsin.F

TYPE: bug fix
KEYWORDS: tslist, mpi, bcast, ij
Problem:
With the introduction of the ability to use (i,j) as the location for a time series output from WRF,
the code failed to work for (i,j) using MPI with more than one rank (SHA [43ac4e93f](https://github.com/wrf-model/WRF/commit/43ac4e93fb29a753893152d8e228f3b8c8b96f42), 
PR #712 "new tslist options: add W; cell-centered u,v; (i,j) and (lat,lon) locations").
The original (lat,lon) capability, both serial and DM parallel, continue to work.
Solution:
The `tslist_ij` flag, determined on the master process, needed to be communicated to the other
MPI processes. Additionally, the (i,j) locations needed to be communicated.
Also, for code clean up: removed two arrays that were never used.
LIST OF …

BF: TSLIST broken for (i,j) with MPI rank > 1

---

main/depend.common

TYPE: bug fix
KEYWORDS: AFWA diagnostics dependency
Problem:
The file `phys/module_diag_afwa.o` was always re-compiled, even when there were no updated
dependencies.
Solution:
The `depend.common` file incorrectly listed a file, `module_diag_afwa_hail.o`, as one of the 
required files to produce `module_diag_afwa.o`. The file `module_diag_afwa_hail.o` does not 
exist. 
1. The file `module_diag_afwa_hail.o` is removed as a target in `depend.common`.
2. This file is removed from the list of dependencies for `module_diag_afwa.o`.
M main/depend.common

Fix dependencies for AFWA diagnostics

---

Registry/registry.afwa
phys/module_diag_afwa.F

TYPE: bug fix
KEYWORDS: AFWA diagnostics, memory allocation
SOURCE: internal, reported by Abby Jaye (NCAR/MMM) and other users
Problem:
When AFWA diagnostics switch is turned on (`afwa_diag_opt = 1`), the model can behave badly,
usually by "hanging" when a history file is written. The problem is that some of the variables used 
in the diagnostic routine are not packaged correctly. Unless one turns on every afwa_* option,
essentially the union of all packages for AFWA diagnostic options, the WRF executable can fail.
Solution:
Identify variables that are ALWAYS assumed to be used, and include those in the basic option for
using the AFWA diagnostic capability.
Notes:
1. This error does not manifest in all situations (for example, the small January 2000 test case …

BF: Incorrect AFWA diagnostics packaging; symptom: model hangs on history output

---

var/da/da_main/da_solve.inc

TYPE: bug fix
KEYWORDS: WRFDA, EnVar, cv_options, alpha_cv
SOURCE: JJ Guerrette
DESCRIPTION OF CHANGES: WRFDA throws an error for this unsupported set of namelist variables
ISSUE:
```
Fixes #867 
```
M       var/da/da_main/da_solve.inc
TESTS CONDUCTED: WRFDA compiles successfully.  No impact to results.

Added check for cv_option=3 and ensdim_alpha>0

---

Registry/registry.afwa
phys/module_diag_afwa.F
share/module_check_a_mundo.F

TYPE: bug fix
KEYWORDS: AFWA, moist, scalar, package, memory
1. For each routine that uses a particular moist of scalar 3d component, verify that component has 
been allocated. For example:
Original code:
```
DO i=ims, ime
DO k=kms, kme
DO j=jms, jme
qvapr(i,k,j) = moist(i,k,j,P_QV)
ENDDO
ENDDO
ENDDO
```
New code:
```
IF ( F_QV ) THEN
DO i=ims, ime
DO k=kms, kme
DO j=jms, jme
qvapr(i,k,j) = moist(i,k,j,P_QV)
ENDDO
ENDDO
ENDDO
END IF
```
2. When using dz on half levels, do not use z(k)-z(k-1), since k-1 gives you a 0 index. Use dz8w.
Original code:
```
melt(i,j)=melt(i,j)+9.8*(((t_phy(i,k,j)-273.15)/273.15)* &
(z(i,k,j)-z(i,k-1,j)))
```
New code:
```
melt(i,j)=melt(i,j)+9.8*(((t_phy(i,k,j)-273.15)/273.15)* &
(dz8w(i,k,j)))
```
3. Verify for each …

Several "AFWA diagnostic" memory fixes

---

wrftladj/module_first_rk_step_part2_tl.F

TYPE: bug fix
KEYWORDS: wrfplus
Problem: 
WRFPlus code does not compile.
Solution:
With SHA 05c7fd2d99abf6fd (PR #804 "Make random seeds for stochastic schemes able to be in 
restart file and be allocatable") modifications were made to the dyn_em/module_first_rk_step_part2.F
file (the interface to the stochastic routine `RAND_PERT_UPDATE`). These modifications need to 
also be introduced in the TL version of the file.
M wrftladj/module_first_rk_step_part2_tl.F
1. WRFDA regtest passed.

BF: WRFPlus TL version of first_rk_step_part2 requires updated arguments to RAND_PERT_UPDATE

---

phys/module_sf_bem.F
phys/module_sf_bep.F
phys/module_sf_bep_bem.F
phys/module_sf_noah_seaice.F
phys/module_sf_noah_seaice_drv.F
phys/module_sf_noahdrv.F
phys/module_sf_noahlsm.F
phys/module_sf_noahlsm_glacial_only.F
phys/module_sf_urban.F

TYPE: enhancement/no impact
KEYWORDS: noah, LSM, mpas, wrf, unify, seaice, urban, glacial
Identical to [PR #630 ](https://github.com/wrf-model/WRF/pull/630). Cherry-picked from that PR (going onto develop) and placed here (unified_physics). Also confirmed the modified files are identical to MPAS test:
commit 001589006b58952bd943a82facedbe6c3c4f7353
Merge: 5f67eb4 bfab9d1
Author: Michael Duda <duda@ucar.edu>
Date:   Wed Apr 3 13:49:42 2019 -0600
Merge branch 'atmosphere/noah_mpas_wrf_unify' into test
* atmosphere/noah_mpas_wrf_unify:
Noah LSM physics unified with WRFV4.0
Toward the effort to unify physics schemes between MPAS and WRF, the Noah Scheme was updated again. Preliminary updates were previously pushed to the code prior to the V4.0 release, …

Additional Mods to Unify WRF and MPAS Noah LSM Scheme

---

share/module_check_a_mundo.F

TYPE: bug fix
KEYWORDS: deng, shcu, check-a-mundo, MYJ, MYNN
SOURCE: Internal 
DESCRIPTION OF CHANGES: When using the Deng shcu scheme, one must use either the MYJ or MYNN PBL scheme. There was a check in module_check_a_mundo.F for this, but the logic was incorrect, meaning that a user would always get a fatal error when using the Deng scheme. Modified logic to correct this.
M     share/module_check_a_mundo.F
TESTS CONDUCTED: none
RELEASE NOTE: Bug fix for Deng shallow cumulus scheme (the scheme and the bug were introduced in release-v4.1). If using the Deng scheme, it is mandatory to use either the MYJ or MYNN PBL scheme. However, even when using one of these required PBL schemes, users would receive a fatal error due to incorrect logic in the check. This check …

bug fix for deng shcu check-a-mundo

---

var/da/da_radiance/da_cloud_detect.inc

TYPE: bug fix
KEYWORDS: WRFDA, Infrared Radiance Data Assimilation, Cloud detection
SOURCE: Dongmei Xu (NUIST/NCAR)
Three arrays are not deallocated in cloud detection subroutine, which caused segmentation fault with gnu-compiler compiled code for two WRFDA regression test cases related to AIRS and IASI DA (now by default cloud detection is on with particle filter) even though ifort-compiled code ran Ok.
M var/da/da_radiance/da_cloud_detect.inc
TESTS CONDUCTED: WRFDA regression tests ran successfully with gnu/ifort+mpt on Cheyenne.

A fix for the cloud detection scheme based on Particle Filter and MMR

---

dyn_em/module_big_step_utilities_em.F

TYPE: bug fix
KEYWORDS: diff_6th_opt, specified
SOURCE: Robert Rozumalski (COMET)
When a restart problem was fixed in 4.0.3 (Dec 18, 2018), an error was introduced. It used a logical 
variable 'specified' in subroutine sixth_order_diffusion, but it was not defined before it was used. This 
caused model failure in the case reported by Rob. This PR fixes the problem.
ISSUE:
Fixes #895 "module_big_step_utilities_em.F - logical variable "specified" not assigned"
M   dyn_em/module_big_step_utilities_em.F
Compiled and verified it fixed the user's problem.
RELEASE NOTE: 
Fixed a bug associated with option diff_6th_opt. When a restart problem was fixed in 4.0.3 (Dec 18, 2018), an error was introduced. It used a logical variable …

logical "specified" should be defined before use in diff_6th_opt

---

dyn_em/module_stoch.F

TYPE: bug fix
KEYWORDS: stochastic, random, pattern, spread, error, seed, dimension
SOURCE: problem found by and solution proposed by Judith Berner (NCAR)
The assignment of seeds for random numbers is complicated by the fact that the standard does not
provide a fixed number of required seeds. What is provided is a function that returns the 
necessary dimension of a random seed. Two currently used compilers (Intel and GNU) have the
dimensions for the seeds as 2 and 33, respectively.
Problem:
When multiple ensembles were run with stochastic processing, there was error but no spread.
Solution:
Judith Berner found that the DO loop for the assignment of value for the random seeds was not
being entered, due to the loop bounds. An IF test now checks if a sufficiently …

fix compiler-sensitive looping for random seeds initialization in stochastic processing

---

phys/module_ra_effective_radius.F

TYPE: bug fix
KEYWORDS: effective radius, radiation, exception
Problem:
This subroutine computes an effective radius given the mass and the number for the cloud,
snow, and graupel. 
1. When a denominator is zero (in the first time step), this gives a divide-by-0 situation.
2. After a time step, (cloud number / cloud mass < 0) is a problem when using a real exponent.
3. The sum of snow and graupel is used as a denominator. Both can be zero.
Solution:
Use MAX function to make sure that positive definite values are >= zero, and make sure that 
denominators are >= a pre-defined small value.
1. Both the cloud mass and the cloud number now use a MAX function with a previously existing value
(r1 = 1.e-12). The `rqcmps` variable is local, so it is changed …

Force positive definite with small mass and number from RRTMG K, avoids floating exception

---

share/input_wrf.F

TYPE: bug fix
KEYWORDS: LBC, valid time
SOURCE: identified by Michael Duda (NCAR/MMM), fixed internally
Problem:
1. If a user tried to start a simulation _after_ the last LBC valid period, the
WRF model would get into a nearly infinite loop and print out repeated statements:
```
THIS TIME 2000-01-24_18:00:00, NEXT TIME 2000-01-25_00:00:00
d01 2000-01-25_06:00:00  Input data is acceptable to use: wrfbdy_d01
2  input_wrf: wrf_get_next_time current_date: 2000-01-24_18:00:00 Status =           -4
d01 2000-01-25_06:00:00  ---- ERROR: Ran out of valid boundary conditions in file wrfbdy_d01
```
2. If a user tries to extend the model simulation beyond that valid times of the LBC, the code
behavior is not controlled (nearly infinite loops on some machines, or runtime errors …

Add controlled stop when detect timing problems with lateral boundary data

---

Registry/registry.var
var/da/da_main/da_wrfvar_init2.inc

KEYWORDS: WRFDA, EnVar, ep
Avoid unused ep allocation in alloc_and_configure_domain for EnVar applications.
ep is allocated in subroutine da_solve_init (var/da/da_main/da_solve_init.inc) or
subroutine reallocate_analysis_grid (var/da/da_main/da_solve_dual_res_init.inc)
with desired dimensions.
The 4th dimension of ep should be ensdim_alpha*num_fgat_time instead of just ensdim_alpha
as defined in registry.
For dual-res EnVar, the ep is re-allocated with coarse intermediate grid dimensions.
Depending on domain/ensemble sizes, the memory reduction with the fix can
allow the job to run on regular nodes instead of large-memory nodes on NCAR/cheyenne.
modified:   Registry/registry.var
modified: …

Fix DA EnVar unnecessary allocation to reduce memory requirement

---

.github/CODEOWNERS

KEYWORDS: CODEOWNERS
Add in a few more active developers
M .github/CODEOWNERS
MMM Classroom regtest; em_real, nmm, em_chem; GNU only
Individual tests:
SUCCESS_RUN_WRF_d01_em_real_32_em_chem_1
SUCCESS_RUN_WRF_d01_em_real_32_em_chem_2
SUCCESS_RUN_WRF_d01_em_real_32_em_chem_5
SUCCESS_RUN_WRF_d01_em_real_32_em_real_03FD
SUCCESS_RUN_WRF_d01_em_real_32_em_real_07NE
SUCCESS_RUN_WRF_d01_em_real_32_em_real_10
SUCCESS_RUN_WRF_d01_em_real_32_em_real_11
SUCCESS_RUN_WRF_d01_em_real_33_em_real_03FD
SUCCESS_RUN_WRF_d01_em_real_33_em_real_07NE
SUCCESS_RUN_WRF_d01_em_real_33_em_real_10
SUCCESS_RUN_WRF_d01_em_real_33_em_real_11
SUCCESS_RUN_WRF_d01_em_real_34_em_chem_1 …

Add more developers to CODEOWNERS file

---

var/gen_be_v3/README.gen_be_v3
var/gen_be_v3/compile_casper
var/gen_be_v3/compile_cheyenne
var/gen_be_v3/gen_be_v3.F90
var/gen_be_v3/util/combine_be_cv7.f90

KEYWORDS: WRFDA, ep, be, cv_options=7, cloud_cv_options=2, bin_type=5
Add a stand-alone program for
1. generating ep (ensemble perturbation)
2. generating be (background error statistics) for cv_options=7 and cloud_cv_options=2 (bin_type=5 only).
See var/gen_be_v3/README.gen_be_v3 for more info.
This PR complements PR#900.
ISSUE: none
new file:   var/gen_be_v3/README.gen_be_v3
new file:   var/gen_be_v3/compile_casper
new file:   var/gen_be_v3/compile_cheyenne
new file:   var/gen_be_v3/gen_be_v3.F90
new file:   var/gen_be_v3/util/combine_be_cv7.f90
Lots of various tests...
RELEASE NOTE: New stand-alone gen_be_v3 for generating ep (ensemble perturbation) and be
(background error) …

New gen_be_v3 for generating ep (ensemble perturbation) and be (background error)

---

var/da/da_obs_io/da_read_obs_bufr.inc

TYPE: bug fix
KEYWORDS: bufr, conventional obs, wrfda, missing value
SOURCE: Internal, JJ Guerrette
This error only arises in a debug build of WRFDA.
nint is applied to QM (quality marker) and PC (program code) values that are sometimes equal to 1e+11 in RAP/HRRR bufr files. Those large values can not be represented with a 4-byte integer. The solution is to check if the obs values are missing (> 9e+8) before using nint.  In a non-debug build, these same observations would normally be filtered out a few lines after the call to nint due to the missing values. Now the missing value check is performed before the error can arise.
This fix allows a debug build to be used to check other types of errors outside the bufr reading.
ISSUE: none
M …

Bugfix for missing values in bufr files

---

var/da/da_setup_structures/da_setup_flow_predictors_ep_format2.inc

TYPE: bug fix
KEYWORDS: ep, ep_format2, bcast, WRFDA
SOURCE: Internal, JJ Guerrette
These modifications are required following #908 for release-v4.1.1.
The interface to wrf_dm_bcast_* requires an array argument instead of a scalar.  A compile error only arises when #908 and #900 are merged together.  The fix was tested in a 4D-Var build, but should be general.
ISSUE: none
M       var/da/da_setup_structures/da_setup_flow_predictors_ep_format2.inc
TESTS CONDUCTED: Compilation is fixed when release-v4.1.1 is merged into develop.  This fix will also work in the current develop branch.

Add 1-d array placeholder for nens for broadcasting

---

share/input_wrf.F

TYPE: bug fix
KEYWORDS: missing files, input_wrf
SOURCE: identified by Michael Duda (NCAR/MMM), fixed internally
Problem:
The user was given an incorrect diagnostic print when an auxiliary file was missing (such as for
SST update or FDDA). The user was ALWAYS told that the WRF model could not read the 
metadata from the wrfout file. 
```
d01 2000-01-24_12:00:00  Error trying to read metadata
d01 2000-01-24_12:00:00 File name that is causing troubles = wrfout_d01_2000-01-24_12:00:00
d01 2000-01-24_12:00:00 wrfout_d01_2000-01-24_12:00:00
d01 2000-01-24_12:00:00  Error trying to read metadata
d01 2000-01-24_12:00:00  You can try 1) ensure that the input file was created with WRF v4 pre-processors, or
d01 2000-01-24_12:00:00  2) use force_use_old_data=T in the …
```

Identify which auxiliary file is missing - stop incorrectly blaming failures on wrfout metadata

---

configure
phys/module_checkerror.F
phys/module_gocart_coupling.F
phys/module_mp_gsfcgce_4ice_nuwrf.F
phys/module_ra_goddard.F

TYPE: bug fix
KEYWORDS: IEEE, GNU
SOURCE: reported by Maik Reichert, fixed internally
Problem:
With the introduction of the Goddard MP and radiation schemes in release-v4.1, there
are locations where the IEEE capability for Fortran 2003 is unconditionally used. With the 
default GNU compiler on Linux, the WRF code will not build. Updating the compiler, while
free, does require that the user then rebuild libraries from scratch.
Solution:
The WRF code has had tests for using IEEE for a number of years (with the svn releases,
starting with v3.6). Since that release, during the `configure` step, if a small test code fails 
to build or run successfully, the `configure.wrf` file sets a cpp compile-time flag. This ifdef
infrastructure is now added to the new …

Enforce conditional use of IEEE Fortran 2003 capabilities in v4.1 Goddard schemes

---

phys/module_mp_gsfcgce_4ice_nuwrf.F
phys/module_ra_goddard.F

TYPE: bug fix
KEYWORDS: Goddard, Intel, CHUNK
SOURCE: RCarpenter
Inside of frame/module_dm.F, there is an optimization effort for the Intel compiler:
```
#ifdef INTEL_ALIGN64
! align on 64 byte boundaries if -align array64byte
ims = ips-CHUNK
ime = ime + (CHUNK-mod(ime-ims+1,CHUNK))
#endif
```
This `CHUNK` variable is defined through a cpp directive in a couple of WRF build stanzas for
Intel: `Xeon Phi (MIC architecture)` and `Xeon (SNB with AVX mods)`, using the Intel compiler. 
For example:
```
ARCH_LOCAL  =   -DNONSTANDARD_SYSTEM_FUNC -DCHUNK=16 -DXEON_OPTIMIZED_WSM5
```
and
```
ARCH_LOCAL  =   -DNONSTANDARD_SYSTEM_FUNC -DCHUNK=64 -DXEON_OPTIMIZED_WSM5
```
[The switch `INTEL_ALIGN64` does not actually appear in any supported WRF build file.]
Therefore, for some …

"CHUNK = 16" -> "chunk = 16": avoids arch/configure.defaults -DCHUNK compiler flag confusion

---

frame/module_alloc_space.h

TYPE: bug fix
KEYWORDS: include, cpp, quotes, angle brackets, ", >
SOURCE: Jamie Bresch (NCAR/MMM)
Problem:
When using CPP \#include, to access local include files, the correct syntax is to use quotes 
to surround the filename. Using angle brackets makes the search look in standard system
directories.
Solution:
Swap the single location of WRF-manufactured include file: `<filename.inc>` for `"filename.inc"`.
modified:   frame/module_alloc_space.h
1. The code builds just fine.
2. The Jan 2000 test case looks as expected at 12-h.

Local CPP includes should use quotes, not angle brackets

---

Registry/Registry.EM_COMMON

TYPE: bug fix
KEYWORDS: Ishmael, DFI, package
The list of variables in the Ishmael MP for DFI mistakenly had a character missing from on field.
1. Before mod, there was a complaint from the Registry program.
```
Packages in gen_scalar_indices1
WARNING: qdfi_v is not a member of 4D array dfi_moist
```
2. After the mod, there is no Registry program complaint.

Ishmael DFI package typo: should be dfi_qv

---

Registry/registry.trad_fields

TYPE: bug fix
KEYWORDS: do_trad_fields, diag_nwp2, traditional fields
Problem:
The variable `theta` is not a state variable, but it was incorrectly used as a variable in the package 
for "do_trad_fields". 
Solution:
This PR removes `theta` from the package list, and replaces `theta` with the correct variable 
`potential_t`.  
Registry/registry.trad_fields
A single case with the option `diag_nwp2=1` (the option to output the traditional fields) is 
conducted. The model runs fine and the results are reasonable.

Correct variable in the package of "do_trad_fields"

---

run/README.namelist

KEYWORDS:  README.namelist, NMM
A few physics options are declared as "NMM only" in README.namelist, whereas they actually work 
for both ARW and NMM. 
Surface Layer: NCEP GFS (`sf_sfclay_physics=3`)
PBL: Hybrid EDMF GFS (`bl_pbl_physics=3`)
This PR corrects the information. 
M    run/README.namelist
A single ARW case is successfully done with the options of sf_sfclay_physics=3 and bl_pbl_physics=3. Results look fine.

Correct some instructions in README.namelist

---

dyn_em/module_initialize_real.F
dyn_em/nest_init_utils.F
main/depend.common
main/ndown_em.F
share/module_check_a_mundo.F

TYPE: bug fix
KEYWORDS: hybrid vertical coordinate, vertical refinement
SOURCE: Katie Lundquist (LLNL) and internal
Problem:
Since the formal introduction of the hybrid vertical coordinate option in
WRF (with version v4.0), the vertical refinement option (also referred to
as vertical nesting) has been broken for both of the options when vert_refine_method
= 1 or 2 (ndown or WRF, respectively). The symptomology is that model 
dies in the first time step, whether in the dynamics, physics, or initialization.
Solution:
Katie discovered that the 1d arrays (c1, c2, c3, c4 which are used to
construct the pressure level of the vertical levels) were never set for
vertical refinement.
Editor's note: These values were set for traditional nests. Since the number of
vertical …

Fix vertical refinement, broken from v4.0 through v4.1

---

var/da/da_vtox_transforms/da_vtox_transforms.f90

TYPE: bug fix
KEYWORDS: WRFDA, serial, compile
The error message of serial build:
```
da_vtox_transforms.f:44:26:
use da_par_util, only : true_mpi_real, mpi_sum, comm
1
Error: Symbol 'true_mpi_real' referenced at (1) not found in module 'da_par_util'
da_vtox_transforms.f:44:41:
use da_par_util, only : true_mpi_real, mpi_sum, comm
1
Error: Symbol 'mpi_sum' referenced at (1) not found in module 'da_par_util'
```
The fix is to move the line of code
use da_par_util, only : true_mpi_real, mpi_sum, comm
inside #ifdef DM_PARALLEL.
ISSUE:
Fixes #923
modified:   var/da/da_vtox_transforms/da_vtox_transforms.f90
WRFDA builds for serial mode after the fix.
RELEASE NOTE: Fix WRFDA V4.1.1 serial compilation …

Fix DA serial compilation failure introduced in commit dba34646

---

var/build/da_name_space.pl

TYPE: bug fix
KEYWORDS: WRFDA, 4DVAR, compile
Following commit 56d4bef4, the new function name (check_which_switch) needs to be added
in da_name_space.pl to avoid name conflict for 4DVAR build.
The error message:
```
duplicate symbol _check_which_switch_ in:
/Volumes/sysdisk1/hclin/WRFV4/wrfplus/main/libwrflib.a(input_wrf.o)
./libwrfvar.a(input_wrf.o)
ld: 1 duplicate symbol for architecture x86_64
collect2: error: ld returned 1 exit status
```
M       var/build/da_name_space.pl
WRFDA 4DVAR builds after the fix.
RELEASE NOTE: Fix WRFDA 4DVAR V4.1.1 compilation failure.

Fix 4DVAR compilation failure after commit 56d4bef4

---

Registry/registry.var

TYPE: bug fix
KEYWORDS: WRFDA, mp_physics, package, QVAPOR, physics_suite
Add back the packaging for mp_physics=-1 (added in commit 93a17919, but dropped
unintentionally in commit 81ca2ff0) to allow WRFDA to allocate qv in the cases when
(1) physics_suite is set and mp_physics is not set,
(2) both physics_suite and mp_physics are not set.
Commit 7427eac9 contains some information about physics_suite in WRFDA.
When mp_physics is not set in the namelist.input, its default -1 leads to no moist variable
(even qv) being allocated. Even if the user is able to identify the incorrect QVAPOR analysis,
it is almost impossible for the user to figure out why and how to solve the problem.
The problem can be avoided by setting proper mp_physics. For …

Fix to allow proper QVAPOR analysis when mp_physics is not set in namelist.input

---

dyn_em/start_em.F
phys/module_diag_trad_fields.F

TYPE: bug fix
KEYWORDS: diagnostics, temperature, moist theta
SOURCE: Nicolas Baldeck (OpenMeteoData), internal
In the traditional fields diagnostics option, the moisture is removed from the (already) dry theta 
perturbation. The `trad_fields` is called in two locations. From the diagnostics driver, the input to the scheme is:
```
CALL trad_fields ( &
!  Input data for computing
U=grid%u_2                                           &
,V=grid%v_2                                          &
,W=grid%w_2                                          &
,t=grid%th_phy_m_t0                                  &
```
From `start_em`, the call incorrectly and inconsistently uses `grid%t_2`, which is fixed in this PR 
to `grid%th_phy_m_t0`.
The name `th_phy_m_t0` means "theta from …

Bug fix: diagnostics: in temperature computation, incorrectly remove moisture from DRY theta perturbation

---

phys/module_diag_trad_fields.F

TYPE: bug fix
KEYWORDS: diagnostics
SOURCE: Nicolas Baldeck (OpenMeteoData), internal
When computing the earth-relative winds from the model's projection-relative winds, the resulting 
values of umet and vmet are correctly placed in the cell center. However, the averaging to the cell 
center from the momentum cell faces is missing a "divide by 2".
ISSUE:
Closes #935 "Bad Wind and Temperature values with diag_nwp2=1" (only the "wind" portion)
modified:   module_diag_trad_fields.F
```
+----- vt -----+        +--------------+
|              |        |              |
|              |        |              |
|              |        |              |
ul   ua,va     ur       |     um,vm    |
|              |        |              | …
```

Bug fix: traditional fields diags, u and v are 2x too large

---

Registry/Registry.EM_COMMON

TYPE: bug fix
KEYWORDS: topographic shading, radiation, restart runs, nested domains
SOURCE: Emily Collier (FAU Erlangen-Nürnberg)
1. Added ht_shad to the restart files
Restart runs aren't reproducible in nested domains when topographic shading is turned on, because ht_shad is not initialised in grid points adjacent to the lateral boundary of the nest.
Zero values for ht_shad at affected grid points (all located one grid point away from the eastern boundary in the same patch) lead to different values of shadowmask and swnorm. Here is a diff of swnorm in D2 in the first affected time step for a restart at 04 UTC:
Here is swdown for reference:
Adding ht_shad to the restart files makes restart runs reproducible for all domains when topo_shading is used.
ISSUE: #922 …

Fix to make restarts reproducible in nests when topo_shading is used

---

phys/module_mp_jensen_ishmael.F

TYPE: bug fixes
KEYWORDS: code changes/bug fixes
1) Added allocation for single-precision lookup tables which are defined from the double-precision ones. Without this, certain versions of PGI throw an error. 
2) Moved the calculation of the inherent growth ratio to prevent if from being undefined in certain instances.
3) Storing dsold (old deltastr value, or shape parameter), use it to diagnose shape during nucleation and aggregation (transfer between ice categories), and ensure that this value stays in bounds. This prevents the updated shape from going out of bounds in certain instances.
4) Moved the mass check for aggregation to occur to around the aggregation subroutine call to prevent the aggregate diagnostics, calculated …

Jensen ISHMAEL microphysics: Bug fixes

---

compile

TYPE: bug fix
KEYWORDS: compile, version_decl
The `compile` script has a line to inform users of the version of WRF that is being built, purely 
for informational purposes:
```
cat inc/version_decl | cut -c 45-54
```
While this could have been more general, it worked OK with the original syntax of the original
`inc/version_decl` file.
With the inclusion of modification 18c66c7eb99e in PR #918 "Prepare for WRF-v4.1.1 release", the 
string in the `inc/version_decl` file is no longer a fixed length, so the original character count
(grabbing 45 through 54), is no longer valid.
A modification to the `compile` script handles retrieving this information in a more robust fashion
from the `inc/version_decl` file.
The old version_decl file:
```
CHARACTER …
```

Fix compile script to print model version, due to new version_decl format

---

run/README.namelist

KEYWORDS: oml_hml0, and dfi_savehydmeteors
SOURCE: Jamie Bresch (NCAR/MMM), internal
Two changes for README.namelist 
1. The namelist variable `oml_hml0` used to be used for constant initial ocean mixed layer depth 
(> 0) and  real-time ocean mixed layer depth (such as from HYCOM) (< 0). But since version 3.9, 
an option was added to use climatology ocean mixed layer depth by setting this variable to 0. This 
information is now added to the README file. 
2. The other correction is to namelist variable `dfi_radar`. It has been renamed to 
`dfi_savehydmeteors` since version 3.5, but that change was not reflected in the README file. 
Both are namelist options are correctly updated with this PR.
TESTS …

README.namelist: Adding new option, correct changed option

---

dyn_em/namelist_remappings_em.h
share/module_check_a_mundo.F

TYPE: bug fix
KEYWORDS: bucket
SOURCE: Chang Hai Liu (NCAR/RAL), internal
Problem:
This modification includes two types of changes dealing with the buckets used for longer-term 
simulations. The purpose of these buckets is to allow for an accurate accumulation of small values
over seasonal or regional climate time scales. These capabilities are both driven by derived namelist
options. Once a user defines a bucket size > 0, then the option is automatically activated.
Solution:
1. The bucket information for precipitation used to be buried in `dyn_em/namelist_remappings_em.h`,
which is not conventional and certainly not easy to find. This assignment of this derived variable is
moved into `module_check_a_mundo.F`, where it belongs.
2. More importantly, there was no …

Relocate derived bucket assignment to conventional location

---

var/da/da_setup_structures/da_setup_background_errors.inc

TYPE: bug fix
KEYWORDS: WRFDA, namelist, alpha_std_dev
SOURCE: Jamie Bresch (NCAR/MMM)
The current default of alpha_std_dev is 1.0, so the new code gives identical results.
The original code would be incorrect if users set namelist alpha_std_dev to values other than 1.0.
B = (1/Jb_factor)*Bb + (1/Je_factor)*Be where (1/Jb_factor)+(1/Je_factor) = 1.0
So that jb_factor = je_factor / ( je_factor - 1.0 ) as in the new da_setup_background_errors.inc.
Beyond the code diff can be seen in this PR,
alpha_std_dev value is assigned to variable sigma_alpha in da_setup_background_errors.inc.
sigma_alpha is then used in da_setup_be_regional.inc to inflate the localization covariance matrix.
modified: …

Fix to make DA namelist alpha_std_dev act as intended for tuning flow-dependent B

---

var/da/da_radiance/da_transform_xtoy_crtm.inc
var/da/da_radiance/da_transform_xtoy_crtm_adj.inc
var/da/da_transfer_model/da_transfer_wrftoxb.inc

TYPE: bug fix
KEYWORDS: CRTM, radiance, DA, water vapor, humidity
SOURCE: JJ Guerrette (NCAR)
DESCRIPTION OF CHANGES: There is a missing unit conversion in the inverse of the specific humidity to mixing ratio [g/kg] conversion for the trajectory value of specific humidity.  The 1000 multiplier in the forward conversion needs to be divided out in both usages of `iv%instid(inst)%qm`.  This is an inverse equation, not a TL or AD equation.  Bug was originally introduced in commit 058491a786df6f2.
M       var/da/da_radiance/da_transform_xtoy_crtm.inc
M       var/da/da_radiance/da_transform_xtoy_crtm_adj.inc
M       var/da/da_transfer_model/da_transfer_wrftoxb.inc
TESTS CONDUCTED: I ran difference tests for convection-permitting clear-sky and all-sky GOES-ABI experiments …

Add missing unit conversion for inverse of specific humidity to mixing ratio [g/kg]

---

phys/module_bl_ysu.F

TYPE: bug fix
KEYWORDS: YSU, WSM3, Kessler, ice check
YSU checks on PRESENT(RQIBLTEN) to determine whether to fill local ice part of qv2d, but 
RQIBLTEN is always present, so this does not avoid copy from ice array when WSM3/Kessler MP 
is used. Better to check flag_qi which is also available and true except for WSM3 and Kessler.
phys/module_bl_ysu.F
RELEASE NOTE: 
Using the YSU PBL scheme in combination with either the WSM3 or Kessler MP schemes (no ice) is now fixed to not use ice array.

YSU PBL: check on flag_qi instead of present(rqiblten)

---

dyn_em/module_initialize_ideal.F

KEYWORDS: ideal, eta
CPreviously, no check existed to detect invalid eta levels that a user specified in the `namelist.input`
file for an idealized case. A couple loops of code were copied from the file
`dyn_em/module_initialize-real.F`, which is used in the _real_ program.
1. Check that first and last level are 1.0 and 0.0, respectively.
2. Check that the eta levels are strictly monotonically decreasing (from surface to model lid).
M dyn_em/module_initialize_ideal.F
TESTS CONDUCTED:  
RELEASE NOTE:
If a user chooses to explicitly list the eta levels for an idealized case, a check has been added to verify that valid eta levels are supplied for idealized cases in the namelist.input file.

check eta levels in ideal case

---

Registry/Registry.EM_COMMON

TYPE: bug fix
KEYWORDS: bug, MYNN, PBL, cldfra_bl, icloud_bl, Registry
DESCRIPTION OF CHANGES: When using the MYNN PBL scheme, restarts did not give bit-for-bit 
results. When using this scheme, the default setting for icloud_bl is 1 (on), but the variable used 
(cldfra_bl) was not put in the restart stream. Simply adding this variable to the restart stream in 
Registry.EM_COMMON corrects the problem.
Confirmed that the code builds, and the change corrects the non-bit-for-bit restart problem.
RELEASE NOTE: When using the MYNN PBL scheme, with icloud_bl = 1 (which is default), restarts did not give bit-for-bit results when compared to a non-restart run. This has been a problem since the option was …

bug fix for mynn PBL restarts - not giving bit-for-bit results

---

Registry/Registry.EM_COMMON

TYPE: bug fix
KEYWORDS: bug, MYNN, registry, el_pbl, restart, differences
DESCRIPTION OF CHANGES: When using the MYNN PBL scheme, restarts were not giving 
bit-for-bit results when comparing the output of a standard run with that of a restart run. This 
was thought to have been corrected in d944f1e, but was not. When using MYNN, the default 
setting for icloud_bl is 1 (on), but a variable that is used (el_pbl) was not put in the restart stream. 
Simply adding this variable to the restart stream in Registry.EM_COMMON corrects the problem.
Confirmed that the code builds, and the change corrects the non-bit-for-bit restart problem.
RELEASE NOTE: When using the MYNN PBL scheme, with icloud_bl = 1 (which …

MYNN PBL restart differences: add restart output stream for el_pbl

---

phys/module_bl_ysu.F

TYPE: bug fix
KEYWORDS: YSU, WSM3, Kessler, ice check
YSU checks on PRESENT(RQIBLTEN) to determine whether to fill local ice part of qv2d, but
RQIBLTEN is always present, so this does not avoid copy from ice array when WSM3/Kessler MP
is used. It is better to check flag_qi which is also available and true (except when using either
WSM3 and Kessler MP schemes).
phys/module_bl_ysu.F
Check code runs and uses flag_qi for simple MP scheme.
RELEASE NOTE:
Using the YSU PBL scheme in combination with either the WSM3 or Kessler MP schemes (no ice) is now fixed to not use ice array.

YSU fix for WSM3 and Kessler no-ice test

---

Registry/registry.var
var/README.namelist
var/da/da_define_structures/da_initialize_cv.inc
var/da/da_main/da_solve.inc
var/da/da_main/da_wrfvar_top.f90
var/da/da_tools/da_set_randomcv.inc

KEYWORDS: WRFDA, RANDOMCV
SOURCE: Jamie Bresch (NCAR/MMM), Tom Auligne (previously NCAR, initiated the change in 2010)
Simplify and cleanup the analysis_type="RANDOMCV" capability.
(1) Remove unnecessary and redundant code for anal_type_randomcv.
Non-relevant files and log messages are not written out.
(2) Add a new namelist n_randomcv (default=1) to allow the generation of multiple perturbed output in one run.
For example, wrfvar_output_randomcv.e001, wrfvar_output_randomcv.e002, etc.
The changes have no impact on non-RANDOMCV applications.
M       Registry/registry.var
M       var/README.namelist
M       var/da/da_define_structures/da_initialize_cv.inc
M       var/da/da_main/da_solve.inc
M …

Improve DA RANDOMCV capability

---

Registry/Registry.EM_COMMON
dyn_em/module_diffusion_em.F
dyn_em/module_first_rk_step_part2.F
dyn_em/solve_em.F
run/README.namelist
share/module_check_a_mundo.F
test/em_real/examples.namelist

KEYWORDS: 3DTKE scheme, scale-adaptive
SOURCE: Xu Zhang (Shanghai Typhoon Institute/CMA, China)
This PR adds a new scale-adaptive 3DTKE scheme (SMS-3DTKE, Shanghai Meteorological Service) 
for subgrid turbulent mixing. The new scheme is self-adaptive to the grid-size between the 
large-eddy simulation (LES) and mesoscale limits. The new 3DTKE scheme is added as a new 
diffusion option km_opt = 5. This option extends original LES subgrid model 1.5-order TKE closure 
(km_opt=2) to the mesoscale, and can be used in LES, mesoscale, and the gray zone resolutions in 
between. In the horizontal diffusion, the new scheme blends horizontal Smagorinsky first-order 
closure (km_opt=4) and 1.5-order TKE-based horizontal diffusivity. In the mesoscale limit, …

Add a scale-adaptive 3DTKE parameterization scheme as a subgrid mixing option 

---

Registry/Registry.EM_COMMON

TYPE: bug fix
KEYWORDS: packaging, sms3dtke
The existing packaging in combination with the logic added in the
code for PR #972 (Add a scale-adaptive 3DTKE parameterization scheme as a subgrid 
mixing option) d059afe1e646f7 causes segmentation faults for most model
simulations that use km_opt=2.
The packaging is important, but we have a broken repository. The
packaging will be removed, developers will fix the problem, and
then put the packaging back into the Registry file for this option.
Jan Mandel states:
> "found that l_scale, th_h_tend, and tke_diffusion_h_tend made my km_opt=2 test case fail, 
and with them removed from the package it did not fail. But I do not know if sms_3dtke even 
with the packaging removed does not break something in a …

SMS3dTKE: Remove broken packaging for km_opt=5

---

dyn_em/module_diffusion_em.F

TYPE: bug fix
KEYWORDS: sms3dtke, km_opt==5
Each location where the optional diagnostics for km_opt==5 are computed,
instead of only using a local IF test, now a combination of the same local
IF test (T/F do the computation) is used in conjunction with and a test
for if the diagnostic is permitted (is km_opt==5).
The km_opt==5 scheme originally had (and hopefully, will eventually again have) 
specified arrays via the package capability in the Registry. Those fields need to be 
protected from accidental use when km_opt==2.
modified:   dyn_em/module_diffusion_em.F

Add missing "IF km_opt==5" tests for diag computations

---

phys/module_sf_oml.F

TYPE: bug fix
KEYWORDS: module_sf_oml, message
When code is compiled with no optimization (configure -D) and distributed memory, and 
sf_ocean_physics = 1, the model stops when trying to write a message requesting the value of 
h0ml(1,1). This value will only be valid for MPI task 0, and therefore causes all other MPI tasks to 
stop with a bounds check error. This h0ml field is a 2d array, and the (1,1) location could be 
masked over land. Other than a simple indicator of which branch of the IF loop, no actual value 
is printed.
M    phys/module_sf_oml.F
RELEASE NOTE: Corrected a problem that caused model to stop when using sf_ocean_physics = 1, with WRF code compiled for bounds checking.

OML: fix out of bounds print

---

phys/module_ra_rrtmg_sw.F
phys/module_ra_rrtmg_swf.F
phys/module_ra_rrtmg_swk.F

TYPE: bug fix
KEYWORDS: RRTMG shortwave radiation, dividing by zero
In 3.5.1, a bug fix was introduced to fix possibility of dividing by zero in subroutine reftra_sw. The fix was to limit the denominator to a small positive number. However, this denominator can be both positive and negative. This fix is hence not correct, and introduced cold bias in areas of cloud. This PR fixes the problem in module_ra_rrtmg_sw.F. The same fix is also added to the other two versions of RRTMG shortwave code.
The attached figure shows temperature difference profiles from original 3.5.1 code and fixed 3.5.1 code compared to v3.4.1 over a Southeast Asia domain 6 h into the forecast. The rest of the difference is due to the introduction of eot, or 'equation of time' …

Bug fix for RRTMG shortwave radiation

---

phys/module_mp_nssl_2mom.F

TYPE: bug fix
KEYWORDS: snow reflectivity; ice effective radius
SOURCE: Ted Mansell (NSSL microphysics developer/maintainer)
Bug fixes:
- Effective radius calculations were only done at history times. Now is done every time step. [impact only when used with RRTMG radiation]
- Snow reflectivity: Previous "fix" was incorrect and yields snow dBZ that is too low. Reverted to old version which was correct
- Incorrectly updated a state value in the reflectivity code. (Could cause small differences if reflectivity is not calculated)
Updates:
- Put limit on snow volume (2 cm diameter) in aggregation rate [enhancement]
- Graupel and hail drag coefficients are returned from fall speed subroutine to use in ventilation coeffs. for consistency (minor change) [enhancement]
- …

Release v4.1.3 nssl mp update

---

phys/module_mp_jensen_ishmael.F

TYPE: bug fix
KEYWORDS: comma, write, syntax, Cray, Ishmael
A comma in a `write` statement following the closing ")" is a Fortran syntax error. Only the Cray
compiler picked this up.
modified:   phys/module_mp_jensen_ishmael.F
in the Jensen MP scheme.

BF: Remove extra comma in write statement inside Jensen MP

---

phys/module_mp_thompson.F

TYPE: bug fix
KEYWORDS: observation nudging, Thompson microphysics
SOURCE: Brian Reen (Army Research Lab)
When observation nudging was used on domain 3, Thompson microphysics was used, and the .dat files used by Thompson microphysics were already present WRF would crash.
The problem originates from the same unit (63) being used for the Thompson microphysics .dat files (qr_acr_qg.dat, qr_acr_qs.dat, and freezeH2O.dat) and the domain 3 observation nudging input file (OBS_DOMAIN301).  The Thompson microphysics code does not explicitly close qr_acr_qg.dat and freezeH2O.dat, and when observation nudging attempts to read from unit 63, it is freezeH2O.dat that is open rather than OBS_DOMAIN301.
This problem was earlier found and corrected in …

Fix conflict between obs nudging and Thompson microphysics

---

arch/Config.pl
share/module_check_a_mundo.F

TYPE: bug fix
KEYWORDS: grid_allowed, check_a_mundo
SOURCE: Kevin Manning (NCAR/MMM), internal
The WRF model has a construct to permit users to bypass specified nested domains (and all of that 
nest's children) using the `grid_allowed` option. In the example below, the 3-domain run is really
only a 2-domain run.
```
&domains
grid_allowed = T, F, T
parent_id    = 0, 1, 1,
max_dom      = 3,
/
```
Problem:
If a user activated this option, the namelist checker in `module_check_a_mundo.F` previously did not consider whether a domain was active. For an unused domain, the WRF model would return a fatal error if, for example, the number of grid cells for the unused domain was too small for the decomposition.
Solution:
For each of the domain-indexed namelist checks in …

Namelist checks only to be conducted on "allowed" grids

---

phys/module_fddaobs_rtfdda.F
share/wrf_fddaobs_in.F

TYPE: bug fix
KEYWORDS: observation nudging, diagnostic prints, obs_prt_max
SOURCE: Brian Reen (Army Research Lab)
The observation nudging diagnostic prints controlled by obs_prt_max were sometimes incorrect.  Information from different observations were sometimes mixed together and sometimes missing values were printed when it tried to print observations that were not available for printing.  This bug did not influence the nudging itself, only the diagnostic prints regarding the nudging.
Observation nudging stores some information to be printed about the obs in arrays specifically for diagnostic prints.  However, some fields printed do not have diagnostic-print specific variables.  When old obs are removed from non-diagnostic-print variables and the placement of …

Obs nudging diagnostic print fix

---

share/input_wrf.F

TYPE: bug fix
KEYWORDS: spelling in comment
SOURCE: Piotr Kasprzyk (CIRI - self employed)"
Change misspelled DIMENSION - it has no "E" letter by mistake
share/input_wrf.F
No tests conducted.

Change S letter to E letter in text DIMENSION

---

Registry/Registry.EM_COMMON
run/README.tslist
share/module_check_a_mundo.F

TYPE: bug fix
KEYWORDS: max_ts_level
SOURCE: Pedro Jimenez Munoz (RAL/MMM), internal
The value of `max_ts_level` should be set less than or equal to the number of half levels. If 
`max_ts_level` is accidentally set to a larger value, the wrf_timeseries.F would try to access 
the vertical velocity (`w_2`) and other variables that are defined on full levels with an index 
outside of the variables' extent.  A check is added to check_a_mundo to ensure that if 
`max_ts_level` is  set up to a number larger than the number of half layers, then it is reset to 
the number of half layers.
ISSUE:
Fixes #976 "Need check_a_mundo test: max_ts_level must be <= number of znu half layers"
M    share/module_check_a_mundo.F
M    run/README.tslist 
TESTS …

max_ts_level should be .LE. the number of half levels

---

phys/module_mp_thompson.F

TYPE: bug fix
KEYWORDS:  MP, Thompson, xDs, vts_boost
SOURCE:  Greg Thompson (NCAR-RAL)
DESCRIPTION OF CHANGES:  Some relatively minor bug fixes and safety checks
1. xDs (mass-weighted mean size snow) was only set if both cloud water and snow coexist in grid 
box, so its calculation was moved out of IF-test to be calculated at any grid box with any 
reasonable amount of snow.
2. couple small safety checks to avoid exceeding max amount of possible snow, graupel, or cloud 
water in a few places (e.g., prs_scw, prr_sml, tmg_gacs)
3. vts_boost should always default 1.0, not 1.5. vts_boost is the factor applied to snow terminal 
fallspeed due to riming of snow (up to 50% faster).
4. ensure snow moment variables get initialized to zero in calc_refl10cm
5. density calculation moved up (out of …

MP Thompson: mean snow size init; limit max values of snow/graupel/cloud; terminal velocity for rimed snow 

---

phys/module_fr_fire_util.F

TYPE: bug fix
KEYWORDS: fire, bounds check, vertical index
A bounds check indicated a half-level variable was accessed with
the vertical index at the top full-level. Only a single array is
in the DO loop. The vertical index is reduced by one.
modified:   phys/module_fr_fire_util.F
throws an error.
completes the simulation without any troubles.

Fire: fix vert index for half-levels

---

wrftladj/module_diffusion_em_ad.F

TYPE: WRFPlus maintainance
KEYWORDS: WRFPlus, adjoint code update
PR #972 breaks wrfplus code compilation, this PR fixes compilation issue.
ISSUE: None.
M:   wrftladj/module_diffusion_em_ad.F
WRFPlus/3DVAR/4DVAR compilation Ok and WRFDA regtests passed.
RELEASE NOTE: None.

Fix WRFPlus compilation issue caused by PR #972.

---

run/README.namelist

KEYWORDS: WSM7, WDM7, README
Microphysics options WSM7 and WDM7 were introduced in 4.1, but not added to README.namelist file. This PR adds them.
No test needed.
RELEASE NOTE:

Add WSM7 and WDM7 to README.namelist

---

chem/module_gocart_settling.F

TYPE: bug fix
KEYWORDS: GOCART, WRF-Chem, dust gravitational settling flux.
SOURCE: Alexander Ukhov, KAUST
DESCRIPTION OF CHANGES: I introduced a typo in #714. This typo affected only the diagnostic variables (GRASET_1,...,5). Dust mixing ratios were not affected. The derivation of the dust gravitational flux in the surface grid-cell is attached below. Multiplication by RHO_air is done in strings 158-162.
chem/module_gocart_settling.F
TESTS CONDUCTED: After the changes model runs and outputs corrected dust flux.

fixed calculation of the dust gravitational flux

---

configure

TYPE: bug fix
KEYWORDS: Linux, Darwin, nc-config, configure
SOURCE: Yago Riveiro (Air Quality and Odor Management - AQOM), internal
This pull fixes the incorrect use of `whereis` when we try to locate `nc-config` 
command. 
- Only the `which` command is valid. 
- The return code is used, not the value of the `which nc-config` command.
- There is no need to determine the OS prior to this test.
M       configure

Fix incorrect use of whereis and which to find nf-config command

---

var/da/da_radiance/da_cld_eff_radius.inc

TYPE: bug fix
KEYWORDS: effective radius, lamda calculation
SOURCE: Yali Wu (NCAR)
DESCRIPTION OF CHANGES: Subroutine `da_cld_eff_radius` uses exponential distribution for calculating the effective radius of different hydrometeor particles. 
Slope parameters should be calculated following:
```
sqrt(sqrt(piover6*rho_x*n0_x/(rho*qx)))
```
but this was incorrectly typed, so that rho is in the numerator:
```
sqrt(sqrt(piover6*rho_x*n0_x*rho/qx)))
```
where, x denotes rain, snow, and graupel.
M       var/da/da_radiance/da_cld_eff_radius.inc
TESTS CONDUCTED: Conducted tests before and after bugfix on Cheyenne. The model simulated MW radiances were slightly improved for a typhoon case, while the simulated IR radiances seemed to have no difference.

Bug fix for calculating effective radius of rain, snow, and graupel

---

phys/module_sf_sfclayrev.F

TYPE: bug fix
KEYWORDS: sfclayrev scheme, divide by zero
SOURCE: internal (reported by CH Liu)
During iterative solution for z/L there are rare cases where the same bit-for-bit value is returned for slightly different inputs to function zolri2 resulting in a divide by zero. This appears to be rare.
Fix is to return when these are found equal because solution is converged already.
phys/module_sf_sfclayrev.F 
Fix works for case that stopped.
Test on standard June case is bit-for-bit as expected
No regtests yet (Jenkins?)
RELEASE NOTE: 
Fix for occasional divide-by-zero error in sfclayrev option.

sfclayrev fix for divide by zero

---

Registry/registry.hyb_coord

KEYWORDS: hybrid comments
SOURCE: Found by Kezhen Chong (Georgia Institute of Technology), fixed internally
Modify the comments in registry.hyb_coord to correctly define c4f and c4h. Originally, the value
of the pressure at the model lid (ptop) was included in the description of the computation of
the C4F and C4H 1d arrays as an added term. Following is the source code showing no such term.
```
!  c4 is a function of c3 and eta.
DO k=1, kde
c4f(k) = ( znw(k) - c3f(k) ) * ( p1000mb - p_top )
ENDDO
!  Now on half levels, just add up and divide by 2 (for c3h).  Use (eta-c3)*(p00-pt) for c4 on half levels.
DO k=1, kde-1
c4h(k) = ( znu(k) - c3h(k) ) * ( p1000mb - p_top )
ENDDO
```
ISSUE: 
Fixes #1050
modified: …

Fix comments in hybrid coordinate registry

---

Makefile
external/RSL_LITE/module_dm.F

TYPE: bug fix
KEYWORDS: HWRF, build, run
To get the HWRF code to build and run the regression test cases, two changes are required:
There is a replicated symbol in subroutine feedback_domain_nmm_part2: SMOOTHER. This
named symbol cannot be both a LABEL and the name of a called SUBROUTINE within 
a single subprogram unit (subroutine or function). Just a quick misspelling of SMOOTHR works
wonders.
Link in (ln -sf) all of the look-up tables to the test/nmm_real directory in the last step of the build
process. Most of the run-time-required links to physics data files were not originally in place.
modified:   Makefile
modified:   external/RSL_LITE/module_dm.F

HWRF fixes: build = replicated symbol; run = link in look-up tables

---

external/RSL_LITE/module_dm.F

TYPE:bug fix
KEYWORDS: fire, pop, push, communicator
Problem:
WRF gets into a state where the code tries to pop or push a stack of communicators. This should 
not happen when doing a Serial or OpenMP build.
Here is the example error message we get with a push on OpenMP:
```
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:    5489
pop_communicators_for_domain on empty stack
-------------------------------------------
```
And here is the example error message with a pop with OpenMP:
```
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:    5464
push_communicators_for_domain would excede stacksize
-------------------------------------------
```
Solution:
This problem only occurs with …

Remove pop/push communicator on non MPI runs

---

dyn_em/module_initialize_real.F
frame/module_driver_constants.F

TYPE: bug fix
KEYWORDS: eta, levels
Problem:
The real program fails when the number of vertical levels is more than a thousand.
Solution:
There is a single PARAMETER in the frame directory that is used to allocate space for the namelist
read and the eta computation in the real program. We absolutely need a parameter for 
allocating space for the namelist variables. The original value for the maximum number of eta 
levels was 1001. The 10x increase in size (from 1001 to 10001) impacts only a couple of 1d
arrays, so the WRF memory footprint is not dramatically increased.
The mods to the real program are for a stand-alone program buried in the source, and therefore
do not impact the traditional processing of either the real program or the WRF model. …

Increase max_eta from 1001 to 10001

---

phys/module_physics_init.F

KEYWORDS: landuse variables
DESCRIPTION OF CHANGES: Add descriptions
M  phys/module_physics_init.F
Text only.

add description for LANDUSE variables

---

Registry/Registry.EM_COMMON
Registry/Registry.NMM
dyn_em/module_diffusion_em.F
dyn_em/module_first_rk_step_part2.F
dyn_em/solve_em.F
share/module_check_a_mundo.F

TYPE: bug fix
KEYWORDS: SMS-3DTKE, package
SOURCE: Xu Zhang (Shanghai Typhoon Institute)
1. Redefined the variable `l_scale` using a new name `l_diss`, which does not conflict with
variables used in `km_opt=2`.
2. Packaged seven variables used in the `km_opt=5`.
3. Deleted most diagnostic variables such as `u_h_tend`, `v_h_tend`, `w_h_tend` that are 
seldom used by most users, and cleaned up the related codes. Only seven state variables used 
in `km_opt=5` are left.
Registry/Registry.EM_COMMON
Registry/Registry.NMM
dyn_em/module_diffusion_em.F
dyn_em/module_first_rk_step_part2.F
dyn_em/solve_em.F
share/module_check_a_mundo.F

Fixing the problem that km_opt=5 breaks km_opt=2 and cleaning codes

---

Registry/Registry.EM_COMMON
Registry/Registry.NMM
main/real_em.F
run/README.namelist
share/mediation_integrate.F
share/module_check_a_mundo.F
test/em_real/examples.namelist

KEYWORDS: LBC files
SOURCE: Kevin Manning and Jim Bresch (MMM/NCAR), internal
For real-time users, the ability to start the WRF model before the
GFS model finishes allows the WRF model to complete a regional 
simulation earlier (because of not delaying the model start). However, this 
only works if the lateral boundary files from subsequent times are able to be 
ingested by the model. As a compile-time option, this split LBC capability has 
existed for years. Now that capability from the compile-time option is run-time 
selectable from the namelist.
1. WRF model
Modify the compile-time option in WRF that provides the capability for split
LBC files, and now make that capability a namelist-driven run-time option.
By default, the multi_bdy_files …

Multiple LBC files for ARW, run-time option

---

Makefile
phys/module_radiation_driver.F
share/module_check_a_mundo.F

TYPE: Enhancement
KEYWORDS: vertical nesting, RRTMG, longwave radiation, ra_lw_physics
SOURCE: Robert Arthur (LLNL)
DESCRIPTION OF CHANGES: When the RRTMG longwave radiation scheme (ra_lw_physics=4) was 
used in combination with vertical nesting, the longwave radiation was incorrect because the 
variable NLAYERS was set incorrectly. To fix this, NLAYERS is recalculated based on the updated 
number of vertical levels. This fix follows what is done already in the code for ra_lw_physics=1.
phys/module_radiation_driver.F
share/module_check_a_mundo.F
1. Regression test runs and gives bit-wise identical parallel solutions with RRTMG and vertical 
nesting (21VN), and is also able to run RRTMG without vertical nesting (case=tropical, 
case=conus):
``` …
```

Fix to allow RRTMG longwave radiation (ra_lw_physics=4) to be used with vertical nesting

---

phys/module_diag_misc.F
phys/module_mp_thompson.F

KEYWORDS: Thompson microphysics, graupel, Y-intercept parameter
SOURCE: Greg Thompson (NCAR-RAL)
Significant alteration of how Y-intercept parameter is diagnosed for one-moment graupel.  
Attempt is made to follow observations of Field et al. (2018JAMC). Y-intercept is now directly 
proportional to mass mixing ratio as opposed to being inversely proportional. Also expands the 
lookup tables for rain collecting either snow or graupel and the total range of Y-intercept values.
ISSUE:  
Fixes issue #966 "module_mp_thompson lookup tables (qr_acr_qs.dat and qr_acr_qg.dat) with 
PR: graupel_Yintercept_new".  Due to the expansion of the elements in 3 vectors (called "r_s," 
"r_g," and "N0g_exp") along with the number of elements held in variables …

Thompson MP: new one-moment Graupel y-intercept

---

Registry/Registry.EM_COMMON
dyn_em/module_big_step_utilities_em.F
dyn_em/module_first_rk_step_part1.F
phys/module_bl_mynn.F
phys/module_pbl_driver.F
phys/module_physics_init.F
share/module_check_a_mundo.F

TYPE: bug fix, enhancement, and new feature
KEYWORDS: mass-flux, diffusivity, subgrid clouds, memory reduction
SOURCE: Joseph Olson (NOAA) with contributions from Jaymes Kenyon (NOAA/CIRES)
-   A series of small tweaks to help reduce a cold bias in the PBL:
- slight increase in diffusion in convective conditions
- relaxed criteria for mass-flux activation/strength
- added capability to cycle TKE for continuity in hourly updating HRRR
- added effects of compensational environmental subsidence in mass-flux scheme,
which resulted in tweaks to detrainment rates.
-    Bug fix for diagnostic-decay of SGS clouds - noticed by Greg Thompson. This has
a very small, but primarily  positive, impact on SW-down biases.
-    Tweak to calculation of KPBL - urged by Laura Fowler - …

Update to MYNN-EDMF

---

arch/configure.defaults
external/RSL_LITE/c_code.c
external/RSL_LITE/module_dm.F
external/RSL_LITE/rsl_lite.h

KEYWORDS: MPI, rsl
Problem:
1. Previously, when the model requested more than 9999 MPI processes, the attempt
to generate the file names for the out and error files from processes 10000 and up,
caused the model to ungracefully stop.
2. Previously, when the model requested more that 10000 MPI processes, a maximum
number of MPI slots was exceeded.
3. If a user did run with a large number of MPI processes (< 9999, but still a large number),
the default behavior was to create an out and error file for each process. While a user may
override this default behavior of file generation, it was not was not easy to figure out.
Solution:
1. The file name is now a function of the total number of MPI processes that are
requested. When …

Allow > 9999 MPI processes

---

phys/module_ra_rrtmg_lw.F
phys/module_ra_rrtmg_lwf.F
phys/module_ra_rrtmg_sw.F
phys/module_ra_rrtmg_swf.F
phys/module_radiation_driver.F

KEYWORDS: CO2, RTTMG longwave and shortwave
CO2 is changing as a function of year. The default RRTMG value is 379 ppm valid in 2005. 
Current values exceed 400 ppm. A simple exponential function fits the past century to about 1%.
The function applied is CO2(ppm) = 280 + 90 exp (0.02 (year-2000)). Below are two plots 
using this function. 
The first figure shows the analytic function and measured values, as a function of time.
The second figure shows the difference in the analytic and measured values for CO2.
This PR partially replaces #705 "User defined values for CO2 content in RRTMG and NOAH-MP".
The modifications are only to RRTMG (and the fast version).
module_ra_rrtmg_lw.F
module_ra_rrtmg_sw.F …

Add year dependent CO2 function as default for RRTMG only

---

phys/module_radiation_driver.F

TYPE: bug fix
KEYWORDS: Deng shallow, radiation-driver clouds
SOURCE: internal and Pedro Jimenez
Line qc_save = qc must be removed from Deng shallow section of radiation driver because it may save qc that is already updated by other physics that have radiation feedback, e.g. icloud, cu or bl. Leads to error when combining Deng shallow with such options (already not recommended with cumulus scheme). qc_save was already set for all options earlier.
phys/module_radiation_driver.F
This fix has been tested by Pedro in WRF-Solar.
No regtests yet.
Test shows impact when Deng shcu is run with sub-grid clouds from MYNN icloud_bl=1. Left fixed, right old. Higher cloud fraction which leads to reduced surface shortwave compared to …

Fix for Deng shallow combined with other subgrid cloud options

---

phys/module_mp_wdm5.F
phys/module_mp_wdm6.F
phys/module_mp_wdm7.F

TYPE: bug fix
KEYWORDS: WDM5, WDM6, WDM7
SOURCE: Kyo-Sun Lim (Kyungpook National University) and Sooya Bae (KIAPS).
Error correction based on Lei et al. (JGR, 2020)
1. Melting of snow/graupel :
-Problem: melting processes of snow/graupel mass and number concentration do not occur 
at the same time.
-Correction: melting of snow/graupel changes the snow/graupel/rain mass and rain number 
concentration at the same time.
-Effect: Generation of rain number concentrations would decrease.
2. Regeneration of CCN number concentration due to the cloud water evaporation:
-Problem: Cloud water number concentration does not add into the CCN number concentration.
-Correction: Adding the cloud water number concentration into the CCN number concentration.
- Effect: CCN number …

WDM scheme minor bug fixes

---

Registry/Registry.EM_COMMON
run/README.namelist
share/module_check_a_mundo.F
test/em_real/namelist.input
test/em_real/namelist.input.global
test/em_real/namelist.input.jan00
test/em_real/namelist.input.jun01

KEYWORDS: GWD, domain dependent
To assist the possibility that a user may turn off GWD in a nest, this PR make gwd_opt domain-dependent.
M       test/em_real/namelist.input
M       test/em_real/namelist.input.global
M       test/em_real/namelist.input.jan00
M       test/em_real/namelist.input.jun01
Code tested with gwd_opt set to 1,1 and 1,0. The code behaves as expected. It passed automatic jenkins test.
RELEASE NOTE: 
The gwd_opt namelist has been changed to domain-dependent namelist. Hence one may turn off the option in a high-resolution domain.

Changing gwd_opt to a domain-dependent namelist

---

phys/module_bl_ysu.F

KEYWORDS: YSU, bl, module_bl_ysu, unified_physics, MPAS
In an effort to ensure the develop branch and unified_physics branches are identical (which
is to keep the WRF and MPAS physics repositories with identical source code for the
targeted suites), the comment at the top of the YSU PBL file was modified to the more 
recent comment found in both the MPAS code and the code from the WRF
unified_physics branch. The unified_physics branch was cut off of the develop branch, which 
has had YSU updates from commits 3fd6cb1d (YSU fix for WSM3 and Kessler no-ice test) 
and 89208e9 (YSU update to include unified_physics branch mods on develop branch), 
meaning this file now differs from the unified_physics branch. 
M …

YSU Modify Comment at Top to Match Unified Physics and MPAS

---

phys/module_diag_misc.F
phys/module_diagnostics_driver.F

KEYWORDS: nwp_diagnostic, adaptive time step
SOURCE: Ivan Toman (University of Zadar, Croatia)
Previously, the nwp_diagnostics feature worked properly only if fixed time step was used. 
If the adaptive time step option was used, resetting max arrays after output time failed 
because the original code expected a fixed number of time steps between output times. 
For this enhancement, the tracking of time after the output is used to determine when the
reset time has been reached. Resetting max arrays is performed after the output at the next 
time step by checking if 0 < if time from output < max_time_step. The details are given in 
code comments.
M       phys/module_diag_misc.F
M       phys/module_diagnostics_driver.F
TESTS …

nwp_diagnostics made compatible with adaptive time step

---

var/gen_be_v3/README.gen_be_v3
var/gen_be_v3/gen_be_v3.F90

TYPE: bug fix
KEYWORDS: WRFDA, gen_be_v3
1. fix the allocation/initialization/deallocation of some arrays.
Some arrays should be initialized inside the loops for variables.
The improper initialized arrays led to incorrect scalelength values for the non-first variables.
2. fix typos in README.gen_be_v3
M       var/gen_be_v3/README.gen_be_v3
M       var/gen_be_v3/gen_be_v3.F90
When single variable is set in the namelist, the results are identical before and after the fix.
When multiple variables are set in the namelist, the result of the first variable remains the same before and after the fix,
and the results of the other variables are now the same as when they are run alone.

Bug fixes for DA stand-alone gen_be_v3 utility in develop branch

---

configure
share/landread.c

KEYWORDS: type.h, rpc, tirpc
SOURCE: Reported on WRF Forum, fixed internally
Problem:
The C header file `rpc/types.h` may be located in a directory other than 
`/usr/include`. If the WRF code cannot find this file, the source code for 
`landread.c` does not compile, and the WRF code fails to build.
Mentioned on WRF Forum as "Problem Compiling WRFV4.0 on Fedora 28"
https://forum.mmm.ucar.edu/phpBB3/viewtopic.php?f=37&t=61&p=15718#p15718
Solution:
Refer to the discussion:
https://forums.gentoo.org/viewtopic-t-1076270-start-0.html
The likely other location for this header file is `/usr/include/tirpc`. During
the `configure` stage, a test is made to determine which of these two 
candidate directories is the correct location of this header file. A cpp …

Handle possible locations for rpc/types.h

---

dyn_em/module_first_rk_step_part1.F
phys/module_radiation_driver.F

TYPE: bug fix
KEYWORDS: FARMS, NMM
Problem:
The NMM HWRF code would not build after the FARMS commit. A few variables passed 
into the radiation driver are ARW specific, so the call from the NMM core did not have:
MUT or DNW (both input associated with ARW only), or the six additional computed 
radiation output fields (sw*2).
Solution:
1. Make the ARW-specific input fields and the additional radiation output fields OPTIONAL.
2. Use an IF(PRESENT(xxx)) before using any of the fields.
These problems were introduced with commit 3c71dd1de6e0df0, PR #1025 "Adding a fast 
surface shortwave parameterization (FARMS)".
modified:   phys/module_radiation_driver.F
modified:   dyn_em/module_first_rk_step_part1.F
1. …

Fix broken NMM build caused by FARMS mods

---

Registry/Registry.EM_COMMON
Registry/Registry.NMM
dyn_em/module_first_rk_step_part1.F
dyn_em/start_em.F
dyn_nmm/module_PHYSICS_CALLS.F
dyn_nmm/start_domain_nmm.F
phys/module_physics_init.F
phys/module_sf_myjsfc.F
phys/module_sf_qnsesfc.F
phys/module_surface_driver.F

KEYWORDS: u10, v10, myjsfc, qnsesfc
SOURCE: reported by Rob Fovell and others, fixed internally
The U10/V10 output when MYJ and QNSE surface layer schemes is used is non-standard over land, which produces higher values. This PR retains the value computed using standard MO 
theory, and moves the modified U10/V10 to U10E/V10E. 
M       Registry/Registry.NMM
M       dyn_em/start_em.F
M       dyn_nmm/module_PHYSICS_CALLS.F
M       dyn_nmm/start_domain_nmm.F
M       phys/module_physics_init.F
M       phys/module_sf_myjsfc.F
M       phys/module_sf_qnsesfc.F
1. Compiled. 
2. Tested with MYJSFC on …

Output standard U10/V10 from MYJSFC and QNSESFC schemes

---

phys/module_cu_bmj.F

TYPE: bug fix
KEYWORDS: BMJ, conservation of enthalpy
SOURCE: Tieh-Yong Koh (Earth Observatory of Singapore, Nanyang Technological University, Singapore); Ricardo Fonseca (Earth Observatory of Singapore, Nanyang Technological University, Singapore); Chee-Kiat Teo (Temasek Laboratories, Nanyang Technological University, Singapore); Tengfei Zhang (Earth Observatory of Singapore, Nanyang Technological University, Singapore)
This PR separates out a bug fix from PR#921 so that even if a user would not want to use the precipitation convective cloud (PCC) option, the benefit of bug fix can be utilized. The fix corrects an error with conservation of enthalpy. The DHDT term is corrected, which should be an integral from p_bot to p_top and not computed at every level as …

A fix for conservation of enthalpy in BMJ cumulus scheme

---

dyn_em/module_first_rk_step_part2.F
phys/module_cu_mskf.F
phys/module_cumulus_driver.F
phys/module_physics_addtendc.F
phys/module_physics_init.F

TYPE:  enhancement
KEYWORDS: Convective Momentum Transport, MSKF
SOURCE: Kiran Alapaty (US EPA)
DESCRIPTION OF CHANGES: Like many regional CP schemes, the MSKF lacked the inclusion of convective momentum transport (CMT) associated with cumulus convection. The CMT formulation developed by Zhang and McFarlane (JGR, 100, 1995) was implemented into the MSKF scheme to include this missing process that improves speed of propagation of storms and squall lines and associated changes in horizontal winds components.  
M       phys/module_cu_mskf.F
M       phys/module_cumulus_driver.F
M       phys/module_physics_addtendc.F
M       phys/module_physics_init.F
M       dyn_em/module_first_rk_step_part2.F
TESTS CONDUCTED:  Two WRF simulations were performed for 2-days to study …

Adding convective momentum transport to MSKF

---

var/gen_be_v3/README.gen_be_v3
var/gen_be_v3/gen_be_v3.F90
var/gen_be_v3/util/combine_be_cv7_ccv2.f90

TYPE: enhancement (to the not-yet-released code)
KEYWORDS: WRFDA, gen_be_v3, memory, be.dat for cloud_cv_options=2
1. For memory issue:
For applications that are for large number of cases and large domain sizes,
the gen_be_v3 program needs to run on a large-memory node.
To deal with the memory issue, add a namelist option pert1_read_opt
to choose how the program accesses pert1 data (output of do_pert_calc=true) internally.
pert1_read_opt=1: (default, original behavior) read and store all cases in memory at once.
pert1_read_opt=2: read from pert1 file when need it.
This option writes out additional vertical-mode-projected fields when do_eof_transform=.true.
Users can set pert1_read_opt=2 if memory insufficiency occurs.
With …

Improve memory usage for DA gen_be_v3 and add another output reformatting tool

---

main/depend.common

TYPE: bug fix
KEYWORDS: Makefile, depend.common, FARMS
Problem:
The DA code did not build. The file module_ra_farms.mod was not available
for the build of module_radiation_driver.o.
Solution:
The depend.common file needed to include the FARMS dependency for the
radiation driver.
modified:   main/depend.common
1. Does not harm (regression test is OK).
2. Fixes DA builds

Add Makefile dependency for FARMS scheme

---

main/depend.common
share/mediation_integrate.F
wrftladj/module_diffusion_em_ad.F

TYPE: bug fix
KEYWORDS: wrfplus, TL/AD code
Two recent WRF model code changes break the wrfplus compilation:
1. ESMF name change 
This modification allowed the CTSM development to use standard ESMF without conflicting 
with WRF _old_ ESMF library namespace.
Commit 8af53855b837, PR #1066 "Enabling WRF build with ESMF library"
2. module_diffusion_em_ad.F, 3d scale aware TKE (one of these, take your pick)
Commit d059afe1e646, PR #972 "Add a scale-adaptive 3DTKE parameterization scheme as a subgrid mixing option
Commit 6d95883111f5, PR #1012 "SMS3dTKE: Remove broken packaging for km_opt=5"
Commit 94e5ed97b69, PR #1013 "Add missing "IF km_opt==5" tests for diag computations"
Commit dd0c2094fc16, PR #1026 "Fixing the problem that km_opt=5 breaks km_opt=2 …

Fix WRFPlus compilation issue

---

phys/module_radiation_driver.F

TYPE: bug fix
KEYWORDS: .OR., cpp
SOURCE: Found by Jamie Bresch (NCAR), fixed internally
An extra .OR. in an expression needs to be removed.
modified:   phys/module_radiation_driver.F
1. Build on cheyenne with Intel OK:
```
cheyenne.ucar.edu:/glade/scratch/gill/WRF_oops_OR>./compile em_real > & ! foo ; tail -20 foo
build started:   Wed Feb 12 12:25:56 MST 2020
build completed: Wed Feb 12 12:39:46 MST 2020
--->                  Executables successfully built                  <---
-rwxr-xr-x 1 gill p66770001 265016704 Feb 12 12:39 main/ndown.exe
-rwxr-xr-x 1 gill p66770001 264300968 Feb 12 12:39 main/real.exe
-rwxr-xr-x 1 gill p66770001 262477808 Feb 12 12:39 main/tc.exe
-rwxr-xr-x 1 gill p66770001 290619280 Feb 12 12:38 …
```

Bug fix to PR "KLUGE - Option to avoid building RRTMK due to GNU problem"

---

arch/postamble

KEYWORDS: RRTMG, FAST, KIAPS, postamble, cpp
Problem:
The WRF code with the GNU compilers (from 6.3.* inclusive to anything before 9.1.0) will
sometimes fail to compile. The error is listed as an "internal compiler error". The two RRTMG 
schemes (FAST and KIAPS) are the standard causes for GNU failing to compile the WRF 
code successfully.
Solution:
The following two mods were previously made to the WRF source code:
1. commit 17b5ac4062, PR #517 "KLUGE: RRTMG FAST + GNU > 6.3.0 is an internal compiler error"
2. commit a83c7cb27d, PR #1084 "KLUGE - Option to avoid building RRTMK due to GNU problem"
This new PR just resests the default settings from "always build these schemes" to "never
build these schemes". …

New default setting for RRTMG FAST and RRTMG KIAPS: no compile

---

main/depend.common
phys/Makefile
phys/module_diag_misc.F
phys/module_diag_nwp.F
phys/module_diagnostics_driver.F

KEYWORDS: diagnostics, misc, nwp diagnostics
The module_diag_misc.F is getting long and complicated and it makes adding additional 
diagnostics (such as accumulated tendencies) difficult. This PR pulls the code related to 
new_diagnostics out to a new module: module_diag_nwp.F, and keeps the rest (currently only 
three items: bucket calculations for long simulations, interval rainfall, and surface pressure 
changes) in the original module: module_diag_misc.F.
LIST OF MODIFIED FILES: list of changed files
M       main/depend.common
M       phys/Makefile
M       phys/module_diag_misc.F
A       phys/module_diag_nwp.F
M       phys/module_diagnostics_driver.F
1. The output in wrfout files (which include PREC_ACC_C, …

Separating new_diagnostics from the rest in diag_misc module

---

chem/module_aerosols_soa_vbs.F
chem/module_aerosols_sorgam.F

TYPE: bug fix
KEYWORDS: aerosols, SOA, VBS, SORGAM, restart
SOURCE: Theodoros Christoudias (Cyprus Institute)
Problem:
If using an existing simulation, aerosols (SOA_VBS and SORGAM) should not be reinitialized 
on restart. 
Solution:
This modification checks the restart configuration flag. If this is a restart run, then do not set 
all aerosols to epsilc.
LIST OF MODIFIED FILES:  
WRF/chem/module_aerosols_soa_vbs.F 
WRF/chem/module_aerosols_sorgam.F
simulation restart. 
Below are consecutive history outputs before and after the restart point. It's clear that PM 
concentrations are reinitialized and there's no continuity with previous concentrations:

Do not reinitialise SOA_VBS or SORGAM aerosols on restart

---

chem/module_chem_plumerise_scalar.F

KEYWORDS: biomass burning, plume rise
SOURCE: Ravan Ahmadov (NOAA/ESRL)
This bug results in adding extra biomass burning mass aloft, when the thickness of the 
vertical grid (dz) increases with altitude. The fix does not change the WRF-Chem model 
results significantly.
M chem/module_chem_plumerise_scalar.F
1. Jenkins test has passed.

Fixing extra biomass burning mass aloft

---

share/interp_fcn.F

TYPE: bug fix
KEYWORDS: nest feedback
SOURCE: Reported by Kevin Manning (NCAR), fixed internally
Problem:
All nonmasked, odd-ratio (with ratios greater than 3:1) feedback was incorrect. The fine
grid feedback was incorrectly shifted down and to the left.
Solution:
A fixed constant value of 1 was correct for a 3:1 ratio since the term was
supposed to be ratio/2. For a 5:1 ratio the value needed to be 2. Replacing
the fixed value with the correct term fixes the problem. This solution works
for all odd ratios.
modified:   share/interp_fcn.F
The test involves generating a known block of values on the fine grid that
should all feedback to their respective parent grid cells. By choosing the
fine grid cells so that only full parent …

Fix feedback for odd nest ratios > 3:1

---

Registry/Registry.EM_COMMON
Registry/Registry.NMM
dyn_em/module_first_rk_step_part1.F
phys/module_surface_driver.F

TYPE: bug fix
KEYWORDS: NoahMP, STEPWTD, mod
Problem:
There were two places in the WRF code that tested for mod(itimestep,STEPWTD).
If STEPWTD==0, then this is an error.
Solution:
The correct test order is defined as
1. Is this opt_run == 5? If true, then the STEPWTD has been previously defined, and can be used.
2. Is this the correct time step?
modified:   Registry/Registry.NMM
modified:   dyn_em/module_first_rk_step_part1.F
modified:   phys/module_surface_driver.F
1. All tests with NoahMP fail immediately with STEPWTD==0 due to a divide by 0.
2. All tests pass with this fix in place.
3. Regression test underway.

Check if STEPWTD==0 in NoahMP before mod(timestep,STEPWTD)

---

Registry/Registry.EM_COMMON
dyn_em/module_first_rk_step_part1.F
phys/module_bl_mynn.F
phys/module_pbl_driver.F
phys/module_radiation_driver.F

TYPE: bug fix, enhancement
KEYWORDS: subgrid cloud ice, shallow-cumulus clouds
SOURCE: Joseph Olson (NOAA) and Jaymes Kenyon (NOAA/CIRES)
Added new array qi_bl as opposed to using qc_bl for both subgrid-scale (SGS) qc and qi. This
gives us more control of the magnitudes of SGS qc & qi, which can be confounded by using
a single array. As a result of this change, many subsequent changes were required,
especially in subroutine mym_condensation, which was cleaned up in the process.
Added the blending of the stratus component of the SGS clouds to the mass-flux
clouds to account for situations where stratus and cumulus may exist in the grid cell.
This has a small impact, but can slightly increase the tenuous shallow-cu cloud decks.
Miscellaneous tweaks and small-impact …

Updates to MYNN-EDMF and related modules

---

share/module_check_a_mundo.F

KEYWORDS: check_a_mundo, FAST_KHAIN_LYNN_SHPUND
check the existence of input tables for running the fast bin microphysics scheme (mp=30)
(FAST_KHAIN_LYNN_SHPUND)
M        share/module_check_a_mundo.F
1. regression test OK
2. With both SBM files linked in:
```
FAST SBM: INITIALIZING WRF_HUJISBM
FAST SBM: ****** WRF_HUJISBM *******
FAST_SBM_INIT : succesfull reading Table-1                                      
FAST_SBM_INIT : succesfull reading Table-1
FAST_SBM_INIT : succesfull reading Table-2                                      
FAST_SBM_INIT : succesfull reading Table-2
FAST_SBM_INIT : succesfull reading Table-3                                      
FAST_SBM_INIT : succesfull reading Table-3 …
```

Check for the existence of input tables for mp=30 FSBM

---

arch/postamble
main/depend.common
share/module_check_a_mundo.F
wrftladj/solve_em_ad.F

TYPE: bug fix
KEYWORDS: WRFPLUS
Problem:
With the develop branch, WRFPLUS did not build.
Solution:
1. There were missing dependencies for two new physics schemes:
irrigation and FSBM. Those were added to physics drivers and
physics init.
2. The argument list for the microphysics driver was also modified by
those same two new physics schemes. The (not used for WRFPLUS) sections
for both irrigation and FSBM were added.
3. Since the DA code builds with 8-byte reals as the default, the FSBM code is
removed from the default compilation (as this code is known to fail to build when
8-byte reals are used). A simple test in the `configure` script is likely to be enough 
for a fix. For example, something similar to the existing test for 8-byte reals:
```
sed …
```

Fixes so WRFPLUS builds with develop branch

---

Registry/registry.chem
share/wrf_timeseries.F

KEYWORDS: tslist, o3, profile
SOURCE: Xin Zhang (NUIST)
1. Add the ozone field to those that are included in the vertical profiles.
2. Add ts_o3_profile to Registry/registry.chem
M Registry/registry.chem
M share/wrf_timeseries.F
GIF of multiple profiles including O3: 
RELEASE NOTES: Add "ozone" to list of profile fields for time series, but only available when building with WRF Chem.

TSLIST: add ozone field to vertical profile output files

---

share/output_wrf.F

KEYWORDS: ntasks, metadata, global attributes
In the global attributes for the WRF history stream, include the number of total
tasks, and the number of tasks in both the X and Y directions.
modified:   share/output_wrf.F
1. Jenkins PASS
2. Example of new metadata in WRF history file:
```
> mpirun -np 1 wrf.exe
starting wrf task            0  of            1
> ncdump wrfo* | grep NTASKS
:NTASKS_X = 1 ;
:NTASKS_Y = 1 ;
:NTASKS = 1 ;
```
```
> mpirun -np 3 wrf.exe
starting wrf task            1  of            3
starting wrf task            2  of            3
starting wrf task            0  of            3
> ncdump wrfo* | grep NTASKS
:NTASKS_X = 1 ;
:NTASKS_Y = 3 ;
:NTASKS = 3 ;
```

Add number of tasks to WRF history global attributes

---

Registry/Registry.EM_COMMON

TYPE: bug fix
KEYWORDS: observation nudging, temperature, tile, halo
SOURCE: Brian Reen (Army Research Lab)
Added th_phy_m_t0 to the HALO statement for observation nudging in the Registry. 
Problem:
Previously, observation nudging using temperature observations on the boundary edge of a 
tile used an incorrect nudging term.  During the interpolation of model potential temperature 
to the observation location, model values outside of the current tile are needed when the 
observation is on the boundary edge of the tile.  However, the model potential temperature 
for these points just outside the current tile was not available in the variable used for this calculation (tb in phys/module_fddaobs_rtfdda.F).  During testing, a value of zero was instead 
seen in these …

Fix nudging of temperature obs at edge of tile

---

README
dyn_em/module_first_rk_step_part1.F
inc/version_decl
phys/module_surface_driver.F

TYPE: bug fix
KEYWORDS: NoahMP, opt_run option
SOURCE: internal 
Problem:
When running the NoahMP scheme with the ground water option (opt_run=5), the STEPWTD 
variable is initialized to a non-zero value. However when opt_run!=5, then the STEPWTD 
variable remains an uninitialized zero value. In the WRF source code, there are a couple of
places where mod(x,STEPWTD) occurs. This causes an immediate "divide by zero" error in
the first call to the surface driver.
Solution:
The IF test logic is re-arranged so that only when opt_run=5 (which means that STEPWTD
is non-zero) is there a second IF test (using mod(x,STEPWTD)) to compute whether 
additional processing takes place.
This modification was made separately to the develop branch after the branch release-v4.1.4 …

bug fix: NoahMP STEPWTD==0, divide by zero

---

dyn_em/module_first_rk_step_part1.F
phys/module_ra_farms.F
phys/module_radiation_driver.F

TYPE: bug fix
KEYWORDS: FARMS, hybrid vertical coordinate
SOURCE: Ju Hye Kim (NCAR/RAL), Jimy Dudhia (NCAR/MMM), and Pedro A. Jimenez (NCAR/RAL)
DESCRIPTION OF CHANGES: Vertical integrations in FARMS were performed using the variable 
MUT. Since the introduction of the hybrid vertical coordinate, this variable is not sufficient
for computing dry pressure. The fix uses rho * dz.
M       phys/module_ra_farms.F
M       phys/module_radiation_driver.F
1. Similar results using hybrid_opt = 0 and hybrid_opt = 2.

Vertical integrations in FARMS fixed for the hybrid vertical coordinate

---

phys/module_ra_rrtmg_sw.F
phys/module_ra_rrtmg_swf.F
phys/module_ra_rrtmg_swk.F

TYPE: bug fix
KEYWORDS: RRTMG-shortwave, PR#997
SOURCE: Mike Iacono, AER
Regarding the fix from PR#997, Mike Iacono, a RRTMG code developer, suggested a different fix, which will cover the cases where “zw” and “zg” (the single-scattering albedo and asymmetry parameter inputs to the “denom” equation) can cause problems with value of 1.0.
LIST OF MODIFIED FILES: list of changed files 
M       phys/module_ra_rrtmg_sw.F
M       phys/module_ra_rrtmg_swf.F
M       phys/module_ra_rrtmg_swk.F
1. Run a test case over East Asia (same case as in PR#997), and compared differences. In the first image below, it shows difference plots for 6 h forecast of temperature at model level 31 (left, about 330 mb) and 46 (right, about 95 mb). The run it compares to has …

Redo PR#997 based on suggestion from Mike Iacono

---

phys/module_ra_farms.F

TYPE: bug fix
KEYWORDS: FARMS, mixed phase clouds, optically thin clouds
SOURCE: Pedro A. Jimenez (NCAR/RAL), Ju Hye Kim (NCAR/RAL) and Yu Xie (NREL)
Improve treatment of mixed phase clouds in FARMS. 
1. This modification accounts for optically thin clouds (cloud optical depth < 1.0), which
were previously neglected. 
2. This fix avoids discontinuities in the surface irradiance at cloud optical depths of 1.
M       phys/module_ra_farms.F
1. Jenkins tests are all PASS.
2. We compared the shortwave global horizontal irradiance (GHI) at the surface before and 
after the fix. Results are similar and the fix avoids discontinuities in the GHI. The following 
figures show results comparing simulations and GHI from the National …

Improved treatment of mixed phase clouds in FARMS

---

share/module_check_a_mundo.F

KEYWORDS: FSBM microphysics, check_a_mundo
SOURCE:  internal
Only check the availability of FSBM input tables when the FSBM code is compiled with the 
cpp flag BUILD_SBM_FAST == 1
M    share/module_check_a_mundo.F
TESTS CONDUCTED:  
1. Regression test OK
2.  TEST1: BUILD_SBM_FAST = 0, and input tables exit. Message is:
```
--- ERROR: FAST SBM scheme must be built with a default compile-time flag
--- ERROR: Run ./clean -a, ./configure, ./compile scripts again
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:    2215
NOTE:       1 namelist settings are wrong. Please check and reset these options
-------------------------------------------
```
3. TEST2: BUILD_SBM_FAST = 1 , files exist
``` …
```

Only test for FSBM input files if the FSBM code is built

---

arch/postamble
configure

TYPE: bug fix
KEYWORDS: DA FSBM real*8
The Fast Spectral Bin Microphysics (FSBM) code only works with default real
size = 4 bytes due to a mixture of declarations using real, real(kind=8),
and double precision. To solve this problem, the FSBM code is ifdef'ed out
for any real(kind=8) build. This is handled via the configure step.
Problem:
The DA code is built with real(kind=8) by default without resorting to any special
setup in the configure file. The choice was to either disable FSBM, or not
build DA. Temporarily before the v4.2 release, we have disabled the FSBM code.
Solution:
This PR identifies the DA builds, and sets internal flags to let the build
know to ifdef out the FSBM code. If no DA code is requested AND if this is
not a real(kind=8) …

Allow DA and FSBM to peacefully coexist in same repo

---

phys/module_diag_solar.F
phys/module_diagnostics_driver.F

TYPE: bug fix
KEYWORDS: WRF-Solar, diagnostics, hybrid vertical coordinate
SOURCE: Timothy Juliano (NCAR/RAL), Pedro A. Jimenez (NCAR/RAL), Jimy Dudhia (NCAR/MMM)
This modification is similar to PR #1119 "Vertical integrations in FARMS fixed for the hybrid 
vertical coordinate".
Vertical integrations in the Solar diagnostics package were performed using the variable MUT. 
Since the introduction of the hybrid vertical coordinate, this variable is not generally sufficient 
for computing dry pressure. The computation for pressure now uses rho * dz.  
M phys/module_diag_solar.F
M phys/module_diagnostics_driver.F
1. Similar results using hybrid_opt = 0 and hybrid_opt = 2.
2. The original code with MUT and hybrid_opt=0 gives …

Fix vertical integrations in Solar diagnostics package for hybrid vertical coordinate

---

phys/module_radiation_driver.F

TYPE: bug fix
KEYWORDS: WRF-Solar, diagnostics
SOURCE: Timothy Juliano (NCAR/RAL)
Remove unintentional icloud dependency for qc_tot and qi_tot variable calculations in radiation 
driver when Solar diagnostics package is activated because we want to also calculate these two 
variables when other methods that account for subgrid hydrometeors are activated.
M phys/module_radiation_driver.F
1. Bit-for-bit results before and after modification.
2. Jenkins test OK.

Remove icloud dependency for qc_tot and qi_tot calc when Solar diagnostics package is activated

---

Registry/Registry.EM_COMMON
share/wrf_timeseries.F

TYPE: bug fix, small enhancement
KEYWORDS: time series profiles of WW, P, simulation start date
SOURCE: reported by Pedro Jimenez of RAL, fixed internally
1. The time series profile output has two other fields, W and P, that were not written out. This PR fixes 
those ommitted fields. 
2. The geopotential height in the time series profiles was on full levels (only the first kte-1 levels). 
This PR moves the calculation to half levels (the same as is already done for the existing vertical 
velocity WW). 
3. A simulation start date is added to the time series output in the form of yyyy-mm-dd_hh:mm:ss. The date remains as simulation start time in a time series file after restart.
LIST OF MODIFIED FILES: list of changed files:
M …

Recover two profiles for W and pressure and  add start date to TS output

---

phys/module_diag_nwp.F
phys/module_mp_thompson.F

TYPE: bug fix
KEYWORDS: graupel, Y-intercept, microphysics
SOURCE: Greg Thompson (NCAR-RAL)
Made some final cross-checks against observed radar reflectivity in order to calibrate the 
one-moment graupel Y-intercept diagnosed with mass mixing ratio.  The prior version had too 
much high reflectivity in the upper end of the distribution.  The small changes to the equation 
(in 3 places in mp_thompson plus 1 corresponding place in the diagnostic for max hail size) reduces 
the high bias to match radar observations better.
phys/module_mp_thompson.F
phys/module_diag_nwp.F
1. Well tested in a PECAN case study and calibrated against the KUDX and KFSD radar data - 
primarily with help from Kyoko Ikeda to ensure the changes are …

Very minor change to Graupel Y-intercept parameter equation

---

share/module_check_a_mundo.F

KEYWORDS: MSKF, 3DTKE
This PR adds a check in module_check_a_mundo.F to stop the model when MSKF (cu_physics=11) and 3DTKE (bl_pbl_physics=0, diff_opt=2, km_opt=5) are used together.
LIST OF MODIFIED FILES: list of changed files 
M     share/module_check_a_mundo.F
1. Jenkins test PASS
2. Test that show model stops with the following message when the two options are selected:
--- ERROR: cu_physics = 11 cannot work with 3DTKE scheme
--- Choose another bl_pbl_physics OR use another cu_physics option
RELEASE NOTE: Add in the release note part for 3DTKE--> MSKF (cu_physics=11) and 3DTKE (bl_pbl_physics=0, diff_opt=2, km_opt=5) cannot be used together.

Preventing MSKF to be used with 3DTKE option

---

dyn_em/module_diffusion_em.F
dyn_em/module_first_rk_step_part2.F
phys/module_diag_functions.F

TYPE: bug-fix
KEYWORDS: horizontal diffusion of w, diff_opt=2
SOURCE: internal, and Katie Lundquist and Tina Chow (LLNL), and Jason Simon (Berkeley)
When calculating horizontal diffusion of w, Kv is needed instead of Kh in the tau13 and tau23 
stress terms for theoretical reasons.
M       dyn_em/module_diffusion_em.F
M       dyn_em/module_first_rk_step_part2.F
Differences in W in quarter_ss case after 1 hr are small.
Jenkins: passed with known failures related to NoahMP STEPWTD fix after 4.1.4
RELEASE NOTE: Fix based on theory for horizontal diffusion of w in diff_opt=2 (Lundquist and Chow, LLNL).

Fix for horizontal diffusion of w (diff_opt=2)

---

run/README.namelist

KEYWORDS: mp_physics=52, 55, bmj_rad_feedback
Adding info for namelists mp_physics = 52 (2-ice P3 scheme), 55 (Jensen-ISHMAEL scheme), 
and bmj_rad_feedback for precipitation cloud scheme for BMJ cumulus scheme.
M     run/README.namelist
Text only change

Updating info in README for namelists

---

phys/module_surface_driver.F

TYPE: bug fix
KEYWORDS: remove conflict marker "<<<<<" and ">>>>"
SOURCE: Jan Mandel
In the surface driver, we have:
```
<<<<<<< HEAD
END IF
END IF
=======
ENDIF
ENDIF
>>>>>>> origin/master
```
TESTS CONDUCTED:  
1. Jenkins auto testing  is PASS

Fix edit conflict in phys/module_surface_driver.F

---

.gitignore
chem/KPP/kpp/kpp-2.1/.gitignore

TYPE: bug fix
KEYWORDS: .gitignore, kpp, f90
Problem:
The *.f90 files are part of .gitignore. This is not entirely correct. There are instances where the
*.f90 files should be tracked by git.
Solution:
Exclude the *.f90 files under the kpp directory from this overly broad identification of files. There
are other directories where this fix could also be applied (such as for DA).
ISSUE:
Fixes #1105 
M  .gitignore
Compile and run WRF-Chem successfully

Allow .f90 files in kpp folder

---

chem/module_gocart_settling.F

TYPE: bug fix
KEYWORDS: GOCART, settling
SOURCE: Stacy Walters (internal)
Put calculation of aerosol settling (variable = transfer_to_below_level) in layers > 1 
into IF/ELSE block that calculates gravitational settling for layer = 1.
M chem/module_gocart_settling.F
TEST CONDUCTED:
Jenkins shows all tests PASS
**Compiled with debug option -check bounds**
_BEFORE FIX_: 2 indexes are OOB for l==1, 3rd dim of delz (> MAX) and 3rd dim of airden (0)
rsl.out.0000
l/=1, calculting transfer_to_below_level =   3.153560196907218E-014
l/=1, calculting transfer_to_below_level =   1.014890436929303E-012
l/=1, calculting transfer_to_below_level =   2.118741307102124E-011
l==1, still calculating transfer_to_below_level =
= …

Prevent 0 index in GOCART settling array

---

run/README.namelist
share/module_check_a_mundo.F

KEYWORDS: Deng shallow scheme, MYNN PBL, Thompson cloud fraction scheme
Add a fatal stop if Deng shallow scheme (shcu_physics=5) and icloud=3 are used together. Modify the PBL check for use with Deng shallow scheme: Deng scheme may be used with MYNN, but EDMF and icloud_bl have to be off. But making these options off will change the behaviour of the MYNN PBL option. Hence this should not be recommended.
1. Tested by turning on and off different physics options to produce the correct message. For example, if one has both shcu_physics = 5 and icloud = 3 on, one should see the following message:
--- ERROR: Options shcu_physics …

Add more checks for Deng shallow scheme

---

share/module_check_a_mundo.F

KEYWORDS: SAS, NMM, check_a_mundo
Previously, ARW users shared the SAS scheme with NMM. The new scale aware SAS
scheme for NMM has been slotted into the location of the older SAS scheme. For
ARW users wanting to run the SAS CU scheme, the correct option is 95.
Instead of just assigning a new option number within the code, the WRF model
stops and tells the user they are using the wrong option.
Also, I added a few missing "is this domain active" IF tests to the surrounding blocks.
modified:   share/module_check_a_mundo.F
1. Jenkins test all PASS
RELEASE NOTE: The typical ARW CU SAS scheme, previously cu_physics=4, has been changed to cu_physics=95.

ARW SAS is CU=95, not CU=4 (scaleaware for NMM)

---

dyn_em/solve_em.F
phys/module_microphysics_driver.F
phys/module_mp_fast_sbm.F

TYPE: bug fix
KEYWORDS: FSBM, IPolar_HUCM, sbm_diagnostics, seg fault
Problem:
The IPolar_HUCM variable is a LOGICAL PARAMETER that is always TRUE. It is a
module local variable. When we get down to the IF test in FSBM to determine if
we are doing diagnostics, we therefore are always proceeding with diagnostic
calculations. If the sbm_diagnostics flag is zero, then the sbmradar array is
only "unit" allocated. We get a segfault when filling the array sbmradar.
Solution:
The sbm_diagnostics namelist variable is used in the registry.polrad to package
the sbmradar array. Use that same variable to determine if we compute the
diagnostics.
modified: …

FSBM: use existing package flag for T/F compute diagnostics

---

phys/module_physics_init.F

KEYWORDS: dx
Instead of piecemeal modifications, we are going to get all of the 2d dx
physics schemes converted, and provide a mechanism to revert back to the
orginal behavior.
Temporarily, the existing mapfactor-dependent 2d dx is disabled. The 2d dx is constant.
modified:   phys/module_physics_init.F
1. Jenkins is OK.
2. Without mods, 2d dx has pattern similar to that of latitude or map factor.
3. With mods, 2d dx is a constant.

Make dx constant, though 2d dx array exists

---

share/module_check_a_mundo.F

KEYWORDS: vertial nest, hybrid_opt, feedback
Problem:
If a user requests a vertical refinement for a nest, there are a couple
of capabilities that need to be shut off. Either will cause the model
to eventually die, and they are really hard to otherwise find.
Solution:
If a users asks for a vertical refinement on the nest, make sure that the
terrain following coordinate is used (`hybrid_opt=0`), and that the
feedback option is turned off (`feedback=0`).
modified:   share/module_check_a_mundo.F
1. Jenkins is OK (hopefully)
2. Incorrectly turning on `hybrid_opt=2` or `feedback=1` is now safely trapped.
```
Domain # 1: dx = 30000.000 m
Domain # 2: dx = 10000.000 m
--- ERROR: …
```

Add vertical nesting checks: no hybrid vert coord, no feedback

---

Registry/Registry.EM_COMMON
phys/module_irrigation.F
share/module_check_a_mundo.F

TYPE: bug fix
KEYWORDS: irrigation, drip, statement function
Problem 1:
In module_irrigation.F, in subroutine sprinkler_irrigation is this line:
```
constants_irrigation=irr_freq*irr_daily_amount/(irr_num_hours*3600*rho(a,kms,b)*dz8w(a,kms,b)*100)
```
It is clear from the rest of the routine, that this is to be treated as a statement function.
1. The line is after all of the declarations and before the first executable statement.
2. The values of a, b, and kms (among others) are not yet defined.
3. The following line _tries_ to use it as a statement function.
```
qr_curr(a,kms,b)=qr_curr(a,kms,b)+irrigation(a,b)*constants_irrigation*dt
```
However, the GNU compiler is segfaulting on the definition of the statement function,
because the variables …

Irrigation clean-up: syntax error, derived nml packaging, protect against div by 0

---

.github/CODEOWNERS

KEYWORDS: CODEOWNERS, SBM, Thompson, phys
DESCRIPTION OF CHANGES: Added 2 new users to the physics section of the CODEOWNERS file. The users are specific to the SBM and Thompson files.
M   .github/CODEOWNERS
TESTS CONDUCTED: None necessary - text only

Adding a couple of users to the CODEOWNERS file

---

phys/module_mp_fast_sbm.F

TYPE: bug fix
KEYWORDS: bcast, parameter, fsbm
Problem:
With GNU compilers 5, 8, and 9: FSBM runs OK serially. FSBM fails with
during intialization with MPI. It is traced to bcast of some variables that are
defined in module_mp_SBM_polar_radar.F.
INTEGER PARAMETER variables:
* temps_water, temps_fd, temps_crystals, temps_snow, temps_graupel, temps_hail
REAL PARAMETER variables:
* fws_fd, fws_crystals, fws_snow, fws_graupel, fws_hail
These variables are above the CONTAINS statement in 
module_mp_SBM_polar_radar.F and are PARAMETER values.
Solution:
We are not supposed to communicate PARAMETER values. These are already global
and cannot be written to. Just remove these unnecessary and illegal bcast statements.
m …

FSBM: don't communicate global PARAMETER values to other MPI processes

---

dyn_em/module_initialize_real.F

TYPE: bug fix
KEYWORDS: aerosol, Thompson, long meeting
SOURCE: Pedro Jimenez (RAL/NCAR), internal
Problem 1:
Users with mp_physics=28 that do not have climatology aerosols from metgrid
have not been aggressively informed that their simulations are not using
climatology. These users have been given a horizontally uniform distribution,
and likely those users did not know it. Previously the user was given only a couple 
lines of print buried in a long print-out in the real program, and probably very few 
users saw that message.
Solution 1:
1. Turn the previous comment-style messaging into a fatal call.
2. Augment the IF test to include `use_aero_icbc` as a reason to fail. If there is no aerosol data,
activating `use_aero_icbc` is not a valid request.
Problem 2:
Until …

MP=28: avoid unintended constant aerosol distribution

---

dyn_em/solve_em.F
external/esmf_time_f90/ESMF_Fraction.F90
external/esmf_time_f90/ESMF_Mod.F90
external/esmf_time_f90/ESMF_TimeInterval.F90
external/esmf_time_f90/Meat.F90

TYPE: bug fix
KEYWORDS: ESMF, ESMF_FractionMod, WRF_ESMF_FractionMod
SOURCE: Milan Curcic (University of Miami)
Problem and solution documented [here](https://github.com/wrf-model/WRF/pull/1066#issuecomment-611272321).
> Currently, it is not possible to build and link WRF with a chosen ESMF library due to the name 
conflicts between WRF internal ESMF interfaces with the intended ESMF library. I faced this problem 
while I was trying to compile WRF with the ESMF library during LILAC project development for coupling 
WRF with CTSM. This is specifically important for users and groups who would like to couple WRF 
with other models using ESMF infrastructure. This issue can be resolved by either updating WRF to 
use the new ESMF time manager interface or renaming all …

Rename ESMF_FractionMod to WRF_ESMF_FractionMod

---

share/input_wrf.F
share/output_wrf.F

KEYWORDS: sf_urban_physics
Problem:
If a user runs the real program with an urban physics option activated, then the
WRF model needs that same option activated. However, if the WRF model just turns
off the urban option, then ANY setting of the real program's namelist value of
sf_urban_physics should be acceptable.
Solution:
Add an extra IF test to check on the WRF model's namelist setting for sf_urban_physics. If
this namelist option is non-zero, then there is a validation test to determine if the
namelist and the input file metadata are identical. The new rule is: if the namelist value for
`sf_urban_physics==0` when running the WRF model, then an inconsistent value of `sf_urban_physics`
in the metadata will always be ignored. …

If WRF model has sf_urban_physics==0, wrf_inputdxx metadata value is ignored

---

dyn_em/solve_em.F
phys/module_microphysics_driver.F
phys/module_mp_nssl_2mom.F
phys/module_mp_thompson.F

TYPE:  enhancement
KEYWORDS: nwp_diagnostics, diag_flag
SOURCE: Ted Mansell (NSSL)
Replaces "Efficiency fix for nwp_diag reflectivity calculation" #1060
Problem:
With commit 86f7675359234d239, PR #749 "make refl_10cm available if nwp_diagnostics is on", 
solve_em.F was changed so that `diag_flag` was always set to true when `nwp_diagnostics==1`. 
This caused the full 3D radar reflectivity to be calculated on each time step, whereas the diagnostic 
for the max dBZ only needs to compute lowest level (k=1). The full 3D nature of the new computation
makes the cost of this diagnostic between one and two orders of magnitude more expensive than 
necessary. 
Solution:
A variable `ke_diag` is added in solve_em to tell the reflectivity calculation whether to do the full …

Efficiency fix for nwp_diag reflectivity calculation

---

.github/PULL_REQUEST_TEMPLATE
tools/commit_form.txt

KEYWORDS: RELEASE NOTES
Prompt contributor for citation in the RELEASE NOTES section of the PR commit message.
modified:   tools/commit_form.txt
modified:   .github/PULL_REQUEST_TEMPLATE
None required for text-only mod.

Better RELEASE NOTES guidelines

---

phys/module_physics_init.F
phys/module_radiation_driver.F
share/module_check_a_mundo.F

TYPE: bug fix
KEYWORDS: FARMS, radii, Goddard
Problem:
The FARMS radiation option (`swint_opt==2`) assumes both the availabilty of effective radii
and mass for three species: cloud, ice, and snow. This causes several issues.
1. The Goddard MP scheme had the effective radii in a separate variable, in different units.
2. The effective radii for snow could be valid with an unallocated mass for snow (for example, WSM3).
3. Two locations in radiation driver that need to have the FARMS option in the IF test
4. Even though use_mp_re=1 is a default, if someone turns it off, the FARMS option is not possible 
(but that was not trapped).
Solution:
1. In the radiation driver, if the MP scheme is Goddard, translate the radii to the correct
variable name and …

Several FARMS radiation related bug fixes

---

arch/configure.defaults

TYPE: bug fix
KEYWORDS: binary I/O, XL
SOURCE: Michael Duda (NCAR/MMM)
For each of the xlf compiler stanzas, a compiler flag `-qufmt=be` is added to the
Makefile macro `FCBASEOPTS_NO_G` to allow the little endian architectures to read
and write big endian binary data. For the WRF model, these binary input files are
typically the look-up tables for physics schemes.
modified:   arch/configure.defaults
1. Testing with WPS only so far, as the target machines for this PR do not yet successfully build WRF. For further information, please see the following:
* Issue: wrf-model/WPS#129 "POWER/Linux configuration needs -qufmt=be"
* PR: wrf-model/WPS#147 "Add -qufmt=be to FFLAGS and F77FLAGS for XL/POWER/Linux stanza"

Add compiler option for XL/POWER/Linux binary I/O

---

var/da/da_radar/da_get_innov_vector_radar.inc

TYPE: bug fix
KEYWORDS: reflectivity, snow retrieval
SOURCE: Tao Sun (NUIST)
A bug in the snow profile retrieval in radar DA has been fixed. When the temperature is above 0℃, zds (dry snow) should be replaced by zws (wet snow). This bug resulted in the overestimation of snow.
M       var/da/da_radar/da_get_innov_vector_radar.inc
TESTS CONDUCTED: WRFDA regression tests running.
RELEASE NOTE: A fix for retrieving a snow profile with radar DA. In the snow profile retrieval with radar DA, when the temperature is above 0℃, dry snow should be replaced by wet snow. This bug resulted in the overestimation of snow.

Bug fix for retrieval radar reflectivity DA

---

compile
wrftladj/solve_em_ad.F

TYPE: bug fix
KEYWORDS: WRFPLUS, AD, SBM
A new argument was added to the nonlinear model for the microphysics
driver (an integer flag for the spectral bin microphysics diagnostics
`sbm_diagnostics`). This argument has been added to the call to the
microphysics driver in `solve_em_ad.F`.
While tracking down this compile-time bug, an old debugging comment for 
WRFPLUS in the `compile` script was found and removed.
modified:   compile
modified:   wrftladj/solve_em_ad.F
1. Without mods, the WRFPLUS code does not compile. With mod, the WRFPLUS
code compiles.
2. Jenkins will continue to pass because this code was not activated.
3. WRFPLUS regtest: ???

Bug fix for WRFPLUS with SBM

---

chem/KPP/clean_kpp

TYPE: bug fix
KEYWORDS: chem, KPP
SOURCE: Michael Newman (Woodard & Curran)
Fixed typo "Makfile_org" to "Makefile_org" in chem/KPP/clean_kpp. Expected behavior: After 
copying "Makefile_org" to "Makefile", the script is expecting to delete "Makefile_org" to clean up.
M chem/KPP/clean_kpp
1. Ran clean_kpp to confirm expected behavior. 
2. Searched code base to confirm no additional references to the typo "Makfile_org".
3. Jenkins tests all PASS.
RELEASE NOTE: Fixed typo "Makfile_org" to "Makefile_org" in chem/KPP/clean_kpp.

Fixed typo "Makfile_org" to "Makefile_org" in clean_kpp

---

var/da/da_minimisation/da_get_innov_vector.inc
var/da/da_minimisation/da_minimisation.f90
var/da/da_radiance/da_get_innov_vector_radiance.inc

TYPE: bug fix
KEYWORDS: Variational Bias Correction, num_fgat_time>1, 4DVar, FGAT
SOURCE: Yali Wu (NCAR)
This is bug fixes for VarBC in 4DVar or FGAT model. The innovations were incorrect for time>1, because the ordering of the VarBC and radiance quality control processes were inconsistent. The issue is resolved by moving forward operator of VarBC and radiance QC routine to a higher level subroutine da_get_innov_vector.inc.
The general procedure for doing VarBC in WRFDA is:
1. calculate bias predictors (da_varbc_pred)
2. call da_varbc_coldstart
3. apply forward operator of bias correction to radiance innovation (da_varbc_direct)
4. radiance da_qc procedures
5. calculate covariance matrix b/w bias predictors for VarBC preconditioning (da_varbc_precond).
Previously, …

bug fix for VarBC when num_fgat_time > 1

---

phys/module_ra_aerosol.F

TYPE: bug fix
KEYWORDS: aer_opt = 2, Goddard SW, single scattering albedo, asymmetry factor, prescribed aerosol optical properties from namelist.input
SOURCE: Pedro A. Jimenez and Ju Hye Kim (NCAR/RAL), and J. Dudhia (NCAR/MMM) 
DESCRIPTION OF CHANGES: Fill in aerssa2d and aerasy2d arrays if aer_opt = 2 and sw = 5 (Goddard shortwave parameterization) with the values imposed in the namelist via aer_ssa_opt = 1 and/or aer_asy_opt = 1 options. The variables aerssa2d and aerasy2d are always present for ARW so there is no concern with memory packaging. The filling of the variables is properly handled by RRTMG but not by the Goddard SW parameterization. Similarly to the RRTMG implementation, no special treatment for HWRF (e.g. ifdef) is necessary to fill in the variables. If the variables are …

Filling aerssa2d/aerasy2d if sw = 5 and prescribed values from namelist

---

phys/module_diag_cl.F

TYPE: bug fix
KEYWORDS: clWRF, maximum, minimum, time, diagnostics
SOURCE: Christopher Thomas (Climate Change Research Centre, UNSW Australia)
TT2MAX and TT2MIN are the times at which T2MAX and T2MIN, the max and min values of 
T2 within a diagnostic period, are achieved. This bug caused the incorrect computation of 
TT2MAX and TT2MIN for cases in which T2MAX or T2MIN occurred at the beginning of the diagnostic period under consideration. At the beginning of each diagnostic period the working 
values of T2MAX and T2MIN are reinitialized with the current value of T2, however the working 
values of TT2MAX and TT2MIN were not reinitialized with the current time value. Thus if the 
max or min actually occurred at the beginning of the diagnostic period, then TT2MAX or …

Fix occurrence of time for max/min of diagnostics in clWRF

---

Registry/Registry.EM_COMMON
Registry/registry.clm
Registry/registry.noahmp

TYPE: bug fix
KEYWORDS: nesting, configure -r8, integer
SOURCE: Yulong Ma (University of Delaware)
Problem:
A segmentation fault occurs when running nesting  with "./configure -r8" and using the urban 
scheme. This was traced to incorrect interpolation (Registry `d` option) and feedback  (Registry
`u` option) subroutines that are assigned in a Registry file. The `interp_fcnm` is a masked 
interpolation for real variables. For integers, the interpolation should use the only available 
option: `interp_fcni`.
Solution:
In Registry/Registry.EM_COMMON, an example of the incorrect subroutine is:
```
state    integer   UTYPE_URB2D  ij    misc        1         -     rd=(interp_fcnm)u=(copy_fcnm)       "UTYPE_URB"  "URBAN TYPE"         "dimensionless"
```
The Registry line …

Fix INTEGER interpolation and feedback Registry arguments

---

phys/module_bl_shinhong.F

TYPE: bug fix
KEYWORDS: shin hong, divide by zero
DESCRIPTION OF CHANGES: When using the Shin-Hong PBL with initially zero wind, divisions by zero can occur. This bug fix includes if-statements to avoid a crash of the model. All limit values that are used instead of the divisions by zero should be mathematically correct, except for the third change where I guessed the appropriate limit value.
LIST OF MODIFIED FILES: phys/module_bl_shinhong.F
RELEASE NOTE: fixed divide by zero in Shin-Hong PBL

fixed divide by zero in Shin-Hong PBL

---

phys/module_mp_fast_sbm.F

TYPE: bug fix
KEYWORDS: macros, compiler, llvm, clang
SOURCE: Isaac Rowe (University of Kentucky)
Problem:
Some versions of LLVM clang cannot parse spaces near parentheses in cpp macros. For example:
```
DM_BCAST_MACRO_R16 ( FAF1 )
```
This bug has been discussed on the LLVM site: https://bugs.llvm.org/show_bug.cgi?id=18011. 
Solution:
The surrounding spaces around the  parentheses from the macros with parameters in 
phys/module_mp_fast_sbm.F were removed. 
```
DM_BCAST_MACRO_R16(FAF1)
```
Only a single file uses this "nonstandard" spacing for the cpp macros.
ISSUE: 
Fixes #1206 (Usage of macros is incompatible with clang cpp -traditional-cpp).
phys/module_mp_fast_sbm.F
1. Now builds with LLVM cpp (Apple clang version …

Remove nonstandard spacing in macro as workaround for LLVM bug 

---

phys/module_fr_fire_phys.F

TYPE: bug fix
KEYWORDS: subroutine, end
SOURCE: Ted Mansell (NSSL), issue reported by Manuel Luis Aznar (University of La Laguna)
Compilation error generated by a subroutine which has an "end" statement but does not have an 
"end subroutine X" statement.
* Platform: Macos High Sierra (10.13)
* Compilers: Fortran: ifort Version 13.0.3.198 Build 20130606; cc: clang-1000.11.45.5
* MPI: Openmpi 2.1.2
ISSUE: 
Fixes issue #1215 (Error in compiling WRF v4.2)
phys/module_fr_fire_phys.F
1. Previously, the compiler complained about the syntax:
```
time mpif90 -f90=ifort -o module_fr_fire_phys.o -c -O3 -fp-model precise -w -ftz -align all -fno-alias -fno-common -FR -convert big_endian  [etc.]  module_fr_fire_phys.f90 …
```

Release v4.2.1 Fire compile error

---

Registry/Registry.EM_COMMON

TYPE: bug fix
KEYWORDS: process_time_series, solar, segfault
SOURCE: Franciano Puhales (Federal University of Santa Maria, Brazil) and internal
When using time series with the solar diagnostic option activated, the model segfaults.
This was traced to missing fields in the package for `tseries_add_solar`: `ts_p_profile`
and `ts_w_profile`.
ISSUE:
Fixes #1227 (time series + solar diagnostics = seg fault)
modified:   Registry.EM_COMMON
1. OP reports this fixes the issue.
2. Jenkins is all PASS.
RELEASE NOTE: When using time series with the solar diagnostic option activated, the model segfaulted.  This problem was traced to missing fields in the package for tseries_add_solar: ts_p_profile and ts_w_profile. The missing fields …

solar diag time series segfault - package needs variables

---

Registry/Registry.EM_COMMON
Registry/Registry.NMM
phys/module_pbl_driver.F
phys/module_wind_fitch.F
run/README.namelist

TYPE: bug fix
KEYWORDS: advection, TKE, wind turbine
SOURCE: Cristina L. Archer, Sicheng Wu, and Yulong Ma (University of Delaware, CReW), and Pedro A. Jimenez (NCAR/RAL)
DESCRIPTION OF CHANGES: The TKE generated by wind turbines is not advected when the user instructs MYNN to advected the TKE. The present PR fixes this issue. Our research (Archer et al. 2020) indicates that after fixing this issue the production of TKE by wind turbines is too large and we have reduced the TKE coefficient (correction factor = 0.25) based on extensive comparison with LES results. The figure bellow summarizes this choice:
ISSUE: N/A
M       phys/module_pbl_driver.F
M       phys/module_wind_fitch.F
M …

Bug fix advection TKE generated by wind farms

---

dyn_em/module_advect_em.F

TYPE: bug fix
KEYWORDS: advection, program, 1d
There were two types of problems. First the original cpp commands were broken. The cpp command was commented out, 
but it is used to build the source code, with cut and paste). The second problem is caused by the modification of the 
advection interface with the release of v4.0.
First Problem and Solution:
1. Original suggested using `cpp -traditional`. This is an incorrect cpp option. The flag is supposed to be 
`cpp -traditional-cpp`.
2. Original suggested using `cpp -C -P`. The `-C` flag puts these GNU comments in the code (which is OK if you 
are writing in the C language).
```
/* Copyright (C) 1991-2012 Free Software Foundation, Inc.
This file is part of the GNU C Library.
The GNU C Library is …
```

Fix 1d advection testing program, broken with hybrid vert coord

---

dyn_em/start_em.F

KEYWORDS: slope, periodic boundary conditions
DESCRIPTION OF CHANGES: In the current WRF version the slope angle on the lateral boundaries of the domain is calculated differently than in the interior of the domain. For the former, forward or backward final differences are used, for the latter central finite differences. This can lead to different shortwave fluxes for equivalent locations in mountainous terrain.
For periodic boundary conditions, the terrain outside of the domain is known and set right before.
This enhancement implements central differences also for the domain boundary to get the same shortwave flux for equivalent locations.
ISSUE: Fixes  #1008
LIST OF MODIFIED FILES: dyn_em/start_em.F …

enhanced slope calculation at domain boundary for periodic BC

---

.github/PULL_REQUEST_TEMPLATE
tools/commit_form.txt

KEYWORDS: PR, commit message, template
Problem:
The older commit templates referred to WTF and had some singleton three quotes in a row (without
a closing set of quotes). There was ambiguity in the requests for what tests were to be conducted, and there
was no reference to the jenkins results.
Solution:
Small text tweaks, just update and clarify expectations from contributors. The text for the two templates is now
consistent.
modified:   .github/PULL_REQUEST_TEMPLATE
modified:   tools/commit_form.txt
1. No source changes, but jenkins will run.

Update PR commit message templates

---

phys/module_mp_nssl_2mom.F

TYPE: bug fix
KEYWORDS: floating point exception, log, gamma
SOURCE: Ted Mansell (NSSL)
1. A previous change to a lookup table caused a log(0) floating point exception. There was no practical impact 
unless compiling with debug checks for FPEs.  The problem was when the incomplete gamma function was 
called with a second argument of zero. It now correctly returns the complete gamma. 
2. Since the gamxinflu lookup table is double precision, calculated values for it are now DP instead of single 
precision. Very slight differences will result.
3. The lookup table is also slightly expanded for the next update -- no impact here.
phys/module_mp_nssl_2mom.F
ISSUE:
Fixes #1207 "Bug: log(0) in module_mp_nssl_2mom.F"
1. Ideal …

NSSL Microphysics log(0) FPE

---

test/em_real/README.grid_fdda
test/em_real/examples.namelist

KEYWORDS: readme, rinblw, max_dom
SOURCE: Peng Zimu (Peking University) and internal
One of the FDDA capabilities for blending observations with the gridded simulation relies on the appropriate 
observation density within a specified radius of influence, which is controlled by the option rinblw (km). To allow 
for different observations on different nests, this option is defined in the Registry as a max_domains namelist entry. 
Therefore this option should be specified for each individual domain. This PR:
1. adds (max_dom) to rinblw in test/em_real/README.grid_fdda
2. adds multiple columns for rinblw in test/em_real/examples.namelist. 
For users with nested domains, before this mod, the WRF code returned:
```
Error in rinblw, please specify a …
```

Update README.grid_fdda - add (max_dom) for rinblw

---

chem/rxn.F

TYPE: bug
KEYWORDS: photolysis scheme, TUV, diagnostics, debug_level
SOURCE: Xin Zhang (NUIST)
Problem:
When using WRF-Chem with the new Photolysis option (phot_opt = 4) activated, the model spends too much time 
writing the TUV.diags. These diagnostics should only used for debugging photolysis rates. The diagnostics should be 
enabled only for an explicitly requested debug value.
Solution:
Enable TUV diagnostics only when `debug_level >= 100`.
ISSUE: 
Fixes #1242 Speed up writing the TUV.diags file
M chem/rxn.F
1. TUV init is much quicker and the WRF-Chem one domain simulation test is successful.
The time is the time of the diagnostics call.
Here's the table if `debug_level = 0`:
|               | Before Commit | After …

Disable TUV diagnostics unless debugging

---

dyn_em/module_diffusion_em.F

TYPE: bug fix
KEYWORDS: m_opt, momentum flux 
When outputting SGS momentum fluxes using the option m_opt, the units of the fluxes should be m2 s-2 according 
to registry.les. The fluxes above the surface are divided by the density and thus have the correct units. The surface 
fluxes, however, still contain the density.
This bug fix divides the surface fluxes by the density to obtain the correct units.
This change only affects the output of the SGS fluxes (nba_mij). The tendencies and thus the results are not changed.
dyn_em/module_diffusion_em.F
1. Jenkins OK
RELEASE NOTE: Fixed units of surface momentum flux in dyn_em/module_diffusion_em.F when using m_opt. This bug fix …

bug fix for m_opt: fixed units of surface momentum flux

---

phys/module_ra_rrtmg_swk.F

TYPE: bug fix
KEYWORDS: module_ra_rrtmg_swk.F, RRTMK, RRTMG
SOURCE: James Ruppert, Penn State University
DESCRIPTION OF CHANGES: Longwave (RTHRATENLW) and shortwave (RTHRATENSW) radiative tendencies were in reversed order at start of subroutine rad_rrtmg_driver in module_ra_rrtmg_swk.F (driver for RRTMK radiation scheme). These reverse-ordered tendencies feed directly up to module_radiation_driver.F. While this bug leads to the output shortwave and longwave tendencies being in swapped positions, this bug does not affect the sum of shortwave and longwave heat tendency (RTHRATEN), so it does not affect model results.
M phys/module_ra_rrtmg_swk.F
TESTS CONDUCTED: Verified that this bug fix places the correct fields into the variables RTHRATENLW (aka RTHRATLW) and …

Radiative heat tendency bug fix for RRTMK scheme

---

dyn_em/module_first_rk_step_part1.F
external/io_grib2/bacio-1.3/baciof.F
frame/Makefile
phys/module_bl_mynn.F

TYPE: New feature
KEYWORDS: Static analysis, regression testing
SOURCE: John Collins (SimCon / Edge Hill University)
CHANGES:
The WRF code has a large number of nonstandard constructs that have been in the code for a while. Part of the capability 
of the FPT static analysis tool is to discover noncompliant Fortran syntax and usage. 
1. A few issues in the existing WRF code preclude the FPT utility from running on WRF, including outright Fortran bugs. 
The bugs are removed. 
2. Additionally, the temporary files in the frame directory associated with the automatic code generation of namelist 
configuration processing are no longer removed by the Makefile. This was not a bug, but the static analyzer needs
the cpp manufactured code to continue to exist.
This PR represents an initial step. …

Various syntax fixes found by FPT tool (static Fortran analysis mode)

---

var/da/da_setup_structures/da_setup_flow_predictors_ep_format2.inc

TYPE: bug fix
KEYWORDS: WRFDA, alpha_hydrometeors, ep_format=2
Problem:
Only rootproc reads in the data, but the broadcasting from rootproc was missing for qice, qsnow and qgraup.
Non-root processors will have qrain values for qice, qsnow and qgraup.
Solution:
add call wrf_dm_bcast_real(temp3d, ijk)
M       var/da/da_setup_structures/da_setup_flow_predictors_ep_format2.inc
RELEASE NOTE: Big fix for WRFDA incorrect ensemble perturbation values for qice, qsnow and qgraup when alpha_hydrometeors=true and ep_format=2.

Fix DA ingesting ep (ensemble perturbation) of hydrometeors in ep_format=2

---

var/da/da_minimisation/da_get_innov_vector.inc

TYPE: bug fix
KEYWORDS: WRFDA, use_obs_errfac, max_ext_its > 1
Problem:
CWB reported seeing obs errors keep decreasing with each outerloop.
Solution:
Add a check for outerloop number, so that when use_obs_errfac=true and errfac.dat exists in the working directory, observation error factors are applied only at the first outerloop.
M       var/da/da_minimisation/da_get_innov_vector.inc
RELEASE NOTE: Bug fix for WRFDA's incorrectly applying errfac.dat at each outerloop when use_obs_errfac=true and max_ext_its > 1.

Fix DA use_obs_errfac for multiple outerloops

---

chem/chemics_init.F

TYPE: bug fix
KEYWORDS: chem, drydep, wesely
SOURCE: Lukas Pilz (Heidelberg University)
Problem:
A namelist option incompatibility between chem_opt (16) and gas_drydep_opt (1) leads to trying to access a variable
that is not available in memory. This leads to unpredictable behaviors. When choosing a tracer-only chem_opt, numgas 
is 0. If gas_drydep_opt is 1 (the default), in the Wesely scheme initialization (dep_init), the field `dvj` is initialized with 
size numgas (here 0). Accessing the variable `dvj` is an error.
Solution:
A fatal error was added for when the Wesely scheme initialization is called with numgas = 0.
This fix is in `chem/chemics_init.F` and not `share/module_check_a_mundo.F` because checking the namelist options 
would require some …

Chem: Prevent seg fault due to numgas==0

---

dyn_em/module_initialize_ideal.F

TYPE: bug fix
KEYWORDS: ideal case, initialization
SOURCE: Tim Raupach (UNSW CCRC)
Problem:
In ideal case initialization routines, incorrect indices were used in the calculation of ph_1 after a perturbation bubble was added.
Impact:
The calculation of perturbation geopotential ph_1 (perturbation geopotential) and Z_BASE (idealized base state height) 
were affected.
1. If hybrid coordinate option was selected, (hybrid_opt = 2), the entire ph_1 initialization is incorrect due to the offset
in the indexing of c1h and c2h (half levels vs full levels).
2. If hybrid_opt = 0, since the 1d variables are initialized kms:kme, there is no impact.
Solution:
The vertical indices were corrected in the calculations of ph_1 in the idealized initialization routine.
ISSUE:
LIST OF …

Fix vertical indices of c1h and c2h in ideal case init of ph_1

---

phys/module_surface_driver.F

Missing argument (irrigation_channel) to be passed to the lsm and lsm_mosaic call.
TYPE: bug fix
KEYWORDS: channel, noah, mosaic
SOURCE: Arianna Valmassoi (Uni-bonn/internal)
Problem:
the water used for irrigation in the channel method was not passed to the lsm
Solution:
Added the argument to the calls: lsm and lsm_mosaic
Fixed an issue with no irrigation method selected when the channel fix is made.
Fixes #1281 
1. Do mods fix problem? Yes. 
How can that be demonstrated, and was that test conducted? Test with the previously working version. Tested with (all 3 methods) and without irrigation.
2. Are the Jenkins tests all passing? no
RELEASE …

fixes irrigation channel: water not passed to the lsm

---

external/RSL_LITE/module_dm.F

TYPE: bug fix
KEYWORDS: mpi, real, bug
SOURCE: Marc Honnorat (EXWEXs)
Problem:
When running real.exe on multiple processes with MPI, one or more process occasionally crashes in setup_physics_suite 
(in share/module_check_a_mundo.F). This has been linked to wrf_dm_initialize non-blocking MPI. 
The real.exe occasionally crashes in setup_physics_suite (in share/module_check_a_mundo.F#L2640) because the latter 
uses model_config_rec % physics_suite, which on some machines is not initialized. The behavior is as if the broadcast of 
model_config_rec performed just before in main/real_em.F#L124 had not been received by all processes.
I had never seen this bug before, it has only happened on one machine (an Intel-based cluster using Intel-MPI and ifort).
The current fix …

Fix MPI synchronization in real

---

dyn_em/module_first_rk_step_part1.F
dyn_em/module_first_rk_step_part2.F
dyn_em/solve_em.F

TYPE: bug fix
KEYWORDS: HALO, h_mom_adv_order
SOURCE: Ted Mansell (NOAA/NSSL)
Problem:
The halo exchange (used during distributed memory communication) had inconsistent use of `h_mom_adv_order`. There 
are locations when the namelist option to check should have `h_sca_adv_order`, and even a couple cases where the
code should have tested both. Consequently, the MPI results did not match for different number of patches or processor 
counts if `h_mom_adv_order=3` and `h_sca_adv_order=5`. This problem only occurs when the advection order differs 
between the momentum and scalar variables.
Solution:
These changes (using the correct variable to test, or using both `h_mom_adv_order` and `h_sca_adv_order`) fix the 
problem of non-reproducibility on different core counts …

Fix horizontal advection flag usage when "mom" != "sca"

---

Makefile
arch/configure.defaults
configure

TYPE: bug fix
KEYWORDS: gfortran/10
SOURCE: Srikanth Yalavarthi (Marvell Semiconductor)
Problem:
Due to argument inconsistencies, the WRF code will not compile with gfortran/10. 
Here are some examples of incorrect Fortran argument usages:
```
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (rank-1 and scalar)
wrf_io.f:7605:71:
7605 |                                                    ,i1,i2,j1,j2,k1,k2 )
|                                                                       1
```
```
Error: Type mismatch in argument ‘field’ at (1); passed INTEGER(4) to REAL(8)
wrf_io.f:7744:49:
2538 |     stat = NF_GET_ATT_INT (DH%NCID,NF_GLOBAL,Element,Buffer)
|                                                     2
......
7744 |     stat = …
```

Temporary fix for gfortran/10 compiler complaints

---

phys/module_sf_sfclayrev.F

TYPE: bug fix
KEYWORDS: occasional instabilities, sfclayrev, look up tables
SOURCE: Pedro A. Jimenez (NCAR/RAL)
Problem:
For some occasions the model turns unstable, and this was found to be originating due to the surface layer option 1, with 
the upper boundary values of the look up tables.
Solution:
Avoiding using the look up tables of the integrated similarity functions for the last tabulated value.
M       phys/module_sf_sfclayrev.F
1. After introducing the fix the model no longer turns unstable in the specific instances noted.
2. The jenkins tests are all PASS.
RELEASE NOTE: A minor fix (excluding use of the upper bounding value of the look-up table) was introduced to avoid occasional instabilities in the surface layer …

Fixes occasional instabilities in the surface layer option 1

---

phys/module_sf_noahmpdrv.F
phys/module_sf_noahmplsm.F
run/MPTABLE.TBL

TYPE: Enhancement
KEYWORDS: Noah-MP-Crop, specific-crop, parameters, photosynthesis, stomata
SOURCE: Zhe Zhang (University of Saskatchewan)
DESCRIPTION OF CHANGES: The current release WRF-Crop option 1, (Liu Xing's model), uses generic-crop parameters in 
stomata subroutine, to calculate photosynthesis and stomata resistance, regardless of crop type. Also some parameters in 
the crop parameters in MPTABLE.TBL, the first and second columns for corn and soybean are not consistent with the values 
used in Xing's paper. This pull request fixes the parameter values for these two columns in the crop parameter section in 
MPTABLE.TBL, as well as adds specific-crop photosynthesis-stomata parameters in this section. 
phys/module_sf_noahmplsm.F
phys/module_sf_noahmpdrv.F …

Enhancement for crop-specific parameters in Noah-MP-Crop

---

arch/configure.defaults
external/io_int/module_io_int_read.F90

TYPE: bug fix
KEYWORDS: integer kind
Problem:
The nine calls to io_int_loc had inconsistent kinds of integer for the actual and dummy arguments. On every machine and
compiler previously, the integer kinds for MPI_offset and c_int64_t were identical. On the raspberry pi (using the 
default apt-get openmpi and gnu fortran), these are not identical.
Solution:
As the integers are being shared through a C interface, that integer kind was selected.
modified: external/io_int/module_io_int_read.F90
1. Without the mods, the WRF model did not build on a raspberry pi. With the mods, the code builds and runs. Here testing
on a raspberry pi includes the distributed memory, so the MPI_offset variable would be in use.
``` …
```

Inconsistent arg types (integer kind) across subroutine call

---

chem/module_mosaic_addemiss.F

Fix for high sulfate concentrations with  biomass_burn_opt = 2
TYPE: bug fix
KEYWORDS: chem,biomassburn,plumerise,sulfate
SOURCE: Neeldip Barman (IIT Guwahati)
Problem:
Namelist option biomass_burn_opt = 2 when used with chem_opt=202 produces very high so4 concentration and so4 plumes reaching near the model top. This further leads to very large optical depths.
Namelist option biomass_burn_opt = 2 does not take sulfate emissions as inputs in registry, but sulfate emission inputs have been defined in module_mosaic_addemiss.F
Solution:
Setting IF ( p_ebu_sulf .gt. 1) aem_so4 = bburn_mosaic_f(n)*ebu(i,k,j,p_ebu_sulf) inplace of aem_so4 = bburn_mosaic_f(n)*ebu(i,k,j,p_ebu_sulf) 
module_mosaic_addemiss.F
1. chem_opt = 202 with …

bug fix: incorrectly adding sulf biomass burning emissions for MOZART/MOSAIC and biomass_burn_opt = 2)

---

phys/module_radiation_driver.F

Updates to improve icloud3 (cloud fraction scheme) based on 72 all year simulations validated against solar radiation observations.
TYPE:  enhancement
KEYWORDS: cloud fraction, radiation
SOURCE: gthompsn
Problem:
From numerous real-time and retrospective WRF simulations, the verification of shortwave radiation has consistently shown too much solar radiation reaching the ground due to a lack of cloudiness.  The existing icloud=1 option (attributed to Xu and Randall) is ineffective at creating a realistic histogram of values of cloud fraction between zero and one.
Solution:
Compared to the previously-released (initial) version of this cloud fraction scheme, these updates have now been verified (by Mei Xu) by 72 WRF simulations spread every 5th day through the year …

Updates to icloud3

---

share/module_check_a_mundo.F

TYPE: bug fix
KEYWORDS: FARMS, Microphysics, module_check_a_mundo.F
SOURCE: Ju Hye Kim and Pedro Jimenez (NCAR/RAL)
Problem:
FARMS can work correctly with microphysics schemes that do not provide effective radii of clouds. But, current WRF model displays an ERROR message and stops when the 'swint_opt is 2' and 'use_mp_re is not 1'. 
Solution:
We remove this constraint from ‘module_check_a_mundo.F’.
1. When FARMS and a microphysics scheme that do not provide effective radii of clouds (ex: mp=2) are used together, the model does not stop anymore.
2. All jenkins tests are passing.
RELEASE NOTE: Fixed an incorrect stop in the model when FARMS radiation is used with microphysics that do not …

Update check_a_mundo to make FARMS work correctly

---

phys/module_mp_morr_two_moment.F
phys/module_mp_morr_two_moment_aero.F

KEYWORDS: saturation vapor pressure, Morrison double-moment scheme
SOURCE: Hugh Morrison (NCAR)
Problem:
Current code gave unrealistically high saturation vapor pressures at T < -80 C.
Solution:
"function polysvp" in module_mp_morr_two_moment_aero.F and module_mp_morr_two_moment.F are modified to correct the problem.
M   phys/module_mp_morr_two_moment_aero.F
M   phys/module_mp_morr_two_moment.F
1. Idealized tests conduced by Morrison, the mods fix the problem. 
2. Jenkins tests have passed.
RELEASE NOTE: Fix a problem with function polyqvp which gave unrealistically high saturation vapor pressures at T < -80 C.

Fix to saturation vapor pressure at low temperatures

---

phys/module_irrigation.F

TYPE: bug fix
KEYWORDS: irrigation, time selection, day selection, bug fix
SOURCE: Arianna Valmassoi (Uni-Bonn)
Problem:
The irrigation schemes weren't working when the date selection was across two different years: i.e. irr_end_julianday < irr_start_julianday. Same problem was found for active hours across the local 00 time: i.e. irr_start_hour+irr_num_hours>23 
Solution:
Fixed by adding/modifying the if statements
M       phys/module_irrigation.F
1. Do mods fix problem? yes
2. Are the Jenkins tests all passing? Passed.
RELEASE NOTE: Bug fixes for temporal selection that spans across different years and different local days.

Irrigation fixes on time constrains across different years and different local midnight hour

---

dyn_em/module_diffusion_em.F

To close the dry theta budget at the lowest grid point when use_theta_m is enabled, the surface heat fluxes, and in the case of km_opt=5 also the non-local heat flux, are multiplied with 1+Rv/Rd*qv.
TYPE: bug fix
KEYWORDS: surface heat flux, use_theta_m, moist theta, non-local flux, 3D TKE
DESCRIPTION OF CHANGES: The conversion of surface heat fluxes from dry to moist theta in WRF is inconsistent. This leads to an unclosed dry theta budget at the lowest grid point. The surface sensible heat flux in the routines `vertical_diffusion_2` and `vertical_diffusion_implicit` should be multiplied with <img src="https://latex.codecogs.com/svg.latex?1+\frac{R_{v}}{R_{d}}q"  /> as is derived below.
Using Reynold's decomposition and averaging we can …

additional factor when converting surface heat fluxes from dry to moist theta

---

dyn_em/module_diffusion_em.F

TYPE: bug fix
KEYWORDS: 3D TKE, km_opt, divide by zero
Problem: 
When compiling WRF with the -D option, several divide-by-zero errors happen in the km_opt=5 scheme. Some of these are the same as in the Shin-Hong PBL scheme (see pull request https://github.com/wrf-model/WRF/pull/1219). I tried to fix all the appearing errors, but some of them are not so straightforward to fix (see annotations in the code).
dyn_em/module_diffusion_em.F
1. Jenkins testing is all PASS.
RELEASE NOTE: fixed divide by zero in km_opt=5

km_opt=5 causes several divide by 0

---

dyn_em/module_diffusion_em.F
wrftladj/module_diffusion_em_ad.F
wrftladj/module_diffusion_em_tl.F

TYPE: bug fix
KEYWORDS: tke, isfflx, tke_heat_flux, tke_drag_coefficient, tke_seed
Problem:
The tke seed value is used in the absence of surface drag or a surface heat flux, since there is no way to generate tke without pre-existing tke. So far the usage of the seed value is only tied to the namelist variables tke_drag_coefficient and tke_heat_flux being greater than 0. However, these namelist variables are only applied if no PBL scheme is used, diff_opt=2, and isfflx=0.
If a PBL scheme is used or diff_opt=1, then isfflx=0 is a sufficient condition to get zero fluxes (see also technical notes).
Solution:
Fixed the if statements to enforce a correct setting of the tke seed value that fits to the purpose of the seed. …

use tke_seed_value only when necessary

---

arch/configure.defaults

KEYWORDS: raspberry pi
SOURCE: Daniel Zurawski and internal
Additional strings, `armv7l` and `aarch64`, have been added to the first gfortran configuration stanza
so that these may be keywords for search from Raspberry Pi's `uname -a` output. No new
stanza was added for the gfortran target, so no re-numbering is required  for existing scripts that 
are reliant on such things as "32 = Gfortran for Linux with a serial build".
Associated with this PR, #1300 (Inconsistent arg types (integer kind) across subroutine call) is
also required to get the Raspberry Pi to build successfully.
modified:   arch/configure.defaults
1. Previously, a Raspberry Pi build returned this:
``` …
```

1st gfortran stanza target for raspberry pi (add aarch64 and armv7l)

---

chem/module_emissions_anthropogenics.F

KEYWORDS: chemistry, emissions, aircraft, indexing
SOURCE: Stacy Walters (formerly NCAR)
Problem:
An improper loop indexing that can cause addressing or floating point errors when aircraft emissions are
used.
Solution:
Fix indexing (i - dimension) for the conversion term, from i to its:ite
M       chem/module_emissions_anthropogenics.F
1. Jenkins test PASSED
RELEASE NOTE: Improper indexing in a conversion factor when using aircraft emissions for WRF Chem previously caused addressing (seg fault) or floating point errors. This has been corrected by matching the indexing on the LHS with the RHS.

bug fix: improper indexing in add aircraft emissions

---

dyn_em/module_initialize_real.F

TYPE: bug fix
KEYWORDS: vertical, interpolation
DESCRIPTION:
The stand-alone vertical interpolation program that is part of the module_initialize_real.F
file allows detailed testing of the existing vertical interpolation process used for ARW
in the real program. It is understood that practically no one except for me ever exercises
this utility.
1. The call to the main vertical interpolation routine, vert_interp, was out of date (missing
the grid id for some diagnostic error prints).
2. A suggestion for a build command is now provided.
3. Locations to use pressure-level or eta-level data are provided.
M	module_initialize_real.F
1. The stand-alone code builds and runs properly.
```
------------------------------------
UNIT TEST FOR …
```

Update vertical interpolation stand-alone, fix vert_interp call

---

external/RSL_LITE/module_dm.F

TYPE: bug fix
KEYWORDS, real, int, integer, wrf_dm_max_int
While looking to see if WRF had a function to return the maximum integer from among the
max values of integers on each of the MPI ranks, it was noticed that the return value for the
existing function was REAL. It should be an INTEGER.
There is only a single use of this function in the entire model, in the file `share/module_trajectory.F`.
```
glb_traj_proc(trj) = wrf_dm_max_int( traj_proc(trj) )
```
In that file, the input to the function, `traj_proc`, and the return value, `glb_traj_proc`, are both declared as integers. Therefore, there is no reason for a function to be given a list of integers, and when finding the max value to actually return that value as a real.
```
integer :: …
```

Fix return type on wrf_dm_max_int (should be an integer)

---

arch/configure.defaults

TYPE: bug fix
KEYWORDS: build, hydro
SOURCE: Ryan Cabell (NCAR)
Problem:
Building coupled WRF/WRF Hydro models fails when choosing configuration INTEL (ifort/icc): HSW/BDW. 
Solution:
Add missing `ifort compiler with icc` text to ARCH line for the HSW/BDW configuration. For completeness, the KNL MIC
configure stanza was also missing the same information, and has been updated.
Neither of these stanzas are involved in the traditional WRF code build, so there is no impact on users of the default WRF
atmosphere model.
Fixes #1325 
M       arch/configure.defaults
1. Modification causes WRF-Hydro build to complete successfully with the `INTEL (ifort/icc): HSW/BDW` configuration
2. …

Add missing compiler name for Intel HSB/BDW config

---

.gitignore
phys/module_cu_mskf.F
phys/module_cu_scalesas.F
phys/module_dust_emis.F
phys/module_mp_fast_sbm.F
phys/module_mp_milbrandt2mom.F
phys/module_mp_p3.F
phys/module_mp_thompson.F
phys/module_ra_goddard.F
phys/module_shcu_deng.F

TYPE: Bug fix
KEYWORDS: Fix, obsolescent, non-standard, features
SOURCE: Milan Curcic (University of Miami)
Problem:
This PR removes or fixes some obsolescent and non-standard features in several physics modules which were 
preventing WRF to be built with IBM XL v16.1.1 on Power9, as reported in #1270.
Solution:
* Replace `amax1()` occurrences with `max()`
* Explicitly cast literal constants that are passed to `min()` and `max()` intrinsics so that they are type and kind 
compatible with other arguments
* Replace calls to the non-standard `flush()` subroutine with the standard `flush()` statement.
ISSUE:
Fixes #1270 
M       phys/module_cu_mskf.F
M       phys/module_cu_scalesas.F
M       phys/module_dust_emis.F
M …

Remove obsolescent and non-standard features in physics modules

---

phys/module_mixactivate.F

TYPE: bug fix 
KEYWORDS: chemistry, sectional, CCN, mixactivate
SOURCE: Calvin Howes (UCLA), Richard Easter (PNNL), internal
Problem:
The sectional scheme diagnostic CCN1, CCN2, ... CCN6 output as computed in mixactivate did not allow for particle 
growth in the computation of volume-mean diameters.  This bug was initially found by Calvin Howes, with the current 
fix proposed by Richard Easter 09/25/2020.  The CCN output fields being diagnostic do not impact actual aerosol 
activation, so cloud properties are not impacted by the bug.
Solution:
Subroutine mixactivate in module_mixactivate.F was modified to use actual time-dependent sizes rather than the default values in computing critical supersaturations and hence CCN.
M …

Corrected bug in mixactivate for diagnostic CCN in sectional schemes

---

dyn_em/module_big_step_utilities_em.F

TYPE: bug fix
KEYWORDS: geopotential, index, horizontal advection, open, specified
When using advection order < 5 and open or specified boundary conditions, the upper limits in the horizontal advection loops of geopotential are one too small.
Let's look at the y-advection with advection order = 2, for instance and assume jte=jde. For open and specified BC the 
lower limit is increased by 1 from jds to jds+1, but the upper limit is decreased by 2 from jde-1 to jtf=jde-1-2=jde-3. It should be jtf=jde-2, however. Starting at line 2092 the jde-1 point is set, but the jde-2 point is not handled anywhere.
The issue is analogous for x-advection and advection order = 4 (jtf=jde-4 instead of jtf=jde-3).
For advection order >= …

fixed boundary issues in rhs_ph

---

phys/module_sf_noahmpdrv.F

TYPE: bug fix
KEYWORDS: lh_urb2d, diagnostics, noahmp
SOURCE: internal (reported by Xin-Zhong Liang)
Problem:
lh_urb2d was inconsistent with other urban budget arrays sh_urb2d, g_urb2d, and rn_urb2d by being the only one multiplied by the urban fraction making it a grid cell average instead of urban area average. This is only a diagnostic for output with using of an urban option together with NoahMP.
Solution:
Divide lh_urb2d by frc_urb2d. Won't affect model run results apart from this diagnostic. These arrays are not in default history output.
phys/module_sf_noahmpdrv.F
1. Yes.
RELEASE NOTE: Fix lh_urb2d diagnostic to be urban area average instead of grid cell average consistent with …

Fix for lh_urb2d diagnostics

---

share/module_bc.F

Missing corner points are set when setting boundary conditions of 3D variables and all staggered variables are treated equally in symmetric BC. Thereby the periodic BC become cleaner and more consistent with set_physical_bc2d and the symmetric BC are fixed as horizontal deformation is treated now as a staggered variable which leads to correct BC for SGS momentum fluxes at the northern boundaries.
TYPE: bug fix
KEYWORDS: boundary conditions, symmetric, corners
Problem:
In idealized simulations, the routine `set_physical_bc3d` sets the boundary zone points for periodic, symmetric, and open boundary conditions.
At first, the routine does not set the corner points (e.g., (ids-1,jds-1)): For the y-boundaries, it iterates …

Corner points

---

chem/chemics_init.F

**TYPE:** bug fix
**KEYWORDS:** `chem_opt = 202`, `n2o5_hetchem = 1`
**SOURCE:** Luke Conibear (University of Leeds)
**DESCRIPTION OF CHANGES:**
_Problem:_
N2O5 heterogeneous chemistry without the Cl- pathway (`n2o5_hetchem = 1`) already works with default MOSAIC aerosol schemes (e.g. `chem_opt = 201/202/601/611`). However, `chem_opt = 202` was not included in the `config_flags%n2o5_hetchem == 1` conditional within `chemics_init.F`.
_Solution:_
Added `chem_opt = 202` to the `config_flags%n2o5_hetchem == 1` conditional within `chemics_init.F`.
**ISSUE:** None
**LIST OF MODIFIED FILES:**
```bash
M       chem/chemics_init.F
```

Bug fix: Adding `chem_opt = 202` to `n2o5_hetchem` conditional

---

Registry/registry.chem
chem/chem_driver.F
dyn_em/solve_em.F
phys/module_microphysics_driver.F
phys/module_mp_morr_two_moment.F
phys/module_mp_morr_two_moment_aero.F
phys/module_mp_nssl_2mom.F
phys/module_mp_thompson.F
phys/module_mp_wsm6.F
share/module_trajectory.F

KEYWORDS: RAINPROD, EVAPPROD, wetscav
SOURCE: Stacy Walters (NCAR)
Originally submitted as PR #682, but was resubmitted due to conflicts
Package the state variables RAINPROD and EVAPPROD into the 4D variable
wetscav_frcing. This allows for a memory footprint reduction when chemistry
is enabled but wet scavenging is disabled.
Add logic to control setting rainprod and evapprod variables only when
the chem group namelist variable wetscav_onoff is set to 1; wetscav_onoff
defaults to 0. This logical "gate" has been added to the following files:
phys/module_mp_morr_two_moment.F
phys/module_mp_morr_two_moment_aero.F
phys/module_mp_nssl_2mom.F
phys/module_mp_thompson.F
phys/module_mp_wsm6.F
This change affects the following microphysics schemes:
MORR_TWO_MOMENT, …

Chem: Wet scavenging optional for MP schemes

---

Registry/registry.chem
chem/aerosol_driver.F
chem/chem_driver.F
chem/cloudchem_driver.F
chem/module_chem_cup.F
chem/module_mosaic_cloudchem.F
chem/module_mosaic_driver.F
chem/module_mosaic_therm.F

KEYWORDS: pH, cloud water, aerosols, mozart_mosaic_4bin_aq
SOURCE: Mary Barth (ACOM/MMM NCAR) and Stacy Walters (formerly NCAR)
Originally submitted as PR #999, but was resubmitted due to inconsistencies
Alter Registry/registry.chem to include diagnostic pH variables ph_cw, ph_aer01, ph_aer02,
ph_aer03, and ph_aer04.
Modify files, listed below, to calculate and set pH diagnostic variables
MOZART is a gas-phase chemistry mechanism (set of reactions) in WRF-Chem
Diagnostics are activated with namelist,chem option mozart_ph_diag=1
MOSAIC is one of the aerosol models in WRF-Chem that represents the size distribution
of the aerosols with 4 size bins (hence "4bin")
The pH is calculated for each of the 4 aerosol size bins. That is why there are 4 variables: pH_aer1,
aer2, …

Add pH diagnostics for mozart_mosaic_4bin_aq chemistry

---

dyn_em/module_initialize_real.F
test/em_real/examples.namelist

TYPE: feature removed
KEYWORDS: UM trajectory, NCAR ACOM trajectory
The UM trajectory option has been replaced by NCAR ACOM trajectory option.  Therefore, the initialization for UM 
trajectory (in the real program) is no longer needed.
M   dyn_em/module_initialize_real.F
(1) A single test case has been conducted to demonstrate that the UM trajectory no longer works. NCAR ACOM trajectory option gives expected results. 
(2) Jenkins test is done successfully.
RELEASE NOTE: Not necessary

Remove UM trajectory initialization from real

---

Registry/registry.diags
dyn_em/start_em.F
phys/module_diag_zld.F
phys/module_diagnostics_driver.F

KEYWORDS: pressure, height level diagnostics, vertical interpolation
SOURCE: Jared A. Lee (NCAR/RAL)
Problem:
To compare WRF simulations against observations from above-ground barometers (e.g., mounted on a wind turbine 
nacelle), it is useful to add air pressure to the list of available height-level diagnostics within WRF.
Solution:
Following the definition and development of variables like t_zl, s_zl, and ght_zl, I added a definition for p_zl in the Registry 
file, set an initial value for output, and then added the new variable to the diagnostic call tree. In the height-level 
diagnostic routine, I set the new variable p_zl to be equal to the already computed (but local) height-interpolated 
pressure. The interpolation to compute the pressure …

height-level diagnostic fixes: add p_zl, use ln(p) interp for pressure

---

clean

KEYWORDS: clean script, HLC.TBL, wind-turbine-1.tbl
Problem:
When executing 'clean -a', two files are not removed: HLC.TBL, and wind-turbine-1.tbl
Solution:
Add these two files to the list of files to be removed in the clean script
M clean
1. It does remove the two files.
2. Jenkins tests are passing.
RELEASE NOTE: The files HLC.TBL, and wind-turbine-1.tbl are now removed from the test/* directories when doing 'clean -a'.

add HLC.TBL and wind-turbine-1.tbl to clean list

---

phys/module_diag_nwp.F
phys/module_mp_thompson.F

KEYWORDS: graupel, hail, microphysics, Y-intercept
SOURCE: Greg Thompson (JCSDA)
Problem:
Since the prior version of the Thompson MP scheme, where a new relationship was created for Y-intercept parameter of one-moment graupel, the maximum radar reflectivity and max hail size were reduced lower than intended/desired.
Solution:
Minor changes to the diagnosis of the Y-intercept parameter, resulting in a slightly increased highest radar reflectivity and maximum hail size. It is not a very significant increase but fits better with the Paul Field et al. (2019) paper that analyzed T-28 aircraft hail data.
M phys/module_mp_thompson.F
M phys/module_diag_nwp.F
1. Numerous simulations run with HRRR-CONUS-like grid.
2. …

Alter graupel Y-intercept parameter diagnosis (replacement of PR#1324)

---

Registry/Registry.EM_COMMON
Registry/registry.wrfplus
dyn_em/module_after_all_rk_steps.F
dyn_em/solve_em.F
phys/module_diag_afwa.F
phys/module_diagnostics_driver.F
wrftladj/solve_em_ad.F
wrftladj/solve_em_tl.F

TYPE: no impact, clean up
KEYWORDS: un-used 3D array, rho_phy
SOURCE: reported by Xin-Liang Zhong of Univ of Maryland
Problem:
There is an un-used 3D array rho_phy.
Solution:
Remove it from the code.
M       Registry/registry.wrfplus
M       dyn_em/module_after_all_rk_steps.F
M       dyn_em/solve_em.F
M       phys/module_diag_afwa.F
M       phys/module_diagnostics_driver.F
M       wrftladj/solve_em_ad.F
M       wrftladj/solve_em_tl.F
1. No impact.
2. Jenkins tests are all pass.
RELEASE NOTE: Removed an un-used 3D array from the ARW Registry and solver (rho_phy).

Remove unused i1 array rho phy

---

dyn_em/adapt_timestep_em.F

Fix for instances of dt = 0 when using adaptive time stepping
TYPE: bug fix
KEYWORDS: adaptive time stepping, time step
SOURCE: internal, reported from two sources
Problem:
When using adaptive time stepping, and when option step_to_output_time is used, time step can be zero and cause the model to stop. The problem occurs in part because the function real_time becomes less accurate when feeding a large value of time interval, i.e. time since the simulation start time.
Solution:
This PR fixes the issue by changing the time interval calculation from relative to simulation start time to model start time, i.e. restart time. 
Fixes #1369
M    dyn_em/adapt_timestep_em.F
1. Test shows …

Fix for instances of dt = 0 when using adaptive time stepping

---

phys/module_ra_farms.F

TYPE: bug fix
KEYWORDS: FARMS, radiation, cloud optical thickness
SOURCE: Timothy W. Juliano and Pedro A. Jimenez (NCAR/RAL)
Problem:
In the ICEMODEL subroutine, there is an issue with the calculation of `Ptau` (lines 602-608 in the official WRF version). If `De <= 26.0` and `solarangle` (cosine of solar zenith angle) is really small, then `Ptau` (ice cloud optical thickness) can be negative. In my case, `Ptau` goes negative and causes the model to crash since `PPDHI` is later calculated using `log10(Ptau)`. It looks like the original code accounted for a small value of `Ptau` but only when `De > 26.0`.
Solution:
I fixed the issue simply by moving the check on `Ptau` to be located after the conditional statements.
M phys/module_ra_farms.F …

Bug fix in FARMS parameterization for ice cloud optical thickness calculation

---

Registry/Registry.EM_COMMON
dyn_em/depend.dyn_em
dyn_em/module_initialize_real.F
run/README.namelist

KEYWORDS: cloud fraction, cloud initialization
SOURCE: Greg Thompson (JCSDA)
Problem:
Cold start simulations without microphysics species take significant time to 'spin-up' the clouds causing the radiation 
to be way off balance at the start of most model simulations. This greatly affects the first few hours up to 12 hours 
or more.
Solution:
The setting of initial cloud fraction and associated cloud water/ice mixing ratio gives a big advantage to 'spin up' 
the clouds by assuming that clouds can be created from conditions of very high relative humidity. The cloud fraction 
scheme of icloud=3 is a viable solution to making initial clouds along with the setting of the water vapor mixing ratio 
to the point of saturation at initialization in …

Possibility to insert initial clouds into cold-start

---

Makefile
clean
run/README.physics_files

Created README.physics_files to describe dependencies with linked files
KEYWORDS: README, README.physics_files, linked, link, physics, schemes
Problem:
There are several files that must reside in (or be linked to) the running directory for many physics schemes. These files 
are in the run/ directory, but are linked to the test/em_real directory during compilation. There is no user documentation 
of which files are mandatory for which schemes.
Solution:
Created a README.physics_files to list all schemes that require additional files, and what those files are. Set the Makefile 
to link this README file to the test/em_real directory upon compilation. Also added this README.physics_files to the clean script.
M …

Created README.physics_files to describe dependencies with linked files

---

Makefile
Registry/Registry.EM_COMMON
dyn_em/module_initialize_real.F
dyn_em/start_em.F
external/RSL_LITE/module_dm.F
share/module_check_a_mundo.F

TYPE: bug fix
KEYWORDS: vertical nesting, vert_refine_method, use_theta_m, rebalance
SOURCE: Robert Arthur and Katie Lundquist, LLNL
Problem:
1. When vertical nesting is used with the moist theta option (use_theta_m=1), large errors occur in the vertically-
refined domain. This is the main problem addressed in this PR.
2. Another minor issue is that rebalance option 2 is redundant, and is therefore unnecessary.
Solution:
1. Several use_theta_m flags were added to the rebalancing routines in start_em.F and module_dm.F, which are 
called when vertical nesting is used. Thus, the rebalanced pressure, inverse density, and geopotential fields are 
calculated correctly and consistently with the rest of the code, regardless of whether use_theta_m=0 or 1.
2. Rebalance …

Fix to allow use_theta_m=1 with vertical nesting and simplify rebalance options

---

Registry/Registry.EM_COMMON
dyn_em/module_diffusion_em.F
dyn_em/solve_em.F

TYPE: bug fix
KEYWORDS: rho, sfs_opt, m_opt, cal_titau
SOURCE: Robert Arthur and Jeff Mirocha (LLNL)
Problem:
In the cal_titau subroutines in module_diffusion_em, rho was not always interpolated to the correct location on the 
staggered grid. This issue affected the subgrid stress terms when sfs_opt .gt. 1. Additionally, when sfs_opt .eq. 0 and 
m_opt .eq. 1, the actual subgrid stresses applied in the code were correct, but the output was wrong. This is a 
follow-on from issue #1214 by @matzegoebel, which addressed the surface stress output from subroutine 
vertical_diffusion_2 when sfs_opt .gt. 0 or m_opt .eq. 1, but did not address the cal_titau subroutines.
Solution:
A rhoavg variable was added to cal_titau_12_21, cal_titau_13_31, and cal_titau_23_32 and used …

Bug fix to use correct rho value in cal_titau subroutines

---

Registry/Registry.EM_COMMON
dyn_em/module_big_step_utilities_em.F
dyn_em/module_small_step_em.F
run/README.namelist

KEYWORDS: geopotential,vertical advection
The geopotential equation in WRF is formulated in the following (advective) form where staggering/destaggering is 
marked with overbars:
The vertical advection term thus employs a double staggering of Omega. First, Omega is destaggered to mass levels 
and multiplied with the phi gradient. Then the product is staggered back to w-levels. This formulation is analogous to the horizontal terms, but the double averaging of Omega may introduce additional inaccuracies and is not necessary. 
The phi gradient can be first staggered to w-levels and then multiplied with the unaveraged Omega:
For consistency and to avoid numerical instabilities, the same thing has to be …

Avoid double staggering of ww in vertical advection of geopotential

---

phys/module_bl_ysu.F
phys/module_pbl_driver.F
phys/module_physics_init.F
run/README.namelist

TYPE: Enhancement
KEYWORDS: BEP, BEP+BEM, YSU PBL scheme, vertical diffusion equations
SOURCE: Eric A. Hendricks (NCAR/RAL/NSAP)
The multilayer BEP (Building Effects Parameterization) and BEP+BEM (BEP with the integration of a Building Energy Model) urban canopy models (UCMs) are added to the YSU planetary boundary layer (PBL) scheme. The implicit (A) and explicit (B) BEP and BEP+BEM source terms are added as forcing to the YSU implicit/explicit vertical diffusion equation solvers. Forcing is applied for zonal momentum, meridional momentum, potential temperature, and water vapor mixing ratio. The A sources are added to the tridiagonal matrix and the B sources are added to the explicit term vectors. Additionally, the finite differencing is modified using the BEP …

Add multilayer UCMs to YSU PBL parameterization 

---

Registry/Registry.EM_COMMON
phys/module_surface_driver.F

KEYWORDS: namelist fractional_seaice, default, replacing original PR#1128
Since GFS, the most commonly used input data source, has been providing fractional seaice
data for a while, it seems reasonable to make the default option for fractional_seaice to be 1.
This should also help our general users. Both ERA5 and ERA-Interim provide fractional seaice
data, too. 
Turning on the fractional seaice flag broke many MPI vs OpenMP comparison tests. This led to the finding that the 
option is not thread safe for a number surface layer physics options: revised MM5, original MM5, MYJ, QNSE and PX (sf_sfclay_physics = 1, 91, 2, 4, and 7). This PR additionally provides the fix for these options.
M …

Change default fractional_seaice option from 0 to 1

---

Registry/Registry.EM_COMMON
dyn_em/module_first_rk_step_part1.F
dyn_em/start_em.F
phys/Makefile
phys/module_bl_eepsilon.F
phys/module_pbl_driver.F
phys/module_physics_addtendc.F
phys/module_physics_init.F
run/README.namelist

KEYWORDS: E-epsilon, EEPS, TKE, PBL 
SOURCE: Chunxi Zhang: 1: (past) International Pacific Research Center, University of Hawai‘i at Mānoa
2: (past) Center for Analysis and Prediction of Storms, University of Oklahoma
3: (current) I. M. System Group, Inc. (IMSG); NOAA/EMC
Yuqing Wang   International Pacific Research Center, and Department of Atmospheric Sciences, University of Hawai‘i at Mānoa
1) the file module_bl_eepsilon.F includes the module for this scheme
2) standard procedures for a new scheme in WRF: changed init, addtendc and driver
3) three more variables are declared in registry.EM_COMMON. e.g.,
pep_pbl (TKE dissipation rate, state)
pek_adv (TKE advection,        scalar)
pep_adv (PEP advection,        scalar)
the files …

Add a new E-epsilon PBL scheme:

---

phys/module_mp_thompson.F

TYPE: bug fix
KEYWORDS: Thompson, MP, aerosol, constant
SOURCE: Greg Thompson (JCSDA), found by Laura Fowler and Mary Barth (NCAR)
A problem with a single constant was discovered a couple months ago, but did not get permanently updated in the 
repository. The fix is to reduce fake surface aerosol emissions by a factor of 4.
modified:   phys/module_mp_thompson.F
1. Jenkins tests are all PASS.
RELEASE NOTE: For the Thompson MP scheme, a problem with a single constant was discovered that caused approximately 4x too much fake surface aerosol emissions.

Thompson MP: reduce fake aerosol emissions by 4x

---

Registry/Registry.EM
Registry/Registry.EM_COMMON
Registry/Registry.NMM
Registry/Registry.tladj
Registry/registry.chem
doc/README.madwrf
dyn_em/depend.dyn_em
dyn_em/module_big_step_utilities_em.F
dyn_em/module_initialize_real.F
dyn_em/solve_em.F
main/depend.common
phys/Makefile
phys/module_madwrf.F
phys/module_microphysics_driver.F
phys/module_physics_init.F
run/README.namelist
share/module_check_a_mundo.F
share/module_optional_input.F

TYPE: New feature
KEYWORDS: MAD-WRF, MADCast, WRF-Solar, cloud initialization, cloud advection/diffusion, nudging
SOURCE: Pedro Jimenez, Jared Lee, and Jimy Dudhia (NCAR), and Greg Thompson (JCSDA)
Problem: There is room for improvement in the short range shortwave irradiance predictions
Solution:
MAD-WRF is a solar irradiance nowcasting system that combines:
1. the benefits of data assimilation and the philosophy of advecting cloud properties of MADCast, and
2. the cloud physics of WRF-Solar. 
The initial cloud field can be enhanced based on relative humidity and the model can impose the cloud mask and the cloud top / base height from available earth observations. The hydrometeor content is advected and diffused as tracers, and the resolved hydrometeors are nudged …

Adding the MAD-WRF model

---

Registry/Registry.EM_COMMON

KEYWORDS: max_rot_angle_gwd, remove, Registry.EM_COMMON, non-applicable
SOURCE: internal 
Problem:
The variable 'max_rot_angle_gwd' is no longer used in the code since V4.0, but was still listed in the 
Registry.EM_COMMON file.
Solution:
Removed 'max_rot_angle_gwd' from Registry.EM_COMMON
M    Registry/Registry.EM_COMMON
1. No impact modification. No testing needed. This variable is not in any other code.
2. Jenkins is OK

Removed 'max_rot_angle_gwd' from Registry - no longer used.

---

phys/module_ra_rrtmg_sw.F

TYPE: bug fix
KEYWORDS: RRTMG, shortwave radiation, solar source function
SOURCE: Timothy W. Juliano and Pedro A. Jimenez (NCAR/RAL), Jimy Dudhia (NCAR/MMM)
Problem:
In subroutine `setcoef_sw` of `phys/module_ra_rrtmg_sw.F`, which is called within subroutine `rrtmg_sw`, the number 
of vertical levels (`nlayers`) and the tropopause level (`laytrop`) are calculated. If the domain top is sufficiently low, 
then the tropopause level is never "found" by the set pressure threshold, and `laytrop` = `nlayers`. In a typical real 
case, where the tropopause is below the model top, `laytrop < nlayers`. Thus, this scenario is likely to occur only in 
idealized cases.
After `nlayers` and `laytrop` are set, subroutine `taumol_sw` is called within the radiation transfer model. …

Bug fix: RRTMG SW solar source function calculation

---

external/RSL_LITE/module_dm.F
share/module_check_a_mundo.F

TYPE: bug fix
KEYWORDS: vertical nesting, hybrid vertical coordinate, vert_refine_method, hybrid_opt
SOURCE: Robert Arthur and Katie Lundquist (LLNL)
Problem:
When vertical nesting is used with the hybrid vertical coordinate option (hybrid_opt=2), large errors occur in the 
vertically-refined domain.
Solution:
An incorrect calculation of pb (base pressure) was fixed in subroutine force_domain_em_part2 (module_dm.F). The pb 
calculation was changed to match similar code in start_em. This fix is within a block of code that is only called if 
vert_refine_method .ne. 0, in order to rebalance on the "intermediate" nested grid. The error was likely a result of the 
switch to the new hybrid coordinate definition, which was not updated correctly in this particular …

Fix to enable vertical nesting with hybrid vertical coordinate

---

phys/module_diag_functions.F

Correct MU layer and PWAT, refine CAPE, CIN, LFC
TYPE: bug fix, enhancement
KEYWORDS: Most unstable layer, Precipitable water, CAPE, CIN, LFC
SOURCE: Zhixiao Zhang (University of Utah), Adam Varble (PNNL and University of Utah), and Katelyn Barber (PNNL)
Problem:
The most unstable (MU) layer and precipitable water(PWAT) are inconsistent with the conventional definitions in 
meteorological communities. LFC, CAPE and CIN calculations do not work well while dealing with multiple inversion 
layers.
Solution:
1. Correct the MU layer definition from the max water vapor mixing ratio (w) level to the max equivalent potential 
temperature (Theta-e) level. Because it is the theta-e rather than mixing ratio conserved during the dry/moist 
adiabatic lifting processes.
2. …

Bug fix in buoyancy diagnostic function

---

Registry/Registry.EM_COMMON
dyn_em/Makefile
dyn_em/module_advect_em.F
dyn_em/module_big_step_utilities_em.F
dyn_em/module_em.F
dyn_em/module_ieva_em.F
dyn_em/solve_em.F
run/README.namelist
test/em_real/namelist.input.IEVA.4km

KEYWORDS: IEVA, vertical advection
SOURCE: Louis Wicker (NOAA/NSSL)
For grids with large aspect ratios (dx/dz >> 1) that permit explicit convection, the large time step is limited by the 
strongest updraft that occurs during integration.  This results in time step often 20-30% smaller, or requires the use 
of w-filtering, such as latent-heat tendency limiting.  Regions of large vertical velocities are also often very small 
relative to the domain.  The Implicit-Explicit Vertical Advection (IEVA) scheme has been implemented (see Wicker, L. J., 
and W. C. Skamarock, 2020: An Implicit–Explicit Vertical Transport Scheme for Convection-Allowing Models. Mon. Wea. 
Rev., 148, 3893–3910) and that permits a larger time step by partitioning the vertical …

Implicit Explicit Vertical Advection (IEVA)

---

dyn_em/module_initialize_fire.F
phys/module_fr_fire_util.F

TYPE: bug fix
KEYWORDS: idealized fire nested domain simulation
SOURCE: Found by Masih Eghdami (NCAR), Pedro Jimenez (NCAR)
Problem:
The atmospheric coordinates (lat/lons) are initialized with spatial coordinates, this will create a fatal error when the 
model is run with nested domains. The error is because lat>90 in share/interp_fcn.F:
```
CALL wrf_error_fatal ( 'Nest over the pole, single input domain, longitudes will be wrong' )
```
Solution:
The lat/lon are initialized with zeros similar to LES idealized cases only if the model has 2 domains to prevent the error. If the model is run with 1 domain, the lat/lon are written with spatial coordinates allowing easier post-processing.
ISSUE: This PR addresses the discussion in #1412 with @pedro-jm and @janmandel. …

bug fix: initialize lat/lon with zeros only for nested fire runs

---

Registry/registry.chem
chem/emissions_driver.F
chem/module_gocart_dust.F
chem/module_gocart_dust_afwa.F
chem/module_qf03.F
chem/module_uoc_dust.F

KEYWORDS: GOCART, dust emission, dust_opt, WRF-Chem
SOURCE: Alexander Ukhov (KAUST)
This PR affects dust emission schemes (dust_opt=1,3,4) coupled with GOCART
aerosol module. 
1. Current implementation of dust_opt=1,3 calculates air mass in the grid box using
cell area and height, and air density, however  a more elegant solution is now implemented 
(by analogy with dust_opt=4). This solution only requires height of the lowest model layer. 
2. Another issue have been also resolved when using dust_opt=1. Due to incorrect
indexing in the tile loop dust emissions diagnostics (variables EDUST1…5) were zero
near the boundaries of the domain.
3. Each emission scheme (dust_opt=1,3,4) reported instantaneous dust emissions diagnostics
(variables EDUST1…5) …

removing dxy from GOCART dust emission schemes. Code clean-up.

---

dyn_em/module_big_step_utilities_em.F

TYPE: bug fix
KEYWORDS: IEVA, OpenMP
Problem:
With IEVA activated, differences appear between OpenMP results with OMP_NUM_THREADS > 1 and any of the following:
1. serial results
2. MPI results
3. OpenMP results with a single thread
Solution:
Working backwards, the computation in WRF (pre-IEVA code) computed the full MU field only on the mass-point tile size: 
```
DO j = jts, jte-1
DO i = its, ite-1
```
We extend the computation one grid cell to the left and right:
```
DO j = jts-1, jte-1
DO i = its-1, ite-1
```
Since WRF previously did not use those values, that is not a problem to have additional rows and columns of valid data inside of the halo region.
This is a follow-on PR to 4412521401e6f #1373 "Implicit Explicit Vertical Advection (IEVA)". …

Fix bit for bit error in OpenMP IEVA

---

dyn_em/module_ieva_em.F

TYPE: bug fix
KEYWORDS: IEVA, tile or memory sized arrays
Problem:
Several local arrays used in the implicit advection routines are currently dimensioned by memory sizes. However this 
does not affect model results, whether it is serial, OMP or MPI.
Solution:
They should be dimensioned by tile sizes for proper memory scaling using OpenMP.
M    dyn_em/module_ieva_em.F
1. It does not change any results.
2. Jenkins is OK

Memory-sized arrays changed to tile-sized arrays

---

phys/module_bl_acm.F
phys/module_pbl_driver.F
phys/module_sf_pxlsm.F
phys/module_sf_pxsfclay.F

TYPE: Enhancement
KEYWORDS: LSM, PBL, ACM2, P-X LSM, PBLH, Q2
SOURCE: Robert Gilliam and Jonathan Pleim (US EPA)
The purpose of this change is to fix the ACM2 PBL scheme for rare crashes and add evaporation pathway to the 
Pleim-Xiu LSM.
Problem:
1. Bug in the ACM2 PBL scheme caused very infrequent crash in extreme terrain of Himalayan mountains found by a 
collaborator who modeled Asia and found negative PBL heights being computed at the time of a crash.  
2. No evaporation directly from ground in vegetation part of a grid cell.
Solution:
1. Modified the PBL height algorithm for stable conditions so that the Richardson number is computed using windspeed 
in layer k rather than wind speed difference between layer k and ksrc.
2. Added new pathway for evaporation …

US EPA ACM2 and PX LSM updates Mar 2021

---

dyn_em/start_em.F
phys/module_mp_ntu.F
phys/module_physics_init.F

TYPE: bug fix
KEYWORDS: ntu_init, SNOWNC
SOURCE: Tzu-Chin Tsai (National Taiwan University)
Problem:
1. The calculation of air density (RHOA) is divided by zero (producing NaN) at the top full level (k=kte) in 
start_em.F.  
2. Incompatible with the description of SNOWNC in the Registry (ACCUMULATED TOTAL GRID SCALE SNOW AND 
ICE).
3. Intel19 compiler error #1444
Solution:
1. The derivations of air density (RHOA), pressure (PRES), and height (z_at_q) are moved from the start_em.F to 
ntu_init through the passing of basic variables (PHB, PH, P, PB, ALT, and QV) from the WRF dynamics. Also, the 
ending indices of the vertical loop are changed to kte-1. 
2. The sedimentation of pristine ice (ICENCV) is appended to the accumulated snow precipitation (SNOWNCV+
ICENCV). …

Corrections for ntu_init

---

chem/chemics_init.F
chem/module_mosaic_newnucb.F
hydro/Routing/module_gw_gw2d.F
phys/module_fr_fire_phys.F
phys/module_gocart_coupling.F
phys/module_mp_fast_sbm.F
phys/module_mp_gsfcgce_4ice_nuwrf.F
phys/module_mp_ntu.F
phys/module_ra_eclipse.F
phys/module_sf_bep_bem.F
phys/module_sf_noahmplsm.F
share/module_check_a_mundo.F
tools/non_ascii_finder.F

KEYWORDS: ASCII
Remove instances of non Fortran character set entries in the WRF source. All of these changes are comments.
1. The \textemdash becomes "-"
2. The non-American keyboard letters become a, e, i, o, u without the dots or accents
3. The superscript 2 is removed, and replaced by a regular 2: W/m2
4. Extra DOS carriage returns are removed (likely when the files come from windows machines)
5. The degree symbol was removed
6. An extra handy vim command was added
modified:   chem/chemics_init.F
modified:   chem/module_mosaic_newnucb.F
modified:   hydro/Routing/module_gw_gw2d.F
modified:   phys/module_fr_fire_phys.F
modified:   phys/module_gocart_coupling.F
modified:   phys/module_mp_fast_sbm.F
modified: …

Remove ASCII chars outside of 32-127 range

---

wrftladj/solve_em_ad.F

TYPE: bug fix
KEYWORDS: IEVA, TLADJ, solve
Problem:
After the IEVA mods (commit 44125214, #1373 "Implicit Explicit Vertical Advection (IEVA)"), which changed the calls to 
rk_tendency and rk_scalar_tend, the WRFPlus code no longer compiled.
Solution:
The new arguments added to the calls to rk_tendency and rk_scalar_tend have been added inside the solve routine
for WRFPlus.
wrftladj/solve_em_ad.F
1. Without mods, there are compiler errors from missing args. After the mods:
```
> ls -ls main/*.exe
94944 -rwxr-xr-x 1 gill p66770001 97217616 Mar 29 10:11 main/wrfplus.exe
```
2. This does not impact jenkins, so expect they are still OK.

BF: IEVA mods in solve required also in WRFPlus

---

dyn_em/module_big_step_utilities_em.F

KEYWORDS: IEVA CFL cfl
Problem:
Historically, when a user has looked for any CFL violations that are reported in the print out, the string searched for
was "cfl". With the introduction of IEVA, a new series of CFL error messages now includes such information as 
horizontal and vertical stability. However, the strings were switched to uppercase.
Solution:
For the few output strings generated for the CFL prints, change the case from upper back to lower case.
Also, there was an extra ")" in a few of the internal write commands. I am not sure why those did not cause compiler 
errors. Those extra ")" characters were removed since I was changing those lines anyways.
modified: …

IEVA: change upper case string "CFL" to lower case

---

phys/module_surface_driver.F

TYPE: bug fix
KEYWORDS: fractional seaice, MYJ and QNSE surface layer, MYNN PBL
SOURCE: internal, reported by Lou Wicker (NSSL)
Problem:
When MYNN PBL is used with MYJ surface layer with the fractional seaice option on, an input field wspd is not defined. 
Solution:
Define wspd just the same as when the fractional seaice option is off. Hence, the loop to define wspd is moved outside the existing `if (fractional_seaice == 1)` block. The same change is applied to QNSE surface layer option too.
LIST OF MODIFIED FILES: list of changed files 
M    phys/module_surface_driver.F
1. This allows MYJ surface layer option to work with MYNN PBL when fractional seaice is on.
2. Jenkins tests all pass.
RELEASE NOTE: When MYNN PBL is used with MYJ surface layer …

Fix for fractional seaice using MYJ and QNSE surface layer and MYNN PBL

---

Registry/Registry.EM_COMMON

TYPE: bug fix
KEYWORDS: shallow convection, period, periodic boundary conditions
Fixed staggering of shallow cumulus tendencies of u and v at periodic boundaries by adding the tendencies to a 
PERIOD communication.
In WRF, the u and v tendencies from the shallow cumulus scheme are computed on the mass points and then 
staggered to the velocity points. This staggering operation requires halo points at the domain and tile boundaries. 
Currently, there is no MPI communication for the halo points at the domain boundaries for periodic boundary 
conditions. Therefore, I added rushten and rvshten to one of the PERIOD communications that is called before 
the staggering. This PERIOD communication also includes the normal …

Fixed staggering of shallow cumulus tendencies of u and v at periodic boundaries

---

phys/module_bl_boulac.F

TYPE: bug fix (no effect)
KEYWORDS: BouLac PBL option
SOURCE: Internal (reported by Xinzhong Liang)
Problem:
PBL tendency was added to old value (no sign that this was causing problems as array may have been zero): e.g.
```
rthblten(ix,iz,iy)=rthblten(ix,iz,iy)+(th1D(iz)-th_phy(ix,iz,iy))/dt
```
This could have problems if BLDT is used
Solution:
Do not add to old value:
```
rthblten(ix,iz,iy)=(th1D(iz)-th_phy(ix,iz,iy))/dt
```
ISSUE:
Fixes part of #1297 (not closed yet)
phys/module_bl_boulac.F
1. Tests with and without change Jan 2000 case, identical after one hour.
2. Jenkins OK.
RELEASE NOTE:  A minor fix to BouLac PBL tendency cleans up the assignment, no longer assuming that the tendency is cumulative (no effect).

Boulac PBL tendency should not be added to previous value

---

dyn_em/solve_em.F

TYPE: bug fix
KEYWORDS: OMP, do_avgflx_em
The missing OMP directive END PARALLEL DO was added at two places: where the time-averaging of fluxes is 
initialized and updated (relevant for do_avgflx_em=1).
dyn_em/solve_em.F
1. Jenkins is OK, and a large number of jenkins tests are with OpenMP.
RELEASE NOTE: Added missing OMP directives in ARW solve for the option: do_avgflx_em=1. Many OpenMP implementations assume the "END PARALLEL DO", but it is more conventional within WRF to have it.

Added two missing END PARALLEL DO directives for do_avgflx_em=1

---

dyn_em/module_diffusion_em.F

Removed redundant code in vertical_diffusion_implicit
The case isfflx=1 in the routine vertical_diffusion_implicit contained do loops with no impact. In these loops, only 
unindexed variables that are not used within the do loop are set. There are no other assignments in the do loops, so 
the loops can be safely removed.
LIST OF MODIFIED FILES:  
dyn_em/module_diffusion_em.F
1. Before vs after is identical.

Removed redundant code in vertical_diffusion_implicit

---

phys/module_bl_camuwpbl_driver.F

TYPE: bug fix
KEYWORDS: UW PBL, input radiative tendency fix
SOURCE: internal (reported by Xinzhong Liang)
Problem:
The top-down mixing in this scheme requires a radiative temperature tendency but the theta tendency is provided. 
The error is small as this tendency is only used for clouds at the top of the PBL. 
Solution:
Convert input radiative tendency from theta to T (exner multiplier included)
qrl8(    1,kflip)   = rthratenlw(i,k,j) _*exner(i,k,j)_ * cpair * dp
ISSUE: 
Fixes one of the issues in #1297 (some still need investigating)
M       phys/module_bl_camuwpbl_driver.F
1. Tests confirm small impact.
2. Jenkins testing is OK.
RELEASE NOTE: 
UW PBL: input radiative tendency corrected to be T tendency instead of theta …

UW PBL: add missing exner multiplier for input radiation T tendency

---

Registry/Registry.EM_COMMON
test/em_real/namelist.input
test/em_real/namelist.input.global
test/em_real/namelist.input.jan00

KEYWORDS: fractional_seaice, registry, Registry.EM_COMMON, namelist.input, SLAB
Problem:
The namelist parameter "fractional_seaice" was recently modified in the Registry.EM_COMMON file to be set to "on"
(1) by default (commit 0fff69a1b117424d, PR #1401 "Change default fractional_seaice option from 0 to 1". However, if 
using the SLAB scheme, fractional_seaice must be turned off, which causes problems for some of the default 
idealized cases. Additionally, some other cases where users are running with the SLAB scheme (and not realizing it's 
turned on by default), would cause lots of user difficulty and confusion.
Solution:
Set fractional_seaice back to 0 (off) in Registry.EM_COMMON, but add it (and turned on) to three of the default …

fractional_seaice turned off in registry, turned on in namelists for real cases

---

Registry/Registry.EM_COMMON
phys/module_surface_driver.F
share/module_check_a_mundo.F

KEYWORDS: namelist, fractional seaice, slab
Problem:
When a user specifies both the SLAB thermal diffusion land model and the fractional seaice option, the model fails 
from the surface driver. As these are namelist settings, the conventional place to detect this inconsistency is in
check_a_mundo.
Solution:
Put in a simple check to find this namelist inconsistency in check_a_mundo, and report this to the user.
modified:   physics/module_surface_driver.F
modified:   share/module_check_a_mundo.F 
1. When the namelist is set up with:
```
&physics
fractional_seaice                   = 1,
sf_surface_physics                  = 1,     1,     1,
```
then the …

NML check: fractional seaice + SLAB not permitted

---

chem/module_add_emiss_burn.F

TYPE: bug fix
KEYWORDS: fire emissions, RACM
SOURCE: Megan Bela, Stu McKeen (CU Boulder CIRES / NOAA CSL)
Add NH3, CH4, CO2 fire emissions for RACM mechanisms. These emissions are present in fire emissions files generated 
by prep_chem_src. Prior to these changes, fire NH3, CH4, CO2 emissions in the fire emissions files generated by 
prep_chem_src were not read in to WRF-Chem, leading to low NH3, CH4, and CO2 values in fire impacted regions. 
Users should now expect significantly higher NH3, CH4, and CO2 values in fire impacted regions when using RACM 
chemical mechanisms.
M chem/module_add_emiss_burn.F
1. Example of using the new emissions
2. Jenkins testing is OK.
RELEASE NOTES: The NH3, CH4, CO2 fire emissions have …

Added NH3, CO2, CH4 fire emissions for RACM mechanisms.

---

chem/KPP/configure_kpp

TYPE: bug fix
KEYWORDS: KPP, GCC
SOURCE: Douglas Lowe (University of Manchester), Will Hatheway
Problem:
Compiling of WRF-Chem with KPP chemistry schemes fails on
ubuntu systems, due to a buffer overflow error for the few largest
chemical schemes. This does not happen on HPC systems, so might
be a ubuntu specific issue (however we were unable to get to the root
cause of what compiler flag differences there might be).
Solution:
We switched off all optimization of the compilers for KPP only (using -O0).
This stopped the buffer overflow error. We did try minor optimization (-O1),
but this caused the error again, so we've left all optimization off. As this only
impacts the speed of the KPP program during compilation of WRF-Chem
(and marginally, at that), we felt this …

Switched off optimization for KPP compilation, to stop buffer overflow.

---

dyn_em/module_em.F

TYPE: bug fix
KEYWORDS: ieva, ww, and wwE arrays
SOURCE: Lou Wicker of NOAA/NSSL
Problem:
A few of the ww arrays in some of the explicit advection calls were supposed to be wwE. It affects w, scalar, as well as geopotential.
Solution:
Replacing array ww with wwE.
dyn_em/module_em.F
1. Developer says mods are OK.
2. Jenkins is OK
RELEASE NOTE: Part of IEVA option, nothing new required for release notes.

Fixes for ieva option

---

run/README.namelist

KEYWORDS: reasonable_time_step_ratio, README.namelist, namelist
Problem:
The new namelist option "reasonable_time_step_ratio" was not added to the README.namelist file when it was 
originally added to the Registry (PR #784). 
Solution:
Added it to the README.namelist file.
M  run/README.namelist
1. Text only - no tests needed
2. Jenkins tests - ok

Add Namelist Option 'reasonable_time_step_ratio' to README.namelist File

---

Registry/Registry.EM_COMMON
dyn_em/module_first_rk_step_part1.F
phys/module_cu_mskf.F
phys/module_cumulus_driver.F

Remove un-used w_up array from MSKF scheme
TYPE: bug fix, enhancement, no impact
KEYWORDS: w_up, MSKF, nests
SOURCE: reported by Samm Elliott (TQI), internal
Problem:
The array w_up is no longer used by the MSKF scheme, and this array also caused a problem in nesting when MSKF is turned off in the nest.
Solution:
Remove this array.
ISSUE: 
Fixes #1448
M       phys/module_cu_mskf.F
M       phys/module_cumulus_driver.F
1. Tested before and after the array removal, model results are identical.
2. The Jenkins tests all passed.

Remove un-used w_up array from MSKF scheme

---

phys/module_shcu_deng.F

TYPE: bug-fix
KEYWORDS: Deng shallow scheme, negative QV input fix
SOURCE: internal with WRF-Solar tests
Problem:
Deng occasionally blows up when taking the log of a negative QV. Some microphysics schemes allow very small 
negative QV to persist.
Solution:
In Deng scheme only, limit internal QV1D minimum to 1.e-12. Because this is the local copy of the variable, there is no 
effect on Qv outside of this shallow CU scheme.
M       phys/module_shcu_deng.F
1. Fix was tested and prevented blow-ups in WRF-Solar
2. jenkins is all passing
RELEASE NOTE:  Small bug-fix to allow the Deng shallow cumulus scheme to work with small negative water vapor input. Previously, the scheme died when taking the log of negative Qv.

Deng shcu - limit to prevent negative QV1D

---

dyn_em/nest_init_utils.F

TYPE: bug fix
KEYWORDS: hybrid vertical coordinate, HVC, 1d
SOURCE: Bill Skamarock (NCAR), internal
Problem:
The hybrid vertical coordinate has a default option (hyb_opt=2). For the not so frequently used option where the 
stretching uses a sin^2() function (hyb_opt=3), the bounding value for the weighting term at the top of the 
atmosphere should be identically zero. It is likely computed to be nearly zero, but an IF test cleanly assigns the 
value. However, that IF test uses the wrong logic for which k-index to check.
Solution:
All we do is swap `kds` with `kde` in the IF test:
```
ELSE IF ( k .EQ. kds ) THEN
```
with
```
ELSE IF ( k .EQ. kde ) THEN
```
modified:   nest_init_utils.F
1. This option is not advertised, so …

Fix hybrid vertical coordinate 1d array assignment

---

Registry/Registry.EM_COMMON

TYPE: bug fix
KEYWORDS: urban, registry, re-used names
Problem:
Two urban variables, SFRV_URB3D and LFRV_URB3D, were accidentally given the names in the Registry of "SFR_URB3D" and "LVR_URB3D", respectively. These names were already in use by the variables SFR_URB3D and LFR_URB3D, again, respectively.
Solution:
Add two characters in the Registry to fix the names and make them unique. Also, while I was at it, I lined up the urban variables in the neighborhood of these fields.
IMPACT:
Without these mods, the WRF model will not give bit-for-bit results on a restart when using BEP BEM. With these mods,
the BEP BEM case is bit-for-bit for a restart comparison.
1. Before …

Fix SFRV and LFRV names in Registry

---

phys/module_mp_nssl_2mom.F
phys/module_physics_init.F

NSSL Microphysics update (April 2021)
TYPE: Bug fixes and minor enhancements
KEYWORDS: mp_physics 17/18 (NSSL 2-moment), CCN regeneration (mp_physics 18)
SOURCE: Ted Mansell (NOAA/NSSL)
Fixes:
- Fall speed air density factor limited to air density of 0.05 (for very high model top) to mitigate excessive fall speeds
- Fixed issue of spurious creation of large concentrations of very small droplets and transient large condensation 
(also increased minimum droplet size) (mp_physics = 17/18)
- Fixed issue of negligible "seed" values of graupel from Bigg freezing at relatively high temperatures (thanks to 
S. Lasher-Trapp)
- Minor bug fix in effective radius calculation of snow.  (thanks to T. Iguchi)
Updates:
- Enabled regeneration of CCN by droplet evaporation and …

NSSL Microphysics update (Release v4.3)

---

dyn_em/module_diffusion_em.F

TYPE: bug fix
KEYWORDS: diffusion, ARW, bounds check, kpbl
Problem:
Running the code with bounds check uncovered several locations where a computed vertical index was outside the range 
of the array (the computed values was k==0). This is in the nonlocal_flux routine.
Solution:
In those two locations, use a MAX() function, where the minimum allowed value will be the lowest vertical index: 1.
modified:   dyn_em/module_diffusion_em.F
1. There are two mods. First, the assignment of the flag `pblflg` needs to be `.LE.`, not `.LT.`. Second, the value
kpbl(i,j)-1` has already been computed, so use that local `k` value. After the mods, the code runs with bounds 
checking on, through to model completion.
2. Jenkins …

diffusion computed k-index == 0 for PBL

---

Registry/Registry.EM_COMMON

TYPE: bug fix
KEYWORDS: restart, at least 3 domains with feedback on, ozone input option 2
Problem:
With o3input = 2 as a default option for RRTMG, and feedback on, the restart capability is not bit for bit when using three or more total domains. This is due to different XLAT and XLONG are used in the initial interpolation of ozone data to the model grid at model start time versus model restart time.
Solution:
Removing 'u' (the Registry "feedback" option) for XLAT and XLONG fixes the problem. While we were making these nesting changes in the Registry, the 'd' and 'u' options for cloud fraction are also removed. There is no need to do either horizontal interpolation or feedback for this variable.
M …

Fix restart problem with 3 or more domains when o3input = 2

---

frame/module_domain.F

KEYWORDS: io_fields_filename, runtime I/O
Problem:
I wanted to add 500 new fields to the history output stream for debugging purposes. There were a number of errors 
I ran into with that large number of additional fields.
Solution:
The run-time streams I/O routine had fairly small limits on how many new arrays were allowed (100), but even more 
restrictive was the length of the string of names (256 chars, so 1.56 characters per field when we include the 
comma separator). It is now 1000 fields, with the string length of 8000 characters.
modified:   frame/module_domain.F
1. With the mods, I was able to add about 550 new fields to the history stream. Note that except for tossing out some _1 …

Allow more run-time fields in namelist-controlled streams

---

Registry/Registry.EM_COMMON

KEYWORDS: Registry.EM_COMMON, max_msftx, max_msfty
Problem:
In Registry.EM_COMMON, the variables max_msftx and max_msfty's output names were spelled incorrectly.
Solution:
corrected the spelling in Registry.EM_COMMON
M   Registry/Registry.EM_COMMON
1. Text only - no tests necessary

corrected variable output names for max_msftx and max_msfty

---

Registry/Registry.EM_COMMON
dyn_em/solve_em.F
run/README.namelist
share/output_wrf.F
wrftladj/solve_em_ad.F
wrftladj/solve_em_tl.F

Remove namelist spec_bdy_final_mu.
KEYWORDS: lateral boundary call, spec_bdy_final, spec_bdy_final_mu
Problem:
The namelist spec_bdy_final_mu was introduced in 3.7 for an ad-hoc fix to the restart problem when spec_bdy_final calls were introduced to ensure the lateral boundary conditions do not drift by using tendencies only. The default has been to call this routine all the time, and not calling this routine does not fix any restart problem any more.
Solution:
Remove this namelist in the code, and make the code cleaner.
M       dyn_em/solve_em.F
M       share/output_wrf.F
M       wrftladj/solve_em_ad.F
M       wrftladj/solve_em_tl.F
TESTS …

Remove namelist spec_bdy_final_mu

---

share/module_check_a_mundo.F

TYPE:  Enhancement
KEYWORDS: Deng shcu, icloud_bl, check_a_mundo, 
SOURCE: Pedro A. Jimenez (NCAR)
Problem:
Deng shcu and icloud_bl are incompatible options
Solution:
Add a check in check_a_mundo to stop if the user selects these options
ISSUE: Fixes #1042
Both Real and WRF stops if shcu = 5 and icloud_bl = 1 (and run if icloud_bl = 0)
2. Are the Jenkins tests all passing? Yes.
RELEASE NOTE: Adding a test to avoid running the model if Deng shcu = 5 and icloud_bl = 1

Adding a check to avoid using shcu = 5 and icloud_bl

---

phys/module_sf_noahmpdrv.F

TYPE: bug fix
KEYWORDS: NoahMP, irrigation
SOURCE: Prasanth Valayamkunnath (NCAR)
Problem: 
Previously, when using iopt_irr=2, the user needed to turn on the crop option (=1) as well. But we want the user to be
able to use the irrigation scheme without the crop scheme activated.
Solution:
If the Noah MP dynamic irrigation scheme is triggered with opt_irr=2, then assign 2D fields of Planting and Harvesting 
dates outside of the crop scheme.
M phys/module_sf_noahmpdrv.F
1. We just ran the test by running the model on Cheyenne with and without the irrigation scheme turned on.
2. Jenkins testing is OK

Bugfix for the NoahMP dynamic irrigation scheme irrigation option (iopt_irr=2)

---

Registry/Registry.EM_COMMON

TYPE: bug fix
KEYWORDS: feedback, smoothing, Registry
A necessary and sufficient situation for feedback smoothing:
* a variable has the feedback smoothing `us` option IFF the variable is listed in HALO_EM_FEEDBACK
modified:   Registry.EM_COMMON
1. Just turning off switches in Registry. However, we do get bit-for-bit results with a restart using the smoothing
options after this fix.
2. Jenkins tests are all PASS.
RELEASE NOTE: ARW Registry cleanup, so that the feedback smoothing options match the list of associated fields in the HALO for feedback.

Add all smoothed fields to FEEDBACK HALO

---

Makefile
clean
phys/module_sf_urban.F

TYPE: bug fix
KEYWORDS: URBPARM.TBL, URBPARM_LCZ.TBL, urban, wudapt, lcz
Problem:
The new URBPARM_LCZ.TBL was not automatically linked to the test/em_real directory, meaning users would always 
get a fatal error if running with use_wudapt_lcz = 1. Additionally, the error simply stated: "ERROR OPEN URBPARM.TBL", 
which was misleading. 
Solution:
Modified the Makefile to ensure URBPARM_LCZ.TBL gets automatically copied to the test/em_real directory during 
compile. Modified phys/module_sf_urban.F to ensure the error message given correctly applied to the type of urban 
case being run (i.e., either with or without wudapt LCZ).
M     Makefile
M     clean
M     phys/module_sf_urban.F
1. Tests conclude that …

Ensure URBPARM_LCZ.TBL is linked to em_* directory & error msg correct

---

run/README.namelist

KEYWORDS: P3, namelist, README
Problem:
The description for mp_physics = 53 is not correct.
Solution:
Correct it in README.namelist
No need for Jenkins tests

Correct a namelist description for mp_physics = 53

---

dyn_em/module_initialize_real.F

TYPE: bug fix
KEYWORDS: Thompson, aerosol, emission 
SOURCE: Laura Fowler, Mary Barth, Tim Juliano (NCAR), Greg Thompson (JCSDA), internal
Problem:
In commit c54cc0a1602d995c, PR #1423 "Thompson MP: reduce fake aerosol emissions by 4x", a change was made 
to the "fake" surface aerosols for the Thompson MP scheme. This change was accidentally not included in the 
initialization step for ARW real.
Solution:
Add the same mods to the fake surface number concentration of water friendly aerosols in the ARW real program.
modified:   dyn_em/module_initialize_real.F
1. The developer proposed these mods.
2. Jenkins tests are all PASS.

Reduce sfc aerosols in Thompson MP initialization (bug fix)

---

run/README.physics_files

KEYWORDS: urban, wudapt, lcz, URBPARM_LCZ.TBL, README.physics_files, chem_opt, Henry's Law, P3
Problem:
1. Since creating README.physics_files, the new table for WUDAPT LCZ option (URBPARM_LCZ.TBL) has been 
added to the run/ directory.
2. The specific chem_opt settings for using Henry's Law have been added for HLC.TBL.
3. Update the new files for the P3 MP scheme.
Solution:
Added this newer option to the README file for physics options.
M   run/README.physics_files
1. No mods needed - text only
2. No testing needed

Update README.physics_files for new files since V4.2, and update chem_opt settings

---

Registry/Registry.EM_COMMON

TYPE: bug fix
KEYWORDS: IEVA, cfl
This is a clean-up PR to 4412521401e6f #1373 "Implicit Explicit Vertical Advection (IEVA)". We are resetting the default critical value to activate the w_damping option to the previous setting.
Problem:
The new namelist option `w_crit_cfl` replaces `w_beta`, where `w_beta` used to be set in module_model_constants.F and had a value of 1.0. Before this PR, the default value of `w_crit_cfl` was set to 1.2 in the Registry. If one didn't use the new namelist option to manually reset the value of `w_crit_cfl` to 1., that meant that w_damping would behave 
differently from previous releases.
Solution:
1. With consultation with the developer, the value for `w_crit_cfl` is now set to 1.0 in the Registry file. This gives …

Revert w_crit_cfl back to 1.0 (from temporary 1.2)

---

README.md

TYPE: bug fix
KEYWORDS: http, README
The README file incorrectly provided the WRF URL protocol as "http". It is actually "https". This presented no
troubles to users, as the web server resolved the address automatically.
modified:   README.md
1. Text only, so no external testing required.
2. README.md, so no jenkins testing done.

http -> https for README.md

---

README

KEYWORDS: README, top-level, V4.3, release
Problem:
Top-level README file needed updating for the v4.3 release:
1. Current version: v4.2.2 -> v4.3. 
2. Link to WRF home page was outdated: http -> https, which has been wrong for a long time.
3. New README files (README.CTSM, README.madwrf, README.crtm) needed to be added to list of docs in the 
top-level README file.
Solution:
Updated README file with all of the above.
M   README
1. Text only
2. Jenkins Test Passes

Updated top-level README for V4.3 release

---

Registry/Registry.EM_COMMON

Add missing var to history file for DA application
TYPE: bug fix
KEYWORDS: topo_wind option 1, data flag got_var_sso
SOURCE: reported by Y. Zhang, fixed by internal
Problem:
topo_wind option 1 requires input field var_sso (variance of the subgrid scale orography). When program real is run, a 
logical variable got_var_sso is defined upon checking whether the variance field exists or not. In the model, both 
namelist option for topo_wind as well as this internal logical are required to use this topo_wind option. If got_var_sso 
is not found when the topo_wind option is requested, the model produces an error "topo_wind requires VAR_SSO data", 
even if the field VAR_SSO field itself exists in the input. When the model history file is used in a DA cycle, missing this …

got_var_sso needs to be in history file for DA

---

Registry/Registry.EM_COMMON

TYPE: text change
KEYWORDS: units in Registry
SOURCE: internal, Tzu-Chin Tsai (NTU)
Problem:
The units for 7 new NTU microphysics variables are incorrectly specified in Registry.EM_COMMON.
Solution:
This PR corrects them.
M     Registry/Registry.EM_COMMON
1. Text change only. No effect on results
RELEASE NOTE: Units specified in Registry are corrected for several NTU microphysics variables.

Correct units for several NTU microphysics variables

---

main/depend.common

TYPE: bug fix
KEYWORDS: eclipse module, radiation driver dependency 
Problem:
The newly added module_ra_eclipse.F was not added to the dependency list of radiation driver. This sometimes causes 
compilation failures.
Solution:
Add module_ra_eclipse to radiation dependency list.
M      main/depend.common
1. It is hard to test that there are no more intermittent build failures caused by this missing dependency. :)
2. Jenkins tests are passing.
RELEASE NOTE: Adding module_ra_eclipse.o to radiation driver's dependency list to avoid occasional compilation failures.

Bug fix: Adding eclipse module to radiation driver's dependency list

---

run/URBPARM_LCZ.TBL

KEYWORDS: Local Climate Zones (LCZ), urban parameters, urban canopy models
SOURCE: Matthias Demuzere (Ruhr University Bochum), Andrea Zonato (Trento University)
Problem:
The values in the current version of the URBPARM_LCZ.TBL are specific for Zonato et al. (2020), reflecting city properties in Italy. Some of these values should be more universal.
Solution:
Changing some of the urban parameter values, to make them more generic. These universal values are based upon the following published materials:
- Stewart ID, Oke TR. Local Climate Zones for Urban Temperature Studies. Bull Am Meteorol Soc. 2012;93(12):1879-1900. doi:10.1175/BAMS-D-11-00019.1
- Stewart ID, Oke TR, Krayenhoff ES. Evaluation of the ‘local climate zone’ scheme using temperature …

default values for LCZ PARAMS

---

share/module_bc.F

TYPE: bug fix
KEYWORDS: dimension, module_bc, spec_bdytend_perturb
SOURCE: internal, Samm Elliott (TQI)
Fixed a dimension error in perturbed bc routine
Problem:
Variable field_tend_perturb in spec_bdytend_perturb and field_scalar_perturb in spec_bdytend_perturb_chem should be dimensioned by jms:jme, but jms:kme was used.
Solution:
Fix the two dimension errors.
Fixes #1524
M     share/module_bc.F
1. It would be difficult to design a test to catch this bug.
2. The Jenkins tests are ok.
RELEASE NOTE: Fixed a dimensional errors in subroutine spec_bdytend_perburb and spec_bdytend_perturb_chem in module_bc.F. This routine is used to perturb fields on the model lateral boundaries for …

Dimension fix for perturbed bc 

---

Registry/Registry.NMM

KEYWORDS: misspelling
SOURCE: Piotr Kasprzyk (IETU Katowice)
Problem:
One misspelled letter in "required" word.
Solution:
Nothing was changed except for the wrong letter.
M       Registry/Registry.NMM
1. No tests were conducted since this is text only.
2. Jenkins tests are all PASS.

NMM Registry misspelling: "required"

---

Registry/Registry.EM_COMMON
Registry/Registry.EM_COMMON.var
Registry/registry.var
phys/module_ra_cam.F

KEYWORDS: correct misspellings
SOURCE: Piotr Kasprzyk (IETU Katowice)
Problem:
The "pressure" spelling was wrong.
Solution:
Words "pressure" were corrected.
M       README
M       Registry/Registry.EM_COMMON.var
M       Registry/registry.var
M       phys/module_ra_cam.F
1. Tests were not conducted, as this is a text only change.
2. All of the jenkins tests are passing.

FIx "pressure" spelling in 4 files

---

Registry/registry.em_shared_collection

TYPE: bug fix
KEYWORDS: moving nest, vortex tracking, segfault, Intel
Problem:
When the Intel compiler is used with the moving nest option (vortex tracking), the tools/registry program seg-faults,
and does not complete building the automatically generated files that are included via cpp into the WRF source code.
Solution:
This is a quick-fix for users. Simply swap the order of the list of registry files.
Fixes #1521
M   Registry/registry.em_shared_collection
1. This mod allows the code to build successfully for intel 19.0.5
2. The code compiles with option 15/3 using Intel OneAPI:  `ifort (IFORT) 2021.1 Beta 20201112`
3. The code compiles with option 15/3 and run …

Moving nest hack

---

dyn_em/module_big_step_utilities_em.F

TYPE: bug fix
KEYWORDS: w_damp, cfl print criterion, IEVA
IEVA = Implicit Explicit Vertical Advection
Problem:
Code in w_damp subroutine was changed in 4.3 to turn on w_damping at CFL = 1.2, and print CFL when it exceeded 1.2. 
Prior to v4.3, w_damping was turned on when CFL = 1.0, and printed the message CFL message when the threshold 
value of 2.0 was exceeded. This change results many more CFL prints. We want to revert to the original behavior.
Solution:
This PR fixes the CFL warning issues by changing the threshold for notification back to what it was before 4.3. 
Importantly, this modification does not change the behavior that sets a higher CFL value to turn on w_damping when
IEVA is used. 
M …

Revert print and when to turn on damping to pre 4.3 code

---

phys/module_mp_nssl_2mom.F

TYPE: bug fix
KEYWORDS: snow radar reflectivity
SOURCE: Ted Mansell (NOAA/National Severe Storms Lab)
Fix:
Restored previous formulation of snow reflectivity (before version 4.1.3), as it was realized that the last change 
incorrectly assumed a fixed density independent of size. Generally lower snow reflectivity values as a result (no 
effect on microphysics).
Other:
1. Generic fall speed coefficients (axx,bxx) to accommodate future frozen drops category (no effect).
2. Reordered collection coefficients (dab1lh) to be consistent (no effect).
3. Switched to full calculation of rain number loss via collection by graupel (chacr) to be consistent with collection by 
hail (chlacr) (minor effects).
M phys/module_mp_nssl_2mom.F …

NSSL_2mom Snow Reflectivity Correction

---

phys/module_sf_bep_bem.F

TYPE: bug fix
KEYWORDS: BEP+BEM, longwave radiation
SOURCE: Andrea Zonato (University of Trento, Italy)
There was an error in the previous version on the calculation of long-wave radiation. The variable rl_emit now accounts for 
the emissivity by the photovoltaic panel. Moreover, the variable rld was incorrectly calculated. This will affect the calculation 
of TSK, in urban areas, that in the previous version was wrong.
M phys/module_sf_bep_bem.F
1. This error affects the calculation of TSK, which now is correctly calculated. As you can see in the figure, there is a 
large bias for the TSK of the roofs. Now it is more realistic.
2. Jenkins test are OK.
RELEASE NOTE: There was an error in the previous version on the …

Bug fix longwave rad bep bem

---

phys/module_mp_nssl_2mom.F
phys/module_mp_ntu.F
phys/module_sf_noahmplsm.F

TYPE: bug fix
KEYWORDS: HPE, CCE, syntax
SOURCE: Tricia Balle (HPE)
Problem:
There were three types of syntax errors that were uncovered by the HPE CCE compiler.
1. Open statement used `action="append"`.
2. Multiple unary operators next to each other `*+`
3. Multiple unary operators next to each other `*-1`.
Solution:
1. The correct usage is `position="append"`.
2. The developer agrees with the new modification to `GS3*+SASR1` was the original intent.
3. Typically, `*(-1)` is intended, and this is the case.
Via some grep'ing, no other occurrences of `*+` or `*-` exist in the physics directory in the compilable
source code. Syntactically OK source code with `/-` (such as for DATA statements) were the only compilable 
examples found. So, we fixed the above problems …

Syntax errors in physics routines: *- and *+

---

phys/module_fr_fire_phys.F

TYPE: bug fix
KEYWORDS: fuel moisture initialisation, net fuel load computation, WRF-Fire
SOURCE: Theodore M. Giannaros (National Observatory of Athens, Greece)
Problem:
Incorrect indexing in the initialization of fuel moisture content in subroutine `read_namelist_fire`, in WRF file `phys/module_fr_fire_phys.F`. 
Solution:
Changed `fmc_gc_initial_value(3)=fmc_1000h` to `fmc_gc_initial_value(4)=fmc_1000h` in subroutine `read_namelist_fire`, in WRF file `phys/module_fr_fire_phys.F`. 
M phys/module_fr_fire_phys.F
1. The correction applied resolved the erroneous initialization of both 1000h and 100h fuel moisture content. Prior to 
this correction, `fmc_gc_initial_value(3)=fmc_1000h` and no initialization was carried out for …

bug fix: initialization of 1000-h fuel moisture content, computation of the net fuel load

---

share/mediation_integrate.F
share/mediation_nest_move.F

KEYWORDS: correct misspellings
SOURCE: Piotr Kasprzyk (IETU Katowice)
Problem:
The "pressure" spelling was wrong.
Solution:
Words "pressure" were corrected.
M       share/mediation_integrate.F
M       share/mediation_nest_move.F
1. Tests were not conducted, as this is a text only change.
2. Jenkins tests are all passing (as expected).

Fix misspelling in comment: pressure

---

dyn_em/module_initialize_real.F

TYPE: bug fix
KEYWORDS: ERA5, smooth_cg_topo, elevation data
Problem:
If a user does not include all of the correct ERA5 invariant files, then there could be
no soil elevation field coming from the metgrid program. Without that field, the flag
`flag_soilhgt` is not set. Then the real program will not generate any topo differences along
the lateral boundary (when requested with smooth_cg_topo = T). This is a quiet failure,
and difficult to track down.
Solution:
If the user asks to smooth the lateral boundary topo on d01, AND the user has no input
soil elevation data from the first-guess model, then this is now a fatal error.
modified:   dyn_em/module_initialize_real.F
1. The original intent of the option …

smooth_cg_topo=T requires soil elevation data

---

configure

TYPE: bug fix
KEYWORDS: configure, shell, echo
Problem:
When building with NetCDF that does not support compression, the warning statements that
are printed out are misaligned, due to missing trailing quotes at the end of some `echo` statements in the
`configure` script.
Solution:
Add those quotes back in.
modified:   configure
1. The printout is now aesthetically appealing. Initially we had a mortifying display of the word `echo`, and the 
accompanying alignment disarray that would be associated with banal shell scripting encroaching upon a user's otherwise elevated build experience:
```
Please make sure NETCDF version is 4.1.3 or later and was built with         
--enable-netcdf4 …
```

configure script missing quotes in two echo statements

---

phys/module_mp_ntu.F

TYPE: bug fix
KEYWORDS: syntax, physics *+
SOURCE: Patricia Balle (HPE)
Problem:
As in hash 7c6fd575b7a8fe, PR #1577 "Syntax errors in physics routines: *- and *+", there is a single
remaining example of the unary operators next to each other.
Solution:
The author agreed that the `*+` combination was supposed to be just `+`.
I searched the WRF code for instances of this `*+` in PR #1577. When I did not find any, I put back one of them from 
NTU code to make sure that my grep was working. It found that example, and no others that I cared about. I forgot
to undo that change before the `git add`, `git commit`.
modified:   phys/module_mp_ntu.F
1. Passes Cray compiler.
2. Jenkins tests are OK

Another physics syntax error

---

var/external/crtm_2.3.0/libsrc/makefile

TYPE: bug fix (?)
KEYWORDS: WRFDA, CRTM, ftn compiler
Problem:
One of the CRTM modules does not compile with Cray Fortran : Version 12.0.3 with default or -O2 optimization.
ftn -hnoomp -c  -N1023 -f free -h byteswapio   SOI_Module.f90
```
ERROR - Trying to add using unusual type properties
op1_type :: <array[t$90] of real*8>
op2_type :: <array[t$90] of real*8>
Error message      ::  Optimization internal error
Error detected     ::  File 'pdgcs/v_expr_pls.c', line 197
Optimizer built    ::  2021-08-16 (production)
File               ::  SOI_Module.f90
Function           ::  crtm_soi_ad
at or near line    ::  656
```
Solution:
Edit CRTM makefile to compile SOI_Module.f90 with -O1 flag when ftn compiler is used.
M …

fix WRFDA CRTM Cray Fortran build

---

arch/configure.defaults

TYPE：enhancement
KEYWORDS: ARM 
Problem:
There are no ARM-only stanzas in arch/configure.defaults. As the suggestion from https://github.com/wrf-model/WRF/pull/1535 , we need a separate PR for ARM specific update.
Solution:
Edit the arch/configure.defaults file and add a stanza for aarch64 and armv7l, using the GNU compiler options. 
The default optimization is -03, up from the usual -02. On two 36-h nested simulations on a raspberry pi, the difference
is a consistent 3% speed increase. This used CONUS, so the -03 seems robust.
M arch/configure.defaults
RELEASE NOTE: Added a new stanza that is only for ARM processors (right now aarch64 and armv7l) with GNU.

Add new stanza for ARM aarch64/openmpi

---

Registry/Registry.EM_COMMON
share/module_check_a_mundo.F

TYPE: bug fix
KEYWORDS: PBL, LES
Problem:
A few PBL schemes include scalar components that are advected. These fields are
required on all domains. With an LES option on a finer domain, that grid does not
have the additional scalar component, which causes a segfault when trying to
access that field.
Solution:
Restrict what PBL schemes are eligible for use with the LES (no PBL) option.
ISSUE:
Fixes #1514
modified:   share/module_check_a_mundo.F
1. When an incompatible CG PBL and FG LES are selected, the code successfully stops.
```
&physics
bl_pbl_physics                      =  5,     0,
--- ERROR: LES PBL on fine grid does not work with CG PBL option  5
Choose a CG PBL …
```

PBL + LES restrictions

---

frame/Makefile

KEYWORDS: 255, return code, true
Problem:
When building the WRF model, one of the early steps is to use the registry program to construct
a large number of include files, and to build the Fortran file module_state_description. This is
constructing a Fortran file, not an executable. The return from that build is non-zero, and that
causes a cascading failure on every AWS build, and (at least) many of the dual OS builds.
Solution:
We cheat. We add the the `true` command after the command that builds the file
module_state_description.F. The return code from the whole process is then, voila, zero.
modified:   frame/Makefile
1. Reproducibly, the build fails due to the non-zero return code for the …

build module_state_description.F -> force zero return code

---

main/real_em.F

TYPE: [bug fix]
KEYWORDS: real.exe, MPI, bug fix
SOURCE: Marc Honnorat (EXWEXs)
Problem:
The communicator `mpi_comm_allcompute`, created by subroutine `split_communicator` called by `init_modules(1)`, 
is not explicitly activated for the call to `wrf_dm_bcast_bytes( configbuf, nbytes )` in real.exe. On some platforms, 
this may prevent broadcast of namelist configuration (put in `configbuf` after the call to `get_config_as_buffer()`) 
across the MPI processes _before_ the call to `setup_physics_suite()`.
An example of a problematic platform: a cluster of Intel Xeon E5-2650 v4 running on CentOS Linux release 7.6.1810, 
with Intel Parallel Studio XE (various versions, including 2018u3 and 2020u4) and Intel MPI Library (same version).
Solution:
The initialization step …

Fix MPI synchronization in real.exe

---

var/da/da_main/da_solve.inc
var/da/da_minimisation/da_calculate_gradj.inc
var/da/da_minimisation/da_calculate_j.inc
var/da/da_minimisation/da_minimise_cg.inc
var/da/da_minimisation/da_transform_vtod_wpec.inc
var/da/da_minimisation/da_transform_vtod_wpec_adj.inc
var/da/da_minimisation/da_transform_vtoy.inc
var/da/da_minimisation/da_transform_vtoy_adj.inc
var/da/da_setup_structures/da_setup_be_regional.inc
var/da/da_vtox_transforms/da_transform_vpatox.inc
var/da/da_vtox_transforms/da_transform_vpatox_adj.inc
var/da/da_vtox_transforms/da_transform_vptox.inc
var/da/da_vtox_transforms/da_transform_vptox_adj.inc
var/da/da_vtox_transforms/da_transform_vtox.inc
var/da/da_vtox_transforms/da_transform_vtox_adj.inc
var/da/da_vtox_transforms/da_vtox_transforms.f90

TYPE: bug fix
KEYWORDS: WRFDA, ensdim_alpha
SOURCE: Jamie Bresch and Craig Schwartz (NCAR), Yi-Chuan Lo (Central Weather Bureau, Taiwan)
The PR includes multiple bug fixes that are somewhat intertwined and related to the use of ensembles under not-usually-used scenarios.
The root cause of the various problems (reported by Craig Schwartz and Yi-Chuan Lo) is the inclusion of alpha control variable in the ill-designed `be` data structure.
The list of fixes:
1. fix minimization for precondition_cg=true (default is false) and orthonorm_gradient=true (default is false) when ensdim_alpha>0. The fix also helps with offline varbc (related to unallocated be%cv_mz when use_background_errors=false).
2. fix for 3DEns-FGAT (num_fgat_time>0 and ensdim_alpha>0 and je_factor=1.0). …

a collection of WRFDA fixes related to ensdim_alpha use cases

---

var/da/da_setup_structures/da_setup_obs_structures.inc
var/da/da_setup_structures/da_setup_obs_structures_ascii.inc
var/da/da_setup_structures/da_setup_obs_structures_bufr.inc
var/da/da_setup_structures/da_setup_structures.f90

KEYWORDS: WRFDA, memory, thin_conv
Problem:
thin_conv is true by default. When ob_format=1 (bufr for conventional ob types), thinning_grid_conv(num_ob_indexes) and its sub data arrays are allocated for all ob types as defined in da_control.f90 (obs_names(num_ob_indexes)) even though not all ob types are used.
Solution:
Do not call make3grids (which allocates several data arrays based on the setting of thin_mesh_conv) for ob types that are not used in the assimilation and not coded for thinning.
Note that gpsref horizontal thinning is not implemented for ob_format=1 (but is implemented for ob_format=2), so its thinning grid does not need to be allocated in da_setup_obs_structures_bufr.inc. That is the reason the specific …

WRFDA memory usage reduction for thin_conv=true

---

var/da/da_monitor/da_rad_diags.f90

TYPE: bug fix
KEYWORDS: WRFDA, da_rad_diags.exe, gfortran-11
Problem:
On MacOS with GNU Fortran (Homebrew GCC 11.1.0_1) 11.1.0, the stand-alone utility da_rad_diags.exe does not build.
The error messages:
```
gfortran -c -O2 -ftree-vectorize -funroll-loops -w -ffree-form -ffree-line-length-none -fconvert=big-endian -frecord-marker=4 -fallow-argument-mismatch -fallow-invalid-boz  -fdefault-real-8 -I/usr/local/include da_rad_diags.f
da_rad_diags.f:1804:28:
1804 |    namelist /record1/ nproc, instid, file_prefix, start_date, end_date, cycle_period
|                            1
Error: Symbol 'nproc' in namelist 'record1' at (1) must be declared before the namelist is declared.
da_rad_diags.f:1804:36:
1804 |    namelist /record1/ nproc, …
```

fix WRFDA stand-alone da_rad_diags.exe build with GNU Fortran 11

---

phys/module_ra_rrtmg_lwk.F

TYPE: bug fix
KEYWORDS: KIAPS, radiation, LW
Problem:
In an attempt to get the KIAPS radiation LW scheme to build with older GNU compilers,
some simplifications were introduced to remove ONLY clauses. However, an error was
introduced - a module from RRTMG was "USEd" (hash 911b8451bf7c9 introduced some
simplifications and the error, hash a83c7cb27d7f4a4 tried to fix the error in the
wrong way).
Solution:
Put the entire KIAPS radiation LW scheme back to the original pristine condition, as the
current GNU compilers have no troubles with building the scheme. And fix that bug!
1. GNU builds the original KIAPS LW radiation scheme.
2. Jenkins is all PASS.
RELEASE NOTE: An error was introduced into the KIAPS LW …

Put KIAPS rad LW back to original

---

Registry/registry.var
var/da/da_control/da_control.f90
var/da/da_obs_io/da_obs_io.f90
var/da/da_obs_io/da_read_obs_ascii.inc
var/da/da_obs_io/da_read_obs_bufr.inc
var/da/da_obs_io/da_scan_obs_ascii.inc
var/da/da_radiance/da_setup_radiance_structures.inc
var/da/da_setup_structures/da_setup_obs_structures.inc
var/da/da_setup_structures/da_setup_obs_structures_ascii.inc
var/da/da_setup_structures/da_setup_obs_structures_bufr.inc
var/da/da_setup_structures/da_setup_obs_structures_rain.inc
var/da/da_setup_structures/da_setup_structures.f90

KEYWORDS: WRFDA, thin_conv
1. add a new namelist variable thin_conv_opt(num_ob_indexes) to complement thin_conv/thin_conv_ascii switch.
When thin_conv/thin_conv_ascii is .true., thin_conv_opt can be set differently for each ob type.
thin_conv_opt is further modified inside WRFDA to account for unused ob types (a different implementation to achieve the same memory reduction purpose as previous commit https://github.com/wrf-model/WRF/pull/1604).
2. Some redundant code in several subroutines is moved to a higher-level subroutine.
Now the calculation of some lat/lon info (rlat_min,rlat_max,rlon_min,rlon_max,dlat_grid,dlon_grid) to be used for making thinning grids is done only once in da_setup_obs_structures.inc, rather …

WRFDA thin_conv code restructuring

---

share/module_check_a_mundo.F

TYPE: bug fix
KEYWORDS: PBL, LES, exists
SOURCE: Tim Juliano (NCAR)
Original: "Fix PBL + LES logic initialization" #1615
Problem:
A logical test relied on the existence of condition, but the logical was a re-used, multi-purpose
variable. Depending on the namelist settings, this flag could be .TRUE. even when failing the
logical tests.
Solution:
Initialize the variable to .FALSE. before running through the existence test.
modified:   share/module_check_a_mundo.F
1. With this modification, the testing is as it should be.
RELEASE NOTE: The v4.3.2 release contained an error in the commit that addressed the situation of segmentation faults when running a PBL on a coarse grid and no PBL on the …

Fix PBL + LES logic initialization - redux

---

chem/dry_dep_driver.F

TYPE: bug fix
KEYWORDS: chem, vertical mixing, exchange, enhancement, wildfires
Original: "Turn off vertical mixing enhancement at layer kts, where should be == 0" #1615
Problem:
In dry_dep_driver, vertical mixing exchange coefficients are artificially enhanced over 'urban' and wildfire grid cells (determined by emissions) from kts->kte/2, however, the mixing should be ==0 at layer kts.
Solution:
This fix adds a "+1" so that the enhancement does not impact the surface
M       chem/dry_dep_driver.F
1. All regression tests pass.
RELEASE NOTE: Fixed indexing bug that incorrectly enhanced vertical mixing at the surface layer in the WRF Chem dry_dep_driver.F file.

Turn off vertical mixing enhancement at layer kts, where should be == 0 - redux

---

Registry/registry.chem

KEYWORDS: photolysis rate, no2, o3_o1d
Original: "Output photolysis rates for NO2 and O1D to history stream by default" #1623
Output photolysis rates for NO2 and O1D to history stream by default
Adds Jno2 and JO1D to history stream by default
M       Registry/registry.chem
1. Just including additional fields with the "h" option.
2. Jenkins tests all all passing.
RELEASE NOTE: Output photolysis rates for NO2 and O1D to history stream by default

Output photolysis rates for NO2 and O1D to history stream by default - redux

---

Registry/registry.chem
chem/aerosol_driver.F
chem/module_aerosols_soa_vbs.F

KEYWORDS: ISORROPIA, RACM-MADE/SOA_VBS
Original: "Control use of ISORROPIA 2.1 in chem_opts = 100,108,109 by namelist" #1624
Control use of ISORROPIA 2.1 in chem_opts = 100,108,109 by namelist ISORROPIA in chem_opts 100, 108, 109 
is now controlled by logical namelist option `do_isorropia`. It is turned off by default (i.e., 
`do_isorropia = .false.`)
Problem: 
Some users have noted issues with ISORROPIA when using the SOA_VBS aerosol schemes due to some 
missing crustal/Cl species. Work is underway to create separate module, but this fix allows the user to control 
the option without recompiling.
Solution:
Added as namelist option, in future will have separate modules for the different chem_opts in addition to 
the namelist …

Control use of ISORROPIA 2.1 in chem_opts = 100,108,109 by namelist- redux

---

Registry/Registry.EM_COMMON.var

TYPE: bug fix
KEYWORDS: WRFDA, IO_NETCDFPAR
Problem:
WRFDA does not build after commit e0186240.
Registry.EM_COMMON was modified in commit e0186240, but WRFDA uses Registry.EM_COMMON.var.
Solution:
Add io_netcdfpar to Registry.EM_COMMON.var
M       Registry/Registry.EM_COMMON.var
1. WRFDA builds after the fix
2. Jenkins is all pass (for real).

fix WRFDA build for Parallel netcdf-4 IO

---

var/da/da_varbc_tamdar/da_varbc_tamdar_tl.inc
var/da/da_varbc_tamdar/da_varbc_tamdar_update.inc

Bug fix for TAMDAR T variational bias correction
TYPE: bug fix
KEYWORDS: TAMDAR, VarBC
SOURCE: Yi-Chuan Lo (Taiwan Central Weather Bureau), Feng Gao (WeatherFlow Inc.)
Problem:
Yi-Chuan Lo at CWB found inconsistency between TAMDAR and Radiance VarBC code.
Solution:
Feng Gao confirmed there is a bug in TAMDAR VarBC code and provided bug fix.
M   var/da/da_varbc_tamdar/da_varbc_tamdar_tl.inc
M   var/da/da_varbc_tamdar/da_varbc_tamdar_update.inc
1. WRFDA regression tests passed.
RELEASE NOTE: Bug fix for TAMDAR T VarBC.

Bug fix for TAMDAR T VarBC

---

var/da/da_radar/da_get_innov_vector_radar.inc
var/da/da_radar/da_radzicevar.inc
var/da/da_radar/da_radzicevar_upper_f.inc
var/da/da_radar/da_transform_xtoy_radar.inc
var/da/da_radar/da_transform_xtoy_radar_adj.inc
var/da/da_setup_structures/da_setup_obs_structures_radar.inc
var/da/da_setup_structures/da_setup_structures.f90

Bug fix for direct assimilation of radar reflectivity (radar_rf_opt=2)
TYPE: bug fix
KEYWORDS: reflectivity operator, quality control 
SOURCE: Zhiquan (Jake) Liu (NCAR/MMM)
Problem:
The namelist parameter "qthres", which is used for hydrometeor base state of TL/AD for no-rain background, should not be used in reflectivity forward operator. QC for radar_rf_opt=2 should not be confused with that of retrieval radar DA.
Solution:
1. Remove the use of "qthres" in forward operator.
3. Simplify QC to keep obs with both observed and background reflectivity >=rfmin (a namelist parameter).
M       var/da/da_radar/da_get_innov_vector_radar.inc
M       var/da/da_radar/da_radzicevar.inc
M       var/da/da_radar/da_radzicevar_upper_f.inc
M …

Bug fix for radar_rf_opt=2

---

arch/configure.defaults

TYPE: bug fix
KEYWORDS: Intel, ifort, HWS, BDW, bug
SOURCE: GitHub user jw500
Problem: When a user chooses one of the following configuration options for the Intel (HWS/BDW) compiler,
`64. (serial)  65. (smpar)  66. (dmpar)  67. (dm+sm)   INTEL (ifort/icc): HSW/BDW`
they will instead be given a configuration for the corresponding option for basic Intel.
`13. (serial)  14. (smpar)  15. (dmpar)  16. (dm+sm)   INTEL (ifort/icc)`
The configure.wrf file will read
```
DESCRIPTION     =       INTEL ($SFC/$SCC)
```
This is the result of "Add missing compiler name for two Intel config stanzas" #1326, hash [commit 0a9c2eb](https://github.com/wrf-model/WRF/commit/0a9c2eb2dc8d81246dd6a4f2d739396c84043fef)
Solution:
Modified configure.defaults to ensure the "#ARCH" lines were …

Fix for Intel: HSW/BDW config option

---

Makefile
Registry/Registry.EM_COMMON
clean
dyn_em/module_first_rk_step_part1.F
dyn_em/start_em.F
main/depend.common
phys/module_physics_init.F
phys/module_ra_cam.F
phys/module_ra_cam_support.F
phys/module_ra_clWRF_support.F
phys/module_ra_rrtm.F
phys/module_ra_rrtmg_lw.F
phys/module_ra_rrtmg_lwf.F
phys/module_ra_rrtmg_sw.F
phys/module_ra_rrtmg_swf.F
phys/module_ra_sw.F
phys/module_radiation_driver.F
run/README.namelist
share/module_check_a_mundo.F
share/output_wrf.F

KEYWORDS: GHG, run-time, radiation, green house gas
This PR improves the way to handle green house gases in radiation schemes (CAM, RRTMG, RRTMGF, RRTM). Previously green house gases (GHGs) were either specified to be constant values or read from historical gas concentration datasets (CAMtr). Note that the latter only worked when the WRF code was compiled with the macro flag `-DCLWRFGHG`. This PR modifies the radiation schemes so that input of GHG concentration from CAMtr becomes a run-time option. The old approach of specifying a time invariant value for the GHG concentrations remains available for backward consistency. 
This PR is a reworking of "Run-time option of GHG concentration from various climate RCPs" #1611.
ISSUE: CLWRF …

Run-time option for climate GHG for radiation

---

dyn_em/module_first_rk_step_part1.F
phys/module_sf_noahdrv.F
phys/module_surface_driver.F

TYPE: bug fix
KEYWORDS: noah mosaic, wudapt
SOURCE: Do Ngoc Khanh (Tokyo Institute of Technology)
Fix runtime error when using sf_surface_mosaic = 1 with use_wudapt_lcz = 0.
Problem:
Segmentation fault occurs when running the model using sf_surface_mosaic = 1 with use_wudapt_lcz = 0 as described in detail in #1633. 
Solution:
The code now checks for use_wudapt_lcz and uses different code to define urban categories in lsm_mosaic routine in module_sf_noahdrv.F.
ISSUE: 
Fixes #1633 
M       phys/module_sf_noahdrv.F
1. When use_wudapt_lcz = 1: bit-by-bit identical output before and after modification.
2. When use_wudapt_lcz = 0: Segmentation fault …

Fix runtime error when using sf_surface_mosaic = 1 with use_wudapt_lcz = 0

---

Registry/registry.chem
chem/chem_driver.F
chem/module_phot_tuv.F
chem/photolysis_driver.F
share/module_check_a_mundo.F

KEYWORDS: MYNN PBL, subgrid clouds, boundary layer clouds, photolysis, TUV
SOURCE: internal 
Adds capability to include sub-grid boundary layer clouds from the MYNN PBL schemes to photolysis option 4 (new TUV)
This update allows subgrid boundary layer clouds from the MYNN PBL scheme to be accounted for in photolysis using `phot_opt =4`. This feature is activated by setting the &chem namelist option `phot_blcld = .true.` The setting `icloud_bl = 1` must also be set.
M       Registry/registry.chem
M       chem/chem_driver.F
M       chem/module_phot_tuv.F
M       chem/photolysis_driver.F
1. Jenkins tests are all passing.
RELEASE NOTE: Add MYNN PBL clouds to WRF Chem …

MYNN PBL clouds in photolysis option 4 (TUV)

---

Registry/Registry.EM_COMMON
Registry/registry.fire
dyn_em/depend.dyn_em
dyn_em/solve_em.F
dyn_em/start_em.F
main/depend.common
phys/Makefile
phys/module_firebrand_spotting.F
phys/module_firebrand_spotting_mpi.F

KEYWORDS: fire firebrand spotting Lagrangian transport passive advection burnout 
SOURCE: Maria Frediani, Tim W. Juliano (NCAR-RAL)
The new module firebrand_spotting for WRF-Fire is a passive Lagrangian transport parameterization to 
advect firebrands. The Firebrand Spotting parameterization was developed for the WRF-Fire component of the 
WRF model versions starting at 4.0.1. The parameterization couples to WRF-Fire and uses a Lagrangian 
particle transport framework to advect firebrands in the innermost nest of the domain. 
The parameterization runs in the atmospheric model inner domain and does not modify model variables (no 
feedback to WRF or WRF-Fire). The code comprises two independent modules, one with the physical 
processes and another …

New module firebrand_spotting for WRF-Fire

---

Registry/Registry.EM_COMMON
dyn_em/module_first_rk_step_part1.F
dyn_em/module_initialize_real.F
dyn_em/nest_init_utils.F
dyn_em/start_em.F
phys/module_physics_init.F
phys/module_sf_sfclayrev.F
phys/module_surface_driver.F
run/README.namelist
share/module_check_a_mundo.F
share/module_optional_input.F
test/em_real/examples.namelist

KEYWORDS: shallow water, roughness, bathymetry
SOURCE: Patrick Hawbecker, Pedro A. Jiménez, and Jimy Dudhia (NCAR)
This incorporates the shallow water drag module into the revised M-O surface layer scheme for over-water roughness calculation.
The new scheme is meant to incorporate the effects of roughness increasing over shallower waters (between 10 
and 100 m deep), mostly near coastlines. In order to include the shallow water roughness parameterization 
from Jiménez and Dudhia (2018) into the revised M-O surface layer scheme, a bathymetry dataset was 
downloaded and converted to the WPS tiled format, new variables and flags for the bathymetry data and 
which scheme is to be used over the ocean are added, and the source code is included into a …

SFCLAY=1, add shallow water roughness calculation

---

Registry/registry.chem
chem/module_emissions_anthropogenics.F

KEYWORDS: anthropogenic emissions
SOURCE: Rebecca Schwantes (CIRES/NOAA CSL)
Update code to add HONO, TERP, and CO2 anthropogenic emissions for RACM mechanisms.
Problem:
HONO, TERP, and CO2 anthropogenic emissions were not automatically pulled into the RACM mechanisms.
Solution:
Added some if statements such that if HONO, TERP, and CO2 are in the anthropogenic emission file and hono, 
api, lim, and co2 are chemical species in the selected RACM mechanism, then the HONO, TERP, and CO2 
anthropogenic emissions would be included in the simulation.
M Registry/registry.chem
M chem/module_emissions_anthropogenics.F
1. The modifications fix the problem of missing (but available) anthropogenic emissions.
2. …

Update HONO, TERP, and CO2 emissions

---

phys/module_mp_thompson.F
phys/module_ra_rrtmg_lw.F
phys/module_ra_rrtmg_lwf.F
phys/module_ra_rrtmg_sw.F
phys/module_ra_rrtmg_swf.F
phys/module_radiation_driver.F

KEYWORDS: microphysics, clouds, cloud fraction, Thompson microphysics
SOURCE:  Greg Thompson (UCAR/Joint Center for Satellite Data Assimilation)
The purpose of these changes is to produce better cloud coverage and radiation amounts per tuning done with 
GFS global model and comparisons to observations.
Problem:
The Thompson-MP code (from ccpp-physics) has been used within UFS/GFS/FV-3 global model for multiple 
day simulations.  Anning Cheng and Ruiyu Sun (NCEP/EMC) have performed most of the simulations and 
analysis and iterated with me to make adjustments to the Thompson-MP.  At first, EMC found that high 
clouds were not present enough, particularly in the tropics.  Once switching to a larger upper limit of cloud 
ice before it becomes snow, …

After testing with UFS/GFS/FV-3, some tuning knob changes to Thompson-MP and icloud3 (cloud fraction) scheme

---

var/build/da_name_space.pl

TYPE: bug fix
KEYWORDS: WRFDA, 4DVAR, compile
Following commit 8b5bfe593, PR #1616, a new subroutine name (med_read_qna_emissions) needs to be 
added in da_name_space.pl to avoid name conflict for 4DVAR build with the error message:
```
duplicate symbol '_med_read_qna_emissions_' in:
/Users/hclin/code/WRFPLUS/develop/main/libwrflib.a(mediation_integrate.o)
./libwrfvar.a(mediation_integrate.o)
ld: 1 duplicate symbol for architecture x86_64
collect2: error: ld returned 1 exit status
```
M var/build/da_name_space.pl
1. 4DVAR builds after the fix.
2. Jenkins tests now pass again.

Fix 4dvar build failure after commit 8b5bfe59

---

Makefile
arch/Config.pl
arch/configure.defaults
configure

TYPE: bug fix
KEYWORDS: netcdfpar, Error
Problem:
With PR #1552 "Parallel netcdf-4 IO option" (SHA1 3cd4713), when then code was built without
the new parallel NetCDF4 compression, the build log had an `Error`. 
```
> grep Error compile.log
Fatal Error: Cannot open module file ‘wrf_data_ncpar.mod’ for reading at (1): No such file or directory
make[2]: [diffwrf] Error 1 (ignored)
make[2]: [diffwrf] Error 1 (ignored)
wrf_io.f:117: Error: Can't open included file 'mpif.h'
make[2]: [wrf_io.o] Error 1 (ignored)
Fatal Error: Cannot open module file ‘wrf_data_ncpar.mod’ for reading at (1): No such file or directory
make[2]: [field_routines.o] Error 1 (ignored)
make[2]: [libwrfio_nfpar.a] Error 127 (ignored)
make[2]: [libwrfio_nfpar.a] Error 1 (ignored) …
```

BF: NETCDFPAR "Error" in build log when option not used

---

phys/module_microphysics_driver.F

TYPE: bug fix
KEYWORDS: EPS, DA
Problem:
The WRF-Solar EPS mods (PR #1547, SHA1 fed10f4ba9) modified the solve_em.F file, with
arguments to the microphysics driver. The solver_em.F file is one of the special files
that has a _ad and a _tl version. Any changes to solve_em.F need to be reflected in the
other two DA-related files.
Solution:
In this case, since only Thompson MP uses the EPS fields, the new args were made optional in
the MP driver.
M phys/module_microphysics_driver.F
1. Yes, code compiles and passes regtests.

BF: WRF-Solar EPS broke DA build

---

phys/module_firebrand_spotting.F

TYPE: bug fix
KEYWORDS: firebrand, PGI, isnan
Problem:
The WRF code does not compile with PGI due to the use of nonstandard ISNAN() intrinsic
function calls (well, really _assumed_ intrinsic if it does not exist).
Solution:
These calls are replaced by the IEEE standard intrinsic function ieee_is_nan(). This intrinsic became available 
with Fortran 2003.
M phys/module_firebrand_spotting.F
1. The code builds with PGI.

In firebrand, replace ISNAN() with IEEE_IS_NAN()

---

phys/module_firebrand_spotting.F

TYPE: bug fix
KEYWORDS: firebrand, Cray, HPE, cat
SOURCE: Patricia Balle (HPE), internal
Problem:
The line
```
get_fuel_cat = ksb(cat)
```
should have an integer as the index to the `ksb` array.
Solution:
At the top of the function is the line
```
icat = INT(cat)
```
which is supposed to be used as the argument.
modified:   phys/module_firebrand_spotting.F
1. The fix allows the HPE CCE compilation to proceed.
2. All jenkins tests are PASS.

BF firebrand array index must be integer

---

dyn_em/solve_em.F

TYPE: bug fix
KEYWORDS: unary operator, Noahmp
Problem:
Found more occurrences of `a* -b` in Noahmp. A space is in between `*` and `-1`. OK even for Cray, but it is still non-standard.
Solution:
The same solution is applied: add parentheses: `a * (-b)`.
ASSOCIATED REPOSITORY CHANGE:
NCAR/noahmp#33
modified: phys/noahmp
1. More code is fixed.

Update Noahmp for unary operation bug fix #2

---

run/CAMtr_volume_mixing_ratio

TYPE: bug fix
KEYWORDS: CAMtr_volume_mixing_ratio, missing link
SOURCE: reported by Pedro Jimenez, internal
Problem:
The newly required file for several radiation options is not linked in the run directory. The source file is there, but it needs to be linked to a specific name used by the code.
Solution:
Create a linked file in the run/ directory for CAMtr_volume_mixing_ratio.
A       run/CAMtr_volume_mixing_ratio
1. The Jenkins tests are all passing

Add link to CAMtr_volume_mixing_ratio.SSP245 in run directory

---

phys/module_sf_noahdrv.F
phys/module_surface_driver.F

Fix a memory problem in Noah LSM after PR#[1641](https://github.com/wrf-model/WRF/pull/1641) 
TYPE: bug fix
KEYWORDS: memory issue, Noah LSM, WRF-Hydro
Problem:
After PR#1641 merge, which consisted modification and additions to NoahMP, problems showed up in the model when Noah LSM is used. Errors include random failures when running with a relatively large domain (581x501x56 in one test) and nests, and when model is trying to write output.
Solution:
Using 'configure -D' with gfortran identified the failure in module_sf_noahdrv.F. Examination of the routine suggests the code related to WRF-Hydro implementation could be an issue when WRF-Hydro is not used. Revision is made to the driver so that variables related to WRF-Hydro are properly defined when …

Fix a invalid memory reference error identified by gfortran

---

phys/module_mp_nssl_2mom.F

TYPE: no impact (compiler warning)
SOURCE: CWB, Taiwan, Fujitsu compiler
Fixes a few compiler warnings of uninitialized variables. The changes have no impact since the uses were either in print statements or conditionals that would not be affected by the value.
phys/module_mp_nssl_2mom.F
Recompiled and checked em_quarter_ss result
Jenkins tests all pass.

Fix for uninitialized variables in NSSL microphysics

---

var/da/da_chem_sfc/da_get_innov_vector_chem_sfc.inc
var/da/da_obs_io/da_read_obs_chem_sfc.inc
var/da/da_obs_io/da_read_omb_tmp.inc

Fixed bugs for the case where PM10 was treated as residuals (=PM10-PM2.5) when assimilated with PM2.5.
TYPE: Bug fix
KEYWORDS: WRFDA, PM10, chemicda_opt, WRF-Chem assimilation
SOURCE: Soyoung Ha (MMM/NCAR)
When assimilated with pm2.5 (e.g., chemicda_opt = 3 or 5) using chem_opt=108, pm10 is treated as (pm10 - pm2.5) residuals in both observations and priors. PM10 obs errors are also adjusted for such residuals.
var/da/da_chem_sfc/da_get_innov_vector_chem_sfc.inc
var/da/da_obs_io/da_read_obs_chem_sfc.inc
TEST CONDUCTED:
WRF-Chem/WRFDA was built with gfortran (e.g., configure option 34) on cheyenne. 
The updated codes passed the cycling tests using chem_opt = 108 and chemicda_opt = 5, resolving the issue of overestimation in surface PM10 …

Bug fixes for pm10 assimilation with chem_opt=108

---

phys/module_ra_sw.F

TYPE: bug fix
KEYWORDS: shortwave option 1, coszen not optional
Problem:
Compiler picked up use of uninitialized eot. This was in the case of no coszen passed in which does not happen in ARW.
Solution:
coszen is no longer optional and branch for no coszen input is removed.
ISSUE: none
M       phys/module_ra_sw.F
1. Only compile test
RELEASE NOTE:

coszen made not optional in Dudhia swrad

---

phys/module_surface_driver.F

TYPE: bug-fix
KEYWORDS: surface driver, uninitialized variables
Problem:
Several variables showed up as used while uninitialized
Solution:
PXLSM does not need to compute sea-ice weighted PBLH
sfclay,sfclayrev FH and FM need to be initialized for use in sea-ice weighting
ISSUE: none
1. compile test only - OK
RELEASE NOTE:

resolve uninitialized variable issues in surface_driver

---

phys/module_sf_urban.F

TYPE: bug fix
KEYWORDS: urban model WDR undefined before use
SOURCE: internal 
Problem:
WDR was used before being defined in urban model. This is a wind direction used in computing the urban roughness length for local surface flux calculations.
Another problem was that logic for some directions was wrong in selecting the correct one of 4 frontal area directions.
Solution:
Uncomment WDR calculation (assumes grid is roughly y direction northwards).
Correct direction if-tests.
ISSUE: None
M       phys/module_sf_urban.F
1. Compile only - recommend test for effect
RELEASE NOTE: minor fix for urban wind directions when using detailed urban morphology maps

Urban model: fix undefined WDR and direction logic

---

phys/module_bl_shinhong.F

TYPE: bug fix
KEYWORDS: Shin-Hong PBL divide by zero
SOURCE: internal, reported by CWB, Taiwan
Problem:
Rare case of divide by zero.
Solution:
Avoided by use of if test. Note that an algorithm fix may be needed later.
M       phys/module_bl_shinhong.F
1. compile only (should fix problem)
RELEASE NOTE: minor bug-fix in Shin-Hong PBL to avoid rare divide by zero

Shin-Hong PBL fix for divide-by-zero problem

---

phys/module_sf_noahdrv.F

Bug fix for emissivity variable of urban code in Noah driver
TYPE: bug fix
KEYWORDS: Noah, urban, emissivity
SOURCE: Cenlin He (NCAR)
Problem:
The rural area emissivity variable is not initialized in module_sf_noahdrv.F before it is used. See Issue #1676 for details.
Solution:
Replace the un-initialized emissivity variable by the correct rural emissivity variable.
ISSUE: #1676
M       phys/module_sf_noahdrv.F
1. The proposed modification fixes the problem.

Bug fix for emissivity in Noah urban code

---

chem/KPP/mechanisms/mozart_mosaic_4bin/mozart_mosaic_4bin.tuv.jmap
chem/KPP/mechanisms/mozart_mosaic_4bin_aq/mozart_mosaic_4bin_aq.tuv.jmap
chem/KPP/mechanisms/mozcart/mozcart.tuv.jmap
chem/KPP/mechanisms/t1_mozcart/t1_mozcart.tuv.jmap

Add second no3 photolysis channel to TUV
TYPE: 
KEYWORDS: TUV, photolysis, NO3, channel, mozart
SOURCE: Alma Hodzic (NCAR)
Problem: missing second no3 phot channel
Solution:
Add second (b) channel
M       chem/KPP/mechanisms/mozart_mosaic_4bin/mozart_mosaic_4bin.tuv.jmap
M       chem/KPP/mechanisms/mozart_mosaic_4bin_aq/mozart_mosaic_4bin_aq.tuv.jmap
M       chem/KPP/mechanisms/mozcart/mozcart.tuv.jmap
M       chem/KPP/mechanisms/t1_mozcart/t1_mozcart.tuv.jmap
1. Jenkins tests all passing?
RELEASE NOTE: adds missing second photolysis channel for NO3 in TUV

Add second no3 photolysis channel to TUV

---

dyn_em/module_initialize_fire.F

Add custom eta_levels capability in idealized WRF-Fire initialization.
KEYWORDS: idealized, WRF-Fire
SOURCE: Masih Eghdami (NCAR)
When using idealized to set up the domain, the eta_levels are ignored for em_fire test. Now if specified, they will be prioritized for calculating the eta levels (znw) in the model.
Solution:
Part of the code for calculating the model levels from module_initialize_ideal.F (Lines 655-706) is copied to module_initialize_fire.F
module_initialize_fire.F
1. Do mods fix problem? Yes, I checked the wrfinput_d01 after running the ideal.exe and the ph+phb levels look as expected.
RELEASE NOTE: The idealized.exe for fire runs previously does not …

adding custom eta levels to idealized fire runs

---

Makefile

TYPE: no impact, text only
KEYWORDS: print, submodule status
Problem:
Currently when we compile, this section of the submodule status check from top-level Makefile always appears in the log file, which can be confusing to users:
if [ \( ! -f run/MPTABLE.TBL \) -o \
\( ! -f phys/module_sf_noahmpdrv.F \) -o \
\( ! -f phys/module_sf_noahmp_glacier.F \) -o \
\( ! -f phys/module_sf_noahmp_groundwater.F \) -o \
\( ! -f phys/module_sf_noahmplsm.F \) ] ; then \
echo " " ; \
echo "------------------------------------------------------------------------------" ; \
echo "Error Error Error NoahMP submodule files not populating WRF directories" ; \
echo "------------------------------------------------------------------------------" ; \
echo " " ; \
exit 31 ; \ …

Make the print for submodule conditionally appearing in log file

---

main/depend.common
phys/module_cu_gf_ctrans.F

Initialize Henry's Law Constants in phys when using MOZART and convective wet scavenging with GF
TYPE: Bug fix
KEYWORDS: MOZART, GF cumulus (3), conv_tr_wetscav
SOURCE: Dale Allen (UMD)
Problem: https://forum.mmm.ucar.edu/phpBB3/viewtopic.php?f=91&t=11275
This fixes a bug introduced with PR #1354. When a MOZART chemistry option is used in conjuction with cu_physics = 3 and conv_tr_wetscav = 1, the Henry's Law Constants intialized in the chemistry directory are not available to the physics code resulting in a memory mapping error when attemtping to index the allocatable array. This commit adds an additional subroutine in module_cu_gf_ctrans.F that is identical to the intitialzation routine in module_ctrans_grell.F, which is the parameterized convective transport …

Init Henry's Law Constants for MOZART & convective wet scavenging with GF

---

var/da/da_obs_io/da_final_write_obs_gas_sfc.inc
var/da/da_obs_io/da_read_omb_tmp.inc
var/da/da_obs_io/da_write_obs_chem_sfc.inc

TYPE: bug fix
KEYWORDS: Chem DA, OMB/OMA
SOURCE: Jake Liu (NCAR/MMM)
Problem:
PR #1575 breaks ChemDA's omb/oma output.
Solution:
Make write/read omb/oma format consistent
M       var/da/da_obs_io/da_final_write_obs_gas_sfc.inc
M       var/da/da_obs_io/da_read_omb_tmp.inc
M.      var/da/da_obs_io/da_write_obs_chem_sfc.inc
Tested mosaic scheme with chemicda_opt = 1,2,3,4, or 5.
RELEASE NOTE: None.

Bug fix for chem DA omb/oma output

---

phys/module_sf_noahdrv.F

Bug fix for the LWDN and SOLNET input variables for urban simulation in Noah LSM driver
TYPE: bug fix
KEYWORDS: Noah, urban, LWDN, SOLNET
SOURCE: Cenlin He (NCAR)
Problem:
The variables SOLNET and LWDN in module_sf_noahdrv.F, that are, respectively, the net shortwave radiation and the absorbed longwave radiation, are computed by using the whole-grid albedo and emissivity from last time step. However, these two variables (LWDN and SOLNET) are the input forcing variables for non-urban fraction of the grid in SFLX subroutine calculations. So to be consistent, LWDN and SOLNET should be computed based on non-urban (instead of whole-grid) albedo and emissivity for the use in SFLX.
Solution:
add the following two lines to re-calculate using non-urban albedo and …

bug fix for Noah urban driver for longwave & shorwave input variables

---

phys/module_sf_sfcdiags_ruclsm.F

TYPE: bug fix
KEYWORDS: 2-m temperature and moisture diagnostics
SOURCE:  Tanya Smirnova, NOAA/ESRL/GSL
Change the default diagnostic method for 2 m temperature and mixing ratio to the flux method, which is used in the operational RAPv5/HRRRv4. This change makes the method the same as the WRF code used in operational models at NCEP.
module_sf_sfcdiags_ruclsm.F
1. Do mods fix problem? Yes.
RELEASE NOTE: The default method to diagnose 2 m temperature and mixing ratio is changed to the flux method in RUC LSM, the same as used in NCEP operational RAPv5/HRRRv4.

Use FLUX method as default for 2-m diagnostics with RUC LSM.

---

Registry/Registry.EM_COMMON
Registry/registry.new3d_wif

Reduce memory used by the model from two previous PRs
TYPE: bug fix
KEYWORDS: qnbca, wif_input_opt, package
Problem:
PR1567 changed default wif_input_opt from 0 to 1, which increased memory use by about 12%. PR1616 added new variable qnbca, but it is not packaged.
Solution:
Change default wif_input_opt option back to 0, and add qnbca to package for mp_physics=28 and its dfi counterpart. Testing the latest release 4.4 code shows a memory reduction (when mp_physics=28 is not used) is down by 11%.
M    Registry/Registry.EM_COMMON
M    Registry/registry.new3d_wif
1. Do mods fix problem? The fix reduces memory use in the model.
RELEASE NOTE:

Reduce memory increase from PRs 1567 and 1616

---

var/da/da_chem_sfc/da_get_innov_vector_chem_sfc.inc
var/da/da_chem_sfc/da_print_stats_chem_sfc.inc
var/da/da_obs_io/da_read_obs_chem_sfc.inc
var/da/da_obs_io/da_scan_obs_chem_sfc.inc

TYPE: bug fix
KEYWORDS: ChemDA for gas species with different units
SOURCE: Soyoung Ha (MMM/NCAR)
Problem:
As pointed out in PR #1724, there were inconsistent data units for gas species depending on test data (meaning chem_cv_options). Thus, the codes related to observations should be treated differently: Data QC based on innovations (o-b) and observation error specification cannot be uniformly applied to all chem_cv_options.
Also, the final output ("statistics_chem") showed wrong units for all six chem species.
Solution:
Data units are clarified in the codes related to observations.
Threshold values for omb are set differently for different chem_cv_options, so are the obs errors for gas species. …

V4.4 bugfix gas omb

---

chem/depend.chem

Add necessary dependency for gocart dust emissions from mosaic
TYPE: bug fix
KEYWORDS:gocart, mosaic_addemiss, dependency
Problem: Would not compile, missing dependency
Solution:
added module_gocart_dust to depend.chem for module_mosaic_addemiss
ISSUE: https://forum.mmm.ucar.edu/phpBB3/viewtopic.php?f=83&t=11458&p=25494#p25494
M    chem/depend.com
RELEASE NOTE: add missing dependency

Add gocart_dust dependency to mosaic_addemiss, necessary for source_du

---

share/module_check_a_mundo.F

TYPE: bug fix, text only
KEYWORDS: full spectral bin microphysics, disable its use
SOURCE: J. Shpund, PNNL
Problem:
The full spectral bin microphysics (mp_physics = 32) appears to be out of date, and it has significantly degraded performance.
Solution:
The contributors hence recommended not to use the full SBM for the time being. Use the fast version instead (mp_physics=30). A stop is added if the model detects the use of the full SBM.
M     share/module_check_a_mundo.F
1. The model will stop if mp_physics is set to 32
RELEASE NOTE: It is recommended not to use the full spectral bin microphysics until it is updated. Use the fast version instead.

Stop users from using full SBM for the time being

---

dyn_em/module_stoch.F

Remove a duplicate 'use module_dm' in module_stoch.F, preventing compilation with older versions of the intel compiler
TYPE: bug fix
KEYWORDS: compilation, intel, module_stoch
SOURCE: Louis Marelle (LATMOS, CNRS; Paris, France)
Problem: When compiling with ifort+dmpar (15), or ifort+serial(13) with an older version (12.1.3) of the intel compiler, the compilation of WRF4.4 fails in module_stoch.f90, giving the following error message:
> module_stoch.f90(117): error #7837: Two or more accessible entities, other than generic interfaces, may have the same name only if the name is not used to refer to an entity in the scoping unit. [WRF_DM_MAXVAL]
> wrf_dm_maxval, wrf_err_message, local_communicator_x, local_communicator_y, data_order_xzy
> --------------------------^
> …

Remove duplicate use module_dm in module_stoch prevenging compilation with intel

---

run/VEGPARM.TBL

WRFv4.4 crashes upon LSM initialization when NLCD40 landuse dataset is used because of the VEGPARM tables settings.
TYPE: bug fix
KEYWORDS: VEGPARM.TBL, NLCD40, LCZ_1, NUDAP
SOURCE: Robert Gilliam, US EPA
Problem:
WRFv4.4 crashes when reading the VEGPARM.TBL file because of the the LCZ_* specs at the end of the main NLCD40 table entries.
Solution:
We just copied the values used for MODIS since the NLCD40 is a blend of US NLCD and MODIS.
Fixes https://github.com/wrf-model/WRF/pull/123
LIST OF MODIFIED FILES: VEGPARM.TBL
Does the mode fix the problem: Yes. We ran a full 2018 simulation at 12 km CONUS and 108 km N. Hemisphere scales and verified this works.
The Jenkins tests have passed.
RELEASE NOTE: …

VEGPARM.TBL update for NLCD40 Landuse crash

---

phys/module_ra_clWRF_support.F

TYPE: bug fix
KEYWORDS: Compiler issue, CRAY CCE 
SOURCE: Jatin Kala (J.Kala@murdoch.edu.au)
Problem:
The Cray CCE compile returns -4001 (rather than -1) when it's finished reading the CAMtr file in module_ra_clWRF_support.F, however the code in 4.4 only checks for -1, which causes WRF to abort when one is using Cray CCE Fortran compiler. 
Solution:
modfify module_ra_clWRF_support.F to check for for -1 and -4001, before aborting.
Fixes #1741
phys/module_ra_clWRF_support.F
Yes, compiled, re-ran, and issue is fixed.
2. …

Fix bug in module_ra_clWRF_support.F with Cray CCE Fortran compiler

---

phys/module_ra_clWRF_support.F

TYPE: bug fix
KEYWORDS: Compiler issue, CRAY CCE
SOURCE: Jatin Kala ([J.Kala@murdoch.edu.au](mailto:J.Kala@murdoch.edu.au))
Problem:
The Cray CCE compile returns -4001 (rather than -1) when it's finished reading the CAMtr file in module_ra_clWRF_support.F, however the code in 4.4 only checks for -1, which causes WRF to abort when one is using Cray CCE Fortran compiler.
Solution:
modfify module_ra_clWRF_support.F to check for for -1 and -4001, before aborting.
Fixes https://github.com/wrf-model/WRF/issues/1741
LIST OF MODIFIED FILES: list of changed files (use git diff --name-status master to get formatted list)
phys/module_ra_clWRF_support.F
Do mods fix problem? How can that be demonstrated, and was that …

Redo PR#1748 to add CCE status code -4001

---

share/module_check_a_mundo.F

TYPE: bug fix
KEYWORDS: Thompson aerosol-aware microphysics scheme
SOURCE: Tim Juliano and Maria Frediani (NCAR/RAL)
Problem:
Check-a-mundo caused a model stop if `qna_update=0` when climatological aerosol option selected (`use_aero_icbc=.true.`), but `qna_update` is only intended for first guess aerosol (`use_aero_rap_icbc=.true.`)
Solution:
Modify logical statement in check-a-mundo.
M share/module_check_a_mundo.F
This fixes the problem as reported by Maria Frediani.
RELEASE NOTE: Minor bug fix for logical checking of time-varying aerosol option when climatological aerosol option selected.

Fixing bug in check-a-mundo for time-varying aerosol

---

phys/module_ra_rrtmg_lw.F
phys/module_ra_rrtmg_lwf.F
phys/module_ra_rrtmg_sw.F
phys/module_ra_rrtmg_swf.F

Bug fix for o3input=0
TYPE: bug fix
KEYWORDS: RRTMG radiation, o3input=0
SOURCE: reported by Mauro Morichetti of Institute of Atmospheric Sciences and Climate (ISAC), ITALY, fixed internally
Problem:
The ozone input option 0 (o3input=0) has been broken since 3.5.1 after a different ozone input option was introduced in 3.5. The code checks the presence of the ozone array O33D, and if it is not present, then the ozone is computed using o3input option 0. But the array is always present, so that code never reaches the other branch. Note also that the default o3input option was changed to 2 since 3.7.
Solution:
This PR fixes the option by checking the ozone input option rather than the presence of the array O33D. As there is an interest to see the output from this …

Bug fix for ozone input option o3input = 0

---

run/README.namelist

TYPE: text only 
KEYWORDS: adaptive time step, max, min, starting, README.namelist
Problem:
The README.namelist description of the starting_time_step, max_time_step, and min_time_step were incorrect. 
Solution:
Those have been updated to correspond with the code.
M    run/README.namelist
1. No tests necessary - text only  
2. Jenkins tests pass.

corrected description for adap_time_step vars in README.namelist

---

tools/data.h

TYPE: bug fix
KEYWORDS: moving nest, vortex-following, compile, intel, ifort, C
Problem:
Beginning with V4.4, neither the specified move (option 2) or vortex-following (option 3) moving nest options were able to compile with an Intel compiler. The error message given was 
`module_comm_dm_4.G:30:0: fatal error: REGISTRY_COMM_DM_PERIOD_subs.inc: No such file or directory`
`#include "REGISTRY_COMM_DM_PERIOD_subs.inc"`
`^`
`compilation terminated.`
`make[2]: [module_comm_dm_4.o] Error 1 (ignored)`
The issue was narrowed down to commit [#fed10f4b](https://github.com/wrf-model/WRF/commit/fed10f4b), and this change caused the file external/RSL_LITE/gen_comms.c to not create the REGISTRY_COMM_DM_PERIOD_subs.inc file when building a moving nest. The newly …

Modification to address Intel compile issue for moving nests

---

arch/configure.defaults
phys/module_cu_tiedtke.F
phys/module_sf_myjsfc.F

This update is to resolve different simulation results on aarch64 and x86 for the same dataset (caused by round up error in the last position for some transcendental functions) 
TYPE: bug fix
KEYWORDS: round up error, transcendental, compiler optimization
SOURCE: Jun Tang, Amazon
Problem:
After investigation, different simulation results on aarch64 and x86 for the same dataset with gcc 10.2 are caused by round up error in the last position for some transcendental functions; and several optimization flags (FMA, inverse square root, ...).  
Solution:
Use double precision for the computation of transcendental function at selected locations can make sure exact same output models are produced on aarch64 and x86 (this patch only covers a few PBL and cumulus scheme). Also …

Matching wrf results aarch64 x86 with gcc10.2

---

share/module_check_a_mundo.F

TYPE: bug fix
KEYWORDS: clm, urban cross check
SOURCE: reported by Shuhua Chen, UC Davis, internal
Problem:
Error check variable oops is not incremented when urban options are checked against land model option CLM.
Solution:
Increment variable oops to correct the error.
M      share/module_check_a_mundo.F
1. Yes. Model gracefully stops when both CLM and an urban option are selected.
RELEASE NOTE: Model will stop if both CLM and an urban physics option are selected.

Add missing oops for CLM plus urban check

---

phys/module_sf_sfclay.F
phys/module_sf_sfclayrev.F

TYPE: bug fix
KEYWORDS: sfclay, sfclayrev, qsfc
SOURCE: Reported by Laura Fowler, NCAR/MMM, internal
Problem:
QSFC variable in sfclay and sfclayrev modules was declared as an OUT variable, but it is only calculated conditionally. For some grid points, it takes the input value. This has caused compilation issue in MPAS.
Solution:
Change the declaration for QSFC from OUT to INOUT variable.
M     phys/module_sf_sfclay.F
M     phys/module_sf_sfclayrev.F
1. It fixed the compilation problem in MPAS.
2. The Jenkins tests have passed.
RELEASE NOTE:

Fix declaration for QSFC to INOUT variable

---

external/RSL_LITE/rsl_bcast.c
external/RSL_LITE/rsl_lite.h

Fix undefined behavior in RSL_LITE 
TYPE: bug fix
KEYWORDS: RSL_LITE
SOURCE: Florian Sammüller (Universität Bayreuth, Germany)
Problem:
RSL_LITE has undefined behavior due to implicitly declared functions.
This may lead to a crash of `wrf.exe` in the initialization of nested domains if WRF is built with link-time optimization and with recent compilers (e.g. GCC 12).
Solution:
Declare rsl_free() and destroy_list() before first use.
ISSUE:
Fixes #1764
M       external/RSL_LITE/rsl_bcast.c
M       external/RSL_LITE/rsl_lite.h
It passed regression tests.
RELEASE NOTE: Fixed an undefined behavior of RSL_LITE due to implicitly declared functions, which might lead to a model abort when using GCC 12.

Fix undefined behavior in RSL_LITE

---

Registry/Registry.EM_COMMON
Registry/registry.chem
chem/chem_driver.F
chem/module_phot_tuv.F
chem/photolysis_driver.F

This adds an option to use GFS total ozone (2D) in the TUV photolysis (phot_opt=4) to scale the simulated column to the GFS total column in the calculation of photolysis rates. This option requires the namelist option to be set (scale_o3_to_gfs_tot) as well as using the variable table Vtable.GFS_OZONE during the ungrib step. Alternatively, users could append the wrfinput file with a total ozone field (through e.g., ncks) with the name O3_GFS_DU.
SOURCE: Jordan Schnell (CIRES/NOAA)
Problem: Only option to provide total ozone field in TUV was a single scalar value.
Solution:
This allows use of GFS total ozone (not time varying)
M       Registry/registry.chem
M       chem/chem_driver.F
M …

Use GFS total column ozone in TUV photolysis 

---

phys/module_mp_jensen_ishmael.F

Small indexing error of rhoair, old indexing used cc, everywhere else in code k is used.
TYPE: bug fix
KEYWORDS: Microphysics, ISHMAEL, indexing, minor
SOURCE: Dylan Reynolds (SLF)
Problem:
indexing error
Solution:
changed index
None using WRF -- ISHMAEL is being tested in the HICAR model where this bug was found.
The Jenkins tests have passed.
RELEASE NOTE: very minor improvement to ISHMAEL MP.

Fixed small indexing error of rhoair in ISHMAEL MP scheme

---

Registry/Registry.EM_COMMON
dyn_em/module_first_rk_step_part1.F
phys/module_cu_ntiedtke.F
phys/module_cumulus_driver.F
run/README.namelist

Add scale-aware to the new Tiedtke scheme as an option
KEYWORDS: new Tiedtke cu scheme, scale aware option
A scale-aware or grid-distance-dependent option is added to the new Tiedtke scheme. The code is based on the paper by Wang (2022), and can be turned on by using namelist option ntiedtke_dx_opt = 1. The option becomes active when grid sizes is less than 15 km.
Wang, W., 2022: Forecasting Convection with a “Scale-Aware” Tiedtke Cumulus Parameterization Scheme at Kilometer Scales. _Wea. Forecasting_, 37/8, 1491 - 1507, 10.1175/WAF-D-21-0179.1.
M       phys/module_cu_ntiedtke.F
M       phys/module_cumulus_driver.F
M …

Add scale-aware to the new Tiedtke cu scheme as an option

---

Registry/Registry.EM_COMMON
Registry/registry.chem
chem/chemics_init.F
chem/dry_dep_driver.F
dyn_em/module_big_step_utilities_em.F
dyn_em/module_first_rk_step_part1.F
dyn_em/solve_em.F
main/depend.common
phys/Makefile
phys/module_bl_fogdes.F
phys/module_bl_mynn.F
phys/module_bl_mynn_common.F
phys/module_bl_mynn_wrapper.F
phys/module_pbl_driver.F
phys/module_physics_addtendc.F
phys/module_physics_init.F
phys/module_sf_fogdes.F
phys/module_shcu_camuwshcu.F
share/module_check_a_mundo.F
wrftladj/module_first_rk_step_part1_ad.F
wrftladj/module_first_rk_step_part1_tl.F
wrftladj/module_pbl_driver_ad.F
wrftladj/module_pbl_driver_tl.F
wrftladj/module_physics_addtendc_tl.F
wrftladj/solve_em_ad.F
wrftladj/solve_em_tl.F

MYNN-EDMF Update from CCPP to WRF
TYPE: bug fix/enhancement/new feature
KEYWORDS: MYNN EDMF closure subgrid clouds CCPP universalization 
SOURCE: Joseph Olson (NOAA-GSL), Wayne Angevine (NOAA-CSL)
- Vacate bl_pbl_physics = 6; will instead regulate the closure level with new namelist variable “bl_mynn_closure”; now has 3 options: level 2.5, 2.6, 3.0. This alone required changes in many files beyond the MYNN code.
- TKE budget fix; change bl_mynn_tkebudget to tke_budget (logical), so it’s a generic flag for other schemes to use
- Universalization of MYNN-EDMF for CCPP and WRF-ARW/MPAS
- Added a new WRF-specific wrapper called in module_pbl_driver.F
- Added a new WRF-specific module for defining constants
- Reordering of subroutines; bring driver to the top
- Improved …

MYNN-EDMF Update from CCPP to WRF

---

phys/module_surface_driver.F
run/README.namelist

This change brought the hard-coded tunable canopy heat capacity parameter in Noah-MP to MPTABLE for users to tune more easily.
KEYWORDS: Noah-MP, canopy heat capacity
SOURCE: Cenlin He (NCAR)
This update has no answer change and brought the hard-coded tunable canopy heat capacity parameter in Noah-MP to MPTABLE for users to tune more easily.
<br class="Apple-interchange-newline">
phys/noahmp
1. The mods has no impact on answers.
2. It passed regression tests.
RELEASE NOTE: This change brought the hard-coded tunable canopy heat capacity parameter in Noah-MP to MPTABLE for users to tune more easily.

Noah-MP update: bring hard-coded tunable canopy heat capacity parameteter to MPTABLE

---

Registry/Registry.EM_COMMON
phys/module_diag_nwp.F
phys/module_diagnostics_driver.F
phys/module_microphysics_driver.F
phys/module_mp_thompson.F
phys/module_physics_init.F

Option to compute two-moment prognostics for graupel/hail
TYPE: enhancement, new feature
KEYWORDS: microphysics, Thompson microphysics, graupel, hail, double-moment
SOURCE: Code developed by Greg Thompson (JCSDA, UCAR) and Anders Jensen (RAL, NCAR).
Implemented in WRF v4.4 by Maria Frediani (RAL, NCAR)
This code update includes
a package to compute two-moment prognostics for graupel/hail and a predicted density graupel category (mp_physics=38); an update to the Y-intercept relationship for one-moment graupel; and it replaces air temperature for wet-bulb temperature in riming and mixed phase processes.
Problem:
One-dimensional graupel/hail growth does not couple to the storm dynamics and is insufficient for predicting more detailed microphysical storm …

MP38 Thompson 2-mom graupel/hail (prev #1667, #1728)

---

phys/module_sf_bep_bem.F

Bug fix for the roof longwave calculation in bep_bem urban code
TYPE: bug fix
KEYWORDS: bep_bem, longwave calculation, urban
SOURCE: Cenlin He (NCAR)
Problem:
One of the parenthesis in the roof longwave radiation ("gfl" variable) calculation in module_sf_bep_bem.F was misplaced.
Solution:
Correct the misplaced parenthesis in the "gfl" variable calculation in module_sf_bep_bem.F
ISSUE: #1804 
/phys/module_sf_bep_bem.F
The modification fixes the problem.
RELEASE NOTE: This is the bug fix for the roof longwave calculation in bep_bem urban code.

WRF-urban bug fix for roof longwave calculation in bep_bem

---

phys/module_ra_rrtmg_lw.F
phys/module_ra_rrtmg_sw.F

TYPE: bug fix
KEYWORDS: O3 output, o3input=0, RRTMG-LW
SOURCE: Reported by Samm Elliott, fixed internally
Problem:
In 4.4, we introduced ozone output o3rad when o3input = 0, that is to use ozone profile provided by the RRTMG code. But the use of output array accessed memory with the vertical dimension > kte. This can cause segmentation fault on some systems.
Solution:
The array is now limited to use only when vertical dimension is less than kte.
M     phys/module_ra_rrtmg_lw.F
1. Yes
RELEASE NOTE:

Fix an error with O31D exceeding vertical dimension kte

---

arch/configure.defaults

Added AMD AOCC Compiler support to WRF 
TYPE: choose one of [new feature]
KEYWORDS: AMD, AOCC, Compiler Support, ZEN Architecture, Configure
SOURCE:  amd-toolchain-support@github.com 
Problem: Added AMD AOCC Compiler Support
Earlier there is no support for AMD AOCC Complier. Now we have added support. 
Solution:
Added AMD AOCC Compiler support to configure using stanzas. 
M       arch/configure.defaults
1. Compiled and tested with AOCC Compiler. Functional test with AOCC 3.2.0 is done.
2. Passed regression tests.
RELEASE NOTE: Provided AMD AOCC Compiler support at the time of configuring WRF for AMD Architectures including Zen1, Zen2 and Zen3.

Amd aocc support

---

chem/aerosol_driver.F
chem/cloudchem_driver.F
chem/module_mosaic_cloudchem.F
chem/module_mosaic_driver.F
chem/module_mosaic_therm.F

Fixed a bug for chem_opt = 201, 202.
TYPE: bug fix
KEYWORDS: MOZART_MOSAIC_4BIN, mozart_pH_diag, bug fix
Problem: 
Users will experience a stalled simulation upon writing history files. This was caused by the pH diagnostics added in v4.3 (https://github.com/wrf-model/WRF/pull/1342) not being activated with the namelist option mozart_ph_diag = 1. 
Solution:
Add as optional arguments only filled if the namelist is activated.
M       chem/aerosol_driver.F
M       chem/cloudchem_driver.F
M       chem/module_mosaic_cloudchem.F
M       chem/module_mosaic_driver.F
M       chem/module_mosaic_therm.F
1. Yes, the fix remedies the …

BUG FIX: chem_opt = 201, 202 ph_diag

---

configure

Correct string test in configure.
TYPE: bug fix
KEYWORDS: configure script
SOURCE: 
Will Hatheway @whatheway
Douglas Lowe
Problem:
Configure is returning an 'Unexpected Operator' error, which is messing up automated scripts for installing WRF.
Solution:
The [ ] test on line 919 of the configure script should use =, not ==, for the string comparison - as this is a more portable syntax (see http://mywiki.wooledge.org/BashFAQ/031 for explanation of this).
configure
1. The change fixes the error.
2. The Jenkins tests have passed.
RELEASE NOTE:
Correction of string test in configure.

Bugfix: Correct string test in configure.

---

Makefile

TYPE: bug fix
KEYWORDS: Makefile, string check
SOURCE:
Problem:
When WRF_CMAQ is empty, it spews the following error message.
```
/bin/sh: line 0: [: -eq: unary operator expected
```
Solution:
Check if WRF_CMAQ is empty first.
Modified files:
M    Makefile
- Yes, the change fixes the error.
- The Jenkins tests have passed. No effect on other code.
RELEASE NOTE:

check if WRF_CMAQ is empty first

---

hydro/IO/netcdf_layer.f90

Add the WRF-Hydro source file `netcdf_layer.f90` to Git.
TYPE: bug fix
KEYWORDS: wrfhydro, git
Problem:
The .gitignore file includes a `*.f90` pattern but WRF-Hydro includes several .f90 files. They must be included with `git add --force` or they will be silently ignored.
Solution:
Manually force-add `hydro/IO/netcdf_layer.f90`
A       hydro/IO/netcdf_layer.f90
1. CI to follow.
2. Reg tests have passed.

Add ignored netcdf_layer.f90 file to git

---

phys/module_mp_ntu.F

Bug fix in exponent letters
TYPE: bug fix
KEYWORDS: exponent letter, double precision, default real, Fortran, underflow
SOURCE: Kengo Miyamoto (RIST)
Problem: 
In Fortran, the exponent letter for double precision numbers should be ‘D’, while the exponent letter ‘E' is used for default real numbers. Furthermore, the value 1.0E-50 is less than the value of ‘tiny', which is the smallest positive number, of default real numbers. This causes error for Fujitsu Fortran compiler when building WRF load module files.
Solution:
Changing the exponent letters of the constants those are compared to double precision variables in SUBROUTINE FIND_RC0 from ‘E’ to ‘D’.
M     phys/module_mp_ntu.F
1. I checked whether Fujitsu compiler could …

Fix exponent letter

---

Registry/Registry.EM_COMMON
phys/module_lightning_driver.F
phys/module_ltng_lpi.F

TYPE: bug fix
KEYWORDS: LPI, malloc error, NaNs
Problem:
The model stops right away with malloc error (with gfortran) when using lightning_option = 3, the option to compute lightning potential index (the problem occurred only with a 2 domain test). The error is due to variable packaging for this option. Once this error is fixed, the model can run but produces NaNs in the diagnostics. Array for hail mixing ratio is removed from the call as well, as it is not used.
Solution:
Add additional variables for packaging, and limit hydrometeors to a number that is not smaller than 1.e-10, which eliminates the NaNs.
M       phys/module_lightning_driver.F
M       phys/module_ltng_lpi.F
TESTS …

Fix Lightning Potential Index calculation failure

---

phys/module_bl_keps.F

TYPE: bug fix
KEYWORDS: KEPS PBL, advection term
SOURCE: internal and Zonato
Problem:
Tests revealed that when model time step is relatively large on coarser grids, the scheme with advection on can become unstable causing the model to abort.
Solution:
Based on Zonato's suggestion, turning off the advection term solves the problem.
M     phys/module_bl_keps.F
1. Tests show it can fix the model abort issue.
2. The Jenkins tests are all passing, no other effect on code.

Turning advection off for KEPS for now

---

phys/module_sf_clm.F

TYPE: bug fix, no impact, text only
KEYWORDS: prints, CLM
Problem:
There are many debugging print statements remaining in the CLM module, and it creates huge rsl.out fiels. 
Solution:
This PR removes those print statements.
M      phys/module_sf_clm.F
1. Do mods fix problem? Yes. There are no more extra prints shown in rsl.out files.
2.The Jenkins tests are all passing, and no effect on code.
RELEASE NOTE:

Remove print statements in CLM

---

phys/module_ltng_crmpr92.F

TYPE: Bug fix
KEYWORDS: dimension and loop condition error in subroutine iccg_crm_pr93
SOURCE: J. Wong <johnwong@ucar.edu>
1. A dimension error was found in subroutine iccg_pr93 in module_ltng_crmpr92.F. The arrays should be dimensioned by ims:ime, instead it is dimensioned by ims:ims.
2. The DO WHILE loop to calculate freezing level height after cloud top height should be replaced from ktop to kfreeze. Otherwise, it might cause a Segmentation fault.
phys/module_ltng_crmpr92.F
The regression tests have passed.
RELEASE NOTE: Fixed a dimension error for arrays refl, t and z.

Bug fix: iccg_crm_pr93

---

phys/module_bl_mynn.F

Fix two numeric operators are consecutive
TYPE: bug fix
KEYWORDS: Fortran, Precedence of operators
SOURCE: Kengo Miyamoto (RIST)
Problem:
In fortran, the formation rules do not permit expressions containing two consecutive numeric operators, such as A ** –B, while an expression such as A ** (–B) is permitted. This cause errors for Fujitsu Fortran compiler when building WRF load module files. gfortran warns to use parentheses.
Solution:
Adding parentheses
LIST OF MODIFIED FILES: phys/module_bl_mynn.F
I checked whether Fujitsu compiler could make WRF and WPS load module files and a tutorial case (Nested Model Run: 2-way with 2 Input Files) could be completed …

Fix two numeric operators are consecutive

---

Registry/Registry.EM_COMMON
dyn_em/module_first_rk_step_part1.F
phys/module_cu_ntiedtke.F
phys/module_cumulus_driver.F

TYPE: bug fix
KEYWORDS: scale-aware ntiedtke
Problem:
The original PR to add scale-awareness to the new Tiedtke scheme had a bug: the introduction of the namelist control didn't work correctly. Also the introduction of the namelist control made the code look ugly. After discussing with the original developer, we agreed if the changes to scale the cloud to rain conversion coefficient (which helps to reduce very light precip), and saturation check as a condition for triggering mid-level convection (which helps to the number of grid points that are classified as mid-level convection) are removed, the rest of the code can be added without a namelist control. 
Solution:
Removing the namelist introduced in PR#1806, and the changes related to …

Bug fix and rework the scale-aware code

---

Makefile
configure
tools/rpc_test.c

Change to configure to test for RPC package instead of checking hardcoded paths, so that non-standard RPC installs can still be found.
KEYWORDS: configure, build, rpc, make, test
SOURCE: Brian Vanderwende (NCAR)
Problem:
If an RPC library is installed in a non-standard prefix with a package manager like Spack, WRF will not be able to find it.
Solution:
Instead of checking hardcoded locations for `rpc/types.h`, compile a test program to check for one of the variants. Since symbolic linking hacks are occasionally done to make tirpc friendlier, it's also good to check constants to confirm the version used.
LIST OF MODIFIED FILES (from develop):
M       Makefile
M       configure
A       tools/rpc_test.c
1. The success is determined …

Test for RPC instead of checking hardcoded paths

---

arch/noopt_exceptions
arch/noopt_exceptions_f

Stop intentionally removing OpenMP flags
KEYWORDS: Compile, OpenMP flag
SOURCE: Kengo Miyamoto (RIST)
Problem:
Some source program files are compiled without OpenMP flags, even though those refer to a variable in the source program file that is compiled with OpenMP flag. This causes errors for Fujitsu Fortran compiler when building WRF load module files. We don’t anticipate any issues if we also compile those files with OpenMP flags when we select 'smpar' or 'sm+dm’ configuration option.
Solution:
Stop intentionally removing OpenMP flags when compiling certain listed source program files. This also might make it easier to maintain building environment (e.g., The time of someone adds new source program files).
ISSUE: …

Stop intentionally removing OpenMP flags

---

phys/module_bl_keps.F

TYPE: bug fix
KEYWORDS: KEPS PBL, tendency for V-component of winds
SOURCE: Andrea Zonato, Department of Environmental, Civil and Mechanical Engineering, University of Trento, Trento, Italy
DESCRIPTION OF CHANGE:
Forgot to add the update of V tendency at line 357 of module_bl_keps.F in PR#[1781](https://github.com/wrf-model/WRF/pull/1781):
rvblten(ix,iz,iy)=rvblten(ix,iz,iy)+(v1D(iz)-v_phy(ix,iz,iy))/dt
TESTS:
1. Single case test shows this corrects the wind error.
2. The Jenkins tests have passed.

Correction of V tendency

---

phys/module_sf_sfclayrev.F

TYPE: bug fix
KEYWORDS: Revised MM5 surface layer
SOURCE: Samm Elliott (TempoQuest Inc.)
Problem: see https://github.com/wrf-model/WRF/issues/1859
Solution:
Limit the maximum iterations of the `zolri` loop to 10 if the solution does not converge due to fp roundoff error.
ISSUE:
Fixes #1859
phys/module_sf_sfclayrev.F
Fixed the issue for the test case discussed in https://github.com/wrf-model/WRF/issues/1859 for AceCAST (GPU-accelerated version of WRF developed by TQI). The same case produced B4B results on CPU (when compared to a run using https://github.com/wrf-model/WRF/commit/755fc49834471330496892e760fb05951b361360).
RELEASE NOTE: Fixed an issue in Revised MM5 (sf_sfclay_physics=1) where the model could potentially …

Revised MM5 - Limit zolri convergence loop to a maximum of 10 iterations

---

configure

TYPE: bug fix
KEYWORDS: configure script, use '=' vs '=='
SOURCE: Chris Bridgham
Problem:
The newly added test in v4.5 in configure script could fail due to less portable use '==' as in 
```
if [ $rpc_type == "rpc" ]; then
```
Solution:
Change the above to
```
if [ $rpc_type = "rpc" ]; then
```
Fixes #1869
M     configure
1. Yes.
RELEASE NOTE:

make configure script more portable 

---

phys/module_ltng_cpmpr92z.F
phys/module_ltng_crmpr92.F
phys/module_ltng_iccg.F

KEYWORDS: reference, lightning options
Problem:
A reference for lightning options (lightning_option = 1 and 2) and contact info in the modules are out of date.
Solution:
Update the reference and remove out of date contact info.
M       phys/module_ltng_cpmpr92z.F
M       phys/module_ltng_crmpr92.F
M       phys/module_ltng_iccg.F
1. Text change only
RELEASE NOTE:

update reference and remove out of date contact info

---

phys/module_physics_init.F
run/README.namelist

TYPE: bug fix
KEYWORDS: aercu_opt, morrison aerosol aware
SOURCE: Samm Elliott (TempoQuest Inc.)
Problem: see #924
Solution: added appropriate calls to `wrf_error_fatal()`
ISSUE: Fixes #924
Tested with valid/invalid/missing CESM_RCP4.5_Aerosol_Data.dat for jan2000 test case 
RELEASE NOTE: User-friendly fatal error messages have been added to inform the user if the optional CESM aerosol data files required for the MSKF cumulus/Morrison microphysics aerosol interaction option (aercu_opt = 1 or 2) are missing.

User-friendly error messages for missing files associated with aercu_opt=[12] initialization

---

phys/module_bl_keps.F

TYPE: bug fix
KEYWORDS: bug fix, k-epsilon counter-gradient term
SOURCE: Andrea Zonato,  Koninklijk Nederlands Meteorologisch Instituut
Problem:
The counter-gradient term for temperature equation at the first level is creating instabilities over water surfaces.
Solution:
The counter gradient has been set =0 for the first atmospheric level.
LIST OF MODIFIED FILES: modue_bl_keps.F
RELEASE NOTE: Correction for the counter-gradient term which causes instabilities and large biases at the first model level over water surfaces.

correction to bl_pbl_physics=17, K-epsilon-theta, to avoid instabilities over water surfaces

---

arch/configure.defaults

TYPE: bug-fix
KEYWORDS: GCC
SOURCE: Stephen Sachs (AWS)
Problem:
GCC-10 onwards compilation fails on ARM
Solution:
In order to patch GCC arguments when using GCC-10+ a line `FCCOMPAT` is necessary in `configure.wrf`. This patch is an extension to https://github.com/wrf-model/WRF/pull/1251.

Apply type-mismatch for gcc-10 to all gcc targets

---

phys/module_sf_urban.F

TYPE: bug fix
KEYWORDS: single-layer urban canopy model, saturated specific humidity for ground
SOURCE: Dan Li (Boston University)
Problem:
When computing the derivative of the saturated specific humidity with respect to surface temperature for the ground in single-layer urban canopy model, the equation had a typo which involved a coefficient. It should be 0.622 (as in for example the same calculations for roof and wall) instead of 0.22. 
Solution:
Change the coefficient from 0.22 to 0.622. 
M    phys/module_sf_urban.F
1. case study.
RELEASE NOTE: Fix a typo in computing the saturated specific humidity in the single-layer urban canopy model. The effect is likely small due to the …

fix a typo in the single-layer urban canopy model 

---

phys/module_mp_wdm6.F
phys/module_mp_wdm7.F

TYPE: bug fixes
KEYWORDS: WDM schemes, uninitialized value, wrong cloud autoconversion rate
SOURCE: Songyou Hong, PSL/NOAA, internal
Problem:
1. cloud autoconversion rate is off by a factor of 600
2. if cloud water is present, cloud number concentration needs to be set at initialization.
Solution:
Both problems are fixed in this PR. 
M    phys/module_mp_wdm6.F
M    phys/module_mp_wdm7.F
1. Tested in case studies.
RELEASE NOTE: This PR fixes two errors in the WDM6 and WDM7 that have been in the code since V4.0: 1. uninitialized cloud number concentration when cloud is present at the start. 2. The cloud autoconversion rate was off by a factor of 600. The effect of the first error isn't …

Fixes for WDM6 and WDM7

---

phys/module_mp_fast_sbm.F

TYPE: bug fix
KEYWORDS: Melting, Supersaturation
SOURCE: Jacob Shpund (Pacific Northwest National Lab), 
Kangen Huang (Nanjing University)
Alexander Khain (The Hebrew University of Jerusalem)
Problem:
This PR addresses the following problems: (1) The order of accumulating the melted mass was erroneous and based on the hydrometeor state after melting. (2) Changes in temperature and water vapor after advection were used via low-order approximation for calculating the supersaturation that caused relatively high values of total mass imbalance. (3) Corresponding code cleanup.
Solution:
(1) Changing the order in melting
(2) Calculating the dynamical tendency directly from the perturbation of Temperature and water vapor …

Bugfix in the calculations of (1) immediate melting, (2) supersaturation dynamical tendency

---

Makefile

Env variable USENETCDFPAR may not be set when running make.
TYPE: bug fix
KEYWORDS: USENETCDFPAR
SOURCE: Wei-keng Liao
When env USENETCDFPAR is not set, running make spews the following error message.
```
/bin/sh: line 0: [: -eq: unary operator expected
```
Solution: Check if USENETCDFPAR  is set first, and then its value if set.
LIST OF MODIFIED FILES: Makefile
TESTS CONDUCTED:  running command make

check if USENETCDFPAR is empty first

---

arch/configure.defaults

KEYWORDS: Intel, LLVM, oneAPI, compilation
Problem:
Addressing issue #1884 for Intel oneAPI ifx/icx builds
Solution:
Add configuration to `configure.defaults` mirroring original Intel ifort/icc build with minor tweaking.
Fixes #1884
M       arch/configure.defaults
1. WRF core em_real compiles with ifx/icx
3. Note that this is the same PR as in [#1893](https://github.com/wrf-model/WRF/pull/1893), but commited to release-v4.5.2 branch (instead of develop)
RELEASE NOTE: Added build configuration for new Intel oneAPI LLVM ifx/icx compilers, which will be available on NCAR's new computer, Derecho.

add compilation stanza for Intel oneAPI for 4.5.2

---

arch/Config.pl

Changing how Config.pl looks for the HDF5 high-level fortran library.
KEYWORDS: HDF5, high-level, fortran, library
SOURCE: Timothy Brown (AWS)
Problem:
Depending on the installation type (autotools or cmake) of HDF5 the high-level fortran library can be either `hdf5_hl_fortran` or `hdf5hl_fortran`.
Solution:
In `Config.pl` we now check the HDF5 library directory for the high-level fortran library.
ISSUE:
Fixes [manual WRF build with Spack](https://github.com/aws-samples/aws-hpc-tutorials/issues/452)
- arch/Config.pl
1. Yes. I have configured and built WRF against installs of HDF5 where the high-level fortran library has been
a. hdf5_hl_fortran
b. hdf5hl_fortran
c. hdf5_hl_fortran and hdf5hl_fortran
2. …

Changing how Config.pl looks for the HDF5 high-level fortran library.

---

frame/module_domain_type.F
share/wrf_tsin.F

This PR corrects an issue in which time series for a parent domain were re-initialized when a child domain started later than the initial time for a simulation.
TYPE: bug fix
KEYWORDS: time series, tslist, nest
SOURCE: Mathieu Landreau (LHEEA, Centrale Nantes, France), Michael Duda (NSF NCAR)
Problem:
When running a simulation with a nest starting later than its parent and with the time series option activated, the parent domain time series is reinitialized when the nest starts.
Solution:
This issue is corrected by:
1) Initializing time series-specific members of the domain type, in particular, initializing `have_calculated_tslocs` to `.FALSE.`
2) Returning early from the wrf_tsin routine if `grid%have_calculated_tslocs` is `.TRUE.` (but avoiding changes to the …

Avoid re-initialization of time series for parent after child domain starts

---

var/da/da_minimisation/da_get_var_diagnostics.inc
var/da/da_statistics/da_analysis_stats.inc

Bugfix for the lightning DA
TYPE: bug fix
There are some bugs in the [PR#1962](https://github.com/wrf-model/WRF/pull/1962), which is fixed in this PR.
M:   var/da/da_minimisation/da_get_var_diagnostics.inc
M:   var/da/da_statistics/da_analysis_stats.inc
1. Tested it using the GNU compiler on Dereche.

bugfix for the lightning DA

---

dyn_em/module_first_rk_step_part1.F

TYPE: bug fix
KEYWORDS: syntax
Problem:
Wrong Fortran syntax most likely being corrected by standard.exe
Solution:
Fix the syntax error
RELEASE NOTE: 
Bug fix for erroneous syntax in dyn_em/module_first_rk_step_part1.F

Bug fix for erroneous syntax in dyn_em/module_first_rk_step_part1.F

---

tools/gen_allocs.c

TYPE: bug fix
KEYWORDS: gen_allocs, registry, defines
Problem:
Conditionally compiled code in `gen_allocs` is flipped to use wrong `#define` for when to use allocatables or pointers
Solution:
Flip logic of `#ifdef` to `#ifndef` to avoid using Fortran `nullify()` statement on allocatables
M tools/gen_allocs.c
RELEASE NOTE: 
Bug fix in gen_allocs to use correct conditional compilation logic on allocatables vs pointers

Bug fix in gen_allocs to use correct conditional compilation logic on allocatables vs pointers

---

compile

Enable WRFDA's compilation with RTTOV and HDF5 libs on Derecho
TYPE: maintenance
KEYWORDS: HDF5, RTTOV, WRFDA
Problem:
HDF5 lib on derecho is changed, which makes WRFDA compilation failed when including RTTOV lib with HDF5.
By default, HDF5 and RTTOV libs are turned off when building WRFDA.
Solution:
Change an existing HDF5 lib name and add additional HDF5 libs. For gcc:
setenv HDF5 /glade/u/apps/derecho/23.06/spack/opt/spack/hdf5/1.12.2/cray-mpich/8.1.25/gcc/12.2.0/wjdl
setenv RTTOV /glade/work/liuz/RTTOVv12.1/hdf5/gnu_12.2.0
before configure/compile WRFDA.
M       compile
1. Build successfully with gnu on Derecho
RELEASE NOTE: None

Enable WRFDA's compilation with RTTOV and HDF5 libs on Derecho

---

external/io_grib2/g2lib/dec_png.c
external/io_grib2/g2lib/enc_png.c

TYPE: bug fix
KEYWORDS: png
Problem:
Incorrect define type used for png void type when compared to libpng functions and NCEP g2lib source code.
While `voidp` does exist, compile may fail when enabling GRIB2 I/O and enabling libpng compression in the makefiles. Additionally no version of libpng (back to 0.89) ever had those functions explicitly compatibly with `voidp`  - likewise the ncep g2 lib version of these files (back to v2.5.0) never has `voidp` in the modified code.
This will __NOT__ affect out-of-the-box native builds of WRF, grib2 enabled or not. One must enable the source code manually to exercise PNG compression and then this issue may appear.
Solution:
Switch to the appropriate define `png_voidp`, as can be seen here : …

Update g2lib png encode/decode to use correct png_voidp define

---

tools/registry.c

KEYWORDS: registry, error check
Problem:
The registry code generation continues regardless of errors and missing fields are not caught until sometimes ~40 minutes into compilation when a subsequent source file is missing registry-generated fields
Solution:
Check returns of `gen_...()` functions that create files to output if respective call failed to generate the registry code
M tools/registry.c
1. On failed registry generation, registry executable will exit with the non-zero return that caused it
RELEASE NOTE: 
Add error checks in registry  to catch code generation failure

Add error checks in registry  to catch code generation failure

---

dyn_em/module_advect_em.F
external/atm_ocn/cmpcomm.F
external/io_adios2/wrf_io.F90
external/io_netcdf/wrf_io.F90
external/io_netcdfpar/wrf_io.F90
external/io_pnetcdf/wrf_io.F90
frame/module_configure.F
phys/module_mp_SBM_polar_radar.F
phys/module_mp_fast_sbm.F

TYPE: bug fix
KEYWORDS: defines, cmake
Problem:
Certain #define constructs prove to be challenging for CMake to process automatically into a dependency graph. 
Solution:
Reduce complexity for #defines that can be rewritten. For those that cannot, create stub modules.
M       dyn_em/module_advect_em.F
M       external/atm_ocn/cmpcomm.F
M       external/io_adios2/wrf_io.F90
M       external/io_netcdf/wrf_io.F90
M       external/io_netcdfpar/wrf_io.F90
M       external/io_pnetcdf/wrf_io.F90
M       frame/module_configure.F
M       phys/module_mp_SBM_polar_radar.F
M       phys/module_mp_fast_sbm.F
1. Do mods fix problem? Local tests demonstrate fixes satisfy new upcoming cmake build
2. Are the Jenkins tests …

Adjust #defines to accommodate future CMake build

---

phys/module_fr_fire_phys.F
test/em_fire/namelist.fire.sb40
test/em_fire/namelist.fire_fmc.sb40

Introducing Scott and Burgan 40 fuel models for WRF-Fire module.
KEYWORDS: WRF-Fire, Fuel, Scott and Burgan, Fuel Model
SOURCE: Kasra Shamsaei (University of Nevada, Reno), Tim Juliano, Domingo Munoz-Esparza, Branko Kosovic (NCAR/RAL)
Current version of WRF-Fire has Anderson'13 fuel models which is for 1982. In this PR, we have added the more recent and improved Scott and Burgan 40 fuel models in addition to the current Anderson's fuel model.
M       phys/module_fr_fire_phys.F
A       test/em_fire/namelist.fire.sb40
A       test/em_fire/namelist.fire_fmc.sb40
1. These modifications are used in historic fires simulations. For instance, see:
- Shamsaei, K., Juliano, T. W., Roberts, M., Ebrahimian, H., …

Adding Scott and Burgan (2005) 40 Fuel Models for WRF-Fire

---

phys/module_sf_sfclay.F
phys/module_sf_sfclayrev.F
share/mediation_integrate.F

Arbitrary limitation in the computation of **QFX** and **HFX**.
TYPE: bug fix
KEYWORDS: SBL
SOURCE: David Robertson, Rutgers University
Problem:
- Arbitrary limitation in the computation of **QFX** and **HFX** in modules  **`module_sf_sfclay.F`** and **`module_sf_sfclayrev.F`** that affects the computation latent heat fluxes and sensible heat flux in coastal areas that limit fog layers.
Solution:
- Comment out the lines in **`phys/module_sf_sfclay.F`** :
```f90
DO 370 I=its,ite
QFX(I)=FLQC(I)*(QSFC(I)-QX(I))
!       QFX(I)=AMAX1(QFX(I),0.)
LH(I)=XLV*QFX(I)
370 CONTINUE
...
ELSEIF(XLAND(I)-1.5.LT.0.)THEN
HFX(I)=FLHC(I)*(THGB(I)-THX(I))
!        HFX(I)=AMAX1(HFX(I),-250.)
ENDIF
400 CONTINUE
```
- Similar changes in **`phys/module_sf_sfclayrev.F`**.
LIST OF MODIFIED …

Remove arbitrary limiting of heat fluxes

---

tools/gen_streams.c
tools/reg_parse.c

KEYWORDS: registry, code generation
Problem:
The current registry generated code assumes generating the autogenerated code should be placed within the WRF repository alongside true source code that is committed to the repository. This leads to a cluttered source tree with hundreds of files that were autogenerated, and relies on various stopgaps (unintuitive ignores, specific path and wildcard `rm` commands within source folders, run code generation from specific location).
In preparation for the future cmake build, it would be ideal to not inherit these limitations of the registry code registration, allowing the source tree to be pristine while autogenerated code is placed in an alternate build directory.
Solution:
Add the …

Add the ability for registry code generation to be out of source

---

Registry/registry.chem

This updates the registry description for settling velocity of bin 5 for GOCART
KEYWORDS: GOCART settling, description of bin 5 settling
SOURCE: [encyclica](https://github.com/encyclica)
Updated the registry to correct tezxt
Solution:
Text change
Fixes #1982 
M       Registry/registry.chem
None
RELEASE NOTE: Updates registry for variable description of settling velocity in bin 5

Fix registry description for settling velocity of bin 5

---

configure

Some versions of make appear to fail on the USENETCDFPAR logic in the top level Makefile if the variable is undefined. Making sure it is at least set to 0 by the configure script fixes the issue.
TYPE: bug fix
KEYWORDS:  make
SOURCE: Ted Mansell (NOAA/NSSL)
Problem: Logic failure in top level Makefile with some versions of make (don't remember which) if USENETCDFPAR is undefined
Solution:
Making sure that at USENETCDFPAR is set to either 0 or 1 in the configure script fixes the issue.
LIST OF MODIFIED FILES: configure
TESTS: it passed regression tests.

Make sure that USENETCDFPAR is not undefined

---

Registry/Registry.EM_COMMON
dyn_em/module_first_rk_step_part1.F
phys/Makefile
phys/module_pbl_driver.F
phys/module_physics_init.F
phys/module_wind_jensen.F
phys/module_wind_mav.F
run/README.namelist

Add three new wind farm parameterizations and their ensembles
KEYWORDS: wind farm parameterization, windfarm option
SOURCE: Cristina Archer (UDEL), Yulong Ma(UDEL;GWA-MWF) and Ahmad Vasel-Be-Hagh(Tennessee Technological University)
Three new wind farm parameterizations and their ensembles have been added. The key innovation of these parameterizations is their ability to directly account for the individual and overlapping sub-grid wakes of wind turbines within a wind farm. This feature was absent in the Fitch parameterization previously used in WRF. Additionally, the three parameterizations differ in their representation of wakes (e.g., top-hat or Gaussian) and their superposition methods (e.g., sum of squared deficits, squared velocities, or …

Add three new wind farm parameterizations and their ensembles 

---

Registry/Registry.EM_COMMON
dyn_em/module_initialize_real.F
run/README.namelist

KEYWORDS: Qv, specific humidity, vertical interpolation
Problem:
In current real program, if either water mixing ratio (Qv) or specific humidity (SH) is available, it first converts it to RH, perform vertical interpolation using RH, and then compute Qv for the model input. Assuming Qv and SH are coming from other model's native levels, which tends to be plenty and generally true, it should not be necessary to go through this Qv (SH) to RH, and RH to Qv steps.
Solution:
Use the flag_qv and flag_sh to avoid using interpolated RH (even though RH is still computed and vertically interpolated). If flag_sh is 1, SH is converted to Qv or mixing ratio. Then Qv is interpolated vertically. A namelist, use_sh_qv, is added for user to choose …

Use Qv or specific humidity in interpolation if they are available

---

phys/module_sf_sfclay.F
phys/module_sf_sfclayrev.F
phys/module_surface_driver.F

KEYWORDS: salinity effect, saturation vapor pressure, ocean
Problem:
The salinity effect of ocean is not considered when computing saturation vapor pressure.
Solution:
Add the effect in the MM5 and revised MM5 surface layer schemes. The 0.98 factor is an approximation for salinity of 34 part per thousands, and applied for saturation specific humidity. Here the approximation is applied to saturation mixing ratio. The lakemask field is used to exclude this effect from inland lakes.
M     phys/module_sf_sfclay.F
M     phys/module_sf_sfclayrev.F
M     phys/module_surface_driver.F
1. Tested in many tropical cyclone cases.
RELEASE NOTE: Add salinity effect …

add salinity effect in sfclay and sfclayrev

---

main/depend.common

TYPE: bug
KEYWORDS: make, dependency
Problem:
PR #1944 adds `module_wind_mav` to `module_physics_init`, but does not update the `main/depend.common` file to add the dependency during compilation
Solution:
Add `module_wind_mav.o` as a dependency to `module_physics_init.o` in the `main/depend.common` file
ISSUE: 
Fixes [comment](https://github.com/wrf-model/WRF/pull/1944#issuecomment-1917898723) noted in #1944 
M main/depend.common
1. Local compilation in single job mode `-j 1` should work now
RELEASE NOTE: 
Add missing dependency module_wind_mav to module_physics_init

Add missing dependency module_wind_mav to module_physics_init

---

phys/module_physics_init.F
phys/module_sf_sfclayrev.F

TYPE: code clean up
KEYWORDS: shalwater_init
Move the call to shallow water roughness length initialization routine from module_sf_sfclayrev.F to module_physics_init.F
This is in preparation to make sfclayrev module ccpp-compliant, and potential make the initialization and physics available to other surface layer modules.
M       phys/module_physics_init.F
M       phys/module_sf_sfclayrev.F
1. Should not change how the variable is initialized.
RELEASE NOTE: This PR moves the call to shalwater_init from module_sf_sfclayrev.F to module_physics_init.F.

Move shalwater_init to physics_init

---

Registry/registry.fire
phys/module_fr_fire_atm.F
phys/module_fr_fire_driver.F
phys/module_fr_fire_driver_wrf.F

This commit adds a new Truncated Gaussian fire and heat distribution scheme in the atmosphere for WRF-Fire. This scheme overcomes the shortcomings of the current scheme and improves simulation results accuracy.
KEYWORDS: WRF-Fire, Heat Release, Smoke, Plume, Gaussian
SOURCE: Kasra Shamsaei (University of Nevada, Reno), Tim Juliano, Branko Kosovic (NCAR/RAL)
Problem:
The current fire heat distribution in the WRF-Fire does not conserve the heat fluxes from the fire. In this new scheme, the fire heat is conserved while distributed in the atmosphere. Additionally, the current smoke tracer release scheme in WRF-Fire was over-simplified.
Solution:
We introduce a Truncated Gaussian fire heat and smoke distribution scheme in WRF-Fire to overcome the …

Truncated Gaussian Heat and Smoke Release Formulation for WRF-Fire

---

Registry/Registry.EM_COMMON
Registry/registry.chem
chem/chem_driver.F
chem/emissions_driver.F

The WRF-SoilN-chem: a dynamic ammonia emission model capable of calculating NH3 emission rate interactively with time- and spatial-varying meteorological and soil conditions.
KEYWORDS: ammonia emission, soil, dynamic, chem, gas phase.
SOURCE: RenChuanhua and Huangxin, Nanjing University.
DESCRIPTION OF CHANGES:  Use a dynamic ammonia emission function instead of a static monthly emission inventory
Problem:
The traditional monthly emission inventory cannot characterize the variation of ammonia emission intensity under different meteorological conditions, which leads to the simulation bias of secondary inorganic aerosol (such as nitrate and sulfate).
Solution:
The meteorological dependent dynamic emission factor (empirical function) is added to the emission file, which can …

The WRF-SoilN-chem: a dynamic ammonia emission model 

---

dyn_em/module_first_rk_step_part1.F
dyn_em/module_initialize_real.F
main/depend.common
phys/module_pbl_driver.F
phys/module_sf_noahdrv.F
phys/module_surface_driver.F

Related to PR#1881.
TYPE: bug fix
KEYWORDS: anthropogenic heat, mosaic
SOURCE: Do Ngoc Khanh (Tokyo Institute of Technology)
Problem 1:
* In https://github.com/wrf-model/WRF/pull/1881#discussion_r1446523703, @cenlinhe said that `FRC_URB2D` should be `IN` (not `INOUT`) and removed a portion of code. See https://github.com/wrf-model/WRF/pull/1986/files#diff-4cf900c383221426961400b9c706d4a7f551833ccff64af20fef15ef6bdc0f1bL3721.
* However, that change causes `UTYPE_URB` passed to urban module to become 0 when mosaic is turn on, and array index out of bound error occurs.
Solution 1:
* As I said before, I don't know why FRC_URB2D and UTYPE should be set there. But apparently the model does not work if they are not set there (even when the new options are turned off and …

Fix AHE option 2 and a problem with mosaic

---

CMakeLists.txt
external/io_int/CMakeLists.txt
external/io_netcdf/CMakeLists.txt
external/io_netcdfpar/CMakeLists.txt

KEYWORDS: cmake, diffwrf
Problem:
New CMake build did not create binaries for io_* `diffwrf`
Solution:
Slight restructure of certain targets to allow for easy creation of the diffwrf executables. Since previously all `diffwrf` binaries were named the same, to house them int the same `install/bin/` location they have been prefix with the type of io or shorthand of that option ( io_int -> `diffwrf_int`, io_netcdf -> `diffwrf_nc`, io_netcdfpar -> `diffwrf_ncpar` ). 
M       CMakeLists.txt
M       external/io_int/CMakeLists.txt
M       external/io_netcdf/CMakeLists.txt
M       external/io_netcdfpar/CMakeLists.txt
1. Diffwrf execs should now be located in cmake install location
RELEASE NOTE: …

CMake build of diffwrf binaries

---

dyn_em/module_initialize_real.F

KEYWORDS: auto_levels_opt, dzbot, dzstretch
Problem:
Lack of information in the standard output when running real.exe using auto_levels_opt = 2.
Solution:
Adds print for parameters used to define vertical levels.
M     dyn_em/module_initialize_real.F
1. Now print like the following is added to output from running real.exe:
p_top =    1000. Pa, dzbot =   30.0 m, dzstretch_s/u =   1.20  1.02
RELEASE NOTE: This PR adds a print for parameters used when running real.exe using auto_levels_opt = 2 option, which is the default.

Print parameters used in auto_levels_opt = 2

---

phys/module_sf_urban.F

To correct for the underestimation of net longwave flux absorbed by the building wall, RB2, in module_sf_urban.F
TYPE: Bug fix
KEYWORDS: Longwave flux, radiation/energy balance, Surface temperature, Urban climate, SLUCM
SOURCE: Parag Joshi (Brookhaven National Lab), Katia Lamer (Brookhaven National Lab)
Problem:
The net long wave fluxes absorbed by the building walls is being underestimated due to multiplication of the emissivity twice in the equation. The command/lines that evaluate RB2 in the module_sf_urban.F (Lines 1300 and 1419 of WRF version-4.5.2) reflect the net long wave fluxes absorbed by building walls. 
Solution:
The code has been corrected by referring to the equation A9 of in the article, Kusaka & Kimora 2004, Journal of Applied Meteorology. 
ISSUE: …

Correcting the equation that calculates the net longwave fluxes in single layer UCM. 

---

main/depend.common

TYPE: bug fix, clean up
KEYWORDS: dependencies, unused
Problem:
Some dependency is declared twice, some are no longer needed.
Solution:
Remove un-used depends.
M      main/depend.common
1. Tested on Derecho with 6 proc to compile
RELEASE NOTE:

Remove unneeded depends

---

dyn_em/module_initialize_real.F

TYPE: bug fix
KEYWORDS: real, use_sh_qv
The logic to control whether specific humidity or mixing ratio is used instead of RH is wrong (PR-1959). It is corrected in this PR.
M     dyn_em/module_initialize_real.F
1. Tested before and after this change. The data without SH is not affected, and the data with SH (EC model level data) is now used directly if use_sh_qv is set to true.
RELEASE NOTE:

Fix a logic for using specific humidity or mixing ratio directly

---

compile

Fix issue with generalized compiler version output using the wrong flags
TYPE: bug fix
KEYWORDS: compile, version
Problem:
A generalized compile version check was proposed in #1987. This logic was implemented in #1942 but the originating logic contains a bug where the `-V` and `--version` flag commands' output is flipped.
Solution:
Use `-V` in the appropriate spot when `$status` is zero for the `-V` check, and respectively for the `--version` check.
M       compile
1. With previous bad logic the compile log output shows a compiler error as the wrong flag is used to output version info. With the fix, the correct output now shows in the compile log.

Fix issue with generalized compiler version output using the wrong flags

---

phys/module_bl_mynn.F

TYPE: bug fix + tuning
KEYWORDS: MYNN EDMF
SOURCE: Joseph Olson (NOAA-GSL)
Problems:
1. overly diminished TKE in stable PBL - always dropping to the lower limit
2. negative mass flux area fractions found (rarely) with activation criteria change from flt to fltv.
3. edmf diagnostics erroneously included rho.
Solution:
1. retuning of mixing lengths and stability function for momentum - mostly just limit changes.
2. check for mf transfer of heat out of the lowest layer was modified
3. removed rho.
phys/module_bl_mynn.F
1. Tested in RRFSv1.
This commit contains the final tuning of the MYNN for RRFSv1, and part of the update for 4.6 (together with PR-1938 and 1996).

Final bug fixes and tuning of MYNN PBL for v4.6

---

phys/module_microphysics_driver.F

TYPE: almost text only
KEYWORDS: extra print, microphysics driver
Problem:
PR-1876 accidentally turned on a diagnostic print for max and min vertical motions
Solution:
The print is removed as in previous code.
M       phys/module_microphysics_driver.F
The Jenkins tests are all passing.
RELEASE NOTE:

Remove print from microphysics driver

---

phys/physics_mmm/cu_ntiedtke.F90
phys/physics_mmm/mp_wsm6_effectRad.F90

KEYWORDS: doxygen comments, shared physics routines
Added some doxygen comments to make routines in physics_mmm/ the same as those in future MMM shared physics repository.
M       phys/physics_mmm/cu_ntiedtke.F90
M       phys/physics_mmm/mp_wsm6_effectRad.F90
The Jenkins tests are all passing.

Add text to two routines in physics_mmm

---

var/da/da_radar/da_get_innov_vector_radar.inc

Bugs fix of duplicated allocation and file close in radar_rhv_opt = 2.
TYPE: bug fix
KEYWORDS: radar DA
Problem:
Duplicated allocation of avg_qws when choosing radar_rhv_opt = 2.
da_free_unit instead of da_get_unit for closing a file when radar_rhv_opt is equal to 2.
ISSUE: #2077 
var/da/da_radar/da_get_innov_vector_radar.inc

Bugfix for duplicated allocation and file closing for radar_rhv_opt = 2

---

run/README.namelist

KEYWORDS: namelists, corrections
SOURCE: JiriRichter and internal
The description of a few namelists are updated. io_style_emiss is removed from this file since it is for WRF-Chem, and not specifiable under &time_control.
Fixes #2071, #2072, #2073
No need for test. 
RELEASE NOTE: The documentation of a few namelists is updated in this PR.

a few changes in documenting namelists

---

phys/module_sf_urban.F

TYPE: Bug fix
KEYWORDS: LECH stability functions, Latent heat flux, Sensible heat flux, SL Urban Canpy Model
SOURCE: Parag Joshi (Brookhaven National Lab), Katia Lamer (Brookhaven National Lab)
Problem:
The stability functions originally proposed by Lech Lobocki which are used in calculating the exchange coefficients between surface layer and roof, building wall, Green roof, and ground are implemented incorrectly. The error surfaced while comparing the formulation suggested in Lobocki 1992 with the equations in commands/lines 3056 and 3062 (WRF-v4.5.2).
Solution:
The code has been corrected by referring to the equations 48 and 49 of the article "A procedure for the derivation of surface layer bulk relationships from simplified second-order closure models" by …

Modified/Corrected LECH's stability functions in the SL Urban Canopy Model following the formulation. 

---

phys/module_sf_bem.F

TYPE: Bug fix
KEYWORDS: PV panels, Correlations, Upward heat flow, BEM (Building Energy Model). 
SOURCE: Parag Joshi (Brookhaven National Laboratory) 
Problem:
A typographical mistake was identified within the correlations that evaluate heat transfer coefficient for the upward heat flow over PV panels in the Building Energy Model (BEM). 
Solution:
The parameters have been modified following the correlation expressions provided in the literature. Please refer to the equation J.2.2a (please see the attached screenshot) on page number 79 of the document below. 
https://nvlpubs.nist.gov/nistpubs/Legacy/IR/nbsir83-2655.pdf
M     phys/module_sf_bem.F
1. No test has been conducted as the parameters seems to have very small or …

Updated heat transfer coefficient correlation parameters for horizontal and upward heat flow over PV panels. 

---

phys/module_sf_urban.F

TYPE: Bug fix
KEYWORDS: Stability function, Urban canopy model, surface energy balance, Green roof temperature. 
SOURCE: Parag Joshi (Brookhaven National Laboratory), Katia Lamer (Brookhaven National Laboratory)
Problem: The earlier equations has a typo where X (= (1-16\zeta)^1/4) is mentioned instead of X0. In addition, following the formulation of surface energy balance of OSU1DPBL scheme by Ek and Mahrt 1991, it appears that when the following definition is used $\sigma * \theta_s^4 = \sigma T_0^4 (1 + 4((\theta_s - T_0)/T_0)))$ is used, the temperature in the calculations of net flux at the surface should use T_0 (temperature at first atmospheric level). However, in the module TGRP (temperature of the green roof surface at previous time step is used)is used …

Stability function correction for momentum in mos subroutine of SLUCM.

---

share/output_wrf.F

Updates global attributes in auxiliary history files and separately for WRF-CMAQ
TYPE: bug fix
KEYWORDS: metadata, global attributes, auxiliary output, auxiliary history, WRF-CMAQ
SOURCE: Tanya Spero and Jeff Willison (U.S. EPA)
Problem:
The suite of global attributes is incomplete in auxiliary history files. Notably, the precipitation tipping bucket is among the fields not included. Separately, there is no metadata in the header to indicate when WRF-CMAQ is used.
Solution:
Changes are introduced in share/output_wrf.F to expand the use cases to write the full suite of global attributes to the metadata of auxiliary output files. In addition, two global attributes are added to the output only when the WRF-CMAQ model is invoked (WRF_CMAQ_OPTION and …

Updated global attributes for auxiliary output as well as runs with WRF-CMAQ

---

phys/module_mp_wsm6.F

TYPE: bug fix
KEYWORDS: radar reflectivity, WSM6
SOURCE: reported by Gabriel Cassol of Sigma Meteorologia, Brazil, internal
Problem:
When moving WSM6 to MMM shared physics directory, the calculation of radar reflectivity was left out.
Solution:
The calculation of radar reflectivity is added back in the WSM6 scheme.
Fixes https://github.com/wrf-model/WRF/issues/2096
M phys/module_mp_wsm6.F
1. The reflectivity is computed now when namelist do_radar_ref is set to 1.
RELEASE NOTE: Fixed the bug of missing radar reflectivity in WSM6 scheme when do_radar_ref is set to 1.

Add reflectivity calculation back to WSM6 scheme

---

dyn_em/module_big_step_utilities_em.F

TYPE: bug fix
KEYWORDS: syntax, compilation
Problem:
dyn_em/module_big_step_utilities_em.F contains nonstandard line continuation symbols that are most likely being ignored by the make build system by the in situ file preprocessing steps. The cmake build does not use sed or standard.exe to preprocess files, so these lines get fed directly to compilers. Fortran compilers that do not support C-style line continuation then fail (nvhpc as an example).
Solution:
Change line continuation characters to standard Fortran.

Fix line continuation syntax causing problems with certain compilers

---

phys/physics_mmm/sf_sfclayrev.F90

TYPE: bug fix
KEYWORDS: sfclayrev, fix possible undefined
SOURCE:  internal reported by Xin-Zhong Liang
Problem:
zol(i) can be left undefined in rare case of br(i) = 0.
Solution:
add line to initialize zol(i)=0.
M       phys/physics_mmm/sf_sfclayrev.F90
1. Only compile tested.
RELEASE NOTE: Fix for rare undefined zol in sfclayrev.

fix for possible undefined zol in sfclayrev

---

phys/module_wind_mav.F

TYPE: bug fix
KEYWORDS: compilation, nonstandard
Problem:
PR #1944 introduced a nonstandard function call `isnan()` which breaks compilation for compilers which don't support this extension. 
Solution:
A potential alternative is to use the `ieee_is_nan()` call from `ieee_arithmetic`. As there is conditional compilation of this module which requires Fortran 2003 standard, an easier alternative is just to check the input values before calling `acos()`

Replace nonstandard isnan() call with value input checks instead

---

external/RSL_LITE/c_code.c
external/RSL_LITE/period.c
external/RSL_LITE/rsl_lite.h

TYPE: bug fix
KEYWORDS: gcc14, compilation, c99
Problem:
From #2047 :
Compilation of WRF v4.6.0 fails with GCC 14 due to new standard changes
> Type checking on pointer types (-Werror=incompatible-pointer-types)
> GCC no longer allows implicitly casting all pointer types to all other pointer types. This behavior is now restricted to the void * type and its qualified variations.
> 
> To fix compilation errors resulting from that, you can add the appropriate casts, and maybe consider using void * in more places (particularly for old programs that predate the introduction of void * into the C language).
> 
> Programs that do not carefully track pointer types are likely to contain aliasing violations, so consider building with -fno-strict-aliasing. …

Add explicit casts to mismatched pointer types in rsl_lite

---

.ci/env/derecho.sh
.ci/env/helpers.sh
.ci/env/hostenv.sh
.ci/tests/build.sh
.ci/wrf_compilation_tests-make.json
.github/workflows/ci.yml
.github/workflows/test_workflow.yml
.gitignore
.gitmodules

KEYWORDS: testing, regression, test framework
Problem:
The current regression suite code is complex, requires maintenance of multiple alternate repositories, and takes involved effort to add a new test making community contribution limited at best. Likewise, the complexity of the system reduces the likelihood of independent local testing of changes, leading to a development cycle of one-off commits done to reinvoke testing to see if meaningful commits fix the issues.
Solution:
This new proposed regression suite addresses these shortcomings in a number of discrete ways:
1. Modularize the testing framework to an generalized independent repo usable by any repo seeking to set up tests that can run locally, on HPC systems, and within …

Initial testing framework

---

CMakeLists.txt
cmake/c_preproc.cmake

TYPE: bug fix
KEYWORDS: cmake, compilation
Problem:
The use of generator expressions in the defines compacts the logic neatly but removes the ability to evaluate these conditionals at configuration time. As such, assumptions must either be made or defines wholly dropped when adding configure-time commands like C preprocessing, both of which are wrong.
Solution:
Switch the logic to a more verbose `if()`-style that guarantees defines that can be known at configure time are resolved. 
M       CMakeLists.txt
M       cmake/c_preproc.cmake
RELEASE NOTE: CMake build no longer uses generator expressions in defines

CMake build no longer uses generator expressions in defines

---

test/em_b_wave/namelist.input

TYPE: no impact directly in the run
KEYWORDS: namelist, end_date, b_wave
SOURCE: Jeronimo Bande (IDING SAS)
Problem:
Wrong end date in namelist. Not good for example.
Solution:
Correct  end date of the simulation.
test/em_b_wave/namelist.input
Jenkins tests are all passing.

Corrected end date for em_b_wave  test case 

---

phys/module_sf_fogdes.F
phys/module_surface_driver.F

Fix fog des (grav_settling) for LCZ dataset 
TYPE: bug fix
KEYWORDS: grav_setting, LCZ
SOURCE: Adam Dury (WeatherQuest)
Problem:
WRF crashes when grav_settling is greater than 0 and wudapt_lcz = 1 due to the historical code using hard coded values for land categories to detect which land use type is being used. This isn't the case now so needed to update to use a variable with actual land use category type so the grav_settling code would work when wudapt_lcz was turned on and the nlcat wasnt the same for each land use type.
Solution:
Changed the if statements to use mminlu rather than nlcat so that the grav_settling option knows what land use dataset is being used. Corrected the error message to go into rsl.error files rather than rsl.out files
LIST OF MODIFIED …

Update how fogdes identifies land use type

---

CMakeLists.txt
arch/configure_reader.py

KEYWORDS: cmake, wrfplus, da
Problem:
The current CMake build only works with the em core / ARW in mind and presents a non-intuitive selection when attempting other cores. While these cores are not yet supported in the CMake build, remove these selections sets up the configuration script to be able to present a familiar set of options.
Solution:
Remove normally unselectable options from `configure_new` after selecting non-ARW cores. Put in place stand-in values for these unselected variables.

CMake Prepare for alternate core selections

---

CMakeLists.txt
cmake/modules/FindnetCDF-Fortran.cmake
cmake/modules/FindnetCDF.cmake
external/CMakeLists.txt
external/RSL_LITE/CMakeLists.txt
external/atm_ocn/CMakeLists.txt
external/esmf_time_f90/CMakeLists.txt
external/fftpack/fftpack5/CMakeLists.txt
external/io_adios2/CMakeLists.txt
external/io_esmf/CMakeLists.txt
external/io_grib1/CMakeLists.txt
external/io_grib1/MEL_grib1/CMakeLists.txt
external/io_grib1/WGRIB/CMakeLists.txt
external/io_grib1/grib1_util/CMakeLists.txt
external/io_grib2/bacio-1.3/CMakeLists.txt
external/io_grib2/g2lib/CMakeLists.txt
external/io_grib_share/CMakeLists.txt
external/io_netcdf/CMakeLists.txt
external/io_netcdfpar/CMakeLists.txt
hydro/CMakeLists.txt
hydro/HYDRO_drv/CMakeLists.txt
hydro/IO/CMakeLists.txt
hydro/Routing/CMakeLists.txt
hydro/Routing/Reservoirs/CMakeLists.txt
hydro/Routing/Reservoirs/Persistence_Level_Pool_Hybrid/CMakeLists.txt
hydro/Routing/Reservoirs/RFC_Forecasts/CMakeLists.txt
hydro/nudging/CMakeLists.txt

KEYWORDS: netCDF, cmake, compilation
Problem:
The current iteration of the cmake build uses the old-style of finding modules.  This limits the usability of transitive properties as well as the native netCDF cmake build which provide imported targets.
See https://cmake.org/cmake/help/latest/manual/cmake-developer.7.html#find-modules for more information on module writing.
Solution:
Augment the output of the provided find module to supply an imported target that fully describes the netCDF library. Additionally, in rewriting how targets in WRF reference netCDF remove unnecessary linking to the library. Ensure the provided import target and flags of the find module matches the netCDF[-Fortran].cmake.in outputs verbatim thus emulating …

Restructure netCDF find modules to use modern import target

---

CMakeLists.txt
confcheck/CMakeLists.txt
tools/fseek_test.c

TYPE: bug fix
KEYWORDS: fseek, compilation, cmake
Problem:
The fseek test lacks correct syntax causing false negative reports of feature not existing when newer compiler standards disallow this.
Solution:
Add `int` to the main program in the fseek test. Also to add further robustness in detecting this feature, use the `-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1` generally *nix standard defines.
M       CMakeLists.txt
M       confcheck/CMakeLists.txt
M       tools/fseek_test.c
RELEASE NOTE: Fix fseek test

Fix fseek test

---

arch/configure_reader.py

KEYWORDS: cmake, configuration
Problem:
In preparation for alternate core compilation, there is need for additional information from the stanzas. Some of these fields include extraneous information to cmake that must be filtered out. The previous version manually listed fields and values to sanitize, but this is brittle when accounting for all stanza types and configurations.
Solution:
Rather than hard-coding the sanitization of stanza fields to be consumed by cmake, a generalized approach is used to allow full use of stanza fields down the line.

CMake improve configure_reader.py script

---

.ci/wrf_compilation_tests-make.json
.github/workflows/ci.yml
.github/workflows/test_workflow.yml

KEYWORDS: testing, compilation
Problem:
The testing frameworks (github actions nor Jenkins) don't run a wide array of compilation tests per compiler family commonly available.
Solution:
Use the github actions / hpc-workflows testing framework to run serial, sm, dm, and dm+sm for GNU, Intel Classic & OneAPI, and PGI/nvhpc on Derecho. Tests will run collectively in one node in parallel to maximize core hour allocations.
1. Tests can be run locally on Derecho by using the .ci/hpc-workflows runner.py to launch all tests as separate jobs, but this is inefficient and not exactly as the tests run. To emulate the tests as done in the github actions workflow use the additional `args` set in the respective testSet of …

Compilation Tests for ARW

---

phys/module_sf_urban.F

TYPE: Bug fix
KEYWORDS: Shortwave radiation balance, reflected radiation, shadowing effect, single-layer urban canopy model (SLUCM), direct and diffuse radiation.
SOURCE: Parag Joshi, Katia Lamer (Brookhaven National Laboratory)
DESCRIPTION OF CHANGES: 
Problem: The single-layer urban canopy model missed a couple of terms that represent the direct and diffuse radiation reaching at a wall reflected from the other wall. It leads to an inaccurate calculation of the shortwave radiation at the walls.
Solution: Mathematical formulation by Kusaka et. al. (2001) was followed to verify the equations used in the SLUCM module in WRF. The equations are corrected.
More details can be found in this [attachment](https://github.com/user-attachments/files/16800936/Shortwave.radiation_Single.Layer.pdf). …

Shortwave radiation balance at the wall missing reflected direct and diffuse radiation reflection from the wall terms.

---

cmake/template/WRFConfig.cmake.in

TYPE: bug fix
KEYWORDS: compilation, cmake, netcdf
Problem:
PR #2054 changes the netCDF target linking for WRF targets generated through CMake. When used with any other software relying on the package config generated from `cmake/template/WRFConfig.cmake`, there must be a way to find non-CMake supported packages like netCDF. WRF provides these find modules in `<install dir>/share` but does not use them within its own package config. WPS also has a FindnetCDF.cmake and FindnetCDF-Fortran.cmake, but these use the classic variable approach instead of an import target. 
Thus, when building WPS referencing WRF with the changes of #2054, it will use the WPS netCDF find modules instead of WRF's. This will result in an error like:
```
CMake Error at …
```

CMake netCDF Compatibility with WPS

---

cmake/confcheck.cmake
confcheck/CMakeLists.txt

KEYWORDS: cmake, configuration
Problem:
The configuration checks done by the CMake build use language-specific calls between various functions. This has lead to a rather complex signature that is also limited in scope.
Solution:
Simplify the `wrf_conf_check` calls to make use of CMake's built-in `try_compile()` and `try_run()` functions, forwarding argument to those as necessary. Aside from minor adjustments to the `wrf_conf_check` calls this should appear as a drop-in replacement that provides the same results as before, i.e. no change to the system configuration options detected.

CMake confcheck switch to try_* functions

---

cmake/modules/FindnetCDF.cmake

TYPE: bug fix
KEYWORDS: netcdf, cmake
Problem:
Certain versions of netCDF with particular configurations return a blank when queried with `nc-config`. To prevent a null argument expansion in CMake we should check for variable emptiness and if empty assume the queried feature is not present. There is a typo copied from the FindnetCDF-Fortran.cmake module causing this check to never get exercised leading to failed configuration due to syntax errors.
Solution:
Correct the typo to reference the netCDF variables rather than the netCDF-Fortran ones.
1. Tested against netCDF 4.7.2 without szlib (`--has-szlib ->    `)
RELEASE NOTE: Bug fix in CMake FindnetCDF.cmake for empty --has-* nc-config fields

Fix typo in cmake find netCDF causing failure on blank responses

---

arch/configure_reader.py

TYPE: bug fix
KEYWORDS: compilation, cmake
Problem:
With the addition of #2088, `ARCH_LOCAL` from the stanza is now being fed into compilation with potential `-D` defines. On versions of CMake <3.26 leading `-D` on defines is not removed from certain function calls like `add_compile_definitions()`. This will pass the configuration stage but will fail to compile when using the defined minimum CMake version of the project.  
Solution:
To simplify the logic, all defines fed into the `wrf_config.cmake` file for the configuration step will be sanitized of leading `-D`. This follows the original design intent where stanza sanitization happens before being fed into CMake, thus allowing the CMake code to focus on configuration of options rather than …

CMake sanitize leading define flag

---

cmake/target_source_properties.cmake

TYPE: bug fix
KEYWORDS: compilation, cmake
Problem:
As noted in #2124, prior to CMake 3.23, when defining custom properties the `BRIEF_DOCS` and `FULL_DOCS` are non-optional arguments. 
Solution:
Add proper documentation to the custom properties to allow minimum CMake version requirements of the project to remain the same.
ISSUE: 
Addresses #2124 
1. Tested on CMake v3.20.6
RELEASE NOTE: 
Add documentation to custom properties in CMake to fix compatibility with older versions.

CMake Add documentation to custom defined properties

---

CMakeLists.txt
cmake/c_preproc.cmake
cmake/m4_preproc.cmake
frame/CMakeLists.txt
tools/CMakeLists.txt

TYPE: bug fix
KEYWORDS: autogeneration, compilation, cmake
Problem:
Currently the CMake build system minimum version is limited by the automated scoping of generated property on certain source files. This in combination of `CMP0118` requires usage of CMake >3.20
Solution:
Set the generated property at the correct scope for source file usage. Lower the minimum required version to reflect this change. Note that CMake 3.18.6 is not used as there are features from 3.19 in use that, while could be implemented by hand, would take more effort to remove than the gained benefit. 
1. Combined with #2125, #2130, and #2131 this was tested on the latest patch of each unique minor release of CMake since v3.19.8. The full list of tested versions …

CMake Correctly set generated property on autogen source code

---

CMakeLists.txt
cmake/template/arch_config.cmake
frame/CMakeLists.txt

TYPE: bug fix
KEYWORDS: cmake, flags, optimization
Problem:
To feed initial flags into the cmake build, a toolchain file is used. 
However, for particular build configurations, namely release and debug, despite the configuration being "Release" and "Debug", respectively, the corresponding `CMAKE_<LANG>_FLAGS_<CONFIG>_INIT` has the configuration name capitalized. 
Additionally, these initial flags supplement the starting flags and do not override any inherited flags that CMake automatically appends. This can cause issues with certain compilers where subsequent flags that normally should supersede previously listed options are ignored. As an example, using nvfortran/pgi the following will cause forced optimization, which is not viable for some files …

CMake set release flags properly

---

CMakeLists.txt
cmake/wrf_case_setup.cmake
main/CMakeLists.txt
wrftladj/CMakeLists.txt

KEYWORDS: cmake, wrfplus
Problem:
The current CMake build does not build the WRF PLUS core configuration
Solution:
Add the necessary source files to compile WRF PLUS. WRF binary will still be created, but a symlink to `wrfplus.exe` will also be created for backward compatibility

CMake WRFPLUS

---

dyn_em/module_initialize_real.F

TYPE: bug fix
KEYWORDS: LCZ, USGS
SOURCE: Lukas Pilz (Heidelberg University)
Problem:
As shown in #2152, for USGS data the wrfinput LU_INDEX field has major differences to the met_em LU_INDEX field. Cells in LU_INDEX which have LCZ categories (>30) were overwritten with the default USGS urban category (1) where FRC_URB2D > 0.5. 
Solution:
Add a check similar to the MODIS case above.
ISSUE:
Fixes #2152 
M    dyn_em/module_initialize_real.F
1. Did local tests, the only differences between wrfinput and met_em which remain are changing LU_INDEX 28 to 16, which is a water body redesignation as to my knowledge.
2. Jenkins tests have passed.
RELEASE NOTE: Bug fix for wrfinput where LCZ urban cells in LU_INDEX were overwritten …

Bug fix for overwriting of LCZ urban cells in LU_INDEX with default USGS urban category.

---

Registry/Registry.EM_COMMON
Registry/registry.var
dyn_em/module_initialize_real.F
dyn_em/solve_em.F
external/io_netcdf/makefile
main/depend.common
main/real_em.F
phys/Makefile
phys/module_microphysics_driver.F
phys/module_mp_rcon.F
phys/module_physics_init.F
run/README.namelist
share/module_check_a_mundo.F

Release of the RCON Microphysics package into WRF.
KEYWORDS: microphysics, physics, rainfall, warm rain, cloud water
SOURCE: Robert Conrick (U. of Washington); robert.conrick@gmail.com
This is the release of the RCON microphysics scheme, the intent of which is to improve warm rain representation within the Thompson-Eidhammer scheme.
modified:   Registry/registry.var
modified:   dyn_em/solve_em.F
modified:   phys/Makefile
modified:   phys/module_microphysics_driver.F
new file:   phys/module_mp_rcon.F
modified:   phys/module_physics_init.F
The code has passed the regression tests.
RELEASE NOTE: 
Release of the RCON Microphysics package into WRF, which improves upon the warm rain …

RCON Microphysics

---

run/README.namelist

KEYWORDS: README.namelist, adaptive time step
Problem:
Definitions for a few adaptive time step-relative variables in README.namelist weren't comprehensible.
Solution:
Modified the wording to make more sense
1. text only

fixed defs for adap time step namelist vars in README.namelist

---

phys/module_bl_keps.F
phys/module_pbl_driver.F

TYPE: bug fix
KEYWORDS: tke-epsilon-tpe, PBL, stability functions
SOURCE: Andrea Zonato, Royal Netherlands Meteorological Institute (KNMI)
Problem:
The stability functions at the surface (phim,phieps) for calculating the boundary values of tke and its dissipation rate in the tke-epsilon-tpe PBL scheme [Zonato et al., 2022](https://doi.org/10.1175/MWR-D-21-0299.1) does not include the correction by z0.
Solution:
Pass the correct stability functions, calculated in module_sf_sfclayrev.F
phys/module_bl_keps.F
phys/module_pbl_driver.F
The Jenkins tests are all passing.
RELEASE NOTE: 
The similarity stability functions phim and phieps, necessary for calculating the surface values of tke and dissipation rate in the tke-epsilon-tpe …

Correction of stability functions for the tke-epsilon-tpe   PBL scheme

---

phys/CMakeLists.txt

TYPE: bug fix
KEYWORDS: cmake, compilation
Problem:
PR #2144 added a new microphysics file `phys/module_mp_rcon.F` which only added it to the make build
Solution:
Add new RCON file to CMake build
1. Develop branch at merge of #2144 fails to build CMake build. These changes fix the build issues

CMake Fix RCON Microphysics

---

frame/collect_on_comm.c

Determine MPI Data Types in col_on_comm() & dst_on_comm() to prevent displacements overflow.
TYPE: bug fix
KEYWORDS: prevent displacements overflow in MPI_Gatherv() and MPI_Scatterv() operations
SOURCE: Benjamin Kirk & Negin Sobhani (NSF NCAR / CISL)
Problem:
The MPI_Gatherv() and MPI_Scatterv() operations require integer displacements into the communications buffers. Historically everything is passed as an MPI_CHAR, causing these displacements to be larger than otherwise necessary. For large domain sizes this can cause the displace[] offsets to exceed the maximum int, wrapping to negative values.
Solution:
This change introduces additional error checking and then uses the function MPI_Type_match_size() (available since MPI-2.0) to determine a suitable MPI_Datatype …

  Determine MPI Data Types in col_on_comm() & dst_on_comm() to prevent displacements overflow. (Fix for #2156)

---

share/mediation_integrate.F

TYPE: bug fix/enhancement
KEYWORDS: wrf, wrfv4, restart, output streams
SOURCE: James Ruppert (University of Oklahoma)
Problem:
When running WRF from as a restart, the option write_hist_at_0h_rst would only apply to the default history stream. Now, when this option is set to true, it will also apply to special user-defined streams. This is required to maintain a consistent number of output time steps per file with multiple time steps writing to a single file, which is often preferred for multiple-day runs.
Solution:
Added an additional loop over history streams with CALL med_hist_out when the following condition is met:
IF ( (config_flags%restart) .AND. ( currTime .EQ. startTime ) .AND. ( config_flags%write_hist_at_0h_rst )) …

When write_hist_at_0h_rst=.true., will now apply to user-def streams

---

Registry/Registry.EM_COMMON
phys/Makefile
phys/module_microphysics_driver.F
phys/module_mp_udm.F
phys/module_physics_init.F

KEYWORDS: UFS Double Moment Microphysics scheme (UDM)
SOURCE: Songyou Hong via internal
The new microphysics option is based on 7-class WDM7 with revision and improvements and will be mp_physics=27. 
M       phys/Makefile
M       phys/module_microphysics_driver.F
M       phys/module_physics_init.F
M       phys/module_mp_udm.F
1. Compilation on derecho Cray Intel (ftn) seems to need -O2.
2. squall2d_x test case runs OK.
3. The Jenkins tests are all passing.
RELEASE NOTE: An new microphysics, UFS Double Moment (UDM), 7-class microphysics from Songyou Hong is added (mp_physics=27). UDM mp largely adopts microphysical processes in WDM7, but with bug fixes or revisions based …

Adding udm microphysics as option 27

---

test/em_real/namelist.input

TYPE: enhancement, no impact, text only
KEYWORDS: vertical coordinate, namelist
Problem:
The current namelist.input file only has dzstretch_s. To properly use the auto_levels_opt, dzstretch_u and dzbot should be considered.
Solution:
Add dzstretch_u and dzbot in the namelist. Parameters based on UG.
M       test/em_real/namelist.input
RELEASE NOTE: Add dzstretch_u and dzbot in namelist.input. Users are advised to check UG for other parameters to use.

Add dzstretch_u and dzbot to namelist.input in test/em_real/

---

phys/CMakeLists.txt

TYPE: bug fix
KEYWORDS: cmake, compilation
Problem:
PR #2147 added a new file that was not added to the CMake build
Solution:
Add the corresponding file to the respective CMakeLists.txt

Fix CMake build for UDM Microphysics

---

frame/CMakeLists.txt

TYPE: bug fix
KEYWORDS: cmake, syntax
Problem:
With certain compilers, the optimization flags reduction were not being substituted correctly and the generator expression was left with partial original syntax.
Solution:
Double quote the expression to mirror all other uses of the categorical flag control and expand the expression.
1. Tested on Derecho with Intel oneAPI

Add quotes to optimization flags exceptions in CMake

---

confcheck/CMakeLists.txt

TYPE: bug fix
KEYWORDS: cmake, typo
Problem:
There is a typo in the confcheck for arguments that are forwarded to `try_compile()` and `try_run()` functions 
Solution:
Fix the typo
1. Tested on Derecho with ifx / oneAPI compilers

Fix typo in confcheck CMakeLists.txt for FSEEKO

---

hydro/OrchestratorLayer/config.F90

TYPE: bugfix
KEYWORDS: hydro, bugfix, lake_option, reservoir DA
SOURCE: Soren Rasmussen, internal hydro group
Problem: If lake_option was set to 3 (Reservoir DA) but no Reservoir DA flags were set to .true. the internal lake_option was not set to [levelpool/off/passthrough] and a cryptic error resulted. 
Solution: NCAR/wrf_hydro_nwm_public#808 This fix now prints an error message and reverts the value to Level Pool if no DA option is selected.
```
M       hydro/OrchestratorLayer/config.F90
```
1. Do mods fix problem? Yes, tested in the WRF-Hydro model. WRF builds with GNU
3. Are the Jenkins tests all passing? Yes
RELEASE NOTE: Hydro reservoir drainage area (DA) lake option bugfix

hydro bugfix: correctly handle lake_option=3 / no DA case, WRF-Hydro PR#808

---

Registry/Registry.EM_COMMON
dyn_em/module_initialize_real.F
run/README.namelist
share/module_check_a_mundo.F

Purpose: add a default_soiltype namelist option
KEYWORDS: FEAT: Add a default_soiltype namelist option
SOURCE: Mathieu Landreau (Centrale Nantes)
Problem:
When running real.exe, in the land cells where no soiltype is defined in the soil dataset, the type is set to 8=silty clay loam. For high-resolution coastal area simulation, this can represent a certain amount of cells.
Solution:
A namelist option named default_soiltype is added. It is checked (in module_check_a_mundo) that the user-defined value is between 1 and 19 and is not water (19)
Registry/Registry.EM_COMMON
dyn_em/module_initialize_real.F
share/module_check_a_mundo.F
- I realized this few month ago and didn't try again. It is …

Default soiltype namelist option

---

chem/module_ftuv_driver.F
chem/module_phot_tuv.F

TYPE: bug fix
KEYWORDS: TUV, distance to the sun, 1 January, Julian day
SOURCE: Sergey Osipov (KAUST)
Problem:
TUV and FTUV fail to initialize the distance to the Sun properly if the simulation starts on 1 Jan. The multiplication factor remains uninitialized at 0, which zeros out photolysis rate calculations (see line 745 @ module_phot_tuv.F. On the next day, the distance is recalculated normally and photolysis rates are calculated properly.
Solution:
Given that the calculation of sun distance is trivial, the if check was disabled
chem/module_phot_tuv.F
chem/module_ftuv_driver.F
The Jenkins tests are all passing.
RELEASE NOTE: This PR fixed a bug where TUV and FTUV fail to initialize the distance to the Sun properly if the …

Fix the bug: TUV photolysis is inactive if simulation starts on 1st Jan

---

Makefile

TYPE: bug fix
KEYWORDS: make, verbose
Problem:
The MYNN-EDMF checkout status check commands in the make build were being output all the time regardless of status causing the `echo` error line to be verbosely printed out along with the actual status.
Solution:
Suppress the verbose output of the subshell command using the make command prefix `@`
1. Recompilation with the change no longer produces unwanted output

Suppress MYNN-EDMF verify checkout command

---

README.LluisFB
phys/module_sf_bep_bem.F

TYPE: bug fix
KEYWORDS: module_sf_bep_bem.F, loop index, debugging-crash
SOURCE: L. Fita (UBA/CIMA/IFAECI)
Problem:
The loop index in line 1600 of subroutine module_sf_bep_bem.F should be up to `nzu`, instead of `nz_um`.
Solution:
This PR fixes the index.
Fixes #2194
M       phys/module_sf_bep_bem.F
1. Code was modified and recompiled in serial debug mode and it did not crashed
RELEASE NOTE: This PR fixed a loop index error in bep_bem urban code.

Bep bem nzu

---

share/landread.c

TYPE: bug fix
KEYWORDS: landuse
Problem:
The `GET_LANDUSE()` function in landread.c when enabled had an implicit return for a non-void function, i.e. it should return an integer to denote status. This results in undefined behavior with an uninitialized return value left to the discretion of the compiler optimization, if it even does auto-initialize returns to some known value.
Solution:
Add a return statement of value `0` to denote success at the very end of the function.
1. Originally exposed with option 78 (Intel OneAPI ifx/icx) on derecho. Tested with 1 MPI rank and 36 MPI ranks to ensure landread did not fail where not expected to with these modifications.
RELEASE NOTE: 
Bug fix in landread.c to address undefined behavior by …

Add return statement to GET_LANDUSE() function

---

share/module_check_a_mundo.F

TYPE: bug fix
KEYWORDS: ghg_input, idealized, no radiation
Problem:
Most idealized cases have radiation options turned off, which causes the following error message to inaccurately print to the rsl files when ideal.exe is run:
ERROR: ghg_input available only for these radiation schemes: CAM, RRTM, RRTMG, RRTMG_fast
And the LW and SW schemes must be reasonably paired together:
OK = CAM LW with CAM SW
OK = RRTM, RRTMG LW or SW, RRTMG_fast LW or SW may be mixed
Solution:
In share/module_check_a_mundo.F, add code to ensure that when radiation is turned off, not only does the message not print, but the namelist value for ghg_input is set to 0, as well. 
M    share/module_check_a_mundo.F
1. Code compiles okay …

Remove inaccurate error message regarding ghg_input

---

external/io_grib2/Makefile

TYPE: bug fix
KEYWORDS: make, grib2
SOURCE: internal, reported by Dmitri Chubarov 
Problem:
Commit 3a0478e removed `wrf_io_flags.h` from `./external/io_grib_share` in order to reduced duplicate code. However, the grib2 Makefile was not updated to point to `./external/ioapi_share` for the consolidated version of this file.
Solution:
Include `ioapi_share` in the search paths when building grib2 io.
Fixes #2184 
1. Confirmed that with the include path changes, compilation is successful of the grib2 io when explicitly requested

Fix compilation of grib2 IO in make build

---

phys/module_surface_driver.F

TYPE: bug fix
KEYWORDS: Urban, Noah-MP, LCZ
SOURCE: Martilli, Alberto (CIEMAT)
Problem:
Use Noah-MP; module_surface_driver.F, all the LCZ_1, LCZ_2, etc. are zero because they are variables in Noah, not for Noah-MP
So it never enters in the ifs like:
IF( IVGTYP(I,J) == ISURBAN    .or. IVGTYP(I,J) == LCZ_1 .or. IVGTYP(I,J) == LCZ_2 .or. &
IVGTYP(I,J) == LCZ_3      .or. IVGTYP(I,J) == LCZ_4 .or. IVGTYP(I,J) == LCZ_5 .or. &
IVGTYP(I,J) == LCZ_6      .or. IVGTYP(I,J) == LCZ_7 .or. IVGTYP(I,J) == LCZ_8 .or. &
IVGTYP(I,J) == LCZ_9      .or. IVGTYP(I,J) == LCZ_10 .or. IVGTYP(I,J) == LCZ_11 )THEN
Solution:
This PR fixes the issue using LCZ_*_TABLE in Noah-MP related if-statement parts in module_surface_driver.F …

bugfix for LCZ index in Noah-MP

---

hydro/CPL/WRF_cpl/CMakeLists.txt
hydro/Data_Rec/CMakeLists.txt
hydro/Debug_Utilities/CMakeLists.txt
hydro/HYDRO_drv/CMakeLists.txt
hydro/IO/CMakeLists.txt
hydro/MPP/CMakeLists.txt
hydro/Routing/CMakeLists.txt
hydro/utils/CMakeLists.txt

TYPE: bug fix
KEYWORDS: cmake, hydro
Problem:
Some dependencies were not being fully satisfied and were implicit / partially fulfilled by subsequent compilation. In compilers that could tolerate these situations the hydro folder would compile successfully.
However, for compilers where dependencies are enforced (i.e. symbols resloved at compile time even within Fortran submodules), compilation would fail. 
Solution:
To account for situations where compilers require all module dependencies be resolved, dependencies between the hydro libraries and the transitive link properties were reworked to propagate dependencies up the chain correctly.
1. Tested building hydro with Intel oneAPI ifx 2024.2.1
RELEASE NOTE: 
Fixed failed …

Rework the dependency linking of hydro CMake compilation

---

arch/configure.defaults

TYPE: bug fix
KEYWORDS: make, compilation, dm
Problem:
When a DM (distributed memory) configuration is selected, the configuration phase of the make build will extract the corresponding stanza from `arch/configure.defaults` and modify various variable lines with substitutions or comment removals.
Of particular note is the normally defined `DMPARALLEL = # 1` which is changed to `DMPARALLEL = 1` when DM configurations are selected. This definition  is then used to inform the make build about which pieces of code to compile for DM capabilities. The `Linux aarch64, GCC` stanza does not have this comment (`# 1`) and so the variable ends up blank when DM is selected causing compilation failure.
This issue possibly also exists for the `Linux aarch64, …

Fix aarch64 GCC build when DM configuration selected

---

.github/workflows/ci.yml
.github/workflows/entry_point.yml
.github/workflows/test_workflow.yml

KEYWORDS: testing, devops, github, workflow
Problem:
The CI/CD testing framework using github actions is set to trigger on PR label events. However, labels are not just used for testing and will trigger the workflow. While the workflow does have checks in place to skip any labels that aren't meant to trigger testing, this skipped workflow status will override any previous actual test status. This can be confusing if two labels are applied at the same time, one being a test label, and only one status appears showing a skipped workflow. Unique naming of workflow runs does not mitigate this problem as the posted status is tied to the workflow internal id and not the run name.
Solution:
Convert the main workflow that hosts the test …

Use proxy workflow and commit statuses to record testing results

---

doc/README.cmake_build

KEYWORDS: cmake, documentation
Problem:
Typos in cmake documentation
Solution:
Fix of some typos and grammatical errors in the cmake README documentation

CMake README documentation typo fixes

---

doc/README.cmake_build

KEYWORDS: cmake, documentation
Problem:
There has been some confusion on what variables are available within the CMake build to control where dependencies can be found. This has been noted a few times within the forum where users want fine tuned control on the location of these dependencies. The current build support this through native CMake support, however the current documentation left it as an exercise to the reader to construct the variables necessary for these features.
Solution:
Add explicit documentation of dependency search variables and how a user would make use of them. Additionally point to the exact external documentation to reference for the CMake `find_package()` call

CMake README documentation on <PackageName>_ROOT variables

---

chem/module_input_chem_data.F

TYPE: bug fix
KEYWORDS: syntax
Problem:
There is invalid Fortran syntax for line continuation in the chem code. More sensitive compilers catch this as an error during the CMake build as files are not sanitized as much compared to the make build.
Solution:
Change the lines to be a single line. 
ISSUE: 
#2214 
1. Recreated issue noted in #2214 using Intel OneAPI compilers and testing code modifications to pass compilation successfully.

Fix errant line contiuation syntax in chem code

---

chem/KPP/util/write_decomp/Makefile

TYPE: bug fix
KEYWORDS: make, compilation
Problem:
PR #2018 introduced CMake compilation of the chem and KPP code. In order to do that certain helper programs created during the compilation process were reworked. The KPP mechanism integration edit program, `integr_edit.exe` was changed to take in explicit arguments for the files to read and write. However, the edits to the makefile that control this call use an invalid variable `$(MODEL)` where `$(MECH)` should be used instead. 
Solution:
Use the appropriate `$(MECH)` variable to construct command line arguments to `intergr_edit.exe`
ISSUE: 
#2216
1. Recreated the issues noted in #2216, though not limited to the intel compilers. Diagnosed as segfault due to reading of nonexistent …

Fix in KPP compilation during integration edit to use correct make variable

---

main/CMakeLists.txt

TYPE: bug fix
KEYWORDS: cmake, ideal
Problem:
PR #2089 introduced the ability to compile WRFPLUS, however it inadvertently removed the compilation of `wrf[.exe]` from any configurations that weren't `PLUS` or 'EM_REAL`. Thus, the ideal cases under `ARW` core but not `EM_REAL` no longer compiled the `wrf` target, effectively breaking compilation for any ideal cases.
Solution:
Adjust the logic to compile the `wrf` executable for `ARW` or `PLUS` cores.
Fixes #2224 
1. Tested fixes to ensure em_real, ideal, chem, and plus configurations all compile correctly again.
RELEASE NOTE: 
CMake bug fix to ensure ideal cases compile correctly again.

CMake Fix ideal compilation

---

phys/module_sf_urban.F

Fix the conversion of kinematic water vapor flux to evaporation in m/s for water budget in slucm
TYPE: bug fix
KEYWORDS: slucm, urban evaporation, urban physics
SOURCE: Einara Zahn, Princeton University
Problem:
Evaporation rate over impervious surfaces was incorrectly computed in SLUCM for option IMP_SCHEME==2. The kinematic vapor flux (kg/kg x m/s) was not converted to evaporation in m/s before entering the water budget equation, leading to wrong update of water storage.
Solution:
Multiplied the kinematic water vapor flux by air density and divided by water density in module_sf_urban.f90, only inside the code block for IMP_SCHEME == 2. The conversion does not affect the default version IMP_SCHEME==1.
Fixes #2186
LIST …

fix units of evaporation for imp_scheme==2 in slucm

---

frame/collect_on_comm.c

TYPE: bug fix
KEYWORDS: mpi, quilting, comm
Problem:
PR #2157 added changes to match an appropriate `MPI_Datatype` to a specific `typesize` during `col_on_comm()` and `dst_on_comm()`. This relies on `MPI_Type_match_size()` to query MPI about the equivalent MPI definition for a particular datatype size. There are safety checks to query `MPI_TYPECLASS_INTEGER` if `MPI_TYPECLASS_REAL` fails. 
However, when given a datatype size that does not match a possible `MPI_TYPECLASS_REAL` value (e.g. 1 byte where no real exists for single byte) instead of getting a failure via return code the query is treated as a critical failure and fully aborts the program. As the query does not rely on critical process handling _and_ since there already exists adequate …

Use a temp pass through errhandler for trivial errors causing abort

---

cmake/c_preproc.cmake
cmake/m4_preproc.cmake

TYPE: bug fix
KEYWORDS: cmake, compilation
Problem:
With the new CMake build, if a file that gets manually preprocessed prior to compilation is edited it will not trigger preprocessing again and thus skip recompilation for those edits.
Solution:
Add the original source file to the list of `DEPENDS` files when adding the custom command. This will add the appropriate make checks to compare timestamps between the original source file and the output results, triggering recompilation.
1. Tested recompilation of `wrf_io.F90` as a file that undergoes C and M4 preprocessing.

Add dependent files to custom command call to enable recompilation timestamp check

---

external/RSL_LITE/rsl_bcast.c
external/io_grib1/MEL_grib1/pack_spatial.c

TYPE: bug fix
KEYWORDS: gcc, gcc15, compilation
Problem:
GCC 15 uses newer standards compliance, notably the disallowance of `func()` function declaration as a way to defer true arguments later specified in the function definition. Instead, functions declared as `func()` will be assumed to mean `func(void)` and any other amount of arguments must be explicitly noted in the declaration.
Solution:
Make sure function declarations and definitions match.
Fixes #2226 
1. Built and tested against GCC 15.1.0
RELEASE NOTE: 
Fix compilation with GCC 15 by correcting function declaration syntax to explicitly list function arguments.

Correct syntax with explicit function arguments where previously implicit
